### ISSUE TITLE
NullPointerException: Could not translate packet ServerBlockBreakAnimPacket/ServerCloseWindowPacket

### ISSUE THREAD

**Issue by diamond-gold** [GeyserMC/Geyser#1004]
**Describe the bug**
These errors appear quite frequently in the logs, but cause is unknown

**To Reproduce**
Unknown

**Expected behavior**
No error

**Server Version**
Paper version git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Viaversion 3.0.1

**Geyser Version**
Geyser build 277

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**
```
Could not translate packet ServerBlockBreakAnimPacket
java.lang.NullPointerException: null
	at org.geysermc.platform.spigot.world.GeyserSpigotWorldManager.getBlockAt(GeyserSpigotWorldManager.java:54) ~[?:?]
	at org.geysermc.connector.network.translators.java.world.JavaBlockBreakAnimTranslator.translate(JavaBlockBreakAnimTranslator.java:46) ~[?:?]
	at org.geysermc.connector.network.translators.java.world.JavaBlockBreakAnimTranslator.translate(JavaBlockBreakAnimTranslator.java:41) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:412) ~[?:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
```
Could not translate packet ServerCloseWindowPacket
java.lang.NullPointerException: null
	at org.geysermc.platform.spigot.world.GeyserSpigotWorldManager.getBlockAt(GeyserSpigotWorldManager.java:54) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:110) ~[?:?]
	at org.geysermc.connector.utils.InventoryUtils.closeInventory(InventoryUtils.java:83) ~[?:?]
	at org.geysermc.connector.network.translators.java.window.JavaCloseWindowTranslator.translate(JavaCloseWindowTranslator.java:40) ~[?:?]
	at org.geysermc.connector.network.translators.java.window.JavaCloseWindowTranslator.translate(JavaCloseWindowTranslator.java:34) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:412) ~[?:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by DoctorMacc** [comment]
Hello, and thanks for the report! This is the same error as #997, so I'm going to close this one. Specifically that reports mentions red nether brick wall - can you correlate that?

**Comment by diamond-gold** [comment]
For the packet ServerCloseWindowPacket, i doubt they are the same issue

**Comment by DoctorMacc** [comment]
Oh, you're the same person! My bad! It's erroring out at the same spot however.
