### ISSUE TITLE
[Bug] Missing locale: nb_NO - java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Baktus79** [GeyserMC/Geyser#1007]
**Describe the bug**

```
[03:04:47] [Network Listener - #1/ERROR] [com.nukkitx.network.raknet.RakNetServer]: An exception occurred in RakNet
java.lang.NullPointerException: null
	at org.geysermc.connector.utils.LanguageUtils.getPlayerLocaleString(LanguageUtils.java:107) ~[?:?]
	at org.geysermc.connector.utils.LoginEncryptionUtils.showLoginWindow(LoginEncryptionUtils.java:160) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:121) ~[?:?]
	at com.nukkitx.protocol.bedrock.packet.SetLocalPlayerAsInitializedPacket.handle(SetLocalPlayerAsInitializedPacket.java:16) ~[?:?]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```

**To Reproduce**

Log into the server with the norwegian locale.

**Expected behavior**

Change to deafult locale as set in the config file.

```yaml
bedrock:
  address: ****
  port: 19132
  motd1: 
  motd2:
remote:
  address: ****
  port: 25565
  auth-type: online
floodgate-key-file: public-key.pem
command-suggestions: true
passthrough-motd: true
passthrough-player-counts: true
legacy-ping-passthrough: false
ping-passthrough-interval: 3
max-players: 200
debug-mode: false
general-thread-pool: 32
allow-third-party-capes: true
allow-third-party-ears: false
show-cooldown: true
default-locale: en_us
cache-chunks: false
above-bedrock-nether-building: false
metrics:
  enabled: true
  uuid: *****
config-version: 3
```

**Screenshots / Videos**

None

**Server Version**

Waterfall 366

**Geyser Version**

1.0.0 (git-master-b103d86) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**

1.16.10 (Android)

**Additional Context**

Everything works perfectly as long as I choose the English language on the client. I understand that Geyser does not support Norwegian locale, but I had hoped it would set to default when it discovered languages that are not supported.

**Comment by DoctorMacc** [comment]
Geyser does support Norwegian (though none of it is translated) - it looks like our files handle `no_NO` but not `nb_NO` (if Bedrock sent the latter, there would be no error and everything would still be English).

If you are interested in translating for Geyser, here is the link: https://translate.geysermc.org/

**Comment by Baktus79** [comment]
Thanks for the link :) The language file is relatively large, but I will start with the translation so we will see how far I get with the time I have available :) Believe it or not, but Norway has two official written languages (nn and nb)

**Comment by Baktus79** [comment]
Just a sidenote: I had to check the language list on the client and the nn part is not there.

**Comment by DoctorMacc** [comment]
Yes - it seems that the Norwegian translation is supposed to be for the language code `nb_no` (we translate for all Bedrock-supported languages), so if you translate anything keep that in mind, please. Thanks for looking into this!

**Comment by rtm516** [comment]
The issue seems to be our config, if you are currently working on Norwegian I would advise putting that on hold until we get this resolved as it may be a case of removing all the existing Norwegian strings to correct it.

**Comment by Baktus79** [comment]
No problem, then I just wait until the issue is taken care of :)

**Comment by mclk623** [comment]
Set it to Chinese as well

**Comment by rtm516** [comment]
Crowdin has now been altered and it should fix this issue

**Comment by DoctorMacc** [comment]
It won't immediately be fixed on Geyser until we update the program with the new strings - but feel free to add strings now!
