### ISSUE TITLE
NullPointerException: ServerEntityCollectItemPacket

### ISSUE THREAD

**Issue by diamond-gold** [GeyserMC/Geyser#1010]
**Describe the bug**
Console was spammed with this error

**To Reproduce**
Unknown, console was spammed with this error

**Expected behavior**
No error

**Server Version**
Paper version git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Viaversion 3.0.1

**Geyser Version**
Geyser build 277

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**
```
Could not translate packet ServerEntityCollectItemPacket
java.lang.NullPointerException: null
	at org.geysermc.connector.network.translators.java.world.JavaCollectItemTranslator.translate(JavaCollectItemTranslator.java:51) ~[?:?]
	at org.geysermc.connector.network.translators.java.world.JavaCollectItemTranslator.translate(JavaCollectItemTranslator.java:35) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:412) ~[?:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
```

**Comment by rtm516** [comment]
Can you provide a dump by doing `/geyser dump` and paste the link in here

**Comment by diamond-gold** [comment]
No longer occurs on build 305
