### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 46

### ISSUE THREAD

**Issue by diamond-gold** [GeyserMC/Geyser#1011]
**Describe the bug**
Console was spammed with this error

**To Reproduce**
Unknown, console was spammed with this error

**Expected behavior**
No error

**Server Version**
Paper version git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
Viaversion 3.0.1

**Geyser Version**
Geyser build 277

**Minecraft: Bedrock Edition Version**
1.16.1

**Additional Context**
```
Could not translate packet InventoryTransactionPacket
java.lang.ArrayIndexOutOfBoundsException: Index 50 out of bounds for length 46
	at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:82) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.action.InventoryActionDataTranslator.translate(InventoryActionDataTranslator.java:70) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.BaseInventoryTranslator.translateActions(BaseInventoryTranslator.java:80) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.CraftingInventoryTranslator.translateActions(CraftingInventoryTranslator.java:84) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139) ~[?:?]
	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167) ~[?:?]
	at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46) ~[?:?]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by DoctorMacc** [comment]
Have you tried redownloading Geyser since your first error?

**Comment by diamond-gold** [comment]
I will be upgrading to build 80 today, i will report back if i see this error again

**Comment by rtm516** [comment]
Can you provide a dump by doing `/geyser dump` and paste the link in here if the update doesn't fix it.

**Comment by birds1338** [comment]
> 
> 
> Can you provide a dump by doing `/geyser dump` and paste the link in here if the update doesn't fix it.

I am getting the same error but on Spigot, latest version, dump: https://dump.geysermc.org/pqz9hmHGl8rY2N5SXfr6M6Ir8hNpk1St

**Comment by rtm516** [comment]
Where you trying to use the crafting grid in the creative inventory?

**Comment by birds1338** [comment]
> Where you trying to use the crafting grid in the creative inventory?

Survival inventory, just the normal crafting grid, not table.

**Comment by bundabrg** [comment]
Index 50 is used for the output slot often. So it's a case of a slot mapping issue. Can you replicate this problem?

**Comment by bundabrg** [comment]
Can you please test using #1028 build. It will log a warning when it occurs but will use what I consider the correct translation. The log is just because I'm curious what action causes it so please add it to this thread. If this solves the issue we can merge it (sans log) to properly resolve the issue.
