### ISSUE TITLE
NullPointer crash while connecting to some servers

### ISSUE THREAD

**Issue by gaussandhisgun** [GeyserMC/Geyser#1024]
**Describe the bug**

New very cool version of GeyserMC suddenly refuses to connect to my favorite server cmm.minecorp.ru:25540, sending me to this error and then crash. Suddenly, this does NOT happen if I set numeric IP (got it by simply pinging hostname). And this did NOT happen on last build I used before, master 56.

```[20:28:02 INFO] ******************************************
[20:28:02 INFO]
[20:28:02 INFO] Loading Geyser version 1.0.0 (git-master-af484a4)
[20:28:02 INFO]
[20:28:02 INFO] ******************************************
Exception in thread "main" java.lang.NullPointerException
        at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:152)
        at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:269)
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:117)
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:80)
```

**To Reproduce**

1. Set remote server adress to cmm.minecorp.ru and port to 25540
2. Start GeyserMC or reload its settings
3. See the error!

**Expected behavior**

Geyser should start properly. 

**Screenshots / Videos**

**Server Version**
 Remote server, restricted version access. Sadly, but I don't know. 

**Geyser Version**
 master 284

**Minecraft: Bedrock Edition Version**
 1.16.0.10, but it makes no sense to ask as Geyser even does not start. 

**Additional Context**

**Comment by DoctorMacc** [comment]
Could you please try https://github.com/GeyserMC/Geyser/pull/1025 ? 

Feel free to join our Discord for assistance with downloading PRs.

**Comment by gaussandhisgun** [comment]
Wow. Quick. That works. Issue closed.

**Comment by DoctorMacc** [comment]
Thank you for testing!
