### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ipad54** [GeyserMC/Geyser#1051]
**Describe the bug**
If You enchant an Item in anvil and hit entity, the plugin throw an error

**To Reproduce**

1. Click on 'Anvil' 
2. Enchant item
3. Hit entity

**Expected behavior**

**Screenshots / Videos**

**Server Version**
Paper-git-111

**Geyser Version**

1.0.0

**Minecraft: Bedrock Edition Version**

1.16.0

**Additional Context**

Error:
12:59:40] [Network Listener - #1/WARN]: [Geyser-Spigot] Could not translate packet InventoryTransactionPacket
java.lang.NullPointerException: null
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal$Style.apply(LegacyComponentSerializerImpl.java:314) ~[?:?]
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.append(LegacyComponentSerializerImpl.java:265) ~[?:?]
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.append(LegacyComponentSerializerImpl.java:261) ~[?:?]
	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:224) ~[?:?]
	at org.geysermc.connector.network.translators.inventory.AnvilInventoryTranslator.translateActions(AnvilInventoryTranslator.java:112) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139) ~[?:?]
	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167) ~[?:?]
	at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46) ~[?:?]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
	at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[12:59:40] [Network Listener - #1/WARN]: java.lang.NullPointerException
[12:59:40] [Network Listener - #1/WARN]: 	at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal$Style.apply(LegacyComponentSerializerImpl.java:314)

**Comment by rtm516** [comment]
Can you test https://github.com/GeyserMC/Geyser/pull/1009

**Comment by ipad54** [comment]
@rtm516 Thank You!

**Comment by ipad54** [comment]
@rtm516 enchanting and repairing does not works

**Comment by DoctorMacc** [comment]
This specific error should be fixed - let us know otherwise if this is not the case.

**Comment by Illustive** [comment]
[Fri, 21. May 2021 21:19:55 UTC WARN] org.geysermc.platform.spigot.shaded.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net/) for more information. Component: TextComponentImpl{content="IllusiveMC is a Community Server that Features Survival. Our SMP Features include the following: MCmmo, VeinMiner, RTP and silkspawners. We are a community server, meaning that we take our members' feedback to help improve the Server. We have Java & Bedrock Support, so our members can join on practically any platform.    BY: IllusiveMC Staff", style=StyleImpl{color=null, obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:58)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.TextComponentImpl$BuilderImpl.build(TextComponentImpl.java:147)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.TextComponentImpl$BuilderImpl.build(TextComponentImpl.java:115)
[2:50 PM]
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:163)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:154)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:74)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:55)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.google.gson.Gson.fromJson(Gson.java:887)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.google.gson.Gson.fromJson(Gson.java:852)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.google.gson.Gson.fromJson(Gson.java:801)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.google.gson.Gson.fromJson(Gson.java:773)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:84)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.platform.spigot.shaded.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:41)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.chat.MessageTranslator.convertMessage(MessageTranslator.java:108)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.chat.MessageTranslator.convertMessageLenient(MessageTranslator.java:133)
[2:50 PM]
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.chat.MessageTranslator.convertMessageLenient(MessageTranslator.java:147)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.item.translators.nbt.BookPagesTranslator.translateToBedrock(BookPagesTranslator.java:59)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.item.ItemTranslator.translateToBedrock(ItemTranslator.java:144)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.inventory.GeyserItemStack.getItemData(GeyserItemStack.java:102)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.inventory.translators.PlayerInventoryTranslator.updateSlot(PlayerInventoryTranslator.java:136)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.lambda$translate$2(JavaSetSlotTranslator.java:89)
[Fri, 21. May 2021 21:19:55 UTC WARN] at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815)
[Fri, 21. May 2021 21:19:55 UTC WARN] at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799)
[Fri, 21. May 2021 21:19:55 UTC WARN] at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.session.GeyserSession.addInventoryTask(GeyserSession.java:1063)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:62)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:57)
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95)
[2:50 PM]
[Fri, 21. May 2021 21:19:55 UTC WARN] at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:791)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[Fri, 21. May 2021 21:19:55 UTC WARN] at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[Fri, 21. May 2021 21:19:55 UTC WARN] at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Camotoy** [comment]
This is not related to this issue at all. Update your Paper build.
