### ISSUE TITLE
reopen #1065

### ISSUE THREAD

**Issue by ipad54** [GeyserMC/Geyser#1067]
**Describe the bug**
if you put item in first slot of Anvil, the plugin throw an error. I use the latest version of Geyser

**Server Version**

Paper-git-version-111

**Geyser Version**

this server is running Geyser version 1.0.0(git-master-54bee1f)(Java: 1.16.1, Bedrock: 1.16.0)
Checking version, please wait... 
No updates available

**Minecraft: Bedrock Edition Version**

1.16.0

**Additional Context**

06:45:14 WARN]: [Geyser-Spigot] Could not translate packet InventoryTransactionPacket
java.lang.NullPointerException: null
��������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal$Style.apply(LegacyComponentSerializerImpl.java:314) ~[?:?]
��������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.append(LegacyComponentSerializerImpl.java:265) ~[?:?]
��������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.append(LegacyComponentSerializerImpl.java:261) ~[?:?]
��������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:224) ~[?:?]
��������at org.geysermc.connector.network.translators.inventory.AnvilInventoryTranslator.translateActions(AnvilInventoryTranslator.java:114) ~[?:?]
��������at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67) ~[?:?]
��������at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58) ~[?:?]
��������at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
��������at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45) ~[?:?]
��������at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139) ~[?:?]
��������at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167) ~[?:?]
��������at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46) ~[?:?]
��������at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
��������at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
��������at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
��������at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
��������at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
��������at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
��������at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
��������at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
��������at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
��������at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
��������at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
[06:45:14 WARN]: java.lang.NullPointerException
[06:45:14 WARN]: �������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal$Style.apply(LegacyComponentSerializerImpl.java:314)
[06:45:14 WARN]: �������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.append(LegacyComponentSerializerImpl.java:265)
[06:45:14 WARN]: �������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.append(LegacyComponentSerializerImpl.java:261)
[06:45:14 WARN]: �������at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:224)
[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.inventory.AnvilInventoryTranslator.translateActions(AnvilInventoryTranslator.java:114)
[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67)
[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58)
[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[06:45:14 WARN]: �������at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45)
[06:45:14 WARN]: �������at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139)
[06:45:14 WARN]: �������at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:45:14 WARN]: �������at java.lang.Thread.run(Thread.java:748)

[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.inventory.AnvilInventoryTranslator.translateActions(AnvilInventoryTranslator.java:114)
[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:67)
[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58)
[06:45:14 WARN]: �������at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[06:45:14 WARN]: �������at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:45)
[06:45:14 WARN]: �������at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:139)
[06:45:14 WARN]: �������at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:46)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278)
[06:45:14 WARN]: �������at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279)
[06:45:14 WARN]: �������at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[06:45:14 WARN]: �������at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:45:14 WARN]: �������at java.lang.Thread.run(Thread.java:748)

**Comment by DoctorMacc** [comment]
I'm closing this and reopening the other.
