### ISSUE TITLE
ProtocolLib kicks Bedrock players when they join

### ISSUE THREAD

**Issue by hyperdefined** [GeyserMC/Geyser#1141]
**Describe the bug**
Using latest [ProtocolLib](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) will kick Bedrock players, preventing them from joining. This is either a Geyser bug or ProtocolLib bug. I was told to report here first if anyone wants to look into it.

**To Reproduce**
1. Install the latest ProtocolLib (476 is the latest as of writing this.)
2. Connect to the server.
3. Remove the plugin, and issue goes away.

**Server Version**
This server is running CraftBukkit version git-Spigot-379750e-f26d8e8 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-bf238f5) (Java: 1.16.2, Bedrock: 1.16.20)
Using Floodgate build 25.

**Minecraft: Bedrock Edition Version**
Using the latest version of Bedrock 1.16.20.

**Additional Context**
https://dump.geysermc.org/780kjau5pAr744WMLaZusQupzOtAoqnV
This is the error that it sends in console:
```
[04:20:19] [Network Listener - #0/INFO]: [Geyser-Spigot] /PLAYER IP:51770 tried to connect!
[04:20:20] [Network Listener - #0/INFO]: [Geyser-Spigot] Player connected with username hyperdefined
[04:20:23] [Network Listener - #0/INFO]: [Geyser-Spigot] Attempting to login using floodgate mode... authentication will be encrypted.
[04:20:23] [Thread-14/INFO]: [Geyser-Spigot] Loaded Floodgate key!
[04:20:24] [nioEventLoopGroup-2-2/INFO]: [Geyser-Spigot] hyperdefined (logged in as: hyperdefined) has connected to remote java server on address 172.18.0.4
[04:20:24] [nioEventLoopGroup-2-2/INFO]: [Geyser-Spigot] hyperdefined has disconnected from remote Java server on address 172.18.0.4 because of Connection closed.
[04:20:24] [Netty Epoll Server IO #1/INFO]: [floodgate-bukkit] Added _hyperdefined 00000000-0000-0000-0009-01f0fa26ebe1
[04:20:24] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 3, length: 104 (expected: range(0, 14))
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:88)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:20:24] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: index: 3, length: 104 (expected: range(0, 14))
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1362)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1357)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.PooledUnsafeDirectByteBuf.nioBuffer(PooledUnsafeDirectByteBuf.java:324)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:769)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1222)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.PacketDataSerializer.toString(PacketDataSerializer.java:1077)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.PacketDataSerializer.e(PacketDataSerializer.java:323)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.PacketHandshakingInSetProtocol.a(PacketHandshakingInSetProtocol.java:17)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.PacketDecoder.decode(SourceFile:40)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	... 30 more
[04:20:24] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: Index: 121, Size: 1
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:20:24] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.IndexOutOfBoundsException: Index: 121, Size: 1
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at java.util.ArrayList.get(ArrayList.java:435)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.EnumProtocol$a.a(SourceFile:387)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.EnumProtocol.a(SourceFile:429)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_16_R2.PacketDecoder.decode(SourceFile:34)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:518)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[04:20:24] [Netty Epoll Server IO #1/WARN]: 	... 30 more
[04:20:24] [Network Listener - #0/INFO]: [Geyser-Spigot] Bedrock user with ip: /PLAYER IP has disconnected for reason CLOSED_BY_REMOTE_PEER
```

**Comment by hyperdefined** [comment]
This issue doesn't seem to happen anymore, I created a new server with new configurations and had ProtocolLib installed. Not sure what caused this, but it seems fine now.
