### ISSUE TITLE
java.lang.IllegalStateException: No PacketCodec is set!

### ISSUE THREAD

**Issue by averyanalex** [GeyserMC/Geyser#1147]
**Describe the bug**
When I try to connect from MCPE, I get this:
```
[16:16:00 ERROR]: [com.nukkitx.network.raknet.RakNetServer] An exception occurred in RakNet
java.lang.IllegalStateException: No PacketCodec is set!
at com.nukkitx.network.util.Preconditions.checkState(Preconditions.java:497) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:102) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockSession.sendPacketImmediately(BedrockSession.java:88) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockServerSession.disconnect(BedrockServerSession.java:35) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockServerSession.disconnect(BedrockServerSession.java:23) ~[?:?]
at org.geysermc.connector.network.session.UpstreamSession.disconnect(UpstreamSession.java:58) ~[?:?]
at org.geysermc.connector.network.session.GeyserSession.disconnect(GeyserSession.java:472) ~[?:?]
at org.geysermc.connector.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:59) ~[?:?]
at com.nukkitx.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:21) ~[?:?]
at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

Debug: https://dump.geysermc.org/ME33R9HWcBw6zfzOYr1tRdArTiSVuRC6

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**
This server is running Paper version git-Paper-378 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
This server is running Geyser version 1.1.0 (git-master-bf238f5) (Java: 1.16.2, Bedrock: 1.16.20). No floodgate

**Minecraft: Bedrock Edition Version**
1.14.60 PE, not official.

**Additional Context**

**Comment by rtm516** [comment]
Please update your bedrock version we only support 1.16.x currently. I will leave this issue open as it needs to be fixed.
