### ISSUE TITLE
Could Not Look Up Profile For Bedrock Players

### ISSUE THREAD

**Issue by xXTeraXx** [GeyserMC/Geyser#1197]
**Describe the bug**
I don't believe I should be afraid of this but my server has been crashing recently So I looked in the logs and saw this warning

[22:43:43] [User Authenticator #1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@1551dc9[id=00000000-0000-0000-0009-01fa32120a93,name=*Rahul201,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationUnavailableException: Cannot contact authentication server
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:104) ~[patched_1.16.1.jar:git-Paper-135]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186) ~[patched_1.16.1.jar:git-Paper-135]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[patched_1.16.1.jar:git-Paper-135]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:179) ~[patched_1.16.1.jar:git-Paper-135]
	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[patched_1.16.1.jar:git-Paper-135]
	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:186) ~[patched_1.16.1.jar:git-Paper-135]
	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:179) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:313) ~[patched_1.16.1.jar:git-Paper-135]
	at net.minecraft.server.v1_16_R1.LoginListener$1.run(LoginListener.java:212) ~[patched_1.16.1.jar:git-Paper-135]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at

This is a bedrock player btw

**To Reproduce**
Get a spigot 1.16.1/2 server and then install multiverse-core and Skywars reloaded updated Link here https://www.spigotmc.org/resources/skywarsreloaded-updated-recoded-1-16-support-new-features-1-8x-1-16x.69436/
The skywars plugin enables Legacy Material Support
Also I am using geyser bungee cord this only happens on the server I call s1 it is a skywars creative kitpvp amd duels server

**Expected behavior**
Kinda self explanatory but I do not want this warning to happen 

**Screenshots / Videos**
N/A

**Server Version**
Spigot/Paper 1.16.2 (I've tried both)

**Geyser Version**
I am using Floodgate as my auth and I am using geyser version 1.1.0 
**Minecraft: Bedrock Edition Version**
1.16.20 (Viaversion)

**Additional Context**
 https://dump.geysermc.org/38Zvrf67I0SVwmTCdzm9juzR4dE4p6Xb
(The server has been restarted since then)
I know that multiverse has not been updated for 1.16.1/2 also I'm using Skywars reloaded updated Duels LaggRemover Essentials KitPVP Citizens CitizensCMD Old Combat and World Edit

**Comment by DoctorMacc** [comment]
Can Java players connect?

**Comment by xXTeraXx** [comment]
Yes java players can connect fine

**Comment by Chew** [comment]
We haven't had any recent reports of this, so we're gonna assume the issue is resolved. If you're having issues, feel free to let us know by opening a new issue. Thank you for your contributions!
