### ISSUE TITLE
No inventory to see upon login: shulker boxes incorrectly translated?

### ISSUE THREAD

**Issue by AryToNeX** [GeyserMC/Geyser#1220]
**Describe the bug**
Players having shulker boxes in their inventory won't see their inventory upon login.

**To Reproduce**

1. Log in to the server via Geyser while having a shulkerbox already in your inventory.

**Expected behavior**
The player should have their inventory visible upon login.

**Server Version**
Paper version git-Paper-160 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.1.0 (git-master-37c4192) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100)

**Minecraft: Bedrock Edition Version**
1.16.20

**Additional Context**
```
[04:31:47 ERROR] Impossibile tradurre il pacchetto ServerWindowItemsPacket
java.lang.NullPointerException: null
        at org.geysermc.connector.network.translators.item.translators.nbt.ShulkerBoxItemTranslator.translateToBedrock(ShulkerBoxItemTranslator.java:4
6) ~[Geyser.jar:?]
        at org.geysermc.connector.network.translators.item.ItemTranslator.translateToBedrock(ItemTranslator.java:142) ~[Geyser.jar:?]
        at org.geysermc.connector.network.translators.inventory.PlayerInventoryTranslator.updateInventory(PlayerInventoryTranslator.java:62) ~[Geyser.jar:?]  
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:54) ~[Geyser.jar:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37) ~[Geyser.jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95) [Geyser.jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:456) [Geyser.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
> java.lang.NullPointerException
        at org.geysermc.connector.network.translators.item.translators.nbt.ShulkerBoxItemTranslator.translateToBedrock(ShulkerBoxItemTranslator.java:46)
        at org.geysermc.connector.network.translators.item.ItemTranslator.translateToBedrock(ItemTranslator.java:142)
        at org.geysermc.connector.network.translators.inventory.PlayerInventoryTranslator.updateInventory(PlayerInventoryTranslator.java:62)
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:54)
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37)
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95)
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:456)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

I am a ShulkerPacks user.
A dump is in:
https://dump.geysermc.org/Ye8ClNOTJxFsGKxf2HwEQEsY5AKgzpkM

**Comment by DoctorMacc** [comment]
Link to the plugin, and server version? Looks like this is an easy fix so I just want to confirm it.

**Comment by AryToNeX** [comment]
@DoctorMacc this is the plugin: https://www.spigotmc.org/resources/shulker-backpacks-1-13-1-16.67466/
