### ISSUE TITLE
Floodgate-bukkit not working properly

### ISSUE THREAD

**Issue by QPCrummer** [GeyserMC/Geyser#1235]
31.08 21:41:38 [Server] Server thread/FATAL Error occurred while disabling floodgate-bukkit v1.0-SNAPSHOT (Is it up to date?)
31.08 21:41:38 [Server] INFO java.lang.NullPointerException: null
31.08 21:41:38 [Server] INFO at org.geysermc.floodgate.BukkitPlugin.onDisable(BukkitPlugin.java:68) ~[?:?]
31.08 21:41:38 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Bukkit4Fabric-1.16.2%20(2).jar:?]
31.08 21:41:38 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[Bukkit4Fabric-1.16.2%20(2).jar:?]
31.08 21:41:38 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[Bukkit4Fabric-1.16.2%20(2).jar:?]
31.08 21:41:38 [Server] INFO at org.geysermc.floodgate.BukkitPlugin.onEnable(BukkitPlugin.java:47) ~[?:?]
------------------------------------------------------------
I have the latest version of floodgate. I'm playing in 1.16.2.

**To Reproduce**
Load a 1.16.2 game with geyser and floodgate
**Expected behavior**
It says it didn't load and doesn't generate any files.

**Server Version**
his server is running Bukkit4Fabric version git-Bukkit4Fabric-UNKNOWN (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Geyser Version**
1.1.0 (git-master-2f9ff0c) (Java: 1.16.2, Bedrock: 1.16.0 - 1.16.100). I am using craft bukkit/spigot

**Minecraft: Bedrock Edition Version**
None(It would be 1.16.20)

**Comment by DoctorMacc** [comment]
This is a Floodgate issue, so I shall transfer it over.
