### ISSUE TITLE
Custom Merchant Inventory Does Not Open

### ISSUE THREAD

**Issue by chuushi** [GeyserMC/Geyser#1256]
**Describe the bug**
The custom, plugin-added merchant/villager trade inventory does not open.

**To Reproduce**
1. Start server with a plugin that has a custom, villager-less merchant inventory
2. Trigger any action to open the said merchant inventory.

**Expected behavior**
On Java edition, the merchant inventory opens and you can proceed to the trade process normally. Nothing happens on Bedrock client.

**Screenshots / Videos**
on Java edition, it shows this inventory GUI.
![image](https://user-images.githubusercontent.com/13530989/92319606-3f335000-efe8-11ea-8cf9-a86b51c3b579.png)

No such inventory opens up in Bedrock edition.

**Server Version**
Paper 1.16.2 build 184

**Geyser Version**
Geyser 1.1.0 (git-master-d47360d)

**Minecraft: Bedrock Edition Version**
v1.16.40 on Windows 10

**Additional Context**
Dump: https://dump.geysermc.org/HhibjqTIIilgs5EEvI84Pd8YBufqpRdL
Plugin with merchant inventory: https://github.com/chuushi/BeaconShrine
  - Mercahnt inventory code in question: [ShrineMultiblock.openMerchant()](https://github.com/chuushi/BeaconShrine/blob/aa43dcfea1e38e811fae3c7491ef0508a997d0be/src/main/java/sh/chuu/mc/beaconshrine/shrine/ShrineMultiblock.java#L262)

**Comment by DoctorMacc** [comment]
Hello! I tried to use the linked plugin, but couldn't figure it out. Is there a quick setup guide I can follow?

**Comment by chuushi** [comment]
Hi, I can compile a simple plugin with minimal code required for this later unless someone else does before me.

**Comment by DoctorMacc** [comment]
That would be lovely!

**Comment by Camotoy** [comment]
I believe this should be fixed since the inventory rewrite. If you are still having issues, let us know! Thanks!

**Comment by Kenuux** [comment]
@Camotoy It actually seems that Custom Merchants are still not functional. Here is the error that comes up:
```[12:59:56 ERROR] Could not translate packet ClientboundMerchantOffersPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getDirtyMetadata()" because "villager" is null
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:63) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:50) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
> java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getDirtyMetadata()" because "villager" is null
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:63)
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaMerchantOffersTranslator.translate(JavaMerchantOffersTranslator.java:50)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Kenuux** [comment]
Fixed
<img width="608" alt="grafik" src="https://user-images.githubusercontent.com/12764339/144752627-2703ad9a-1951-4d23-8649-a3f36232a073.png">
