### ISSUE TITLE
Issue when i try to join from my phone

### ISSUE THREAD

**Issue by Hemonios** [GeyserMC/Geyser#1310]
**Describe the bug**
 [com.nukkitx.network.raknet.RakNetServer] An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV8.deserialize(BedrockWrapperSerializerV8.java:78) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
        at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.util.zip.Inflater.inflateBytes(Native Method) ~[?:1.8.0_251]
        at java.util.zip.Inflater.inflate(Unknown Source) ~[?:1.8.0_251]
        at com.nukkitx.natives.zlib.JavaInflater.inflate(JavaInflater.java:34) ~[?:?]
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:58) ~[?:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV8.deserialize(BedrockWrapperSerializerV8.java:56) ~[?:?]
        ... 23 more

I made a spigot 1.16.2 server on my pc and put the geyser-spigot.jar into my plugins folder, from my phone the server gets pinged but when i try to join i get the error

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

CraftBukkit version git-Spigot-2740d5a-890130b (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**

Geyser versione 1.1.0 (git-master-99e72f3) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**

Alpha 1.0.4.0 GUI3

**Additional Context**

https://dump.geysermc.org/1coEnRod8QdQqfZ9qfNSirV6karfJB4q

**Comment by soshimee** [comment]
Alpha 1.0.4.0 GUI3? What kind of version is that?

**Comment by byquanton** [comment]
Quite an old one: https://minecraft.gamepedia.com/Pocket_Edition_alpha_1.0.4.0
@Hemonios Geyser is currently compatible with 1.16.0 - 1.16.20. Why should they add support for the Alpha of the Pocket Edition?

**Comment by RednedEpic** [comment]
Please follow the issue template. Whatever "Alpha 1.0.4.0 GUI3" is as well will not work with Geyser... we only support 1.16.0 - 1.16.40.
