### ISSUE TITLE
Can't join local server (versions BE 1.16.30.53 beta/JE 1.16.3)

### ISSUE THREAD

**Issue by 4ifi** [GeyserMC/Geyser#1342]
[23:12:31 INFO] ******************************************
[23:12:31 INFO]
[23:12:31 INFO] Загрузка Geyser версии 1.1.0 (git-master-d9b05f5)
[23:12:31 INFO]
[23:12:31 INFO] ******************************************
[23:12:36 INFO] Geyser запущен на 0.0.0.0:19132
[23:12:36 INFO] Выполнено (5,319сек.)! Используйте команду /geyser help для помощи!
[23:12:36 WARN] Geyser переводит движения Bedrock не идеально! Использование Geyser на серверах с анти-читом может привести к бану.
[23:12:40 INFO] /127.0.0.1:63970 попытался подключиться!
[23:12:41 INFO] Подключен игрок с именем пользователя miha5super
[23:12:44 INFO] Попытка входа используя оффлайн режим... аутентификация отключена.
[23:12:44 INFO] miha5super (вошёл как: miha5super) подключился к удалённому java серверу по адресу 127.0.0.1
[23:12:45 INFO] miha5super отключился от удалённого Java сервера 127.0.0.1 по причине Login failed: Invalid login session.
> com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException:
        at com.github.steveice10.mc.auth.util.HTTP.checkForError(HTTP.java:97)
        at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:75)
        at com.github.steveice10.mc.auth.service.SessionService.joinServer(SessionService.java:68)
        at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:66)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
        at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:364)
        at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
[23:12:45 INFO] Bedrock пользователь с ip: /127.0.0.1 отключился по причине CLOSED_BY_REMOTE_PEER
>

**Comment by RednedEpic** [comment]
Please follow the issue template.

**Comment by DoctorMacc** [comment]
Please join our Discord for assistance on these kinds of errors.
