### ISSUE TITLE
Bedrock edition unable to connect because of an older Java version (or something else)

### ISSUE THREAD

**Issue by MinecraftPlayerPC** [GeyserMC/Geyser#1377]
Hello,
So I have used the geyser plugin on my 1.16.2 spigot server, after I am all done and I start trying to connect to it from my phone,
it throws a lot of errors at me and doesn't connect, if you understand what does this mean then try explaining to me what's the problem.
I use an old version of java because of a driver issue (Java version: 8u45).
The errors:
[22:42:21] [Network Listener - #1/ERROR]: An exception occurred in RakNet
java.lang.AssertionError: Expected AES to be available
        at com.nukkitx.natives.aes.JavaAes.<init>(JavaAes.java:26) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.natives.aes.JavaAes$$Lambda$3964/462224221.get(Unknown Source) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.enableEncryption(BedrockSession.java:207) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.utils.LoginEncryptionUtils.startEncryptionHandshake(LoginEncryptionUtils.java:152) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.utils.LoginEncryptionUtils.encryptConnectionWithCert(LoginEncryptionUtils.java:137) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.utils.LoginEncryptionUtils.encryptPlayerConnection(LoginEncryptionUtils.java:99) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:73) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:21) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:285) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[Geyser-Spigot.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [Geyser-Spigot.jar:?]
        at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Spigot.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]

**Comment by DoctorMacc** [comment]
Unfortunately that AES error is a limitation of older Java versions. If you're running your own server, and assuming the driver thing is graphics-related you should be able to download multiple instances of Java; use a new one from https://adoptopenjdk.net/ alongside the one you already use. Otherwise for the time being this is likely a won't fix due to limitations beyond our control.

**Comment by MinecraftPlayerPC** [comment]
> Unfortunately that AES error is a limitation of older Java versions. If you're running your own server, and assuming the driver thing is graphics-related you should be able to download multiple instances of Java; use a new one from https://adoptopenjdk.net/ alongside the one you already use. Otherwise for the time being this is likely a won't fix due to limitations beyond our control.

yeah I knew it was not going to work because of the Java version, I will try the workaround that you told me.

**Comment by MinecraftPlayerPC** [comment]
> Unfortunately that AES error is a limitation of older Java versions. If you're running your own server, and assuming the driver thing is graphics-related you should be able to download multiple instances of Java; use a new one from https://adoptopenjdk.net/ alongside the one you already use. Otherwise for the time being this is likely a won't fix due to limitations beyond our control.

The workaround actually worked, thanks man,
now I can make minecraft run through the old version of java and the server through openjdk.
