### ISSUE TITLE
error using velocity

### ISSUE THREAD

**Issue by MrGeorgen** [GeyserMC/Geyser#1383]
sorry for using a template, but it doesn't really fit. I'm not sure if it is bug or config error. I tried asking for support at the discord server, but the logs are to large
bedrock players fly in a empty world.
on the velocity server at startup I get the following error:
```
[21:51:04 WARN] [org.geysermc.platform.velocity.shaded.reflections.Reflections]: given scan urls are empty.
ration
[21:51:04 WARN] [org.geysermc.platform.velocity.shaded.reflections.Reflections]: given scan urls are empty.
ration
[21:51:06 WARN] [org.geysermc.platform.velocity.shaded.reflections.Reflections]: given scan urls are empty.
ration
[21:51:06 INFO] [geyser]: Started Geyser on 0.0.0.0:19132
[21:51:06 INFO] [geyser]: Done (19.356s)! Run /geyser help for help!
[21:51:06 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[21:51:06 ERROR]: #1:
java.lang.NoSuchMethodError: com.velocitypowered.api.command.CommandManager.register(Ljava/lang/String;Lcom
mand/Command;[Ljava/lang/String;)V
        at org.geysermc.floodgate.VelocityPlugin.onProxyInitialization(VelocityPlugin.java:96) ~[?:?]
        at net.kyori.event.asm.generated.9928023442.VelocityPlugin-onProxyInitialization-ProxyInitializeEve
ce) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethod
:148) ~[velocity.jar:1.0.11-SNAPSHOT (git-8238865b-b246)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.0.11-SNAPSHOT (git
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~
PSHOT (git-8238865b-b246)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:11
-SNAPSHOT (git-8238865b-b246)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_251]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
[21:51:06 INFO]: Listening on /0.0.0.0:25565
```
error on velocity if a bedrock player connects:
```
[18:48:41] [nioEventLoopGroup-6-2/INFO]: MCbos31YT has disconnected from remote Java server on address 144.91.69.11 because of Connection closed.
[18:48:41] [Network Listener - #1/INFO]: Bedrock user with ip: /80.208.184.247 has disconnected for reason
CLOSED_BY_REMOTE_PEER
[18:49:13] [Network Listener - #1/INFO]: /80.208.184.247:58958 tried to connect!
[18:49:13] [Network Listener - #1/INFO]: Player connected with username MCbos31YT
[18:49:19] [Network Listener - #1/INFO]: Attempting to login using floodgate mode... authentication will be encrypted.
[18:49:19] [Thread-149/INFO]: Loaded Floodgate key!
[18:49:19] [nioEventLoopGroup-7-2/INFO]: MCbos31YT (logged in as: MCbos31YT) has connected to remote java server on address 144.91.69.11
[18:49:19] [Velocity Event Executor - #2/ERROR]: Oct 09, 2020 6:49:19 PM org.geysermc.floodgate.VelocityPlugin onConnectionHandshake
[18:49:19] [Velocity Event Executor - #2/ERROR]: INFO: Added *MCbos31YT 00000000-0000-0000-0009-01f9c3c3d0a6
[18:49:49] [Netty epoll Worker #3/ERROR]: [initial connection] /144.91.69.11:56614: read timed out
[18:49:49] [Netty epoll Worker #3/INFO]: [initial connection] /144.91.69.11:56614 has disconnected
[18:49:49] [nioEventLoopGroup-7-2/INFO]: MCbos31YT has disconnected from remote Java server on address 144.91.69.11 because of Connection closed.
[18:49:49] [Network Listener - #1/INFO]: Bedrock user with ip: /80.208.184.247 has disconnected for reason
CLOSED_BY_REMOTE_PEER
```
on lobby server it seems like the player is not connected at all
flooadgate config:
```
# In Floodgate bedrock player data is send encrypted
# The following value should point to the key Floodgate generated.
# The public key should be used for the Geyser(s) and the private key for the Floodgate(s)
key-file-name: key.pem

# Floodgate prepends a prefix to bedrock usernames to avoid conflicts
# However, certain conflicts can cause issues with some plugins so this prefix is configurable using the property below
# It is recommended to use a prefix that does not contain alphanumerical to avoid the possibility of duplicate usernames.
username-prefix: "*"

# Should spaces be replaced with '_' in bedrock usernames?
replace-spaces: true

# Should Velocity send the bedrock player data to the servers it is connecting to?
# This requires Floodgate to be installed on the servers.
# You'll get kicked if you don't use the plugin. The default value is false because of it
send-floodgate-data: false

disconnect:
  # The disconnect message Geyser users should get when connecting
  # to the server with an invalid key
  invalid-key: Please connect through the official Geyser
  # The disconnect message Geyser users should get when connecting
  # to the server with the correct key but not with the correct data format
  invalid-arguments-length: Expected {0} arguments, got {1}. Is Geyser up-to-date?

# Configuration for player linking
player-link:
  # Whether to enable the linking system. Turning this off will prevent
  # players from using the linking feature even if they are already linked.
  enable: false
  # The type of storage system you want to use
  # Currently implemented: SQLite
  type: sqlite
  # Whether to allow the use of /linkaccount and /unlinkaccount
  # You can also use allow specific people to use the commands using the
  # permissions floodgate.linkaccount and floodgate.unlinkaccount.
  # This is only for linking, already connected people will stay connected
  allow-linking: true
  # The amount of time until a link code expires in seconds
  link-code-timeout: 300
```
geyser config:
```
# --------------------------------
# Geyser Configuration File
#
# A bridge between Minecraft: Bedrock Edition and Minecraft: Java Edition.
#
# GitHub: https://github.com/GeyserMC/Geyser
# Discord: https://discord.geysermc.org/
# --------------------------------

bedrock:
  # The IP address that will listen for connections.
  # There is no reason to change this unless you want to limit what IPs can connect to your server.
  address: 0.0.0.0
  # The port that will listen for connections
  port: 19132
  # Some hosting services change your Java port everytime you start the server and require the same port to be used for Bedrock.
  # This option makes the Bedrock port the same as the Java port every time you start the server.
  # This option is for the plugin version only.
  clone-remote-port: false
  # The MOTD that will be broadcasted to Minecraft: Bedrock Edition clients. This is irrelevant if "passthrough-motd" is set to true
  motd1: "GeyserMC"
  motd2: "Another GeyserMC forced host."
  # The Server Name that will be sent to Minecraft: Bedrock Edition clients. This is visible in both the pause menu and the settings menu.
  server-name: "Geyser"
remote:
  # The IP address of the remote (Java Edition) server
  # If it is "auto", for standalone version the remote address will be set to 127.0.0.1,
  # for plugin versions, Geyser will attempt to find the best address to connect to.
  address: auto
  # The port of the remote (Java Edition) server
  # For plugin versions, if address has been set to "auto", the port will also follow the server's listening port.
  port: 25565
  # Authentication type. Can be offline, online, or floodgate (see https://github.com/GeyserMC/Geyser/wiki/Floodgate).
  auth-type: floodgate

# Floodgate uses encryption to ensure use from authorised sources.
# This should point to the public key generated by Floodgate (Bungee or CraftBukkit)
# You can ignore this when not using Floodgate.
floodgate-key-file: public-key.pem

## the Xbox/MCPE username is the key for the Java server auth-info
## this allows automatic configuration/login to the remote Java server
## if you are brave/stupid enough to put your Mojang account info into
## a config file
#userAuths:
#  bluerkelp2: # MCPE/Xbox username
#    email: not_really_my_email_address_mr_minecrafter53267@gmail.com # Mojang account email address
#    password: "this isn't really my password"
#
#  herpderp40300499303040503030300500293858393589:
#    email: herpderp@derpherp.com
#    password: dooooo

# Bedrock clients can freeze when opening up the command prompt for the first time if given a lot of commands.
# Disabling this will prevent command suggestions from being sent and solve freezing for Bedrock clients.
command-suggestions: true

# The following three options enable "ping passthrough" - the MOTD, player count and/or protocol name gets retrieved from the Java server.
# Relay the MOTD from the remote server to Bedrock players.
passthrough-motd: true
# Relay the protocol name (e.g. BungeeCord [X.X], Paper 1.X) - only really useful when using a custom protocol name!
# This will also show up on sites like MCSrvStatus. <mcsrvstat.us>
passthrough-protocol-name: true
# Relay the player count and max players from the remote server to Bedrock players.
passthrough-player-counts: true
# Enable LEGACY ping passthrough. There is no need to enable this unless your MOTD or player count does not appear properly.
# This option does nothing on standalone.
legacy-ping-passthrough: false
# How often to ping the remote server, in seconds. Only relevant for standalone or legacy ping passthrough.
# Increase if you are getting BrokenPipe errors.
ping-passthrough-interval: 3

# Maximum amount of players that can connect
max-players: 100

# If debug messages should be sent through console
debug-mode: false

# Thread pool size
general-thread-pool: 32

# Allow third party capes to be visible. Currently allowing:
# OptiFine capes, LabyMod capes, 5Zig capes and MinecraftCapes
allow-third-party-capes: true

# Allow third party deadmau5 ears to be visible. Currently allowing:
# MinecraftCapes
allow-third-party-ears: false

# Allow a fake cooldown indicator to be sent. Bedrock players do not see a cooldown as they still use 1.8 combat
show-cooldown: true

# The default locale if we dont have the one the client requested. Uncomment to not use the default system language.
# default-locale: en_us

# Configures if chunk caching should be enabled or not. This keeps an individual
# record of each block the client loads in. While this feature does allow for a few
# things such as block break animations to show up in creative mode and among others,
# it is HIGHLY recommended you disable this on a production environment as it can eat
# up a lot of RAM. However, when using the Spigot version of Geyser, support for features
# or implementations this allows is automatically enabled without the additional caching as
# Geyser has direct access to the server itself.
cache-chunks: false

# Specify how many days images will be cached to disk to save downloading them from the internet.
# A value of 0 is disabled. (Default: 0)
cache-images: 0

# Bedrock prevents building and displaying blocks above Y127 in the Nether -
# enabling this config option works around that by changing the Nether dimension ID
# to the End ID. The main downside to this is that the sky will resemble that of
# the end sky in the nether, but ultimately it's the only way for this feature to work.
above-bedrock-nether-building: false

# Force clients to load all resource packs if there are any.
# If set to false it allows the user to disconnect from the server if they don't
# want to download the resource packs
force-resource-packs: true

# bStats is a stat tracker that is entirely anonymous and tracks only basic information
# about Geyser, such as how many people are online, how many servers are using Geyser,
# what OS is being used, etc. You can learn more about bStats here: https://bstats.org/.
# https://bstats.org/plugin/server-implementation/GeyserMC
metrics:
  # If metrics should be enabled
  enabled: true
  # UUID of server, don't change!
  uuid: fe9e664d-38a4-43de-8617-9e1a27c38115

# ADVANCED OPTIONS - DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING!

# Geyser updates the Scoreboard after every Scoreboard packet, but when Geyser tries to handle
# a lot of scoreboard packets per second can cause serious lag.
# This option allows you to specify after how many Scoreboard packets per seconds
# the Scoreboard updates will be limited to four updates per second.
scoreboard-packet-threshold: 20

# Allow connections from ProxyPass and Waterdog.
# See https://www.spigotmc.org/wiki/firewall-guide/ for assistance - use UDP instead of TCP.
enable-proxy-connections: false

# The internet supports a maximum MTU of 1492 but could cause issues with packet fragmentation.
# 1400 is the default.
# mtu: 1400

config-version: 4
```
the lobby server is a fabric server with the fabricProxy mod to support velocity. Java players can join fine and because geyser only translates the protocol this should not be a problem

**Comment by toinouH** [comment]
Hello, I see you use velocity 1.0.11 but it will not work.
Use Velocity 1.1.0 (the dev version)

**Comment by MrGeorgen** [comment]
> Hello, I see you use velocity 1.0.11 but it will not work.
> Use Velocity 1.1.0 instead (the dev version)

I still get the same error at startup. What happens if a bedrock join I unfortunately can't test because Minecraft crashes on my phone when I click on xbox live account login button and my friend which uses bedrock sleep. I'll give an update

**Comment by DoctorMacc** [comment]
Please provide a Geyser dump by running `/geyser dump`.

**Comment by MrGeorgen** [comment]
now it works, I figured out I did not rename the new velocity version properly. Maybe you could add a info that velocity 1.1 is required at the readme or at common issues in the wiki

**Comment by DoctorMacc** [comment]
It should already be documented. Either way, glad the issue is fixed!

**Comment by kotx** [comment]
> It should already be documented. Either way, glad the issue is fixed!

I had the same issue, but I don't see it documented anywhere. Maybe make it more accessible?

**Comment by DoctorMacc** [comment]
Huh, I guess it's nowhere on the setup page. I'll add that now.
