### ISSUE TITLE
ping pashtrough issue

### ISSUE THREAD

**Issue by LegacyGamerHD** [GeyserMC/Geyser#142]
**Describe the bug**

add cleanmotd or serverlistplus and anable ping pastrough and you will get 

`[m>[2K 07:11:49 [INFORMATION] [Geyser-BungeeCord] LegacyGamer7025 (logged in as: LegacyGamer7025) has connected to remote java server on address 185.239.237.166
[m>[2K 07:11:49 [INFORMATION] [Geyser-BungeeCord] LegacyGamer7025 has disconnected from remote java server on address blank because of java.io.IOException: Datenübergabe unterbrochen (broken pipe)`

it happens after a random amount of times

**Expected behavior**
i should be able to join

**Screenshots**

**Server version**
latest paper and bungee

**Geyser version**
Jenkins plugin version and my branch bungeecord

**Bedrock version**
1.14.1

**Comment by RednedEpic** [comment]
Please enable debug mode and send the error in hastebin.

**Comment by LegacyGamerHD** [comment]
changing the port and motd shows up again

**Comment by LegacyGamerHD** [comment]
i will give more info if i get it with debug again

**Comment by LegacyGamerHD** [comment]
@RednedEpic  

`Caused by: java.lang.IllegalStateException: key must be lowercase
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-77]
        at com.sk89q.worldedit.registry.Registry.get(Registry.java:49) ~[?:?]
        at com.sk89q.worldedit.registry.NamespacedRegistry.get(NamespacedRegistry.java:47) ~[?:?]
        at com.sk89q.worldedit.world.item.ItemTypes.get(ItemTypes.java:920) ~[?:?]
        at com.sk89q.worldedit.session.SessionManager.setDefaultWand(SessionManager.java:225) ~[?:?]
        at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:175) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.session.AsyncSessionManager.get(AsyncSessionManager.java:113) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:361) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 29 more
[m> 
[K[17:26:30 INFO]: **Obama[0;37;1m [0;33m[[0;31mOwner[0;33m][m [0;37mTheRobLP[0;36;1m: [0;37;1mjoining w/ PE[m
> 
[K[17:26:32 INFO]: TheRobLP lost connection: Disconnected
> 
[K[17:26:34 INFO]: [0;33m[[0;32;1mno-faction[0;33m][m [0;33m[[0;32mMember[0;33m][m [0;37m*LegacyGamer7025[0;36;1m: [0;37;1mis my item corrupt[m
> 
[K[31;1m[17:26:49 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@2f533b6f to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
        at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:603) ~[?:?]
        at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:140) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-77]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-77]
        at com.heirteir.perworldpluginspremium.registeredlisteners.BukkitRegisteredListener.callEvent(BukkitRegisteredListener.java:35) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:425) ~[patched_1.15.2.jar:git-Paper-77]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:421) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1416) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-77]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-77]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 29 more
Caused by: java.lang.IllegalStateException: key must be lowercase
        at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-77]
        at com.sk89q.worldedit.registry.Registry.get(Registry.java:49) ~[?:?]
        at com.sk89q.worldedit.registry.NamespacedRegistry.get(NamespacedRegistry.java:47) ~[?:?]
        at com.sk89q.worldedit.world.item.ItemTypes.get(ItemTypes.java:920) ~[?:?]
        at com.sk89q.worldedit.session.SessionManager.setDefaultWand(SessionManager.java:225) ~[?:?]
        at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:175) ~[?:?]
        at org.primesoft.asyncworldedit.worldedit.session.AsyncSessionManager.get(AsyncSessionManager.java:113) ~[?:?]
        at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:361) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 29 more
`

**Comment by RednedEpic** [comment]
> @RednedEpic
> 
> `Caused by: java.lang.IllegalStateException: key must be lowercase
> at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-77]
> at com.sk89q.worldedit.registry.Registry.get(Registry.java:49) ~[?:?]
> at com.sk89q.worldedit.registry.NamespacedRegistry.get(NamespacedRegistry.java:47) ~[?:?]
> at com.sk89q.worldedit.world.item.ItemTypes.get(ItemTypes.java:920) ~[?:?]
> at com.sk89q.worldedit.session.SessionManager.setDefaultWand(SessionManager.java:225) ~[?:?]
> at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:175) ~[?:?]
> at org.primesoft.asyncworldedit.worldedit.session.AsyncSessionManager.get(AsyncSessionManager.java:113) ~[?:?]
> at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:361) ~[?:?]
> at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
> at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
> at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
> ... 29 more
> �[m>
> �[K[17:26:30 INFO]: **Obama�[0;37;1m �[0;33m[�[0;31mOwner�[0;33m]�[m �[0;37mTheRobLP�[0;36;1m: �[0;37;1mjoining w/ PE�[m
> 
> > 
> 
> �[K[17:26:32 INFO]: TheRobLP lost connection: Disconnected
> 
> > 
> 
> �[K[17:26:34 INFO]: �[0;33m[�[0;32;1mno-faction�[0;33m]�[m �[0;33m[�[0;32mMember�[0;33m]�[m �[0;37m*LegacyGamer7025�[0;36;1m: �[0;37;1mis my item corrupt�[m
> 
> > 
> 
> �[K�[31;1m[17:26:49 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@2f533b6f to handler EventHandler{priority=NORMAL}
> java.lang.reflect.InvocationTargetException: null
> at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
> at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
> at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
> at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
> at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
> at com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:603) ~[?:?]
> at com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:140) ~[?:?]
> at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
> at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-77]
> at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-77]
> at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-77]
> at com.heirteir.perworldpluginspremium.registeredlisteners.BukkitRegisteredListener.callEvent(BukkitRegisteredListener.java:35) ~[?:?]
> at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-77]
> at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:458) ~[patched_1.15.2.jar:git-Paper-77]
> at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:425) ~[patched_1.15.2.jar:git-Paper-77]
> at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:421) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1416) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-77]
> at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-77]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
> Caused by: java.lang.reflect.InvocationTargetException
> at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
> at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
> at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
> ... 29 more
> Caused by: java.lang.IllegalStateException: key must be lowercase
> at com.google.common.base.Preconditions.checkState(Preconditions.java:444) ~[patched_1.15.2.jar:git-Paper-77]
> at com.sk89q.worldedit.registry.Registry.get(Registry.java:49) ~[?:?]
> at com.sk89q.worldedit.registry.NamespacedRegistry.get(NamespacedRegistry.java:47) ~[?:?]
> at com.sk89q.worldedit.world.item.ItemTypes.get(ItemTypes.java:920) ~[?:?]
> at com.sk89q.worldedit.session.SessionManager.setDefaultWand(SessionManager.java:225) ~[?:?]
> at com.sk89q.worldedit.session.SessionManager.get(SessionManager.java:175) ~[?:?]
> at org.primesoft.asyncworldedit.worldedit.session.AsyncSessionManager.get(AsyncSessionManager.java:113) ~[?:?]
> at com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:361) ~[?:?]
> at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source) ~[?:?]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
> at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
> at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
> ... 29 more
> `

Seems entirely unrelated to Geyser altogether. Looks like a WorldEdit issue. Also please send the error from Geyser with debug mode enabled, and **please** use hastebin next time rather than posting here.

**Comment by LegacyGamerHD** [comment]
whoops wrong log

**Comment by LegacyGamerHD** [comment]
am experimenting with bungee right now
