### ISSUE TITLE
Can't connect to any servers

### ISSUE THREAD

**Issue by NotDarkFox** [GeyserMC/Geyser#1448]
I tried to connect to a server on my switch but when i put my acc details and click submit it disconnects me
I tried this on my own server, and also on another server that i don't own
[12:30:13 INFO] ******************************************
[12:30:13 INFO] 
[12:30:13 INFO] Ładowanie Geyser wersja 1.1.0 (git-master-c30cb78)
[12:30:13 INFO] 
[12:30:13 INFO] ******************************************
[12:30:18 INFO] Uruchomiono Geyser o 192.168.1.69:139
[12:30:18 INFO] Wykonano (5,047s)! Użyj komendy -> help jeśli chcesz uzyskać pomoc!
[12:30:18 WARN] Geyser doesn't translate Bedrock movements perfectly! Using Geyser in servers that have an anticheat could get you banned.
[12:31:10 INFO] /192.168.1.64:28466 spróbował się połączyć!
[12:31:11 INFO] Gracz połączony z nickiem NotDarkFox
[12:31:55 INFO] NotDarkFox się rozłączył ze zdalnego serwera java pod adresem 127.0.0.1, ponieważ io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:28748
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:28748
Caused by: java.net.ConnectException: Connection refused: no further information
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:589)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:839)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
[12:31:55 INFO] Gracz Bedrock z ip: /192.168.1.64 rozłączył się z powodu CLOSED_BY_REMOTE_PEER
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1012)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:966)
	at org.geysermc.platform.standalone.gui.GeyserStandaloneGUI.lambda$startUpdateThread$9(GeyserStandaloneGUI.java:293)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
![2020102512385000-11B64E28AD7A49CA9EC8AC007BE858C6](https://user-images.githubusercontent.com/73426991/97106097-edda3f80-16bf-11eb-908f-3af757dd96e7.jpg)

**Comment by DoctorMacc** [comment]
Please join the Geyser Discord, as this is a connection error. You're probably putting the remote address in the wrong location.
