### ISSUE TITLE
PaperSpigot Plugin gives error

### ISSUE THREAD

**Issue by SeniorHeld** [GeyserMC/Geyser#1505]
Hello, 
after starting the server with the plugin inside the pluginsfolder I get the following error:

`[00:46:13 ERROR]: Could not load 'plugins/Geyser-Spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_212]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_212]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_212]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_212]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.4.jar:git-Paper-261]
        ... 6 more`

No `config.yml` is generated. 
Is this normal? Am I doing something wrong?

I have additionally tried Floodgate. 

Sorry for bad english!

**Comment by DoctorMacc** [comment]
Your jarfile is corrupt. Redownload it!

For further support on this, please join our Discord.
