### ISSUE TITLE
ERROR: Login failed: Invalid login session w/ PAPER 1.16.3 AND BEDROCK 1.16.x

### ISSUE THREAD

**Issue by Symeloxk** [GeyserMC/Geyser#1519]
**_Hi, 
this is my version of Minecraft Java: 1.16.3 with paper 
and Bedrock: 1.16.x_**

**_So this is the error log:_**

[06:33:06 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:33:06 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:33:06 WARN]:        at java.lang.Thread.run(Thread.java:748)

_**And In game:**_ Login Failed: attempt ...

So what i've to do?

**Comment by DoctorMacc** [comment]
Please join us on Discord as this is likely a user error. Additionally, that stack trace is incomplete. Thank you!
