### ISSUE TITLE
ERROR: Login failed: Invalid login session.

### ISSUE THREAD

**Issue by Symeloxk** [GeyserMC/Geyser#1520]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

**Geyser Version**

**Minecraft: Bedrock Edition Version**

**Additional Context**

**Comment by Symeloxk** [comment]
This is the full error with debug-mode: true


[06:45:12 WARN]: com.github.steveice10.mc.auth.exception.request.InvalidCredentialsException:
[06:45:12 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.checkForError(HTTP.java:97)
[06:45:12 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:75)
[06:45:12 WARN]:        at com.github.steveice10.mc.auth.service.SessionService.joinServer(SessionService.java:68)
[06:45:12 WARN]:        at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:66)
[06:45:12 WARN]:        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[06:45:12 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[06:45:12 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:364)
[06:45:12 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:45:12 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[06:45:12 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by Symeloxk** [comment]
Finally good but not working on BungeeCord :/
