### ISSUE TITLE
Failed to translate ServerPlayBuiltinSoundPacket

### ISSUE THREAD

**Issue by ArtemPRO-122** [GeyserMC/Geyser#1539]
474 Geyser build
Minecraft Java version: 1.16.4
Minecraft bedrock version: 1.16.40
Error log:
[18:55:02 ERROR] Не удалось перевести пакет ServerPlayBuiltinSoundPacket
java.lang.NullPointerException: null
	at org.geysermc.connector.network.translators.world.block.BlockTranslator.getJavaBlockState(BlockTranslator.java:351) ~[Geyser.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:85) ~[Geyser.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40) ~[Geyser.jar:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser.jar:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:527) [Geyser.jar:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
java.lang.NullPointerException
	at org.geysermc.connector.network.translators.world.block.BlockTranslator.getJavaBlockState(BlockTranslator.java:351)
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:85)
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40)
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:527)
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
	at java.lang.Thread.run(Unknown Source)
[19:04:58 ERROR] Не удалось перевести пакет ServerPlayBuiltinSoundPacket
java.lang.NullPointerException: null
	at org.geysermc.connector.network.translators.world.block.BlockTranslator.getJavaBlockState(BlockTranslator.java:351) ~[Geyser.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:85) ~[Geyser.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40) ~[Geyser.jar:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser.jar:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:527) [Geyser.jar:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
java.lang.NullPointerException
	at org.geysermc.connector.network.translators.world.block.BlockTranslator.getJavaBlockState(BlockTranslator.java:351)
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:85)
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40)
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:527)
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
	at java.lang.Thread.run(Unknown Source)
Geyser Dump:
https://dump.geysermc.org/1LQaViLR8jIquF6EycbZg1TMKOdvKbkh

**Comment by DoctorMacc** [comment]
Thank you for reporting! However, there's not much we can do with this error without context as to how it happened. Next time, please follow the issue template!

(However if you are able to identify how to reproduce this error, I will likely reopen this issue)

**Comment by MrZomka** [comment]
Обнови Гейзер.
