### ISSUE TITLE
Error while loading Geyser-Spigot

### ISSUE THREAD

**Issue by FoxyWolves** [GeyserMC/Geyser#1560]
**Describe the bug**
The Geyser plugin isn't loading properly when starting the server.
"Error occurred while enabling Geyser-Spigot v1.2.0-SNAPSHOT (Is it up to date?)"

I'm relatively new in running such a server, so I have no idea what I should/can do to solve the problem.

**To Reproduce**
I don't know if the error if reproducible, but it occurs to me since the Bedrock update to 1.16.100 yesterday - there was the login message "Outdated Geyser proxy" (or sth like this).
After the Bedrock update I updated my Geyser-Spigor.jar today to the latest version ([Build #487](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/487/))

**Expected behavior**
The plugin should load normally and without errors.

**Screenshots / Videos**
This is what my console output is after starting the server:

> [09:07:32] [Server thread/INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v1.2.0-SNAPSHOT
> [09:07:32] [Server thread/INFO]: [Geyser-Spigot] Auto-loaded Floodgate key
> [09:07:32] [Server thread/WARN]: [Geyser-Spigot] Loaded class org.geysermc.common.PlatformType from floodgate-bukkit v1.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
> [09:07:32] [Server thread/ERROR]: Error occurred while enabling Geyser-Spigot v1.2.0-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: SPIGOT
at org.geysermc.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:114) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-57bbdd8-dea4138]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Server Version**
git-Spigot-57bbdd8-dea4137 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
openjdk version "1.8.0_252"
The server is hosted via Witherhosting. I run ViaVersion and ViaBackwards, too.

**Geyser Version**
[Build #487](https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/487/)

**Minecraft: Bedrock Edition Version**
Tested with Windows10 - 1.16.100

**Additional Context**
No Geyser command is working, so I can't put a dump here.

**Comment by FoxyWolves** [comment]
Okay, I don't know what happened, but I stopped my server again, deleted the Geyser and Floodgate Pluginfiles, downloaded them again and copied into the plugins folder, restarted my server and now it works again without any error or warn message in the console.

**Comment by rtm516** [comment]
This was caused due to a change we made breaking older Floodgate builds with new versions of Geyser, so all that was required was updating the Floodgate plugin jar
