### ISSUE TITLE
I can't login

### ISSUE THREAD

**Issue by mcoo** [GeyserMC/Geyser#1611]
https://dump.geysermc.org/ZKbnRET3ZcUmIC6zFEPKXXwpyPHEqIs7

Console:
"""
[19:03:49 INFO]: [Geyser-Spigot] Player connected with username ZiHang6
[authlib-injector] [INFO] Transformed [com.github.steveice10.mc.auth.service.AuthenticationService] with [Constant URL Transformer]

[19:04:11 WARN]: Exception in thread "Thread-13" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
[19:04:11 WARN]:        at com.google.gson.Gson.assertFullConsumption(Gson.java:863)
[19:04:11 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:826)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.processResponse(HTTP.java:140)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.performPostRequest(HTTP.java:127)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.util.HTTP.makeRequest(HTTP.java:69)
[19:04:11 WARN]:        at com.github.steveice10.mc.auth.service.AuthenticationService.login(AuthenticationService.java:201)
[19:04:11 WARN]:        at com.github.steveice10.mc.protocol.MinecraftProtocol.createAuthServiceForPasswordLogin(MinecraftProtocol.java:284)
[19:04:11 WARN]:        at com.github.steveice10.mc.protocol.MinecraftProtocol.<init>(MinecraftProtocol.java:244)
[19:04:11 WARN]:        at org.geysermc.connector.network.session.GeyserSession.lambda$authenticate$2(GeyserSession.java:417)
[19:04:11 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:04:11 WARN]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
[19:04:11 WARN]:        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
[19:04:11 WARN]:        at com.google.gson.Gson.assertFullConsumption(Gson.java:859)
[19:04:11 WARN]:        ... 9 more
"""

**Comment by FrankHan052176** [comment]
I think the author won't answer you

**Comment by FrankHan052176** [comment]
> I think the author won't answer you

**Comment by rtm516** [comment]
This is not a Geyser issue, its caused by `authlib-injector` sending invalid data to our authentication library. And please follow the issue template next time.
