### ISSUE TITLE
Floodgate Null Point Error

### ISSUE THREAD

**Issue by joseplmartins** [GeyserMC/Geyser#1639]
Im using Geyser-Bungeecord and floodgate-bungeecord as well ip forwarding on bungeecord and same key files on floogate-bukkit, but when a bedrock player joins the server it gets disconnected with this error:

Dump link: https://dump.geysermc.org/leqDFjrmLRIYngDUyVBiQJBTHG3dht29

`
[15:55:30 INFO] [Geyser-BungeeCord]: Could not find packet for ClientToServerHandshakePacket
[15:55:30 INFO] [Geyser-BungeeCord]: Could not find packet for ClientCacheStatusPacket
[15:55:30 INFO] [Geyser-BungeeCord]: Player connected with username AltF4ForFly
[15:55:31 INFO] [Geyser-BungeeCord]: Could not find packet for RequestChunkRadiusPacket
[15:55:31 INFO] [Geyser-BungeeCord]: Could not find packet for TickSyncPacket
[15:55:35 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@63998bf4, id=94, owner=org.geysermc.floodgate.BungeePlugin@42edde25, task=org.geysermc.floodgate.BungeePlugin$$Lambda$463/204763606@3abcf614, delay=0, period=0, running=true) encountered an exception
java.lang.NullPointerException: null
	at org.geysermc.floodgate.util.ReflectionUtil.makeAccessible(ReflectionUtil.java:160) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtil.getValue(ReflectionUtil.java:54) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtil.getValue(ReflectionUtil.java:64) ~[?:?]
	at org.geysermc.floodgate.BungeePlugin.lambda$onPreLogin$0(BungeePlugin.java:115) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:af18705:381]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

Is this a known bug?

**Comment by DoctorMacc** [comment]
This is likely an issue with either nLogin or nAntiBot. If it is the former, we won't try to work around it.
