### ISSUE TITLE
java.lang.AssertionError: Unable to download and extract en_us locale!

### ISSUE THREAD

**Issue by Ivanhai** [GeyserMC/Geyser#1715]
[09:56:04 INFO]: Time elapsed: 20084 ms
[09:56:05 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v1.2.0-SNAPSHOT
[09:56:12 INFO]: [Geyser-Spigot] ******************************************
[09:56:12 INFO]: [Geyser-Spigot] 
[09:56:12 INFO]: [Geyser-Spigot] Loading Geyser version 1.2.0-SNAPSHOT (git-master-c921500)
[09:56:12 INFO]: [Geyser-Spigot] 
[09:56:12 INFO]: [Geyser-Spigot] ******************************************
[09:58:24 INFO]: [Geyser-Spigot] Failed to load locale asset cache: Unrecognized token 'launchermeta': was expecting ('true', 'false' or 'null')
 at [Source: (String)"launchermeta.mojang.com"; line: 1, column: 13]
[09:58:24 INFO]: [Geyser-Spigot] Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)
[09:58:24 ERROR]: Error occurred while enabling Geyser-Spigot v1.2.0-SNAPSHOT (Is it up to date?)
java.lang.AssertionError: Unable to download and extract en_us locale!
        at org.geysermc.connector.utils.LocaleUtils.downloadEN_US(LocaleUtils.java:256) ~[?:?]
        at org.geysermc.connector.utils.LocaleUtils.downloadLocale(LocaleUtils.java:165) ~[?:?]
        at org.geysermc.connector.utils.LocaleUtils.downloadAndLoadLocale(LocaleUtils.java:124) ~[?:?]
        at org.geysermc.connector.utils.LocaleUtils.<clinit>(LocaleUtils.java:60) ~[?:?]
        at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:142) ~[?:?]
        at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:359) ~[?:?]
        at org.geysermc.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:121) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-332]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-332]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-332]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-332]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-332]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:469) ~[patched_1.16.4.jar:git-Paper-332]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-332]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-332]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-332]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NullPointerException
        at org.geysermc.connector.utils.LocaleUtils.downloadEN_US(LocaleUtils.java:225) ~[?:?]
        ... 16 more
[09:58:24 INFO]: [Geyser-Spigot] Disabling Geyser-Spigot v1.2.0-SNAPSHOT

help

**Comment by rtm516** [comment]
This issue is better suited for discord.
Also next time use the issue template.
See https://github.com/GeyserMC/Geyser/wiki/Common-Issues#failed-to-load-locale-asset-cache-unrecognized-token-cannot as that's likely the same issue
