### ISSUE TITLE
Enchanting Issue with (Level 30 Enchantments/And Other Levels)

### ISSUE THREAD

**Issue by red0fireus** [GeyserMC/Geyser#1751]
**Describe the bug**
Bedrock: Bug with enchanting.
Enchantments are not showing up in the table.
Level 30 enchantments (We think)

**To Reproduce**
1) Get Enchantment Levels
2) Place an Enchantment Table down
3) Open the Enchantment Table
4) Tested with Diamond Helmet, Diamond Chest plate, Diamond Leggings, and Diamond Boots

**Expected behavior**
There should be 3 different enchantment options but 2 show no enchantments and it throws an error in Console. (Can change How many enchantments show but mostly 2 are missing)

**Screenshots / Videos**
![Screenshot 2020-12-28 144603](https://user-images.githubusercontent.com/7908370/103242317-702eec00-491b-11eb-897c-0ad7c9d958f1.png)

**Server Version**
Paper Version git-Paper-350 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

**Geyser Version**
Geyser 1.2.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
1.16.100/1.16.101 - 1.16.200.5

**Additional Context**
Using Java 11

**Error Message**
`[14:49:34 WARN]: [Geyser-Spigot] Could not translate packet ServerWindowPropertyPacket
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 38
        at org.geysermc.connector.network.translators.inventory.EnchantmentInventoryTranslator.updateProperty(EnchantmentInventoryTranslator.java:131) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowPropertyTranslator.translate(JavaWindowPropertyTranslator.java:46) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowPropertyTranslator.translate(JavaWindowPropertyTranslator.java:35) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:562) ~[?:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by Camotoy** [comment]
This will be resolved with the inventory rewrite.

**Comment by red0fireus** [comment]
Is there a time frame? I'm just curious.

**Comment by Camotoy** [comment]
There is no timeframe, but we are hopeful for a test build to come out soon. Please join our discord and run `!rank geysernews` to get notified when such a build is available.
