### ISSUE TITLE
Reload cause login problems

### ISSUE THREAD

**Issue by DunoCZ** [GeyserMC/Geyser#1789]
When you reload server then bedrock players can't login.
I'm using floodgate, tried set manually java ip to 127.0.0.1, switching through java versions and "distributions" (like AdoptOpenJDK etc.)
`[16:59:41] [nioEventLoopGroup-2-2/INFO]: [Geyser-Spigot] DunoCZ (logged in as: DunoCZ) has connected to remote java server on address 127.0.0.1
[16:59:41] [nioEventLoopGroup-2-2/WARN]: [floodgate-bukkit] Loaded class org.geysermc.floodgate.util.BedrockData from Geyser-Spigot v1.2.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
[16:59:42] [nioEventLoopGroup-2-2/WARN]: [Geyser-Spigot] Downstream packet error! Invalid packet id: 25
[16:59:42] [Server thread/INFO]: /127.0.0.1:43496 lost connection: Internal Exception: java.lang.IllegalStateException: zip file closed
[16:59:42] [nioEventLoopGroup-2-2/INFO]: [Geyser-Spigot] DunoCZ has disconnected from remote Java server on address 127.0.0.1 because of java.io.IOException: Connection reset by peer
[16:59:42] [nioEventLoopGroup-2-2/WARN]: java.io.IOException: Connection reset by peer
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at org.geysermc.platform.spigot.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:59:42] [nioEventLoopGroup-2-2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[16:59:42] [Network Listener - #1/INFO]: [Geyser-Spigot] Bedrock user with ip: /10.0.0.3 has disconnected for reason CLOSED_BY_REMOTE_PEER`

**Comment by RednedEpic** [comment]
/reload is not supported. Additionally, follow the issue template in future reports.
