### ISSUE TITLE
plugin.yml error

### ISSUE THREAD

**Issue by MCTTV06** [GeyserMC/Geyser#1797]
[20:17:59 ERROR]: Could not load 'plugins/Geyser (3).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.4.jar:git-Paper-372]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.4.jar:git-Paper-372]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-372]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-372]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-372]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-372]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
... 7 more

**Comment by RednedEpic** [comment]
Use Geyser-Spigot.jar, and please follow the issue template in the future.
