### ISSUE TITLE
MCPE Crash on join

### ISSUE THREAD

**Issue by MightyEclipseAWE** [GeyserMC/Geyser#1874]
[10:39:37 INFO]: [Geyser-Spigot] /########:29977 tried to connect!        
[10:39:38 INFO]: [Geyser-Spigot] Player connected with username MightyEclips    
[10:39:42 INFO]: [Geyser-Spigot] Attempting to login using floodgate mode... aut
hentication will be encrypted.                                                  
[10:39:42 WARN]: [Geyser-Spigot] Loaded class org.geysermc.floodgate.util.Encryp
tionUtil from floodgate-bukkit v1.0-SNAPSHOT which is not a depend, softdepend o
r loadbefore of this plugin.                                                    
[10:39:42 INFO]: [Geyser-Spigot] Loaded Floodgate key!                          
[10:39:42 INFO]: [Geyser-Spigot] MightyEclips has disconnected from remote Java 
server on address 0.0.20.131 because of org.geysermc.platform.spigot.shaded.nett
y.channel.AbstractChannel$AnnotatedSocketException: Invalid argument: /0.0.20.13
1:25565                                                                         
[10:39:42 WARN]: org.geysermc.platform.spigot.shaded.netty.channel.AbstractChann
el$AnnotatedSocketException: Invalid argument: /0.0.20.131:25565                
[10:39:42 WARN]: Caused by: java.net.SocketException: Invalid argument          
[10:39:42 WARN]:        at java.base/sun.nio.ch.Net.connect0(Native Method)     
[10:39:42 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:476)       
[10:39:42 WARN]:        at java.base/sun.nio.ch.Net.connect(Net.java:468)       
[10:39:42 WARN]:        at java.base/sun.nio.ch.SocketChannelImpl.connect(Socket
ChannelImpl.java:694)                                                           
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.intern
al.SocketUtils$3.run(SocketUtils.java:83)                                       
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.intern
al.SocketUtils$3.run(SocketUtils.java:80)                                       
[10:39:42 WARN]:        at java.base/java.security.AccessController.doPrivileged
(Native Method)                                                                 
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.intern
al.SocketUtils.connect(SocketUtils.java:80)                                     
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.soc
ket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:315)                   
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio
.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:248)      
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.Def
aultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1354)       
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.Abs
tractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:547)
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.Abs
tractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:532)      
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.Abs
tractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:514)      
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.Def
aultChannelPipeline.connect(DefaultChannelPipeline.java:990)                    
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.Abs
tractChannel.connect(AbstractChannel.java:252)                                  
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.bootstrap.B
ootstrap$3.run(Bootstrap.java:246)                                              
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concur
rent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)          
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concur
rent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)  
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.channel.nio
.NioEventLoop.run(NioEventLoop.java:518)                                        
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concur
rent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)       
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.intern
al.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)                           
[10:39:42 WARN]:        at org.geysermc.platform.spigot.shaded.netty.util.concur
rent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)               
[10:39:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)      
[10:39:42 INFO]: [Geyser-Spigot] Bedrock user with ip: /'######## has disco
nnected for reason CLOSED_BY_REMOTE_PEER

**Comment by Camotoy** [comment]
`org.geysermc.platform.spigot.shaded.netty.channel.AbstractChann
el$AnnotatedSocketException: Invalid argument: /0.0.20.131:25565`

The `remote` `address` is set to an incorrect IP.

**Comment by MightyEclipseAWE** [comment]
How can I fix this?
Or which ip should I add there?

**Comment by Konicai** [comment]
This was fixed by setting the remote address to Mighty's public address, even though Geyser was being run as a plugin.
