### ISSUE TITLE
Server can’t start cause by network connection failure.

### ISSUE THREAD

**Issue by FBioCS1** [GeyserMC/Geyser#1949]
**To Reproduce**
1. Start server
2. It displays "loading Geyser ..."
3. Then it stuck there for an hour.

**Expected behavior**

It should bypass the connection to mineraft.net when network connection time out.

**Screenshots / Videos**

![image](https://user-images.githubusercontent.com/73772910/108315010-c6baf700-71f5-11eb-8f6d-e3d0ef01968c.png)

**Server Version and Plugins**

Paper 1.16.5 build 469
Geyser c4573bb

**Additional Context**

In **China**,the connection to minecraft.net is bad. So when Geyser tries to get locale files from resources.Minecraft.net, the server can't start up, even I have download the file and put it into the directory.

It didn't throw any Exception on my server, but it display when enbled
```
Exception encountered when loading plugin: Geyser-BungeeCord
java.lang.AssertionError: Unable to download and save file: plugins\Geyser-BungeeCord\locales\zh_cn.json (https://resources.download.minecraft.net/34/340457631ac98c2349ef3318ecf9bf0fdca3a6b9)
        at org.geysermc.connector.utils.WebUtils.downloadFile(WebUtils.java:86) ~[?:?]
        at org.geysermc.connector.utils.LocaleUtils.downloadLocale(LocaleUtils.java:173) ~[?:?]
        at org.geysermc.connector.utils.LocaleUtils.downloadAndLoadLocale(LocaleUtils.java:124) ~[?:?]
        at org.geysermc.connector.utils.LocaleUtils.<clinit>(LocaleUtils.java:60) ~[?:?]
        at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:145) ~[?:?]
        at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:377) ~[?:?]
        at org.geysermc.platform.bungeecord.GeyserBungeePlugin.onEnable(GeyserBungeePlugin.java:108) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
Caused by: javax.net.ssl.SSLException: Connection reset
        at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:144) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at org.geysermc.connector.utils.WebUtils.downloadFile(WebUtils.java:83) ~[?:?]
        ... 10 more
        Suppressed: java.net.SocketException: Connection reset by peer
                at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
                at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
                at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
                at java.net.Socket$SocketOutputStream.write(Socket.java:1051) ~[?:?]
                at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:82) ~[?:?]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:400) ~[?:?]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
                at sun.security.ssl.SSLTransport.decode(SSLTransport.java:144) ~[?:?]
                at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
                at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
                at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
                at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[?:?]
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[?:?]
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600) ~[?:?]
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528) ~[?:?]
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
                at org.geysermc.connector.utils.WebUtils.downloadFile(WebUtils.java:83) ~[?:?]
                at org.geysermc.connector.utils.LocaleUtils.downloadLocale(LocaleUtils.java:173) ~[?:?]
                at org.geysermc.connector.utils.LocaleUtils.downloadAndLoadLocale(LocaleUtils.java:124) ~[?:?]
                at org.geysermc.connector.utils.LocaleUtils.<clinit>(LocaleUtils.java:60) ~[?:?]
                at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:145) ~[?:?]
                at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:377) ~[?:?]
                at org.geysermc.platform.bungeecord.GeyserBungeePlugin.onEnable(GeyserBungeePlugin.java:108) ~[?:?]
                at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
                at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
                at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
                at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
Caused by: java.net.SocketException: Connection reset
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:981) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1488) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1394) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1600) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at org.geysermc.connector.utils.WebUtils.downloadFile(WebUtils.java:83) ~[?:?]
        ... 10 more
```
and when disabled:
```
Exception disabling plugin Geyser-BungeeCord
java.lang.NullPointerException: Cannot invoke "org.geysermc.connector.GeyserConnector.shutdown()" because "this.connector" is null
        at org.geysermc.platform.bungeecord.GeyserBungeePlugin.onDisable(GeyserBungeePlugin.java:123) ~[?:?]
        at net.md_5.bungee.BungeeCord.independentThreadStop(BungeeCord.java:473) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at net.md_5.bungee.BungeeCord.access$000(BungeeCord.java:100) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
        at net.md_5.bungee.BungeeCord$5.run(BungeeCord.java:413) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
```
on my PC, so it seems a network issue. Somtimes the connection is alive but can't finish the task in a proper time, it caused the server can't start up at all. I think the connection should be an option in the config.

**Comment by Camotoy** [comment]
#1951 should allow Geyser to run. It doesn't add a "connection option" in the config (my opinion is that I'm not *entirely* opposed, but I think a better option is just to fail quickly if a download cannot be achieved and still allow Geyser to boot).

**Comment by Camotoy** [comment]
#1951 should address this, more or less. If there are issues, please address there here and we will address in response.
