### ISSUE TITLE
CommandException after stopping Geyser

### ISSUE THREAD

**Issue by kdkasad** [GeyserMC/Geyser#1956]
**Describe the bug**

After running `/geyser stop`, running the command `/geyser` by itself causes a `CommandException`.

**To Reproduce**

1. Run `/geyser stop`
2. Run `/geyser`

**Expected behavior**

Nothing should happen. At the very least, no exception should occur.

**Screenshots / Videos**

Not a screenshot, but here's the log:
```text
>geyser stop
[10:06:57] [Server thread/INFO]: [Geyser-Spigot] Shutting down Geyser.
[10:06:57] [Server thread/INFO]: [Geyser-Spigot] Geyser shutdown successfully.
>geyser
[10:07:01] [Server thread/WARN]: Unexpected exception while parsing console command "geyser"
org.bukkit.command.CommandException: Unhandled exception executing command 'geyser' in plugin Geyser-Spigot v1.2.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:762) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:747) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:387) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1008) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:847) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.geysermc.connector.command.GeyserCommand.execute(org.geysermc.connector.network.session.GeyserSession, org.geysermc.connector.command.CommandSender, String[])" because the return value of "org.geysermc.platform.spigot.command.GeyserSpigotCommandExecutor.getCommand(String)" is null
        at org.geysermc.platform.spigot.command.GeyserSpigotCommandExecutor.onCommand(GeyserSpigotCommandExecutor.java:72) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.5.jar:git-Spigot-73fb609-d5c5d99]
        ... 9 more
```
**Server Version and Plugins**

Spigot version git-Spigot-73fb609-d5c5d99 (MC: 1.16.5)
Geyser version 1.2.0-SNAPSHOT (git-master- c26a2ba)

**Geyser Dump**

`/geyser dump` does not produce output since this error occurs after stopping Geyser. I can give a dump from before stopping Geyser, though.

**Minecraft: Bedrock Edition Version**

No Bedrock client, since this is a command issue.

**Additional Context**

none

**Comment by Camotoy** [comment]
This is *probably* a won't-fix. There will always be some error since we're shutting down Geyser. Perhaps we can disable the plugin to give a "plugin is disabled" message instead?

**Comment by kdkasad** [comment]
I figured it would be either unfixable or a wont-fix. I just file an issue whenever I get an unhandled exception in plugins anyways. Feel free to close this issue, then.

**Comment by Chew** [comment]
The stop command has been removed on all but standalone, so this issue is now irrelevant. Thank you for reporting, however!
