### ISSUE TITLE
Skin problem

### ISSUE THREAD

**Issue by KeyloHyum** [GeyserMC/Geyser#1997]
### Describe the bug

Hi, I'm having problem with error in console and server is loading so long.

### To Reproduce

1. you probably have to run offline server
2. then join on server, use skinsrestorer too
3. but I have original account, so this is so weird

### Expected behaviour

Any error

### Screenshots / Videos

[11:26:18 WARN] [Geyser-BungeeCord]: Failed getting skin for db3c9d86-8e29-277a-9d02-dad5f5cc7204
java.lang.IllegalArgumentException: Invalid legacy skin
        at com.nukkitx.protocol.bedrock.data.skin.ImageData.of(ImageData.java:47) ~[?:?]
        at org.geysermc.connector.skin.SkinManager.buildEntryManually(SkinManager.java:85) ~[?:?]
        at org.geysermc.connector.skin.SkinManager.lambda$requestAndHandleSkinAndCape$0(SkinManager.java:173) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]
[11:26:18 WARN] [Geyser-BungeeCord]: Failed getting skin for 2d5462e3-2629-26e6-a58d-1b83327ca7fd
java.lang.IllegalArgumentException: Invalid legacy skin
        at com.nukkitx.protocol.bedrock.data.skin.ImageData.of(ImageData.java:47) ~[?:?]
        at org.geysermc.connector.skin.SkinManager.buildEntryManually(SkinManager.java:85) ~[?:?]
        at org.geysermc.connector.skin.SkinManager.lambda$requestAndHandleSkinAndCape$0(SkinManager.java:173) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[?:?]

### Server Version and Plugins

1.16.5

### Geyser Dump

https://dump.geysermc.org/FiV5E58nyIGf3imBm9iXZqa1KIfeOqw6

### Geyser Version

version 1.2.0-SNAPSHOT (git-server-inventory-f02105e) (Java: 1.16.4 - 1.16.5, Bedrock: 1.16.100/1.16.101 - 1.16.200/1.16.201)

### Minecraft: Bedrock Edition Version

1.16.200/1.16.201

**Comment by Camotoy** [comment]
Likely resolved in #1940.
