### ISSUE TITLE
New install - "Error processing inventory task"

### ISSUE THREAD

**Issue by s1h4d0w** [GeyserMC/Geyser#2130]
### Describe the bug

I've just installed geyser and configured it correctly. I had my first random bedrock player join and they issued the "/shop" command which opens up a UI with the server shop. This causes the console to spit out a big error regarding "Error processing inventory task".

### To Reproduce

1. Run Geyser on a 1.16.5 paper server with the SS Dynamic Shop plugin (https://www.spigotmc.org/resources/ss-dynamic-shop-1-13-1-16.65603/)
2. Open the shop menu using /shop

### Expected behaviour

No errors to show

### Screenshots / Videos

```
[20:05:13 WARN]: [Geyser-Spigot] Error processing inventory task
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:94) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:54) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.translators.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.lambda$translate$0(JavaWindowItemsTranslator.java:54) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession.addInventoryTask(GeyserSession.java:966) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:42) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:753) ~[?:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

```
[20:06:51 WARN]: [Geyser-Spigot] Error processing inventory task
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:94) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:54) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.translators.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.lambda$translate$0(JavaWindowItemsTranslator.java:54) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession.addInventoryTask(GeyserSession.java:966) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:42) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:753) ~[?:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[20:06:55 WARN]: [Geyser-Spigot] Error processing inventory task
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.connector.inventory.Inventory.getItem(Inventory.java:94) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:54) ~[?:?]
        at org.geysermc.connector.network.translators.inventory.translators.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.lambda$translate$0(JavaWindowItemsTranslator.java:54) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:815) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:799) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2121) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession.addInventoryTask(GeyserSession.java:966) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:42) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaWindowItemsTranslator.translate(JavaWindowItemsTranslator.java:37) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:753) ~[?:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

### Geyser Dump

https://dump.geysermc.org/zS77gxc9lGAmeEvLQbuFivvBfcjkDhVn

### Geyser Version

1.2.1-SNAPSHOT (git-master-7dc9c03)

### Minecraft: Bedrock Edition Version

unknown

**Comment by Camotoy** [comment]
Unable to replicate on Paper 579.

**Comment by s1h4d0w** [comment]
Updated to newest build (588), will report if error happens again.

**Comment by Camotoy** [comment]
Any update?

**Comment by s1h4d0w** [comment]
Ah my bad, seems to have fixed it! Haven't seen any more errors in console.

**Comment by Camotoy** [comment]
Thanks for the update!
