### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Maximillus** [GeyserMC/Geyser#2161]
### Describe the bug

On latest guyser #675 trying to login produces: 
Exception in thread "Thread-36" java.lang.NoSuchMethodError: com.github.steveice10.mc.auth.service.AuthenticationService.<init>(Ljava/lang/String;Ljava/net/URI;)V
at com.github.steveice10.mc.auth.service.MojangAuthenticationService.<init>(MojangAuthenticationService.java:35)
at com.github.steveice10.mc.auth.service.MojangAuthenticationService.<init>(MojangAuthenticationService.java:26)
at org.geysermc.connector.network.session.GeyserSession.lambda$authenticate$2(GeyserSession.java:578)
at java.lang.Thread.run(Thread.java:748)

### To Reproduce

Try to login using mojang account on latest

### Expected behaviour

Shouldnt throw error, should log in

**Comment by Camotoy** [comment]
Looks like you have a corrupt jarfile. Please redownload it. Thank you!
