### ISSUE TITLE
"Invalid Type" Error

### ISSUE THREAD

**Issue by ImKlat** [GeyserMC/Geyser#2166]
### Describe the bug

[09:08:05 ERROR]: java.lang.IllegalArgumentException: Invalid type
[09:08:05 ERROR]:       at com.nukkitx.protocol.bedrock.data.entity.EntityData$Type.from(EntityData.java:192)
[09:08:05 ERROR]:       at com.nukkitx.protocol.bedrock.data.entity.EntityDataMap.put(EntityDataMap.java:213)
[09:08:05 ERROR]:       at org.geysermc.connector.entity.LivingEntity.updateBedrockMetadata(LivingEntity.java:88)
[09:08:05 ERROR]:       at org.geysermc.connector.entity.player.PlayerEntity.updateBedrockMetadata(PlayerEntity.java:253)
[09:08:05 ERROR]:       at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:53)
[09:08:05 ERROR]:       at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:38)
[09:08:05 ERROR]:       at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95)
[09:08:05 ERROR]:       at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:753)
[09:08:05 ERROR]:       at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[09:08:05 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[09:08:05 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[09:08:05 ERROR]:       at java.lang.Thread.run(Thread.java:748)
[09:08:05 WARN] [Geyser-BungeeCord]: Error translating metadata: EntityMetadata(id=7, type=FLOAT, value=20.0) for entity PLAYER
[09:08:05 WARN] [Geyser-BungeeCord]: Could not translate packet ServerEntityMetadataPacket
java.lang.IllegalArgumentException: Invalid type
        at com.nukkitx.protocol.bedrock.data.entity.EntityData$Type.from(EntityData.java:192) ~[?:?]
        at com.nukkitx.protocol.bedrock.data.entity.EntityDataMap.put(EntityDataMap.java:213) ~[?:?]
        at org.geysermc.connector.entity.LivingEntity.updateBedrockMetadata(LivingEntity.java:88) ~[?:?]
        at org.geysermc.connector.entity.player.PlayerEntity.updateBedrockMetadata(PlayerEntity.java:253) ~[?:?]
        at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:53) ~[?:?]
        at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:38) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:753) ~[?:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[09:08:05 ERROR]: java.lang.IllegalArgumentException: Invalid type
[09:08:05 ERROR]:       at com.nukkitx.protocol.bedrock.data.entity.EntityData$Type.from(EntityData.java:192)
[09:08:05 ERROR]:       at com.nukkitx.protocol.bedrock.data.entity.EntityDataMap.put(EntityDataMap.java:213)
[09:08:05 ERROR]:       at org.geysermc.connector.entity.LivingEntity.updateBedrockMetadata(LivingEntity.java:88)
[09:08:05 ERROR]:       at org.geysermc.connector.entity.player.PlayerEntity.updateBedrockMetadata(PlayerEntity.java:253)
[09:08:05 ERROR]:       at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:53)
[09:08:05 ERROR]:       at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:38)
[09:08:05 ERROR]:       at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:95)

### To Reproduce

1. Setup geyser on Bungeecord
2. Configure Geyser
3. Any people join in bedrock version

### Expected behaviour

That it did not give me any error and it works perfectly

### Server Version and Plugins

1.8.8 "Light Spigot"

Bungee Plugins:
![image](https://user-images.githubusercontent.com/76802264/115886858-bc9cbb00-a427-11eb-82ef-fb34852ff3b4.png)

Hub Plugins:

### Geyser Dump

https://dump.geysermc.org/fw9jKxWmk6McH2V7bWAfYpq4SFoIBXto%3E

### Geyser Version

Latest

### Minecraft: Bedrock Edition Version

1.16.220

### Additional Context

This error appears when someone enters my server from minecraft bedrock lets it enter and everything but it is a bit annoying because it is repeated a lot and I can not check the other logs

**Comment by ImKlat** [comment]
i just discovered that this happens in the first moments when the world still does not load and you are falling down

**Comment by Camotoy** [comment]
You are several versions behind - please update your Geyser and re-test. If it still happens, provide a new log.

I will be marking this as low-priority due to the weird 1.8 fork being used.

**Comment by ImKlat** [comment]
I updated everything and now it doesn't even let me in and throws an error "readtimeout: null"

**Comment by RednedEpic** [comment]
Very likely your server software or some plugin sending invalid entity data. Not a Geyser issue; I'd highly recommend updating off 1.8 as it's nearly 7 years old at this time, and using a supported server software like Paper.
