### ISSUE TITLE
Bad Packet ID 25, no velocity/bungee/waterdog/etc

### ISSUE THREAD

**Issue by shelbykauth** [GeyserMC/Geyser#2189]
### Describe the bug

When a bedrock player attempts to join the server, I get the following error message in the console, and they get "Connection Closed"

```
02.05 19:54:44 [Server] INFO [Geyser-Spigot] /<player's_ip>:<port> tried to connect!
02.05 19:54:45 [Server] INFO [Geyser-Spigot] Player connected with username <player's_name>
02.05 19:54:53 [Server] INFO [Geyser-Spigot] Attempting to login using floodgate mode... authentication will be encrypted.
02.05 19:54:53 [Server] WARN [Geyser-Spigot] Loaded class org.geysermc.floodgate.util.EncryptionUtil from floodgate-bukkit v1.0-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
02.05 19:54:53 [Server] INFO [Geyser-Spigot] Loaded Floodgate key!
02.05 19:54:53 [Server] INFO [Geyser-Spigot] <player's_name>(logged in as: <player's_name>) has connected to remote java server on address <server_ip>
02.05 19:54:53 [Server] WARN [floodgate-bukkit] Loaded class org.geysermc.floodgate.util.BedrockData from Geyser-Spigot v1.2.1-SNAPSHOT which is not a depend, softdepend or loadbefore of this plugin.
02.05 19:54:53 [Server] WARN [Geyser-Spigot] Downstream packet error! Invalid packet id: 25
02.05 19:54:53 [Server] INFO [Geyser-Spigot] <player_name>has disconnected from remote Java server on address <server_ip> because of Connection closed.
02.05 19:54:53 [Server] INFO [Geyser-Spigot] Bedrock user with ip: /<player's_ip> has disconnected for reason CLOSED_BY_REMOTE_PEER
```

That was 9 versions back.  With the newest version of Geyser, we get... "java.io.IOException: Connection reset by peer"
```
02.05 20:37:27 [Server] INFO [Geyser-Spigot] Player connected with username <player_name>
02.05 20:37:35 [Server] INFO [Geyser-Spigot] Attempting to login using floodgate mode... authentication will be encrypted.
02.05 20:37:35 [Server] INFO [Geyser-Spigot] Loaded Floodgate key!
02.05 20:37:35 [Server] INFO [Geyser-Spigot] <player_name>(logged in as: <player_name>) has connected to remote java server on address <server_ip>
02.05 20:37:35 [Server] WARN [Geyser-Spigot] Downstream packet error! Invalid packet id: 25
02.05 20:37:35 [Server] INFO [Geyser-Spigot] <player_name>has disconnected from remote Java server on address <server_ip> because of java.io.IOException: Connection reset by peer
02.05 20:37:35 [Server] WARN java.io.IOException: Connection reset by peer
02.05 20:37:35 [Server] WARN at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
02.05 20:37:35 [Server] WARN at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
02.05 20:37:35 [Server] WARN at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
02.05 20:37:35 [Server] WARN at sun.nio.ch.IOUtil.read(IOUtil.java:192)
02.05 20:37:35 [Server] WARN at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1134)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
02.05 20:37:35 [Server] WARN at org.geysermc.platform.spigot.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
02.05 20:37:35 [Server] WARN at java.lang.Thread.run(Thread.java:748)
02.05 20:37:35 [Server] INFO [Geyser-Spigot] Bedrock user with ip: /<player_ip> has disconnected for reason CLOSED_BY_REMOTE_PEER
```

### To Reproduce

I'll admit that I don't have a minimal reproduction of this bug.  Because it was hell to get the server to even accept her connection without asking for her Java login.

- server port is the geyser config.yml
- auth-type = floodgate

Attempts to connect via the Hive with `<server_ip>:<port>` or `<server_url>:<port>`,

### Expected behaviour

My bedrock player should be able to connect to my server.

### Server Version and Plugins

- I am using Paper-629 on ggservers hosting
- I am using Geyser and Floodgate, both downloaded in the last week
- There is no Velocity, Bungee, Waterfall, Waterdog, or a bunch of other login-type plugins I've heard of and not used.

List of all jar files in my plugins folder (I'm not sure how to list all installed plugins with versions)
- Brewery-3.0.jar
- CommandHook.jar
- DropHeads.jar
- Dynmap-3.1-spigot.jar
- EssentialsX-2.18.2.0.jar
- Geyser-Spigot.jar
- Harbor-1.6.3.jar
- HolographicDisplays.jar
- LuckPerms-Bukkit-5.2.104.jar
- MarriageMaster.jar
- Multiverse-Core-4.2.2.jar
- Multiverse-Inventories-4.2.1.jar
- Multiverse-NetherPortals-4.2.1.jar
- Multiverse-Portals-4.2.1.jar
- Multiverse-SignPortals-4.2.0.jar
- PlayerStatueBuilderXv1.9-SkyTechBytes.jar
- PlugMan.jar
- Shopkeepers-2.12.0.jar
- SilkSpawners.jar
- Vault.jar
- armorstandeditor-1.16-25.jar
- floodgate-bukkit.jar
- worldedit-bukkit-7.2.2-dist.jar
- worldguard-bukkit-7.0.4.jar

### Geyser Dump

https://dump.geysermc.org/GcyrOlVWgCBpm6rSN2dXeMGSNmDATEsi https://dump.geysermc.org/n6KjARuuoPDtMoVEzZiH6He1ekpnjqSb

### Geyser Version

1.2.1-SNAPSHOT (git-master-e74fa6c)

### Minecraft: Bedrock Edition Version

1.16.221

### Additional Context

The other closed issues I can find specify problems with waterdog, velocity, bungee, etc, and thus do not apply to my server.

**Comment by Camotoy** [comment]
Hey! We'd recommend heading on over to our Discord server for help. You likely just have a setup error.

Also, if you're trying to interact with the Hive Java Edition server, that's shut down now.

Thanks!
