### ISSUE TITLE
Honeycomb block displays in crafting table

### ISSUE THREAD

**Issue by SightedBike273** [GeyserMC/Geyser#2275]
### Describe the bug

It displays honeycomb block as a craftable item without honeycomb.

### To Reproduce

1. Join your server
2. Open your inventory in survival or crafting table
3. It will display honeycomb blocks as craftable

### Expected behaviour

It's not meant to show a honeycomb block as craftable unless you have the correct ingredients 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/73698519/121574075-d2892e00-ca1d-11eb-9b5e-2e61d83dd226.png)
![image](https://user-images.githubusercontent.com/73698519/121574135-de74f000-ca1d-11eb-8226-241d498ef8ef.png)
![image](https://user-images.githubusercontent.com/73698519/121574176-e765c180-ca1d-11eb-8fe8-93f917d080f5.png)

### Server Version and Plugins

MC Paper 771

* I have via version 

### Geyser Version

cc2d26d

**Comment by SightedBike273** [comment]
I tried and this happned
`>geyser dump
17:42:13 [INFO] Collecting dump info
17:42:14 [INFO] Uploading dump
17:42:24 [INFO] Failed to upload dump, check console for more information
17:42:24 [WARNING] [Geyser-BungeeCord] Failed to upload dump
java.net.UnknownHostException: dump.geysermc.org
    at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
    at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.base/java.net.Socket.connect(Socket.java:609)
    at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
    at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1334)
    at java.base/sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1332)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
    at org.geysermc.connector.utils.WebUtils.post(WebUtils.java:97)
    at org.geysermc.connector.command.defaults.DumpCommand.execute(DumpCommand.java:120)
    at org.geysermc.platform.bungeecord.command.GeyserBungeeCommandExecutor.execute(GeyserBungeeCommandExecutor.java:75)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:207)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:157)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:74)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

any idea what may cause this?

**Comment by UrLocalPerson** [comment]
> I tried and this happned
> `>geyser dump 17:42:13 [INFO] Collecting dump info 17:42:14 [INFO] Uploading dump 17:42:24 [INFO] Failed to upload dump, check console for more information 17:42:24 [WARNING] [Geyser-BungeeCord] Failed to upload dump java.net.UnknownHostException: dump.geysermc.org at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) at java.base/java.net.Socket.connect(Socket.java:609) at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289) at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182) at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474) at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569) at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372) at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203) at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1071) at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1069) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795) at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1068) at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189) at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367) at java.base/sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1334) at java.base/sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1332) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795) at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1331) at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246) at org.geysermc.connector.utils.WebUtils.post(WebUtils.java:97) at org.geysermc.connector.command.defaults.DumpCommand.execute(DumpCommand.java:120) at org.geysermc.platform.bungeecord.command.GeyserBungeeCommandExecutor.execute(GeyserBungeeCommandExecutor.java:75) at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:207) at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:157) at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:74) at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`
> 
> any idea what may cause this?

Might be a problem by bungee honestly dont know or its a problem with the java

**Comment by kylevardy1** [comment]
You are having this geyser dump problem since your server host only allows specific packets. This does not appear to be a problem on the latest geyser version.
