### ISSUE TITLE
Bedrock players can't join the server

### ISSUE THREAD

**Issue by Ozzxx** [GeyserMC/Geyser#2277]
### Describe the bug

Bedrock players will receive the error "java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token" when trying to join the server. 

The server logs: https://pastebin.com/QWSBt8Ux
I set up the plugin following this guide: https://apexminecrafthosting.com/geysermc/
The server provider I use is Apex Hosting

### To Reproduce

1. Use the server provider "Apex Hosting"
2. Use server software Spigot 1.17
3. Install GeyserMC and Floodgate
4. Setup GeyserMC (change address, both ports and auth-type)
5. Try to join with a bedrock account after restarting the server

### Expected behaviour

I expected to either be able to join with my Bedrock account or to get an error that I was using an outdated version of Geyser. 

### Server Version and Plugins

This server is running CraftBukkit version 3100-Spigot-c9cea60-5182f92 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)
The only plugins active on the server are GeyserMC and Floodgate. 

### Geyser Dump

https://dump.geysermc.org/aoEZGxJ9CfF5uOBW4FsDys0nt5h3kUb4

### Geyser Version

1.4.0-SNAPSHOT (git-master-cc2d26d)

### Minecraft: Bedrock Edition Version

1.17.0

### Additional Context

I tried to toy a bit with the public-key file, which was absent in this version of the plugin. I tried moving the regular key file from floodgate to geyser, tried simply copying and pasting the previous public-key file and I tried it without touching any files in floodgate at all. I have no idea if that's the actual issue, though. I'm not that experienced with things like this.

**Comment by ethpsa09** [comment]
This is also happening to me, here is an image of the error. (using aternos)[https://imgur.com/a/62TBy06](url)

**Comment by ethpsa09** [comment]
https://imgur.com/a/62TBy06

**Comment by ethpsa09** [comment]
> This is also happening to me, here is an image of the error. (using aternos)[https://imgur.com/a/62TBy06](url)

Sorry it was linking to GitHub for some reason

**Comment by miekemb** [comment]
Same here, local server for my kids on Raspberry 4

Found this in the logs (during server startup):
[12:43:39] [Server thread/INFO]: [floodgate] Enabling floodgate v2.0-SNAPSHOT
[12:43:39] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
[12:43:39] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
[12:43:39] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
[12:43:39] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[12:43:39] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[12:43:39] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[12:43:39] [Server thread/WARN]:        at org.geysermc.floodgate.util.ReflectionUtils.getClass(ReflectionUtils.java:73)
[12:43:39] [Server thread/WARN]:        at org.geysermc.floodgate.util.ReflectionUtils.getPrefixedClass(ReflectionUtils.java:58)
[12:43:39] [Server thread/WARN]:        at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:159)
[12:43:39] [Server thread/WARN]:        at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:58)
[12:43:39] [Server thread/WARN]:        at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:124)
[12:43:39] [Server thread/WARN]:        at org.geysermc.floodgate.SpigotPlatform.enable(SpigotPlatform.java:48)
[12:43:39] [Server thread/WARN]:        at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:66)
[12:43:39] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:43:39] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
[12:43:39] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[12:43:39] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
[12:43:39] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
[12:43:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
[12:43:39] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
[12:43:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
[12:43:39] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[12:43:39] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[12:43:39] [Server thread/ERROR]: [floodgate] Failed to inject the packet listener!
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "clazz" is null
	at org.geysermc.floodgate.util.ReflectionUtils.getMethod(ReflectionUtils.java:287) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.getMethod(ReflectionUtils.java:306) ~[?:?]
	at org.geysermc.floodgate.util.ReflectionUtils.invokeStatic(ReflectionUtils.java:432) ~[?:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:162) ~[?:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:58) ~[?:?]
	at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:124) ~[?:?]
	at org.geysermc.floodgate.SpigotPlatform.enable(SpigotPlatform.java:48) ~[?:?]
	at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:66) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:3108-Spigot-191e497-74575d4]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3108-Spigot-191e497-74575d4]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3108-Spigot-191e497-74575d4]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[server.jar:3108-Spigot-191e497-74575d4]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[server.jar:3108-Spigot-191e497-74575d4]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[server.jar:3108-Spigot-191e497-74575d4]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[server.jar:3108-Spigot-191e497-74575d4]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[server.jar:3108-Spigot-191e497-74575d4]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3108-Spigot-191e497-74575d4]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[12:43:39] [Server thread/INFO]: [floodgate] Disabling floodgate v2.0-SNAPSHOT

**Comment by zaytoz** [comment]
im having this same issue too
11.06 11:01:39 [Server] Server thread/INFO Enabling floodgate v2.0-SNAPSHOT
11.06 11:01:39 [Server] Server thread/WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.MinecraftServer
11.06 11:01:39 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140)
11.06 11:01:39 [Server] Server thread/WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99)
11.06 11:01:39 [Server] Server thread/WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
11.06 11:01:39 [Server] Server thread/WARN at java.base/java.lang.Class.forName0(Native Method)
11.06 11:01:39 [Server] Server thread/WARN at java.base/java.lang.Class.forName(Class.java:375)
11.06 11:01:39 [Server] Server thread/WARN at org.geysermc.floodgate.util.ReflectionUtils.getClass(ReflectionUtils.java:73)
11.06 11:01:39 [Server] Server thread/WARN at org.geysermc.floodgate.util.ReflectionUtils.getPrefixedClass(ReflectionUtils.java:58)
11.06 11:01:39 [Server] Server thread/WARN at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:159)
11.06 11:01:39 [Server] Server thread/WARN at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:58)
11.06 11:01:39 [Server] Server thread/WARN at org.geysermc.floodgate.FloodgatePlatform.enable(FloodgatePlatform.java:124)
11.06 11:01:39 [Server] Server thread/WARN at org.geysermc.floodgate.SpigotPlatform.enable(SpigotPlatform.java:48)
11.06 11:01:39 [Server] Server thread/WARN at org.geysermc.floodgate.SpigotPlugin.onEnable(SpigotPlugin.java:66)
11.06 11:01:39 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
11.06 11:01:39 [Server] Server thread/WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
11.06 11:01:39 [Server] Server thread/WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
11.06 11:01:39 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495)
11.06 11:01:39 [Server] Server thread/WARN at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409)
11.06 11:01:39 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607)
11.06 11:01:39 [Server] Server thread/WARN at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264)
11.06 11:01:39 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986)
11.06 11:01:39 [Server] Server thread/WARN at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
11.06 11:01:39 [Server] Server thread/WARN at java.base/java.lang.Thread.run(Thread.java:831)
11.06 11:01:39 [Server] Server thread/ERROR Failed to inject the packet listener!
11.06 11:01:39 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "clazz" is null
11.06 11:01:39 [Server] INFO at org.geysermc.floodgate.util.ReflectionUtils.getMethod(ReflectionUtils.java:287) ~[?:?]
11.06 11:01:39 [Server] INFO at org.geysermc.floodgate.util.ReflectionUtils.getMethod(ReflectionUtils.java:306) ~[?:?]
11.06 11:01:39 [Server] INFO at org.geysermc.floodgate.util.ReflectionUtils.invokeStatic(ReflectionUtils.java:432) ~[?:?]
11.06 11:01:39 [Server] INFO at org.geysermc.floodgate.inject.spigot.SpigotInjector.getServerConnection(SpigotInjector.java:162) ~[?:?]
11.06 11:01:39 [Server] INFO at org.geysermc.floodgate.inject.spigot.SpigotInjector.inject(SpigotInjector.java:58) ~[?:?]
11.06 11:01:40 [Multicraft] Skipped 18 lines due to rate limit (30/s)

**Comment by hydevdotbiz** [comment]
> Spigot 1.17 wasn't out yet when we released support for it.
> We're working on fixing that problem

so now under working for fix problem ?

**Comment by Camotoy** [comment]
Looks like this is a Floodgate issue for you all. If you absolutely need to use Floodgate, please install Velocity and put Floodgate on the backend. Otherwise, we will be tracking the issue at https://github.com/GeyserMC/Floodgate/issues/156. Thank you!
