### ISSUE TITLE
Connection closed. When i join my Geyser server

### ISSUE THREAD

**Issue by Zenzy18** [GeyserMC/Geyser#2321]
### Describe the bug

Connection closed. When i join my Geyser server

### To Reproduce

1. Go to servers 
2. Type the ip and Port I made
3. Click join and then get error

### Expected behaviour

I thought all my friends on bedrock could join.

### Screenshots / Videos

![Minecraft 6_23_2021 9_14_53 PM](https://user-images.githubusercontent.com/65931486/123187709-a7b0c800-d468-11eb-9903-62611a76d031.png)

### Server Version and Plugins

Server Version 1.17, No other Plugins Involved.

### Geyser Dump

https://dump.geysermc.org/7TwVfzc3QWWKy2yK82GyV2a1UXMJwPA7

### Geyser Version

1.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.2

### Additional Context

Started Up my Apex Pro Hosting Server  for the first time and then this happened. Also it works Java works but bedrock does not.

**Comment by Camotoy** [comment]
Please send your full server logs, including startup.

**Comment by Zenzy18** [comment]
> Please send your full server logs, including startup.


23.06 21:58:10 [Server] INFO Loading floodgate v2.0-SNAPSHOT
23.06 21:58:10 [Server] INFO Took 320ms to boot Floodgate
23.06 21:58:10 [Server] INFO Loading Geyser-Spigot v1.4.0-SNAPSHOT
23.06 21:58:10 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
23.06 21:58:10 [Server] INFO Preparing level "paper_1_17_1303005"
23.06 21:58:11 [Server] INFO -------- World Settings For [paper_1_17_1303005] --------
23.06 21:58:11 [Server] INFO Experience Merge Radius: 3.0
23.06 21:58:11 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Ra 48 / Mi 16 / Tiv true
23.06 21:58:11 [Server] INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
23.06 21:58:11 [Server] INFO Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313 Ocean: 14357621 Shipwreck: 165745295 End City: 10387313 Slime: 987234911 Bastion: 30084232 Fortress: 30084232 Mansion: 10387319 Fossil: 14357921 Portal: 34222645
23.06 21:58:11 [Server] INFO Max TNT Explosions: 100
23.06 21:58:11 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
23.06 21:58:11 [Server] INFO Cactus Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Cane Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Melon Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Mushroom Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Pumpkin Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Sapling Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Beetroot Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Carrot Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Potato Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Wheat Growth Modifier: 100%
23.06 21:58:11 [Server] INFO NetherWart Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Vine Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Cocoa Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Bamboo Growth Modifier: 100%
23.06 21:58:11 [Server] INFO SweetBerry Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Kelp Growth Modifier: 100%
23.06 21:58:11 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
23.06 21:58:11 [Server] INFO View Distance: 10
23.06 21:58:11 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
23.06 21:58:12 [Multicraft] Skipped 71 lines due to rate limit (30/s)
23.06 21:58:12 [Server] INFO Time elapsed: 1368 ms
23.06 21:58:12 [Server] INFO Preparing start region for dimension minecraft:the_nether
23.06 21:58:14 [Server] INFO Preparing spawn area: 0%
23.06 21:58:14 [Server] INFO Preparing spawn area: 0%
23.06 21:58:14 [Server] INFO Preparing spawn area: 0%
23.06 21:58:14 [Server] INFO Time elapsed: 1478 ms
23.06 21:58:14 [Server] INFO Preparing start region for dimension minecraft:the_end
23.06 21:58:15 [Server] INFO Preparing spawn area: 0%
23.06 21:58:15 [Server] INFO Preparing spawn area: 0%
23.06 21:58:15 [Server] INFO Preparing spawn area: 0%
23.06 21:58:15 [Server] INFO Preparing spawn area: 0%
23.06 21:58:16 [Server] INFO Preparing spawn area: 0%
23.06 21:58:16 [Server] INFO Preparing spawn area: 0%
23.06 21:58:17 [Server] INFO Preparing spawn area: 0%
23.06 21:58:17 [Server] INFO Preparing spawn area: 0%
23.06 21:58:18 [Server] INFO Preparing spawn area: 0%
23.06 21:58:18 [Server] INFO Time elapsed: 4311 ms
23.06 21:58:18 [Server] INFO Enabling floodgate v2.0-SNAPSHOT
23.06 21:58:18 [Server] INFO Enabling Geyser-Spigot v1.4.0-SNAPSHOT
23.06 21:58:19 [Server] INFO ******************************************
23.06 21:58:19 [Server] INFO Loading Geyser version 1.4.0-SNAPSHOT (git-master-71fe262)
23.06 21:58:19 [Server] INFO ******************************************
23.06 21:58:23 [Server] INFO Loaded Floodgate key!
23.06 21:58:23 [Server] INFO Started Geyser on 147.135.9.232:19333
23.06 21:58:23 [Server] Startup Done (3.906s)! Run /geyser help for help!
23.06 21:58:23 [Server] INFO Running delayed init tasks
23.06 21:58:23 [Server] Startup Done (14.148s)! For help, type "help"
23.06 21:58:23 [Server] INFO Timings Reset

**Comment by Camotoy** [comment]
Shut down your server, delete any key files in your folders and start your server back up. For further help, please join our Discord server. Thanks!

**Comment by SEAN9372** [comment]
> Shut down your server, delete any key files in your folders and start your server back up. For further help, please join our Discord server. Thanks!

I have that same problem

**Comment by SEAN9372** [comment]
> Shut down your server, delete any key files in your folders and start your server back up. For further help, please join our Discord server. Thanks!
[](https://aternos.org/:en/)[](https://aternos.org/account/)Aternos Logo
SmGMineSMPiZ6S
#LcSxP9LY3LYxdeHh
0/20
[Server](https://aternos.org/server/)
[Options](https://aternos.org/options/)
[Console](https://aternos.org/console/)
[Log](https://aternos.org/log/)
[Players](https://aternos.org/players/)
[Software](https://aternos.org/software/)
[Plugins](https://aternos.org/addons/)
[Files](https://aternos.org/files/)
[Worlds](https://aternos.org/worlds/)
[Backups ](https://aternos.org/backups/)
[Access](https://aternos.org/access/)
Advertisement
Console
[Log](https://aternos.org/log/)
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12-39) Host: Linux 5.4.0-90-generic (amd64)
Loading libraries, please wait...
[17:29:47 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:29:48 INFO]: Reloading ResourceManager: Default, bukkit
[17:29:50 INFO]: Loaded 7 recipes
[17:29:53 INFO]: Starting minecraft server version 1.18.1
[17:29:53 INFO]: Loading properties
[17:29:53 INFO]: This server is running Paper version git-Paper-184 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9940bca)
[17:29:53 INFO]: Server Ping Player Sample Count: 12
[17:29:53 INFO]: Using 4 threads for Netty based IO
[17:29:53 INFO]: Default game type: SURVIVAL
[17:29:53 INFO]: Generating keypair
[17:29:54 INFO]: Starting Minecraft server on *:43210
[17:29:54 INFO]: Using epoll channel type
[17:29:54 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[17:29:54 INFO]: Paper: Using OpenSSL 1.1.x (Linux x86_64) cipher from Velocity.
[17:29:55 INFO]: [floodgate] Loading floodgate v2.1.0-SNAPSHOT
[17:29:56 WARN]: [floodgate] en_ is not a supported Floodgate language.
[17:29:56 INFO]: [floodgate] Took 910ms to boot Floodgate
[17:29:56 INFO]: [Geyser-Spigot] Loading Geyser-Spigot v2.0.0-SNAPSHOT
[17:29:56 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:29:56 INFO]: Preparing level "world"
[17:29:58 INFO]: Preparing start region for dimension minecraft:overworld
[17:29:59 INFO]: Preparing spawn area: 0%
[17:29:59 INFO]: Preparing spawn area: 0%
[17:29:59 INFO]: Preparing spawn area: 0%
[17:30:00 INFO]: Preparing spawn area: 0%
[17:30:00 INFO]: Preparing spawn area: 0%
[17:30:01 INFO]: Preparing spawn area: 0%
[17:30:01 INFO]: Preparing spawn area: 0%
[17:30:02 INFO]: Preparing spawn area: 0%
[17:30:02 INFO]: Time elapsed: 3678 ms
[17:30:02 INFO]: Preparing start region for dimension minecraft:the_nether
[17:30:02 INFO]: Preparing spawn area: 0%
[17:30:02 INFO]: Preparing spawn area: 0%
[17:30:03 INFO]: Preparing spawn area: 0%
[17:30:03 INFO]: Preparing spawn area: 0%
[17:30:03 INFO]: Time elapsed: 1624 ms
[17:30:03 INFO]: Preparing start region for dimension minecraft:the_end
[17:30:04 INFO]: Preparing spawn area: 0%
[17:30:04 INFO]: Preparing spawn area: 0%
[17:30:04 INFO]: Time elapsed: 934 ms
[17:30:04 INFO]: [floodgate] Enabling floodgate v2.1.0-SNAPSHOT
[17:30:05 INFO]: [Geyser-Spigot] Enabling Geyser-Spigot v2.0.0-SNAPSHOT
[17:30:06 INFO]: [Geyser-Spigot] Auto-loaded Floodgate key
[17:30:06 INFO]: [Geyser-Spigot] ******************************************
[17:30:06 INFO]: [Geyser-Spigot] 
[17:30:06 INFO]: [Geyser-Spigot] Loading Geyser version 2.0.0-SNAPSHOT (git-master-9d908c5)
[17:30:06 INFO]: [Geyser-Spigot] 
[17:30:06 INFO]: [Geyser-Spigot] ******************************************
[17:30:12 INFO]: [Geyser-Spigot] Loaded Floodgate key!
[17:30:12 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:43210
[17:30:12 INFO]: [Geyser-Spigot] Done (5.905s)! Run /geyser help for help!
[17:30:12 INFO]: Starting GS4 status listener
[17:30:12 INFO]: Thread Query Listener started
[17:30:12 INFO]: Query running on 0.0.0.0:9898
[17:30:12 INFO]: JMX monitoring enabled
[17:30:12 INFO]: Running delayed init tasks
[17:30:12 INFO]: Done (19.132s)! For help, type "help"
[17:30:12 INFO]: Timings Reset
[17:31:10 INFO]: [Geyser-Spigot] /112.198.121.154:51375 tried to connect!
[17:31:11 INFO]: [Geyser-Spigot] /112.198.121.154:51375 tried to connect!
[17:31:14 INFO]: [Geyser-Spigot] Player connected with username SEAN8920
[17:31:14 INFO]: [Geyser-Spigot] SEAN8920 (logged in as: SEAN8920) has connected to the Java server
[17:31:15 WARN]: java.lang.reflect.InvocationTargetException
[17:31:15 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:31:15 WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[17:31:15 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:31:15 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[17:31:15 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:169)
[17:31:15 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:118)
[17:31:15 WARN]: 	at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[17:31:15 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:31:15 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:31:15 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:31:15 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[17:31:15 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[17:31:15 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:31:15 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[17:31:15 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
[17:31:15 WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[17:31:15 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[17:31:15 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:31:15 WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:31:15 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:31:15 WARN]: Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[17:31:15 WARN]: 	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[17:31:15 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200)
[17:31:15 WARN]: 	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38)
[17:31:15 WARN]: 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187)
[17:31:15 WARN]: 	at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31)
[17:31:15 WARN]: 	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:191)
[17:31:15 WARN]: 	at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:184)
[17:31:15 WARN]: 	at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:398)
[17:31:15 WARN]: 	... 20 more
[17:31:15 INFO]: [floodgate] Floodgate player logged in as .SEAN8920 disconnected
[17:31:15 INFO]: [Geyser-Spigot] SEAN8920 has disconnected from the Java server because of Connection closed.
[17:31:15 INFO]: com.mojang.authlib.GameProfile@2e35d385[id=00000000-0000-0000-0009-01ff3b3419da,name=.SEAN8920,properties={},legacy=false] (/112.198.121.154:0) lost connection: Disconnected
[17:31:15 INFO]: [Geyser-Spigot] Bedrock user with ip: /112.198.121.154 has disconnected for reason CLOSED_BY_REMOTE_PEER
Advertisement

**Comment by SEAN9372** [comment]
> Shut down your server, delete any key files in your folders and start your server back up. For further help, please join our Discord server. Thanks!

Pls help me

**Comment by Leifoh-B** [comment]
try set online-mode to false

**Comment by timr2000** [comment]
Having the same problem on purpur, still connection closed, tried to delete every folder and regenerate it. Updated everything to the latest version. Nothing seems to work.

**Comment by SEAN9372** [comment]
> 

How do i set online mod false?

**Comment by SocMinarch** [comment]
Offline mode isn’t supported and likely isn’t even relevant if Floodgate is being used

**Comment by SEAN9372** [comment]
> Offline mode isn’t supported and likely isn’t even relevant if Floodgate is being used

What do u mean?

**Comment by SEAN9372** [comment]
I need a explanation

**Comment by Camotoy** [comment]
Please update Floodgate from https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/. Otherwise, don't bump old issues.

**Comment by SEAN9372** [comment]
> Please update Floodgate from https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/. Otherwise, don't bump old issues.

What should i do there?

**Comment by Leifoh-B** [comment]
I did fix the problem after changing online-mode to false tho

**Comment by Leifoh-B** [comment]
> 

delete your old floodgate version file and download the new version with that link

**Comment by ComingFlex** [comment]
> Please update Floodgate from https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/. Otherwise, don't bump old issues.

It didn't help me. What to do?

**Comment by ImWaffles** [comment]
er
