### ISSUE TITLE
NPE when a player join the server from Bedrock

### ISSUE THREAD

**Issue by MasqueOu** [GeyserMC/Geyser#2341]
### Describe the bug

Hello, I have a bug on Geyser on my server, when a player named ".Kant2latess" connects to the server, Geyset emits an NPE in the console (it happens so far on my side only for him), it seems according to other Bedrock players that as soon as he connects to the server, these other players suffer from bugs (extreme rollback)

### To Reproduce

No idea

### Expected behaviour

When the player named ".Kant2latess" connects from Geyser to the server, other Bedrock players experience high latency and extreme rollback

### Server Version and Plugins

This server is running Paper version git-Paper-60 (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT) (Git: 4713937)
You are 6 version(s) behind

Plugins list: Tabouret-Core, ProtocolLib, WorldGuard, WorldEdit, Geyser-Spigot, Floodgate-Spigot, Chunky, Core-Protect, SmartInvs*, Harbor

### Geyser Dump

https://dump.geysermc.org/yg4QrxLD6ailApKsxmI3F8Vicc0ru6wk

### Geyser Version

1.4.0 SNAPSHOT

### Minecraft: Bedrock Edition Version

1.17.0

### Additional Context

NPE:
`[16:29:11] [Network Listener - #1/INFO]: [Geyser-Spigot] /XX.XX.XX.XXX:40534 à essayé de se connecter !
[16:29:14] [Network Listener - #1/INFO]: [Geyser-Spigot] Joueur connecté avec le nom d'utilisateur Kant2latess
[16:29:22] [Network Listener - #1/INFO]: [Geyser-Spigot] Tentative de connexion en utilisant le mode Floodgate... l'authentification sera cryptée.
[16:29:22] [epollEventLoopGroup-2-4/INFO]: [Geyser-Spigot] Kant2latess (identifié en tant que: Kant2latess) s'est connecté au serveur java distant sur l'adresse 54.38.226.248
[16:29:22] [Netty Epoll Server IO #0/WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at org.geysermc.floodgate.player.FloodgateHandshakeHandler.fetchLinkedPlayer(FloodgateHandshakeHandler.java:256)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at org.geysermc.floodgate.player.FloodgateHandshakeHandler.handle(FloodgateHandshakeHandler.java:159)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:67)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:289)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[16:29:22] [Netty Epoll Server IO #0/WARN]: Caused by: java.lang.NullPointerException
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.io.Reader.<init>(Reader.java:167)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at org.geysermc.floodgate.util.HttpUtils.createReader(HttpUtils.java:131)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at org.geysermc.floodgate.util.HttpUtils.readDefaultResponse(HttpUtils.java:104)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at org.geysermc.floodgate.util.HttpUtils.get(HttpUtils.java:58)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at org.geysermc.floodgate.link.GlobalPlayerLinking.lambda$getLinkedPlayer0$1(GlobalPlayerLinking.java:95)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[16:29:22] [Netty Epoll Server IO #0/WARN]: 	... 1 more
[16:29:23] [Netty Epoll Server IO #0/INFO]: UUID of player .Kant2latess is 00000000-0000-0000-0009-01f1020e41a5`

**Comment by Camotoy** [comment]
Is this still an issue with the latest Floodgate build?

**Comment by MasqueOu** [comment]
Need to verify but i think that's ok

**Comment by MasqueOu** [comment]
Issue resolved with the latest version.

Thanks you.
