### ISSUE TITLE
Bedrock Player can't join

### ISSUE THREAD

**Issue by ElektrodemonNl** [GeyserMC/Geyser#2352]
### Describe the bug

Bedrock Players can't join with a Error. I tried to download older vesion but nothing happend. I upgraded from Spigot 1.16.5 to PaperSpigot 1.16.5 and there it didn't worked.

### To Reproduce

layer can't join Server with error.

dump: https://dump.geysermc.org/TmoWGVBv0CzH4B5A0n3g8KnClN9pYLEQ 

This is the Error:
[20:19:00 WARN]: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:25565
[20:19:00 WARN]: Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
[20:19:00 WARN]:        at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
[20:19:00 WARN]:        at io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
[20:19:00 WARN]:        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
[20:19:00 WARN]:        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
[20:19:00 WARN]:        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
[20:19:00 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
[20:19:00 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[20:19:00 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:19:00 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:19:00 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[20:19:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

### Expected behaviour

The Bedrock Player should be able to join.

### Server Version and Plugins

You can see all plugins in the dump too.

### Geyser Dump

dump: https://dump.geysermc.org/TmoWGVBv0CzH4B5A0n3g8KnClN9pYLEQ 

### Geyser Version

See in dump i dont know :D

### Minecraft: Bedrock Edition Version

1.17

**Comment by Camotoy** [comment]
- PaperSpigot is now called Paper.
- That error means Geyser cannot connect to the backend server. Set `remote` `address` to `auto`. If you still have issues, please join our Discord. Thank you!

**Comment by ElektrodemonNl** [comment]
wow that was a fast answser :D
