### ISSUE TITLE
Netty errors when running on Java 16

### ISSUE THREAD

**Issue by Jaawn** [GeyserMC/Geyser#2417]
### Describe the bug

When running Geyser on Java 16 with debug-mode enabled, some Netty exceptions are printed in the log. This does not occur when running on Java 8.

### To Reproduce

Launch Geyser.jar with debug-mode enabled using a Java 16 JRE

### Expected behaviour

Geyser launches without errors/exceptions

### Server Version and Plugins

The error occurs before connecting to any server, but I tested with Minecraft server version: 
CraftBukkit version 3173-Spigot-610a8c0-b5d7883 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Geyser Dump

https://dump.geysermc.org/ZTbvxJDpW3mvcusrvcQ7ISgalVHfsp1I

### Geyser Version

1.4.1-SNAPSHOT (git-master-46cd26f)

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

Here are the 2 stack traces printed in the Geyser log:
```
[12:49:56 DEBUG] direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
        at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31) ~[Geyser.jar:?]
        at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:238) ~[Geyser.jar:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:232) ~[Geyser.jar:?]
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:294) ~[Geyser.jar:?]
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:93) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:279) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:150) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37) ~[Geyser.jar:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[Geyser.jar:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[Geyser.jar:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[Geyser.jar:?]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:86) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:81) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:68) ~[Geyser.jar:?]
        at com.nukkitx.network.util.EventLoops$ChannelType.lambda$static$2(EventLoops.java:58) ~[Geyser.jar:?]
        at com.nukkitx.network.util.EventLoops.<clinit>(EventLoops.java:36) [Geyser.jar:?]
        at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:243) [Geyser.jar:?]
        at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:519) [Geyser.jar:?]
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:220) [Geyser.jar:?]
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:173) [Geyser.jar:?]
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:167) [Geyser.jar:?]
[12:49:56 DEBUG] java.nio.Bits.unaligned: available, true
[12:49:56 DEBUG] jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @1283bb96
        at jdk.internal.reflect.Reflection.newIllegalAccessException(Unknown Source) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:352) ~[Geyser.jar:?]
        at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:343) ~[Geyser.jar:?]
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:294) ~[Geyser.jar:?]
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:93) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:279) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:150) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:138) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:146) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37) ~[Geyser.jar:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[Geyser.jar:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[Geyser.jar:?]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[Geyser.jar:?]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:86) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:81) ~[Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:68) ~[Geyser.jar:?]
        at com.nukkitx.network.util.EventLoops$ChannelType.lambda$static$2(EventLoops.java:58) ~[Geyser.jar:?]
        at com.nukkitx.network.util.EventLoops.<clinit>(EventLoops.java:36) [Geyser.jar:?]
        at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:243) [Geyser.jar:?]
        at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:519) [Geyser.jar:?]
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:220) [Geyser.jar:?]
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:173) [Geyser.jar:?]
        at org.geysermc.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:167) [Geyser.jar:?]
[12:49:56 DEBUG] java.nio.DirectByteBuffer.<init>(long, int): unavailable
```

**Comment by Camotoy** [comment]
Seeing as this is present in Netty and not Geyser, there's nothing we can do here. I'm no expert, but I'm fairly certain there's a reason these are *debug* logs: they describe specific behavior that isn't available on the specific platform but have workarounds. Unless behavior is unavailable, I see no reason to fret here. Thanks anyway.

**Comment by Jaawn** [comment]
I get that these were DEBUG errors, but it seemed odd that they only showed up under Java 16. I went ahead and built Geyser locally after changing the netty.version property in the Connector POM file to the latest (4.1.66.Final) and the errors are now gone. Currently it is several versions back on 4.1.59.Final, so it might make sense to update the dependency anyway assuming there aren't any conflicts.
