### ISSUE TITLE
Error number 2

### ISSUE THREAD

**Issue by JekoTC** [GeyserMC/Geyser#2427]
### Describe the bug

[05:16:00 INFO] [Geyser-BungeeCord]: /172.58.129.207:53107 tried to connect!
[05:16:00 INFO] [Geyser-BungeeCord]: /172.58.129.207:53107 tried to connect!
[05:16:04 INFO] [Geyser-BungeeCord]: Player connected with username JekoOwner
[05:16:07 INFO] [Geyser-BungeeCord]: Attempting to login using offline mode... authentication is disabled.
[05:16:07 INFO] [Geyser-BungeeCord]: JekoOwner (logged in as: JekoOwner) has connected to remote java server on address 103.9.158.72
[05:16:08 ERROR]: [/103.9.158.72:57037] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 0a0d0a000d0a515549540a2111
[05:16:08 INFO] [Geyser-BungeeCord]: JekoOwner has disconnected from remote Java server on address 103.9.158.72 because of java.io.IOException: An established connection was aborted by the software in your host machine
[05:16:08 ERROR]: java.io.IOException: An established connection was aborted by the software in your host machine
[05:16:08 ERROR]:       at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532)
[05:16:08 ERROR]:       at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:953)
[05:16:08 ERROR]:       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:917)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
[05:16:08 ERROR]:       at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:223)
[05:16:08 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.packetSent(ClientListener.java:130)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.event.session.PacketSentEvent.call(PacketSentEvent.java:51)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:227)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:223)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:223)
[05:16:08 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:140)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:332)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[05:16:08 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[05:16:08 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[05:16:08 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpClientSession$2.channelActive(TcpClientSession.java:286)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[05:16:08 ERROR]:       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
[05:16:08 ERROR]:       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[05:16:08 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[05:16:08 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[05:16:08 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[05:16:08 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[05:16:08 INFO] [Geyser-BungeeCord]: Bedrock user with ip: /172.58.129.207 has disconnected for reason CLOSED_BY_REMOTE_PEER

### To Reproduce

idk

### Expected behaviour

[05:16:00 INFO] [Geyser-BungeeCord]: /172.58.129.207:53107 tried to connect!
[05:16:00 INFO] [Geyser-BungeeCord]: /172.58.129.207:53107 tried to connect!
[05:16:04 INFO] [Geyser-BungeeCord]: Player connected with username JekoOwner
[05:16:07 INFO] [Geyser-BungeeCord]: Attempting to login using offline mode... authentication is disabled.
[05:16:07 INFO] [Geyser-BungeeCord]: JekoOwner (logged in as: JekoOwner) has connected to remote java server on address 103.9.158.72
[05:16:08 ERROR]: [/103.9.158.72:57037] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 0a0d0a000d0a515549540a2111
[05:16:08 INFO] [Geyser-BungeeCord]: JekoOwner has disconnected from remote Java server on address 103.9.158.72 because of java.io.IOException: An established connection was aborted by the software in your host machine
[05:16:08 ERROR]: java.io.IOException: An established connection was aborted by the software in your host machine
[05:16:08 ERROR]:       at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
[05:16:08 ERROR]:       at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532)
[05:16:08 ERROR]:       at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:953)
[05:16:08 ERROR]:       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:917)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
[05:16:08 ERROR]:       at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:223)
[05:16:08 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.packetSent(ClientListener.java:130)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.event.session.PacketSentEvent.call(PacketSentEvent.java:51)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:227)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:223)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[05:16:08 ERROR]:       at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:223)
[05:16:08 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:140)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:332)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[05:16:08 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[05:16:08 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[05:16:08 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[05:16:08 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpClientSession$2.channelActive(TcpClientSession.java:286)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[05:16:08 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[05:16:08 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[05:16:08 ERROR]:       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
[05:16:08 ERROR]:       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[05:16:08 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[05:16:08 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[05:16:08 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[05:16:08 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[05:16:08 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[05:16:08 INFO] [Geyser-BungeeCord]: Bedrock user with ip: /172.58.129.207 has disconnected for reason CLOSED_BY_REMOTE_PEER

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/85834402/127234811-bfeac233-ad34-4de7-b6b2-d54dd8278ff7.png)

### Geyser Dump

 https://dump.geysermc.org/bKDg38BvGJT6jXhcWL4jWdd5KQVPpcVm

### Geyser Version

Geyser version 1.4.1-SNAPSHOT (git-master-e0e6605) (Java: 1.17.1, Bedrock: 1.17.0/1.17.1/1.17.2 - 1.17.10)

### Minecraft: Bedrock Edition Version

1.17.10

**Comment by Camotoy** [comment]
You still have `use-proxy-protocol` enabled in `remote` `address`. Please do not use GitHub issues for connection issues. Thank you.

**Comment by JekoTC** [comment]
> You still have `use-proxy-protocol` enabled in the `remote` section. Please do not use GitHub issues for connection issues that are a result of setup misconfigurations. Thank you.

bruh? already
