### ISSUE TITLE
Packet processing error

### ISSUE THREAD

**Issue by RishavV123** [GeyserMC/Geyser#2439]
### Describe the bug

When i attack on any player i get disconnected with msg showing Packet processing error

### To Reproduce

starts the server 
attack on other player with sword
Client Crashes

### Expected behaviour

Clients should be able to pvp without crashing

### Screenshots / Videos

no response

### Server Version and Plugins

Running Airplane 1.16.5
Plugins (69): AdvancedEnchantments, AuctionMaster, AureliumSkills, BlockRegen, Citizens, CitizensCMD, ClearLag, CMILib, CommandPanels, ConsoleSpamFix, CraftEnhance, CraftingStore, CrazyCrates, DeluxeMenus, DeluxeTags*, DiscordSRV, Drop2Inventory, Elevator, EpicSpawners, Essentials, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), floodgate, GambleBarLite*, Geyser-Spigot, HandyOrbs, HolographicDisplays, HolographicExtension, HyperRegions, Images, ItemJoin, Jobs, KeepItems*, LPC, LuckPerms, MoneyPouch, Multiverse-Core, MyPet, MysqlEconomyBank, MythicMobs, NBTAPI, NoPluginPlus*, PlaceholderAPI, PlayerBounties, PlayerVaults, PlugMan, ProtocolLib, PvPManager, Quests, Sellwand, ShopGUIPlus, ShopGUIPlus-SellGUI, SimpleBossBar*, SimpleRename, SimpleScore, Skript, StackMob, SuperiorSkyblock2, TouchscreenHolograms, TradePlus, UltimateFishing, UltraMinions, Vault, ViaVersion, Votifier, VotingPlugin, WorldGuard, WorldGuardExtraFlags

### Geyser Dump

https://dump.geysermc.org/UgWrYtdCIOICYeh8x4foHje4iS4Qxy0a

### Geyser Version

1.4.1-SNAPSHOT (git-master-46cd26f)

### Minecraft: Bedrock Edition Version

1.17.10

### Additional Context

[09:53:15] [Server thread/ERROR]: Error whilst processing packet net.minecraft.server.v1_16_R3.PacketPlayInUseEntity@34ec05cf for xxxxxxxxxxxxx[/xxxxxxxxxxx:72672]
java.lang.IllegalStateException: Unregistered scoreboard component
	at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftTeam.checkState(CraftTeam.java:339) ~[patched_1.16.5.jar:git-Airplane-4]
	at org.bukkit.craftbukkit.v1_16_R3.scoreboard.CraftTeam.allowFriendlyFire(CraftTeam.java:147) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.EntityHuman.a(EntityHuman.java:926) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.EntityPlayer.a(EntityPlayer.java:1200) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:1170) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1227) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2290) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2546) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Airplane-4]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Airplane-4]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[09:53:15] [Netty Epoll Server IO #2/INFO]: [floodgate] Floodgate player logged in as xxxxxxxxxx disconnected
[09:53:15] [epollEventLoopGroup-2-2/INFO]: [Geyser-Spigot] xxxxxxxxxx has disconnected from remote Java server on address 127.0.0.1 because of Packet processing error
[09:53:15] [Server thread/INFO]: xxxxxxxxxxx lost connection: Packet processing error

**Comment by Jens-Co** [comment]
This is probably not a geyser error but a misconfigured scoreboard or bad scoreboard plugin. Can you please share the full latest.log with this link (https://mclo.gs/).

**Comment by Camotoy** [comment]
And if this happens with Java players too, it is very likely not our issue.

**Comment by RednedEpic** [comment]
This is an NPE inside of the server software, and whatever is causing that is likely causing the problem. Not a Geyser problem. Seems to be scoreboard related so I would check to see if the SimpleScore plugin (which I assume is scoreboards) is causing problems first.

**Comment by Doglovers18** [comment]
Necro Commenting to let you know that it is probably the player glow from PvPManager. Anything that makes bedrock players glow typically causes glitches or straight kicking. Hope this helps you are someone like me who found this thread wondering why only geyser players were getting kicked while PvPing!

**Comment by ba110cu** [comment]
> Necro Commenting to let you know that it is probably the player glow from PvPManager. Anything that makes bedrock players glow typically causes glitches or straight kicking. Hope this helps you or someone like me who found this thread wondering why only geyser players were getting kicked while PvPing!

not working
