### ISSUE TITLE
Cannot reply to EncryptionRequestPacket without profile and access token.

### ISSUE THREAD

**Issue by Xevolu** [GeyserMC/Geyser#2498]
### Describe the bug

Sometimes when I join my server, I get kicked immediately and this stacktrace is printed in my server console. I've noticed that this doesn't happen every time, but I've not been able to find out what might cause this problem to occur.

At first I thought I simply misconfigured something, but I've been able to reproduce this issue on a clean Purpur server, without any configuration changes and without other plugins. And even when I was testing on said Purpur server, the issue didn't happen every time I tried to join. I have no idea what causes this to happen, it seems very random to me.

```
[19:48:12 WARN]: java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.
[19:48:12 WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)
[19:48:12 WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[19:48:12 WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146)
[19:48:12 WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:332)
[19:48:12 WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)
[19:48:12 WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[19:48:12 WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:48:12 WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:48:12 WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:48:12 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:48:12 WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:48:12 WARN]: 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[19:48:12 WARN]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[19:48:12 WARN]: 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[19:48:12 WARN]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[19:48:12 WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[19:48:12 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[19:48:12 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:48:12 WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[19:48:12 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

### To Reproduce

1. Download Purpur from [purpur.pl3x.net](https://purpur.pl3x.net). I'm not 100% sure Purpur is actually required to reproduce this issue, though. I think it may be possible that you can reproduce the same issue on Paper or Spigot too.
2. Simply download GeyserMC and Floodgate into the plugins folder, there's no need to change any configuration files.
3. Start the server and try to join from Bedrock Edition. The issue probably won't occur every time, though. To reproduce the issue, I had to restart my server around 5 times. I couldn't find out why it didn't happen every time.
4. If the issue does eventually occur, you'll get kicked almost immediately with a message saying "Cannot reply to EncryptionRequestPacket without profile and access token" and the server will print a large stacktrace

### Expected behaviour

I expected that I can join my Purpur server on Bedrock without this issue randomly happening. It did eventually work after I restarted my server multiple times, but after some time, the exact same thing started happening again.

### Server Version and Plugins

Purpur version git-Purpur-1343 (MC: 1.17.1)
No plugins except for Geyser and Floodgate

### Geyser Dump

https://dump.geysermc.org/ZQoAv99qIhYT04LCYu8NQY0CqHzbjqvD

### Geyser Version

Reproduced on:
1.4.1-SNAPSHOT (git-master-26a778f)
and 1.4.1-SNAPSHOT (git-master-a1d167d) 

### Minecraft: Bedrock Edition Version

Minecraft: Pocket Edition v1.17.11

### Additional Context

I posted this issue here instead of the Floodgate repository because the stacktrace shows an exception in the `Geyser-Spigot.jar` and not in Floodgate. However, the issue is possibly related to a combination of both Geyser and Floodgate.

**Comment by Xevolu** [comment]
I've updated to the latest Floodgate, and sadly, that didn't seem to fix my issue. I will do some testing today, maybe I can find out a bit more about the issue and why it happens. It's probably a different issue from what RealTriassic had because I didn't get a NullPointerException when the IllegalStateException occurred.

**Comment by Camotoy** [comment]
Maybe added in Floodgate, which should be the same config option or otherwise labelled `debug`.

To verify, this occurs for you if you install a brand-new setup of Purpur, Geyser and Floodgate with zero configuration changes? Does `/floodgate firewall` work correctly?

**Comment by Xevolu** [comment]
Yes, I'm able to reproduce this issue with a clean, brand-new setup of Purpur, Geyser, Floodgate without any changes in any configuration file. This is the server log with debug mode enabled in both Geyser and Floodgate: [https://mclo.gs/I8m82NW](https://mclo.gs/I8m82NW). And this is the Geyser dump if you need it: [https://dump.geysermc.org/SqqAh7bGDs26oLgB1FadS7N2vgZfb966](https://dump.geysermc.org/SqqAh7bGDs26oLgB1FadS7N2vgZfb966).

I noticed that the error is much easier to reproduce if you restart your server every time after joining it to see if the error occurred. Also, the issue occurs almost every time when I try to join my main Purpur server, where I changed a lot of options in the configuration files, but it doesn't occur nearly as often when I try to join my testing Purpur server, where I didn't change anything in any configuration file. The `/floodgate firewall` command works correctly and doesn't show any errors.

**Comment by MrPowerGamerBR** [comment]
Can confirm the same issue, using Geyser Standalone with offline mode authentication (no Floodgate or anything like that)

```
[00:08:16 INFO] MrPowerGamerBR has disconnected from remote Java server on address 127.0.0.1 because of java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token
.
> java.lang.IllegalStateException: Cannot reply to EncryptionRequestPacket without profile and access token.
        at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:55)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146)
        at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:332)
        at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:36)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
        
I also noticed this error too
```
> java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271)
        at com.nukkitx.nbt.util.VarInts.decodeUnsigned(VarInts.java:48)
        at com.nukkitx.nbt.util.VarInts.readUnsignedInt(VarInts.java:25)
        at org.geysermc.connector.ping.GeyserLegacyPingPassthrough.run(GeyserLegacyPingPassthrough.java:100)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by Camotoy** [comment]
I would think your issue is unrelated - if the server is in offline mode then it shouldn't even be sending that packet.

**Comment by Chew** [comment]
Not much discussion has happened here, so I'm closing for the same reasons provided in #2232. If you continue to have an issue, don't hesitate to ask for help on [our Discord Server](https://discord.gg/geysermc). Thank you!

**Comment by MiloApianCat099** [comment]
I am having this same error with paper 1.18 and the newest Geyser-spigot and floodgate-spigot

**Comment by saguaro3** [comment]
> I am having this same error with paper 1.18 and the newest Geyser-spigot and floodgate-spigot

after one day of tweaking settings, I figured out that if u just turn off online mode, the error will disappear. gg
