### ISSUE TITLE
Server crash error Could not translate packet MovePlayerPacket and java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by l3unnyAnoF4** [GeyserMC/Geyser#2540]
### Describe the bug

```
[20:57:47] [Geyser player thread-2-50/WARN] [Geyser-BungeeCord]: Could not translate packet MovePlayerPacket
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3511) ~[?:?]
	at java.util.Arrays.copyOf(Arrays.java:3480) ~[?:?]
	at java.util.ArrayList.grow(ArrayList.java:237) ~[?:?]
	at java.util.ArrayList.grow(ArrayList.java:244) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:454) ~[?:?]
	at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
	at org.geysermc.connector.network.translators.collision.CollisionManager.getCollidableBlocks(CollisionManager.java:229) ~[?:?]
	at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovementForCollisions(CollisionManager.java:338) ~[?:?]
	at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovement(CollisionManager.java:289) ~[?:?]
	at org.geysermc.connector.network.translators.collision.CollisionManager.correctPlayerMovement(CollisionManager.java:283) ~[?:?]
	at org.geysermc.connector.network.translators.collision.CollisionManager.adjustBedrockPosition(CollisionManager.java:153) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:100) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:44) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry$$Lambda$994/0x000000080135cbc0.run(Unknown Source) ~[?:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[20:57:47] [Geyser player thread-2-50/ERROR]: java.lang.OutOfMemoryError: Java heap space
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at java.base/java.util.Arrays.copyOf(Arrays.java:3511)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at java.base/java.util.Arrays.copyOf(Arrays.java:3480)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at java.base/java.util.ArrayList.add(ArrayList.java:454)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at java.base/java.util.ArrayList.add(ArrayList.java:467)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.collision.CollisionManager.getCollidableBlocks(CollisionManager.java:229)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovementForCollisions(CollisionManager.java:338)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovement(CollisionManager.java:289)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.collision.CollisionManager.correctPlayerMovement(CollisionManager.java:283)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.collision.CollisionManager.adjustBedrockPosition(CollisionManager.java:153)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:100)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:44)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry$$Lambda$994/0x000000080135cbc0.run(Unknown Source)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[20:57:47] [Geyser player thread-2-50/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
```

```
[01:24:40] [Geyser player thread-2-27/WARN] [Geyser-BungeeCord]: Could not translate packet MovePlayerPacket
--
715 | java.lang.OutOfMemoryError: Java heap space
716 | at java.util.Arrays.copyOf(Arrays.java:3480) ~[?:?]
717 | at java.util.ArrayList.grow(ArrayList.java:237) ~[?:?]
718 | at java.util.ArrayList.grow(ArrayList.java:244) ~[?:?]
719 | at java.util.ArrayList.add(ArrayList.java:454) ~[?:?]
720 | at java.util.ArrayList.add(ArrayList.java:467) ~[?:?]
721 | at org.geysermc.connector.network.translators.collision.CollisionManager.getCollidableBlocks(CollisionManager.java:229) ~[?:?]
722 | at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovementForCollisions(CollisionManager.java:338) ~[?:?]
723 | at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovement(CollisionManager.java:289) ~[?:?]
724 | at org.geysermc.connector.network.translators.collision.CollisionManager.correctPlayerMovement(CollisionManager.java:283) ~[?:?]
725 | at org.geysermc.connector.network.translators.collision.CollisionManager.adjustBedrockPosition(CollisionManager.java:153) ~[?:?]
726 | at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:100) ~[?:?]
727 | at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:44) ~[?:?]
728 | at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115) ~[?:?]
729 | at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96) ~[?:?]
730 | at org.geysermc.connector.network.translators.PacketTranslatorRegistry$Lambda$973/0x0000000801359ee0.run(Unknown Source) ~[?:?]
731 | at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
732 | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
733 | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
734 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[SSCord.jar:SSCord-1.17.1-20210813-9fc5172]
735 | at java.lang.Thread.run(Thread.java:831) [?:?]
736 | [01:24:40] [Network Listener - #1/INFO] [Geyser-BungeeCord]: /**.**.**.**:51342 tried to connect!
737 | [01:24:40] [Geyser player thread-2-27/ERROR]: java.lang.OutOfMemoryError: Java heap space
738 | [01:24:40] [Network Listener - #1/INFO] [Geyser-BungeeCord]: /**.**.**.**:51342 tried to connect!
739 | [01:24:40] [Geyser player thread-2-27/ERROR]: at java.base/java.util.Arrays.copyOf(Arrays.java:3480)
740 | [01:24:40] [Geyser player thread-2-27/ERROR]: at java.base/java.util.ArrayList.grow(ArrayList.java:237)
741 | [01:24:40] [Geyser player thread-2-27/ERROR]: at java.base/java.util.ArrayList.grow(ArrayList.java:244)
742 | [01:24:40] [Geyser player thread-2-27/ERROR]: at java.base/java.util.ArrayList.add(ArrayList.java:454)
743 | [01:24:40] [Geyser player thread-2-27/ERROR]: at java.base/java.util.ArrayList.add(ArrayList.java:467)
744 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.collision.CollisionManager.getCollidableBlocks(CollisionManager.java:229)
745 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovementForCollisions(CollisionManager.java:338)
746 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.collision.CollisionManager.correctMovement(CollisionManager.java:289)
747 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.collision.CollisionManager.correctPlayerMovement(CollisionManager.java:283)
748 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.collision.CollisionManager.adjustBedrockPosition(CollisionManager.java:153)
749 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:100)
750 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.bedrock.entity.player.BedrockMovePlayerTranslator.translate(BedrockMovePlayerTranslator.java:44)
751 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115)
752 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96)
753 | [01:24:40] [Geyser player thread-2-27/ERROR]: at org.geysermc.connector.network.translators.PacketTranslatorRegistry$Lambda$973/0x0000000801359ee0.run(Unknown Source)
754 | [01:24:40] [Geyser player thread-2-27/ERROR]: at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
755 | [01:24:40] [Geyser player thread-2-27/ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
756 | [01:24:40] [Geyser player thread-2-27/ERROR]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
757 | [01:24:40] [Geyser player thread-2-27/ERROR]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
758 | [01:24:40] [Geyser player thread-2-27/ERROR]: at java.base/java.lang.Thread.run(Thread.java:831)

```

### To Reproduce

I still don't know how to Reproduce. But it's been like this twice already.

### Expected behaviour

Use Java adoptopenjdk jdk-16.0.2+7 and use Using Aikar's flags

-Xms2G -Xmx2G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -Dfile.encoding=UTF-8 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar SSCord nogui

### Geyser Dump

https://dump.geysermc.org/hhfI2NIK1niHEooF9qnjLKHAbwLUVcfW

### Geyser Version

1.4.3-SNAPSHOT (git-master-65ac6b7)

**Comment by Camotoy** [comment]
Can you upload a complete log?

**Comment by Camotoy** [comment]
This should be fixed in the latest builds.

**Comment by Camotoy** [comment]
Seeing how we have fixed the root issue and there have been no further reports, I'm going to close this.
