### ISSUE TITLE
"villager" is null on custom Merchant trade by plugin

### ISSUE THREAD

**Issue by RgtArRr** [GeyserMC/Geyser#2543]
### Describe the bug

I have a small plugin that have some trades using bukkit `this.getServer().createMerchant` and for bedrock recently(because i was like ~month ago) it doesnt works.

### To Reproduce

small bukkit code

```
Merchant merchant = Main.getInstance().getServer().createMerchant(Component.text("Test"));
List<MerchantRecipe> recipes = new ArrayList<>();
MerchantRecipe recipe = new MerchantRecipe(new ItemStack(Material.EMERALD), 10000);
recipe.addIngredient(new ItemStack(Material.COAL, 15));
recipes.add(recipe);
merchant.setRecipes(recipes);
p.openMerchant(merchant, false);
```

### Expected behaviour

able to open a custom trade menu on bedrock

### Geyser Dump

https://dump.geysermc.org/fzAd1EFnqmD8zH6qjQkd6rBCUYakSqxi

### Geyser Version

1.4.3-SNAPSHOT (git-master-82bb6ad)

### Minecraft: Bedrock Edition Version

1.17.11

### Additional Context

```
java.lang.NullPointerException: Cannot invoke "org.geysermc.connector.entity.Entity.getMetadata()" because "villager" is null
        at org.geysermc.connector.network.translators.java.world.JavaTradeListTranslator.translate(JavaTradeListTranslator.java:64) ~[?:?]
        at org.geysermc.connector.network.translators.java.world.JavaTradeListTranslator.translate(JavaTradeListTranslator.java:50) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96) ~[?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at java.lang.Thread.run(Unknown Source) [?:?]
[21:51:24 ERROR]: java.lang.NullPointerException: Cannot invoke "org.geysermc.connector.entity.Entity.getMetadata()" because "villager" is null
[21:51:24 ERROR]:       at org.geysermc.connector.network.translators.java.world.JavaTradeListTranslator.translate(JavaTradeListTranslator.java:64)
[21:51:24 ERROR]:       at org.geysermc.connector.network.translators.java.world.JavaTradeListTranslator.translate(JavaTradeListTranslator.java:50)
[21:51:24 ERROR]:       at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115)
[21:51:24 ERROR]:       at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96)
[21:51:24 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[21:51:24 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[21:51:24 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:51:24 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:51:24 ERROR]:       at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Camotoy** [comment]
It appears that your code doesn't ever add `recipe` to `recipes`, which may explain your error - I am aware of an issue where empty villagers cause errors on Geyser.

**Comment by RgtArRr** [comment]
sorry was a mistake from begin copy(300 lines of trades) from my plugin, but recipes.add(recipe) is done, and java players can open the trade without issue

**Comment by RgtArRr** [comment]
bruh momento, actually the sample code works, I think the issue is because the trigger is not from command(testing), is from a chest and I have to close the inventory and open a merchan for 20 ticks laters(10 cause the error for some reaons), now it works
