### ISSUE TITLE
Failed to parse message

### ISSUE THREAD

**Issue by PanHaskins** [GeyserMC/Geyser#2606]
### Describe the bug
```
[11:13:14 WARN]: [Geyser-Spigot] Failed to parse message
java.lang.NullPointerException: input
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at org.geysermc.platform.spigot.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:79) ~[?:?]
        at org.geysermc.platform.spigot.shaded.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75) ~[?:?]
        at org.geysermc.platform.spigot.shaded.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306) ~[?:?]
        at org.geysermc.connector.network.translators.chat.MessageTranslator.convertMessage(MessageTranslator.java:109) ~[?:?]
        at org.geysermc.connector.network.translators.java.scoreboard.JavaTeamTranslator.translate(JavaTeamTranslator.java:102) ~[?:?]
        at org.geysermc.connector.network.translators.java.scoreboard.JavaTeamTranslator.translate(JavaTeamTranslator.java:46) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:115) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:96) ~[?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[patched_1.17.1.jar:git-Purpur-1262]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1262]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1262]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.17.1.jar:git-Purpur-1262]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
### To Reproduce

Bedrock joined to the server

### Expected behaviour

IDK

### Geyser Version

Build #915

### Minecraft: Bedrock Edition Version

lasted version

**Comment by Camotoy** [comment]
Are you able to send the scoreboard.dat file in your world folder under `data`?

**Comment by Camotoy** [comment]
Also, please send a Geyser dump.

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by PanHaskins** [comment]
https://dump.geysermc.org/lwr9EFw86tVoZf64iAn7FvicxZYEjXUF

**Comment by PanHaskins** [comment]
Good day. It is still not fixed. I've updated all the plugins and I'm still spamming the same bug.

**Comment by Camotoy** [comment]
Can you enable debug mode in the Geyser config, restart your server, and send logs again?

**Comment by Dacaly** [comment]
I'm having the same issue on my proxy server.

**Comment by reiminecraft** [comment]
I found out what was causing the error in Geyser-Spigot, my friends, was the **SimpleScore** Plugin, on the version 3.8.1, this error probably happens in all versions of this plugin, I haven't tested it yet. I'll try to switch to another Scoreboard plugin to see if I can replace it with another one, any updates of this thread I'll notice!

 **![image](https://user-images.githubusercontent.com/43071572/143091852-c3c07355-4902-4771-a6da-3099218ad71c.png)**

![image](https://user-images.githubusercontent.com/43071572/143092903-23e955b8-c14d-464e-95f1-ce65c7711122.png)

**Comment by Camotoy** [comment]
@reiminecraft with the default SimpleScore config and Paper 1.17.1 I was unable to replicate this. Can you send your SimpleScore config, please? My DMs are also open on Discord if you wish to share it in private.

**Comment by Camotoy** [comment]
I believe we now have code to prevent this. Thanks for the report!
