### ISSUE TITLE
I am running latest Java, but it says a JNI error has ocurred and that I need a newer Java

### ISSUE THREAD

**Issue by thelabcat** [GeyserMC/Geyser#2616]
### Describe the bug

I am running the latest java, and have checked for updates on it, but I still get this error:

`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\abc\Downloads\Geyser> java -jar Geyser.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/geysermc/platform/standalone/GeyserStandaloneBootstrap has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
PS C:\Users\abc\Downloads\Geyser>`

### To Reproduce

Download Geyser.jar from https://ci.opencollab.dev//job/GeyserMC/job/Geyser/job/master/
Run Geyser.jar
![Java Virtual Machine Launcher 11_5_2021 1_58_12 PM](https://user-images.githubusercontent.com/53358500/140556925-7d3725a4-15af-429e-8240-ababfc91e863.png)
![Java Virtual Machine Launcher 11_5_2021 1_58_16 PM](https://user-images.githubusercontent.com/53358500/140556929-7ca94346-9464-46e4-9a62-56046eccebd6.png)

### Expected behaviour

Running the Geyser.jar file doesn't produce an error.

### Geyser Version

Downloaded 11/5/2021 at 1:41 PM latest

**Comment by Chew** [comment]
You likely aren't running the latest Java, but probably the latest Java 8.

You will need to upgrade to 16 with this guide: https://paper.readthedocs.io/en/latest/java-update/index.html#windows-10

**Comment by Camotoy** [comment]
Yup. Thanks for reporting anyway!

**Comment by thelabcat** [comment]
"Wait… Java no longer has the latest Java? What kind of black market brewery business is this?"

Well, OK.￼￼ thanks for the link! :-)￼

**Comment by thelabcat** [comment]
Confirmed, installing OpenJDK fixed the problem! TYL 😊. Thanks!
