### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by morgan2233** [GeyserMC/Geyser#2640]
### Describe the bug

Error on Startup

### To Reproduce

Start Server

### Expected behaviour

No error

### Server Version and Plugins

Waterfall MC #454

### Geyser Dump

https://dump.geysermc.org/aDccwSmF1feu6kzr7hbXKoE6xCCgkOWq

### Geyser Version

1.4.3-SNAPSHOT (git-master-b92b49b)

### Additional Context

[15:13:34] [Network Listener - #5/WARN]: Error dispatching event ProxyPingEvent(connection=org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough$GeyserPendingConnection@46f5e87b, response=ServerPing(version=ServerPing.Protocol(name=Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, protocol=756), players=ServerPing.Players(max=20, online=0, sample=null), description=Another Bungee server, modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener dev.simplix.protocolize.bungee.listener.PlayerListener@6dadcf58
java.lang.ClassCastException: class org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough$GeyserPendingConnection cannot be cast to class net.md_5.bungee.protocol.AbstractPacketHandler (org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough$GeyserPendingConnection is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @173a6728; net.md_5.bungee.protocol.AbstractPacketHandler is in unnamed module of loader 'app')
	at dev.simplix.protocolize.bungee.listener.PlayerListener.onPing(PlayerListener.java:27) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough.getPingInformation(GeyserBungeePingPassthrough.java:54) ~[?:?]
	at org.geysermc.connector.network.ConnectorServerEventHandler.onQuery(ConnectorServerEventHandler.java:100) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockServer$BedrockServerListener.onQuery(BedrockServer.java:93) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer.onUnconnectedPing(RakNetServer.java:239) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer.access$400(RakNetServer.java:34) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:366) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:616) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:651) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:56) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:490) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Camotoy** [comment]
You can temporarily remove the error by disabling ping passthrough options or enabling legacy ping passthrough.

**Comment by Camotoy** [comment]
Protocolize appears to have fixed this issue on their end.
