### ISSUE TITLE
geyser crashes on reload

### ISSUE THREAD

**Issue by MistaBiieest** [GeyserMC/Geyser#2675]
### Describe the bug

As the title already describes,
geyser crashes everytime on my server when I reload the server.
The only thing that helps is to restart the server, but thats a little anoying, because it takes so long.

### To Reproduce

reload the server

### Expected behaviour

I expected the plugin reloads, but not crash

### Server Version and Plugins

 Version: Paper version git-Paper-54 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: b4a77a8)
plugins:
Essentials, EssentialsChat, floodgate, Geyser-Spigot, Lobby*, LuckPerms, LuckTab*, Multiverse-Core, PlotSquared, WorldEdit, WorldGuard

### Geyser Dump

https://dump.geysermc.org/1KsZGkxSCzDsone4tIt0lWBmn8JGi4IT

### Geyser Version

2.0.0-SNAPSHOT (git-master-70ec77b) (Java: 1.18, Bedrock: 1.17.30 - 1.18.0)

### Additional Context

the error output of geyser after reload:
[19:51:23 WARN]: java.lang.RuntimeException: Unable to find listening channel!
[19:51:23 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.GeyserSpigotInjector.initializeLocalChannel0(GeyserSpigotInjector.java:104)
[19:51:23 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.network.netty.GeyserInjector.initializeLocalChannel(GeyserInjector.java:64)
[19:51:23 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:191)
[19:51:23 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:51:23 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[19:51:23 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[19:51:23 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
[19:51:23 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
[19:51:23 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.reload(CraftServer.java:1015)
[19:51:23 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:814)
[19:51:23 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
[19:51:23 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[19:51:23 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876)
[19:51:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2267)
[19:51:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2078)
[19:51:23 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2059)
[19:51:23 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[19:51:23 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[19:51:23 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[19:51:23 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:51:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:149)
[19:51:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(IAsyncTaskHandlerReentrant.java:23)
[19:51:23 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1413)
[19:51:23 WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189)
[19:51:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:122)
[19:51:23 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1391)
[19:51:23 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1384)
[19:51:23 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:132)
[19:51:23 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1362)
[19:51:23 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1268)
[19:51:23 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[19:51:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

output if a bedrock player tries to join after a server reload:
[19:52:50 WARN]: java.lang.IllegalStateException: zip file closed
[19:52:50 WARN]:        at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831)
[19:52:50 WARN]:        at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:330)
[19:52:50 WARN]:        at java.base/java.util.jar.JarFile.getEntry(JarFile.java:518)
[19:52:50 WARN]:        at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:473)
[19:52:50 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163)
[19:52:50 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[19:52:50 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[19:52:50 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[19:52:50 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[19:52:50 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.player.FloodgateHandshakeHandler.handle(FloodgateHandshakeHandler.java:118)
[19:52:50 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.handle(CommonDataHandler.java:93)
[19:52:50 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:111)
[19:52:50 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:52:50 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[19:52:50 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:52:50 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[19:52:50 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
[19:52:50 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
[19:52:50 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:52:50 WARN]:        at net.minecraft.server.network.LegacyPingHandler.channelRead(LegacyPingHandler.java:122)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:52:50 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:52:50 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[19:52:50 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[19:52:50 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[19:52:50 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:52:50 WARN]:        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[19:52:50 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
[19:52:50 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
[19:52:50 WARN]:        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
[19:52:50 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[19:52:50 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[19:52:50 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:52:50 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
And then there's a text with "closed connection"

I hope you can help.
Thanks in advace!

**Comment by Camotoy** [comment]
Already documented in #2665 - this will be addressed but you really should not reload: https://madelinemiller.dev/blog/problem-with-reload/
Thanks for reporting anyway!
