### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by weihao** [GeyserMC/Geyser#2676]
### Describe the bug

```
velocity_1        | [06:49:47 ERROR] [geyser]: Could not translate packet ClientboundLevelChunkWithLightPacket
velocity_1        | java.lang.NullPointerException: Cannot invoke "com.github.steveice10.opennbt.tag.builtin.CompoundTag.contains(String)" because "tag" is null
velocity_1        |     at org.geysermc.geyser.translator.level.block.entity.BannerBlockEntityTranslator.translateTag(BannerBlockEntityTranslator.java:44) ~[?:?]
velocity_1        |     at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:46) ~[?:?]
velocity_1        |     at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:271) ~[?:?]
velocity_1        |     at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78) ~[?:?]
velocity_1        |     at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
velocity_1        |     at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]      
velocity_1        |     at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity-3.1.0-95.jar:3.1.0]
velocity_1        |     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.0-95.jar:3.1.0]
velocity_1        |     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.0-95.jar:3.1.0]
velocity_1        |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.0-95.jar:3.1.0]   
velocity_1        |     at java.lang.Thread.run(Thread.java:833) [?:?]
velocity_1        | [06:49:47 ERROR]: java.lang.NullPointerException: Cannot invoke "com.github.steveice10.opennbt.tag.builtin.CompoundTag.contains(String)" because "tag" is null
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.level.block.entity.BannerBlockEntityTranslator.translateTag(BannerBlockEntityTranslator.java:44)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:46)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:271)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)     
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
velocity_1        | [06:49:47 ERROR]:   at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
velocity_1        | [06:49:47 ERROR]:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
velocity_1        | [06:49:47 ERROR]:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
velocity_1        | [06:49:47 ERROR]:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
velocity_1        | [06:49:47 ERROR]:   at java.base/java.lang.Thread.run(Thread.java:833)
velocity_1        | [06:49:47 ERROR] [geyser]: Could not translate packet ClientboundLevelChunkWithLightPacket
velocity_1        | java.lang.NullPointerException: Cannot invoke "com.github.steveice10.opennbt.tag.builtin.CompoundTag.contains(String)" because "tag" is null
velocity_1        |     at org.geysermc.geyser.translator.level.block.entity.BannerBlockEntityTranslator.translateTag(BannerBlockEntityTranslator.java:44) ~[?:?]
velocity_1        |     at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:46) ~[?:?]
velocity_1        |     at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:271) ~[?:?]
velocity_1        |     at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78) ~[?:?]
velocity_1        |     at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
velocity_1        |     at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]      
velocity_1        |     at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity-3.1.0-95.jar:3.1.0]
velocity_1        |     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.0-95.jar:3.1.0]
velocity_1        |     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.0-95.jar:3.1.0]
velocity_1        |     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.0-95.jar:3.1.0]   
velocity_1        |     at java.lang.Thread.run(Thread.java:833) [?:?]
velocity_1        | [06:49:47 ERROR]: java.lang.NullPointerException: Cannot invoke "com.github.steveice10.opennbt.tag.builtin.CompoundTag.contains(String)" because "tag" is null
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.level.block.entity.BannerBlockEntityTranslator.translateTag(BannerBlockEntityTranslator.java:44)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:46)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:271)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78)
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)     
velocity_1        | [06:49:47 ERROR]:   at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
velocity_1        | [06:49:47 ERROR]:   at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
velocity_1        | [06:49:47 ERROR]:   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
velocity_1        | [06:49:47 ERROR]:   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
velocity_1        | [06:49:47 ERROR]:   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
velocity_1        | [06:49:47 ERROR]:   at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

N/A

### Expected behaviour

N/A

### Geyser Version

CI #952, velocity

**Comment by Chew** [comment]
Please provide a Geyser Dump. There's nothing we can do with such little context...

**Comment by Camotoy** [comment]
Even better would be a world file!

**Comment by weihao** [comment]
> Please provide a Geyser Dump. There's nothing we can do with such little context...

https://dump.geysermc.org/RTGjcgq9pu53iE0UyhMc2zKJlj5ZLrNL

**Comment by weihao** [comment]
> Even better would be a world file!

```
sudo du -h --max-depth=1
2.1M    ./logs
60M     ./libraries
1.9G    ./world_the_end
4.0K    ./plugins
18G     ./world
4.0K    ./bluemap
17M     ./versions
45M     ./cache
2.9G    ./world_nether
23G     .
```

world file is large, are you sure you need it? let me know if you are still interested, I can DM you on discord

**Comment by Camotoy** [comment]
You can just send me the chunk this happens in. You can find the chunk region file using https://dinnerbone.com/minecraft/tools/coordinates/. However, my DMs are open on Discord if you want the send the entire world file.

**Comment by Camotoy** [comment]
Likely fixed with b134dd3.

**Comment by Chew** [comment]
If it was solved, I'm curious to see if you ran into the same issues I did.

1) A single chunk was completely missing, but you could right click blocks to "repair" it.
2) That chunk had a banner in it.

**Comment by weihao** [comment]
> If it was solved, I'm curious to see if you ran into the same issues I did.
> 
> 
> 
> 1) A single chunk was completely missing, but you could right click blocks to "repair" it.
> 
> 2) That chunk had a banner in it.

That's correct
