### ISSUE TITLE
Unable to Geyser Dump

### ISSUE THREAD

**Issue by weihao** [GeyserMC/Geyser#2682]
### Describe the bug

```
[01:54:05 INFO] [velocityrcon]: Rcon connection from [/127.0.0.1:36570]
[01:54:05 WARN] [io.netty.channel.DefaultChannelPipeline]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoSuchMethodError: 'boolean com.velocitypowered.api.command.CommandManager.execute(com.velocitypowered.api.command.CommandSource, java.lang.String)'
        at me.uniodex.velocityrcon.server.RconHandler.handleCommand(RconHandler.java:86) ~[?:?]
        at me.uniodex.velocityrcon.server.RconHandler.channelRead0(RconHandler.java:61) ~[?:?]
        at me.uniodex.velocityrcon.server.RconHandler.channelRead0(RconHandler.java:15) ~[?:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.0-95.jar:3.1.0]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.0-95.jar:3.1.0]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.0-95.jar:3.1.0]  
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.0-95.jar:3.1.0]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.0-95.jar:3.1.0]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.0-95.jar:3.1.0]  
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.0-95.jar:3.1.0]       
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.0-95.jar:3.1.0]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.0-95.jar:3.1.0]        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.0-95.jar:3.1.0]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.0-95.jar:3.1.0]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### To Reproduce

docker exec -i orchestration_velocity_1 rcon-cli geyser dump

### Expected behaviour

geyser dump

### Geyser Version

CI #952, velocity

### Additional Context

this issue blocked #2676

**Comment by Camotoy** [comment]
This doesn't seem like an us issue but instead with whatever RCON plugin you use. Try making a Geyser dump directly through the console.
(Though, just provide the world file or chunk in question and I should be able to address the issue)
