### ISSUE TITLE
geyser does not work under certain hardware

### ISSUE THREAD

**Issue by August7** [GeyserMC/Geyser#2741]
### Describe the bug

Hello, I encountered a weird problem: when I started to join the server, everything was normal. But a few minutes later,I can't open Inventory,cant't open chest,furnace,and any block/entity,can't load chunk,can't send chat and command. Seems to have become a ghost. I have tried changing the java version(oracle openjdk 16 17),change the system version(windows 10 11),use completely clean paper and create new world. This problem seems to only occur on specific hardware(nuc11 PAHi5 surfacepro7 i5). It works great on my other computers.

### To Reproduce

1.Start Geyser
2.Login
2.Wait a while

### Expected behaviour

Normal work

### Screenshots / Videos

https://youtu.be/0v-W9MyK-Xg

### Server Version and Plugins

Server Version : paper 1.18.1-121
plugin: essentialsx 2.19.2    dynmap 3.3-beta4    LuckPerms   5.3.87    Multiverse 4.2.1    worldedit 7.2.8    CoreProtect  20.3

I tried to use a clean paper, but this problem still exists. So I think it has nothing to do with plug-ins.   
The same configuration works on my other computer. So it seems to have nothing to do with paper. 

### Geyser Dump

https://dump.geysermc.org/hOAouH7VaUSsX8FO9nvJ36ufLRExj3K0

### Geyser Version

Geyser version 2.0.0-SNAPSHOT (git-master-3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

[01:10:55.069 main/INFO] 为Windows添加了环回豁免!
[01:10:55.170 main/INFO] ******************************************
[01:10:55.171 main/INFO] 
[01:10:55.171 main/INFO] Loading Geyser version 2.0.0-SNAPSHOT (git-master-3251d90)
[01:10:55.171 main/INFO] 
[01:10:55.171 main/INFO] ******************************************
[01:10:57.725 Network Listener - #1/INFO] Started Geyser on 0.0.0.0:19132
[01:10:57.730 main/INFO] Done (2.559s)! Run /geyser help for help!
[01:10:57.730 main/WARN] Geyser doesn't translate Bedrock movements perfectly! Using Geyser in servers that have an anticheat could get you banned.
[01:11:09.506 Network Listener - #1/INFO] /10.0.0.2:54549 tried to connect!
[01:11:10.458 Network Listener - #3/INFO] Player connected with username Aug77x
[01:11:28.167 nioEventLoopGroup-4-1/INFO] Aug77x (logged in as: Aug) has connected to remote java server on address 127.0.0.1
[01:13:55.922 Network Listener - #3/WARN] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$992/0x0000000801176db0@86b5d58
java.lang.RuntimeException: Unable to inflate buffer data
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.zip.DataFormatException: invalid distance too far back
	at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
	at java.util.zip.Inflater.inflate(Unknown Source) ~[?:?]
	at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser.jar:?]
	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:58) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser.jar:?]
	... 8 more
[01:13:55.963 Network Listener - #3/WARN] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$992/0x0000000801176db0@73b17de7
java.lang.RuntimeException: Unable to inflate buffer data
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.zip.DataFormatException: invalid stored block lengths
	at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
	at java.util.zip.Inflater.inflate(Unknown Source) ~[?:?]
	at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser.jar:?]
	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:58) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser.jar:?]
	... 8 more
[01:13:56.010 Network Listener - #3/WARN] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$992/0x0000000801176db0@738f4cb5
java.lang.RuntimeException: Unable to inflate buffer data
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.zip.DataFormatException: invalid block type
	at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
	at java.util.zip.Inflater.inflate(Unknown Source) ~[?:?]
	at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser.jar:?]
	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:58) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser.jar:?]
	... 8 more
[01:13:56.056 Network Listener - #3/WARN] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$992/0x0000000801176db0@32adf679
java.lang.RuntimeException: Unable to inflate buffer data
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.util.zip.DataFormatException: invalid stored block lengths
	at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
	at java.util.zip.Inflater.inflate(Unknown Source) ~[?:?]
	at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser.jar:?]
	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:58) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser.jar:?]
	... 8 more

**Comment by August7** [comment]
The device that can run geyser normally is an old desktop computer, and nuc11 and surface pro7 are mobile computers.

**Comment by Camotoy** [comment]
Looks like this is the same issue as #2694 and the different hardware lines up with other reports we've been getting. I'm going to close this issue to keep things organized; feel free to continue there. Thanks!
