### ISSUE TITLE
NPE inventory issue

### ISSUE THREAD

**Issue by DemsarMa** [GeyserMC/Geyser#2753]
### Describe the bug

My player has opened a furnace to gain iron, as soon as he tried to pick them up, they disconnected and threw a NPE error in my console (error in expected behaviour).

I've updated Geyser to the latest build as soon as I retrieved the error.
The player also reported to me that he was crafting bookshelves and disconnected the same way. I knew it's something with inventory event.

Tell me if you need more info.

### To Reproduce

Craft/smelt anything that is interactable in the inventory

### Expected behaviour

NPE error and player disconnect, console error:

[02:39:51 ERROR]: Packet encoding of packet ID 20 threw (skippable? false)
java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.c()" because the return value of "java.util.Map$Entry.getValue()" is null
        at net.minecraft.nbt.CompoundTag.copy(CompoundTag.java:459) ~[?:?]
        at net.minecraft.world.item.ItemStack.cloneItemStack(ItemStack.java:662) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.world.item.ItemStack.copy(ItemStack.java:653) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.network.FriendlyByteBuf.writeItem(FriendlyByteBuf.java:498) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.writeCollection(FriendlyByteBuf.java:144) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundContainerSetContentPacket.write(ClientboundContainerSetContentPacket.java:48) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:44) ~[paper-1.18.1.jar:git-Paper-132]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:16) ~[paper-1.18.1.jar:git-Paper-132]
        at jdk.internal.reflect.GeneratedMethodAccessor60.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268) ~[ProtocolLib.jar:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274) ~[ProtocolLib.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at su.nexmedia.engine.manager.packet.PacketManager$1.write(PacketManager.java:103) ~[NexEngine.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:87) ~[TradeSystem_v2.0.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:87) ~[TradeSystem_v2.0.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:428) ~[?:?]
        at net.minecraft.network.Connection.lambda$writePacket$8(Connection.java:402) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[ProtocolLib.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:39:51 INFO]: [REDACTED] lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NBTBase.c()" because the return value of "java.util.Map$Entry.getValue()" is null

### Server Version and Plugins

Version: git-Paper-132 (MC: 1.18.1) (git: 5e30e19)

### Geyser Dump

https://dump.geysermc.org/4lAqHMRM38fKTKLFLJDdcrGIy7p1lcML

### Geyser Version

2.0.0-SNAPSHOT (git: 3251d90)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by Camotoy** [comment]
The stack trace you give here doesn't point to this being a Geyser issue whatsoever. This lines up better as another plugin; see https://github.com/PaperMC/Paper/issues/7130. Thanks anyway.
