### ISSUE TITLE
[Geyser-Spigot] Got an error java.net.UnknownHostException: No such host is known (api.geysermc.org)

### ISSUE THREAD

**Issue by SleepyCatten** [GeyserMC/Geyser#2765]
### Describe the bug

A warning message appeared a few times on my paper server for which I have not been able to find any explanation.

[Geyser-Spigot] Got an error
java.net.UnknownHostException: No such host is known (api.geysermc.org)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1509) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1367) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1301) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1251) ~[?:?]
	at org.java_websocket.client.WebSocketClient$1.resolve(WebSocketClient.java:210) ~[Geyser-Spigot.jar:?]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:460) ~[Geyser-Spigot.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

I've pasted the entire log here:
https://gist.github.com/SleepyCatten/556e6ad7bdcff1c37738bc1d627f05d7

### To Reproduce

1. Create a Paper server with the same plugins and datapacks as listed.
2. Leave the server idle for a while (possibly a day).
3. See if the warning message appears.

### Expected behaviour

No warning message.

### Server Version and Plugins

This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)

Plugins (21)
AngelChest, BestTools, ChestSort, Chunky, CoreProtect, Drop2InventoryPlus, floodgate, Geyser-Spigot, HolographicDisplays, LuckPerms, PetMaster, PluralKitMC, ProNouns, ProtocolLib, RoseStacker, StackableItems, UltimateTimber, VanillaTweaks, Vault, ViewDistanceTweaks, voicechat

Datapacks
There are 4 data packs enabled:
[vanilla (built-in)], [file/bukkit (world)], [file/armor statues v2.8.3.zip (world)], [file/global-trades.zip (world)]

### Geyser Dump

https://dump.geysermc.org/m8hUSIkupQDVGR3dHaz4C2SnLiUIvou1

### Geyser Version

Geyser-Spigot v2.0.0-SNAPSHOT

### Additional Context

I'm not a developer or coder sadly, so please accept my apologies for not being immediately technically minded or knowing how to report this in a more-helpful way 😞

**Comment by Konicai** [comment]
The global api was down briefly, this wasn't anything on your end. Thanks for the report!
