### ISSUE TITLE
Unable to convert packets

### ISSUE THREAD

**Issue by lonely-nightmare** [GeyserMC/Geyser#2783]
### Describe the bug

[12:38:31 WARN] [Geyser-BungeeCord]: Unable to convert packets ClientboundContainerClosePacket
java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @7d151a)
        at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:142) ~[?:?]
        at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:111) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[12:38:31 ERROR]: java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @7d151a)
[12:38:31 ERROR]:       at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:142)
[12:38:31 ERROR]:       at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:111)
[12:38:31 ERROR]:       at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41)
[12:38:31 ERROR]:       at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34)
[12:38:31 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[12:38:31 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[12:38:31 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[12:38:31 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[12:38:31 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:38:31 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[12:38:31 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

1.Join with a Bedrock account.
2.Use Trmenu to open menu

### Expected behaviour

Trmenu for high versions players is very functional
I also hope Bedrock players can enjoys this 

### Server Version and Plugins

Previous version: git-Paper-152 (MC: 1.18.1)
Geyser-BungeeCord#1009
floodgate-bungee#57
floodgate-spigot#57
Trmenu 3.1.1

### Geyser Dump

https://dump.geysermc.org/addtBVIEM3qkH9fOv5xhxjCbCwLqDbct

### Geyser Version

Geyser-BungeeCord#1009

### Minecraft: Bedrock Edition Version

1.18.1

**Comment by onebeastchris** [comment]
does this issue still occur with the latest version of Geyser?

**Comment by XXY233** [comment]
Still have this issue when using build #1295.

**Comment by onebeastchris** [comment]
@ XXY233 @lonely-nightmare 

If this issue still occurs in the latest version of Geyser, please send a geyser dump by running "geyser dump" in the console, and send the link you get here. Additionally, a full log from the server where the issue appears would help - please upload the latest.log file to mclo.gs, and send that link too here.

**Comment by onebeastchris** [comment]
Furthermore; since TRmenu is a paid (and outdated plugin), we probably won't be able to reproduce this unless it also affects an up-to-date, ideally free plugin.

**Comment by onebeastchris** [comment]
Closing due to no response.
