### ISSUE TITLE
EOFException in standalone Geyser logs when passthrough-player-counts is enabled

### ISSUE THREAD

**Issue by marcbal** [GeyserMC/Geyser#2792]
### Describe the bug

When enabling `passthrough-player-counts` in the configuration of Geyser standalone, I regularly have a EOFException in the console:
```
java.io.EOFException
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:273)
        at com.nukkitx.nbt.util.VarInts.decodeUnsigned(VarInts.java:48)
        at com.nukkitx.nbt.util.VarInts.readUnsignedInt(VarInts.java:25)
        at org.geysermc.geyser.ping.GeyserLegacyPingPassthrough.run(GeyserLegacyPingPassthrough.java:99)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

In the Bungeecord server log, I also have a regular error message:
```
18:25:15 [WARNING] [/192.168.3.3:51828] <-> InitialHandler - read timed out
18:25:45 [WARNING] [/192.168.3.3:52024] <-> InitialHandler - read timed out
18:26:15 [WARNING] [/192.168.3.3:52210] <-> InitialHandler - read timed out
```

Due to these errors, the player count in the server list always shows 0 players.

### To Reproduce

1. Run Bungeecord with the configuration provided in the pastebin link below (change the IP/port of the listener for appropriate values).
2. Run standalone Geyser with the configuration provided in the Geyser dump (IP/port in the remote section can be adjusted accordingly).
3. Wait and see in the console of both applications
4. Notice the number of online players in the Bedrock client always showing 0/100.

### Expected behaviour

No errors, and the actual number of connected players is visible on the Bedrock client’s server list.

### Server Version and Plugins

The Backend server is Bungeecord: `git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:a9d75c5:1616`. The configuration is provided here: https://pastebin.com/AXiPR0Ak

I only have floodgate plugin installed: `Loaded plugin floodgate version 2.1.0-SNAPSHOT by GeyserMC` (build 57).

### Geyser Dump

https://dump.geysermc.org/dILUhinprLLAM83ArHAKsD7x2fG8sboH

### Geyser Version

2.0.0-SNAPSHOT (git-master-5ce2c11)

### Additional Context

It may be related to #1631 , but the exception in the console is not the same.

**Comment by Camotoy** [comment]
Looks like this is the same as https://github.com/GeyserMC/Geyser/issues/2323 - the issue being you're using HAProxy.
