### ISSUE TITLE
The server is not connected.

### ISSUE THREAD

**Issue by minsuho** [GeyserMC/Geyser#2802]
### Describe the bug

The server cannot be accessed due to an error.

[00:44:06 INFO]: [Geyser-Spigot] /192.168.0.2:50440에서 접속을 시도했습니다!
[00:44:07 INFO]: [Geyser-Spigot] 플레이어가 사용자명 minendus01(으)로 연결했습니다.
[00:44:07 INFO]: [Geyser-Spigot] minendus01 (minendus01로 로그인) (이)가 Java 서버에 접속했습니다
[00:44:09 WARN]: java.lang.reflect.InvocationTargetException
[00:44:09 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:44:09 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[00:44:09 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:44:09 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[00:44:09 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:169)
[00:44:09 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:118)
[00:44:09 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[00:44:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:44:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:44:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:44:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[00:44:09 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[00:44:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:44:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[00:44:09 WARN]:        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
[00:44:09 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[00:44:09 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[00:44:09 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:44:09 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[00:44:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:44:09 WARN]: Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[00:44:09 WARN]:        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[00:44:09 WARN]:        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200)
[00:44:09 WARN]:        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38)
[00:44:09 WARN]:        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187)
[00:44:09 WARN]:        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31)
[00:44:09 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:191)
[00:44:09 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:184)
[00:44:09 WARN]:        at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:398)
[00:44:09 WARN]:        ... 20 more
[00:44:09 INFO]: [floodgate] .minendus01(으)로 로그인된 Floodgate 플레이어의 연결이 끊어졌습니다
[00:44:09 INFO]: [Geyser-Spigot] minendus01(이)가 Java 서버에서 사유 Connection closed.로 인하여 접속이 종료되었습니다
[00:44:09 INFO]: com.mojang.authlib.GameProfile@1abcdcc[id=00000000-0000-0000-0009-01f277fc21d8,name=.minendus01,properties={},legacy=false] (/192.168.0.2:0) lost connection: Disconnected
[00:44:10 INFO]: [Geyser-Spigot] IP /192.168.0.2 Bedrock 사용자가 사유 CLOSED_BY_REMOTE_PEER로 인해 접속이 종료되었습니다.

### To Reproduce

1. Server access.

### Expected behaviour

1. Server access.

### Screenshots / Videos

![Minecraft 2022-02-03 오전 12_49_53](https://user-images.githubusercontent.com/58880552/152188326-9da5d2e5-1416-46d7-992b-dd39fd802ba6.png)

### Server Version and Plugins

paper-1.18.1-182.jar

### Geyser Dump

https://dump.geysermc.org/4RvRLxaJRREerKCJEyN0vBPfxi2GzcU7

### Geyser Version

2.0.0-SNAPSHOT (git-master-9d908c5)

### Minecraft: Bedrock Edition Version

1.18.2

**Comment by L-S-2020** [comment]
I have the same issue

**Comment by Camotoy** [comment]
We are aware of this issue. We know a lot of people are having the issue. We don't know why it happens or when it will be fixed. If you use Spigot, the issue doesn't appear to happen. Stay tuned to our Discord for any possible updates.

**Comment by Camotoy** [comment]
Update: Paper-only instances should be fixed. Velocity should be fixed. We're working on BungeeCord.

**Comment by Camotoy** [comment]
This issue has been resolved. Update Floodgate at https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/master/.
