### ISSUE TITLE
Failed to verify username

### ISSUE THREAD

**Issue by srlss123** [GeyserMC/Geyser#2805]
### Describe the bug

Unable to enter subserver after using geyser in 1.18.1 waterfall-1.18-477

### To Reproduce

1.Use waterfall-1.18-477 and spigot
2.Install Geyser-BungeeCord and floodgate-bungee
3.join game

### Expected behaviour

Can not join subserver!
Show “failed to verify username!”

### Server Version and Plugins

floodgate-bungee #60
Geyser #1017
No another plugins in Waterfall and paper.

### Geyser Dump

https://dump.geysermc.org/c8Nfi4FAzKgvNDp1Gbjn6UukIAD7qUOJ

### Geyser Version

git-master-9d908c5

### Minecraft: Bedrock Edition Version

v1.18.2

### Additional Context

$[04:22:40 INFO]: Disconnecting com.mojang.authlib.GameProfile@45312697[id=00000000-0000-0000-0009-01fc40153ad0,name=.srlss123,properties={},legacy=false] (/123.139.73.235:52938): Failed to verify username!
[04:22:40 WARN]: Exception verifying .srlss123
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.2.38.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.18.1.jar:git-Paper-182]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.2.38.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.18.1.jar:git-Paper-182]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:191) ~[paper-1.18.1.jar:git-Paper-182]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:184) ~[paper-1.18.1.jar:git-Paper-182]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:398) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:285) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:22:40 INFO]: com.mojang.authlib.GameProfile@45312697[id=00000000-0000-0000-0009-01fc40153ad0,name=.srlss123,properties={},legacy=false] (/123.139.73.235:52938) lost connection: Failed to verify username!

**Comment by Camotoy** [comment]
Please update Floodgate. If the issue persists, let us know.

**Comment by srlss123** [comment]
This Bug in #61 is fix Thanks !
