### ISSUE TITLE
`java.nio.channels.ClosedChannelException` on velocity

### ISSUE THREAD

**Issue by AlexXanderGrib** [GeyserMC/Geyser#2808]
### Describe the bug

When bedrock player joins, in Velocity console appears the following message, but in Paper console is nothing. For java players everything works fine

```log
[09:21:16 INFO] [geyser]: /<IP>:53694 tried to connect!
[09:21:17 INFO] [geyser]: Player connected with username AlexXanderGrib
[09:21:17 INFO] [geyser]: AlexXanderGrib (logged in as: AlexXanderGrib) has connected to the Java server
[09:21:17 INFO] [geyser]: AlexXanderGrib has disconnected from the Java server because of java.nio.channels.ClosedChannelException
[09:21:17 ERROR]: java.nio.channels.ClosedChannelException
[09:21:17 ERROR]:       at io.netty.channel.local.LocalChannel.doWrite(LocalChannel.java:368)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:949)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:913)
[09:21:17 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
[09:21:17 ERROR]:       at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
[09:21:17 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[09:21:17 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:249)
[09:21:17 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:139)
[09:21:17 ERROR]:       at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[09:21:17 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:145)
[09:21:17 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:346)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[09:21:17 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[09:21:17 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[09:21:17 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[09:21:17 ERROR]:       at org.geysermc.geyser.network.netty.LocalSession$2.channelActive(LocalSession.java:126)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[09:21:17 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[09:21:17 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[09:21:17 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[09:21:17 ERROR]:       at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
[09:21:17 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[09:21:17 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[09:21:17 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:21:17 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[09:21:17 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[09:21:17 INFO] [geyser]: Bedrock user with ip: /<IP> has disconnected for reason CLOSED_BY_REMOTE_PEER
[10:10:36 INFO]: [connected player] AlexXanderGrib (/<IP>:51698) has disconnected
[10:10:36 INFO]: [server connection] AlexXanderGrib -> main has disconnected
```

### To Reproduce

1. Create 2 servers with the following configurations
2. Join the proxy server from Bedrock edition

### Expected behaviour

Server is accessible from bedrock edition

### Screenshots / Videos

![Screenshot](https://sun9-55.userapi.com/impg/H1SjMmoCm3LSxqnMiEGvGM1pJO3cxYQ0nlsHGw/OHT-EJJID80.jpg?size=810x1080&quality=95&sign=b19b7c0f3df14e106bc2139630250a10&type=album)

### Server Version and Plugins

1. Proxy - Velocity `3.1.1-98`
Floodgate `2.1.0-SNAPSHOT`
Geyser `2.0.0-SNAPSHOT (git-master-9d908c5)`
2. Main - Purpur `1.18.1-1542`  
Floodgate `v2.1.0-SNAPSHOT`

Main's settings

1. `spigot.yml`
```yaml
settings:
  ...
  bungeecord: false
  ...
```

2. `paper.yml`
```yaml
settings:
  ...
  velocity-support:
    enabled: true
    online-mode: true
    secret: 'secret'
  ...
```

3. `server.properties`
```ini
online-mode=false
```

Proxy's settings
1. `velocity.toml`
```toml
online-mode = true
prevent-client-proxy-connections = false
player-info-forwarding-mode = "modern"
forwarding-secret = "secret"
ping-passthrough = "all"
```
2. `plugins/Geyser/config.yml`
```yaml
bedrock:
  address: 0.0.0.0
  port: 19133
  clone-remote-port: false
  enable-proxy-protocol: false
remote:
  address: auto
  port: 25565
  auth-type: floodgate
  allow-password-authentication: true
  use-proxy-protocol: true
  forward-hostname: true
forward-player-ping: true
enable-proxy-connections: false
mtu: 1400
use-direct-connection: true
```

### Geyser Dump

https://dump.geysermc.org/fNqS8YhmPJPtboC7SGRxoAG3DRJIEkAV

### Geyser Version

2.0.0-SNAPSHOT (git-master-9d908c5)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

Account is globally linked

**Comment by Camotoy** [comment]
Please share logs from the backend Spigot/Paper server.

**Comment by AlexXanderGrib** [comment]
Logs are full, the first time I tried to join from java to see purpur logs of this, the second time from bedrock (xbox via bedrock connect, worked fine without velocity)

[purpur.log](https://github.com/GeyserMC/Geyser/files/8007288/purpur.log)
[velocity.log](https://github.com/GeyserMC/Geyser/files/8007289/velocity.log)

**Comment by Camotoy** [comment]
Do you have proxy protocol enabled in Velocity?

**Comment by AlexXanderGrib** [comment]
Thanks, that's helped

**Comment by walflofer** [comment]
hey guys, I need some help, I have the same problem but I don't understant how to fix it, maybe one of u can explain me how can I disable the proxy protocol in Geyser.

**Comment by marlowegorman** [comment]
I also have this problem I don’t k ow how to fix
