### ISSUE TITLE
Massive error spam.

### ISSUE THREAD

**Issue by HideyBoi** [GeyserMC/Geyser#2820]
### Describe the bug

After a while the server console started to spam an error.

### To Reproduce

Load up a standard Version of PaperMC and Geyser

### Expected behaviour

Bedrock players should be able to connect and use the java server.

### Server Version and Plugins

 git-Paper-187 (MC: 1.18.1)

### Geyser Dump

https://dump.geysermc.org/5Y38dEjYbGJL2cCwQQhoFr2BYRLEZWpi

### Geyser Version

2.0.1-SNAPSHOT (git-master-e73a4ef)

### Minecraft: Bedrock Edition Version

1.18.2

### Additional Context

`[22:33:43] [Server thread/INFO]: HideyBoi lost connection: Disconnected
[22:33:43] [Server thread/INFO]: HideyBoi left the game
[22:35:37] [Network Listener - #3/WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$6146/0x0000000801dbbda8@ec387ea
java.lang.RuntimeException: Unable to inflate buffer data
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser-Spigot.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.DataFormatException: invalid code lengths set
	at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
	at java.util.zip.Inflater.inflate(Inflater.java:546) ~[?:?]
	at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser-Spigot.jar:?]
	... 8 more`

The actual error gets spammed a lot more and caused me to be unable to see the beginning of the console without going into the logs.

**Comment by Konicai** [comment]
Possibly related to https://github.com/GeyserMC/Geyser/issues/2694

**Comment by HideyBoi** [comment]
That's what I'd though, but that thread seemed to be inactive.

**Comment by Camotoy** [comment]
If you're using a modern Intel processor, see #2861. Otherwise, let us know. Thanks!
