### ISSUE TITLE
Loading more than one extension fails

### ISSUE THREAD

**Issue by ImDaBigBoss** [GeyserMC/Geyser#2826]
### Describe the bug

When you have 2 extensions to load, Geyser fails to load the second one.

Here is the stack trace:
```
Couldn't load TestGeyserExtension.jar in folder /path/to/folder/TestGeyserExtension.jar:
org.geysermc.geyser.api.extension.exception.InvalidExtensionException: org.geysermc.geyser.api.extension.exception.InvalidExtensionException: Class com.github.imdabigboss.testgeyserextension.TestGeyserExtension not found, extension cannot be loaded
	at org.geysermc.geyser.extension.GeyserExtensionLoader.loadExtension(GeyserExtensionLoader.java:84) ~[Geyser.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.lambda$loadAllExtensions$0(GeyserExtensionLoader.java:204) ~[Geyser.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) [?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) [?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) [?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) [?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) [?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) [?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) [?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) [?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) [?:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.loadAllExtensions(GeyserExtensionLoader.java:156) [Geyser.jar:?]
	at org.geysermc.geyser.api.extension.ExtensionManager.loadAllExtensions(ExtensionManager.java:116) [Geyser.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionManager.init(GeyserExtensionManager.java:53) [Geyser.jar:?]
	at org.geysermc.geyser.GeyserImpl.<init>(GeyserImpl.java:173) [Geyser.jar:?]
	at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:539) [Geyser.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:217) [Geyser.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:169) [Geyser.jar:?]
	at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:163) [Geyser.jar:?]
Caused by: org.geysermc.geyser.api.extension.exception.InvalidExtensionException: Class com.github.imdabigboss.testgeyserextension.TestGeyserExtension not found, extension cannot be loaded
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.<init>(GeyserExtensionClassLoader.java:56) ~[Geyser.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.loadExtension(GeyserExtensionLoader.java:82) ~[Geyser.jar:?]
	... 19 more
Caused by: java.lang.ClassNotFoundException: com.github.imdabigboss.testgeyserextension.TestGeyserExtension
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.findClass(GeyserExtensionClassLoader.java:90) ~[Geyser.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.classByName(GeyserExtensionLoader.java:115) ~[Geyser.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.findClass(GeyserExtensionClassLoader.java:86) ~[Geyser.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.findClass(GeyserExtensionClassLoader.java:76) ~[Geyser.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at org.geysermc.geyser.extension.GeyserExtensionClassLoader.<init>(GeyserExtensionClassLoader.java:54) ~[Geyser.jar:?]
	at org.geysermc.geyser.extension.GeyserExtensionLoader.loadExtension(GeyserExtensionLoader.java:82) ~[Geyser.jar:?]
	... 19 more
```

### To Reproduce

1. Create 2 extensions
2. Put them into the extensions folder
3. Start Geyser
4. Voilà, error.

### Expected behaviour

The second extension should load.

### Geyser Version

2.0.1-SNAPSHOT (git-custommodeldata-b2fd8a2)

### Minecraft: Bedrock Edition Version

1.18.10

**Comment by ImDaBigBoss** [comment]
Yeah yeah. I've tried with different file names too, so that the extensions load in a different order, and the same happens.
