### ISSUE TITLE
Not working with paper-1.14.4 and spigot1.14.4

### ISSUE THREAD

**Issue by kuretoshi** [GeyserMC/Geyser#2848]
### Describe the bug

An error occurs when starting the server and only Geyser does not work.

Can be reproduced with paper-1.14.4-245.jar and spigot1.14.4.jar.

Plug-ins used.
Geyser-Spigot.jar
GeyserSkinManager-Spigot.jar
floodgate-spigot.jar
BungeeTabListPlus_BukkitBridge-3.4.4.jar
ViaVersion-4.1.1.jar
ViaRewind-2.0.2.jar
ViaBackwards-4.1.1.jar
LunaChat.jar

The java version used.
Java 1.8 (OpenJDK 64-Bit Server VM 25.312-b07)

### To Reproduce

Create a new server and install the plugin.
I get the following message at startup.

[17:29:09 ERROR]: Fatal error trying to convert Geyser-Spigot v2.0.1-SNAPSHOT:org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin.class
java.lang.IllegalArgumentException: Unsupported class file major version 60
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:195) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:176) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.<init>(ClassReader.java:162) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.util.Commodore.convert(Commodore.java:170) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:283) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:112) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[17:29:09 ERROR]: Could not load 'plugins/Geyser-Spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:138) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.UnsupportedClassVersionError: org/geysermc/geyser/platform/spigot/GeyserSpigotPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_312]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_312]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_312]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_312]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.14.4.jar:git-Paper-245]
        ... 6 more

### Expected behaviour

It will launch successfully and create a Geyser folder directly under the plugins folder for BedRock users to enter.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/40343560/154648460-07a39b5b-b38c-42f6-8388-22af22ec1b3a.png)
![image](https://user-images.githubusercontent.com/40343560/154648502-0a4cfd5a-2075-408c-935e-bf49be360a71.png)
![image](https://user-images.githubusercontent.com/40343560/154648521-9ad6b71d-c730-4d76-9f03-2cf4945157b4.png)
![image](https://user-images.githubusercontent.com/40343560/154648534-b6c3f9be-4124-4ce0-9cb9-06f7284ac50c.png)

### Geyser Version

2.0.1-SNAPSHOT (git-master-31fd57a)

### Minecraft: Bedrock Edition Version

1.18.12

**Comment by Tim203** [comment]
Geyser currently requires Java 16 or later to run. You can download Java 17 at https://adoptium.net/
To find out how to change your Java version on hosts or other platforms, look at https://paper.readthedocs.io/en/latest/java-update/index.html
