### ISSUE TITLE
Bedrock Console Errors

### ISSUE THREAD

**Issue by BrandonT80** [GeyserMC/Geyser#2929]
### Describe the bug

Error on latest version and bedrock players cannot join. Console error produced

### Screenshots / Videos

[03:14:30 ERROR]: Uncaught exception in thread Profile Lookup Executor #9
java.lang.RuntimeException: Original profile: 'com.mojang.authlib.GameProfile@4a2c6dba[id=<null>,name=.ColdBrew3195,properties={},legacy=false]' Run with -DPaper.debugInvalidSkullProfiles=true for further debug information.
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:192) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.3.39.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.18.2.jar:git-Paper-287]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.18.2.jar:git-Paper-287]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$4(SkullBlockEntity.java:170) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:427) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:167) ~[?:?]
        ... 3 more

### Server Version and Plugins

Latest paper build, updated with Geyser

### Geyser Dump

https://dump.geysermc.org/hPF3ofkpRscsiSy8LWb5qs3lpOrk2Lcg

### Geyser Version

2.0.2-SNAPSHOT git-master-0803c5d

### Minecraft: Bedrock Edition Version

1.17.40

### Additional Context

[03:14:30 ERROR]: Uncaught exception in thread Profile Lookup Executor #9
java.lang.RuntimeException: Original profile: 'com.mojang.authlib.GameProfile@4a2c6dba[id=<null>,name=.ColdBrew3195,properties={},legacy=false]' Run with -DPaper.debugInvalidSkullProfiles=true for further debug information.
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:192) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.3.39.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.18.2.jar:git-Paper-287]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.18.2.jar:git-Paper-287]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$4(SkullBlockEntity.java:170) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:427) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:167) ~[?:?]
        ... 3 more

**Comment by Camotoy** [comment]
That log is just from a player head somewhere in the world/inventory; it won't impede you joining. Please send a full log.

**Comment by BrandonT80** [comment]
https://paste.gg/p/anonymous/1625e6ed8336457c85b139bcc9a803ee

**Comment by Camotoy** [comment]
Yeah, there's not much we can do about that specific console error. If Bedrock players cannot connect, that's separate, and may be related if you changed `bedrock` `address` in your Geyser config (most times it should stay as `0.0.0.0` ). For further help debugging if players cannot connect, please join our Discord. Thanks!

**Comment by BrandonT80** [comment]
Apologies, I had updated this earlier to removed that. It turns out that bedrock was down at the time on Mojang's side and this error just happened to show up at the same time. Is the error anything I need to worry about?
