### ISSUE TITLE
issues with inventory on 1.18.2 (on bedrock)

### ISSUE THREAD

**Issue by Xulgoos** [GeyserMC/Geyser#2933]
### Describe the bug

cannot craft items and cannot take items in inventory 
(on bedrock)

### To Reproduce

take items in inventory issue:
1 open inventory
2 take items from creative inventory, crafting table or mostly any inventory
3 the item does not appear in inventory in survival and produce an error
`[16:08:27 WARN]: java.lang.Throwable: DEBUGGING: ItemStackRequest rejected ItemStackRequest(requestId=-35, actions=[CraftCreativeStackRequestActionData(creativeItemNetworkId=221), CraftResultsDeprecatedStackRequestActionData(resultItems=[ItemData(id=4, damage=0, count=1, tag=null, canPlace=[], canBreak=[], blockingTicks=0, blockRuntimeId=1318, usingNetId=false, netId=0)], timesCrafted=1), PlaceStackRequestActionData(count=64, source=StackRequestSlotInfoData(container=CREATIVE_OUTPUT, slot=50, stackNetworkId=-35), destination=StackRequestSlotInfoData(container=HOTBAR, slot=5, stackNetworkId=0))], filterStrings=[])
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:772)
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.InventoryTranslator.rejectRequest(InventoryTranslator.java:761)
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.InventoryTranslator.translateCreativeRequest(InventoryTranslator.java:719)
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:167)
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[16:08:27 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[16:08:27 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[16:08:27 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[16:08:27 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:08:27 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:08:27 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)`

crafting issue:
1. get a crafting table and open it
2. try to craft any item
3. the item cannot be taken into inventory or does not appear in the crafting table
4. error
`[16:11:43 INFO]: [Geyser-Spigot] Could not find packet for CraftingEventPacket
[16:11:43 INFO]: [Geyser-Spigot] Could not find packet for ClientboundRecipePacket
[16:11:43 INFO]: [Geyser-Spigot] Could not find packet for ClientboundRecipePacket`
(not sure how to make code blocks sorry for the readability)
### Expected behaviour

in both case the item should appear and be placed into the inventory

### Server Version and Plugins

server: git-Purpur-1611 (MC: 1.18.2
geyser: 2.0.3-SNAPSHOT (git-master-67f4de9)
plugins: please look at the dump

### Geyser Dump

https://dump.geysermc.org/8dXRKvKx1MTPYIgYlrhmYQOdTRRdcYi6

### Geyser Version

2.0.3-SNAPSHOT (git-master-67f4de9)

### Minecraft: Bedrock Edition Version

v1.18.12

**Comment by Camotoy** [comment]
Can you show a video of what you try to do in Bedrock? And, if it isn't clear by the video, what gamemode are you in?

**Comment by Xulgoos** [comment]
https://gameclipscontent-d3017.xboxlive.com/xuid-2535443899749189-private/40f44d1d-c223-4d7d-a349-02fdbf26abfc.MP4?sv=2015-12-11&sr=b&si=DefaultAccess&sig=B4Hq2lSu2SPP%2Fmmkzq0f%2FNbW%2FPxq%2B9lD6Q3UeY9dO84%3D&__gda__=1650300595_f103b7ef33cf861a4a9356dcefca6076
(sorry for the long link) looks like some craft works but others don't

**Comment by rtm516** [comment]
We cant see the video, can you download it and then upload it to a service like https://streamable.com/ or even just straight into github

**Comment by Xulgoos** [comment]
ah my bad here sorry https://image.xulgos.com/images/view?img=e9b1910ad42dfa9a091cac701.mp4

**Comment by Xulgoos** [comment]
still no update?
