### ISSUE TITLE
The Bug which cannot translate the chunk for bedrock edition players

### ISSUE THREAD

**Issue by bzdnd** [GeyserMC/Geyser#2948]
### Describe the bug

when players login,the geyser output the error about the Chunk

### To Reproduce

As the players join in,it will happen.

### Expected behaviour

Players cannot break any blocks and back to the original place when running.

### Server Version and Plugins

Pufferfish 1.18.2
[17:01:17 INFO]: Plugins (90): ajLeaderboards, ajParkour, AlonsoTags, AnvilRepair, AureliumSkills, AutoComposter, BalancedVillagerTrades, BetterLogStrip, BetterProfiles, BetterTridents, BloodFading, BloodMoon, Boosters, CancelLavaDamage*, Cartographer2, ChatCommandArg, ChestProtect, ChestSort, Citizens, ClueScrolls, CMI, CMIEInjector*, CMILib, CombatPets, CopperOxidizer, CoralStay, CustomCrafting, CustomWings, CyberWorldReset, DeluxeMenus, DoorsReloaded, DragonDropElytra, eco, EcoEnchants, EcoEnchantsGUI, EcoItems, Elevators, EliteMobs, EliteMobsBan, EpicFurnaces, EpicHoppers, EZColors, FastAsyncWorldEdit (WorldEdit), FireFlies, floodgate, HarvestXP, HeadDatabase, HiveChecker, HolographicDisplays, HolographicExtension, Jobs, JukeBoxPlus, LibsDisguises, LoneLibs, Lootin, LuckPerms, Multiverse-Core, NBTAPI, NexEngine, ntdLuckyBlock, OfflineGrowthPro, Oh_the_dungeons_youll_go, OSZOAntiWDL*, OverleveledEnchanter, PlaceholderAPI, PlayerPoints, PlayerShopGUIPlus, PlotSquared, ProtocolLib, RainbowsPro, RealisticSeasons, Reforges, RePlant, ShopGUIPlus, ShopGUIPlus-SellGUI, Skript, Slimefun, TAB, TheSearch, TradePlus, Trash*, UltimateCatcher, UltimateTimber, UpgradeableSpawners, Vault, VentureChat, Waterex*, WildTools, WolfyUtilities, WorldGuard

### Geyser Dump

ClientboundLevelChunkWithLightPacket java.lang.IllegalArgumentException: Invalid value 4 	at com.nukkitx.network.util.Preconditions.checkArgument(Preconditions.java:181) ~[Geyser.jar:?] 	at org.geysermc.geyser.level.chunk.bitarray.Pow2BitArray.set(Pow2BitArray.java:66) ~[Geyser.jar:?] 	at org.geysermc.geyser.translator.level.BiomeTranslator.multiplyIdToStorage(BiomeTranslator.java:153) ~[Geyser.jar:?] 	at org.geysermc.geyser.translator.level.BiomeTranslator.toNewBedrockBiome(BiomeTranslator.java:142) ~[Geyser.jar:?] 	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:339) ~[Geyser.jar:?] 	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:81) ~[Geyser.jar:?] 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser.jar:?] 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser.jar:?] 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser.jar:?] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?] 	at java.lang.Thread.run(Thread.java:833) [?:?] java.lang.IllegalArgumentException: Invalid value 4 	at com.nukkitx.network.util.Preconditions.checkArgument(Preconditions.java:181) 	at org.geysermc.geyser.level.chunk.bitarray.Pow2BitArray.set(Pow2BitArray.java:66) 	at org.geysermc.geyser.translator.level.BiomeTranslator.multiplyIdToStorage(BiomeTranslator.java:153) 	at org.geysermc.geyser.translator.level.BiomeTranslator.toNewBedrockBiome(BiomeTranslator.java:142) 	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:339) 	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:81) 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 	at java.base/java.lang.Thread.run(Thread.java:833)

### Geyser Version

2.0.3-SNAPSHOT (git-master-5a94bda)

### Minecraft: Bedrock Edition Device/Version

1.18.30

### Additional Context

As I use /spawn to back to the spawn,the behavior solved.

**Comment by Camotoy** [comment]
This is a known bug with RealisticSeasons: https://github.com/GeyserMC/Geyser/issues/2744

Closing as it is a duplicate. Thanks anyway!
