### ISSUE TITLE
[Geyser player thread-5-3/ERROR]: Could not translate packet ClientboundContainerSetContentPacket | Cant smelt item in furnace

### ISSUE THREAD

**Issue by TypicalShavonne** [GeyserMC/Geyser#2958]
### Describe the bug

Players cant put item into a furnace
`[07:23:37] [Geyser player thread-5-3/ERROR]: Could not translate packet ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111) ~[?:?]
	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43) ~[?:?]
	at org.geysermc.geyser.inventory.updater.ContainerInventoryUpdater.updateInventory(ContainerInventoryUpdater.java:42) ~[?:?]
	at org.geysermc.geyser.translator.inventory.AbstractBlockInventoryTranslator.updateInventory(AbstractBlockInventoryTranslator.java:84) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[07:23:37] [Geyser player thread-5-3/ERROR]: java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.inventory.updater.ContainerInventoryUpdater.updateInventory(ContainerInventoryUpdater.java:42)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.translator.inventory.AbstractBlockInventoryTranslator.updateInventory(AbstractBlockInventoryTranslator.java:84)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[07:23:37] [Geyser player thread-5-3/ERROR]: Could not translate packet ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111) ~[?:?]
	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43) ~[?:?]
	at org.geysermc.geyser.inventory.updater.ContainerInventoryUpdater.updateInventory(ContainerInventoryUpdater.java:42) ~[?:?]
	at org.geysermc.geyser.translator.inventory.AbstractBlockInventoryTranslator.updateInventory(AbstractBlockInventoryTranslator.java:84) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-acc407a6-b135)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[07:23:37] [Geyser player thread-5-3/ERROR]: java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.inventory.updater.InventoryUpdater.updateInventory(InventoryUpdater.java:43)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.inventory.updater.ContainerInventoryUpdater.updateInventory(ContainerInventoryUpdater.java:42)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.translator.inventory.AbstractBlockInventoryTranslator.updateInventory(AbstractBlockInventoryTranslator.java:84)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[07:23:37] [Geyser player thread-5-3/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)`

### To Reproduce

1. Put item into a furnace

### Expected behaviour

Item in furnace and get smelted

### Screenshots / Videos

https://cdn.discordapp.com/attachments/970345883449315338/970346022926704691/screen-20220501-222714.mp4

### Server Version and Plugins

>....[08:46:34 INFO]: Velocity 3.1.2-SNAPSHOT (git-acc407a6-b135)
[08:46:34 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[08:46:34 INFO]: velocitypowered.com - GitHub

[08:46:43 INFO]: ------------=[ ServerUtils Plugins ]=-------------
[08:46:43 INFO]:  Plugins (10): AntiToolBox2, floodgate, Geyser-Velocity, LuckPerms, Neutron, PlayerOnlineSync, ServerUtils, SkinsRestorer, spark and VelocityUtils

### Geyser Dump

https://dump.geysermc.org/KAEHOxxI2uVDAbfBUA0lWeTEx51vF9DD

### Geyser Version

2.0.3-SNAPSHOT (git-master-31a84ea)

### Minecraft: Bedrock Edition Device/Version

1.16.30

### Additional Context

no

**Comment by Camotoy** [comment]
Can you please give the output of plugins on the backend server, as well as `/version`?

**Comment by TypicalShavonne** [comment]
[08:49:36 INFO]: Plugins (65): BetterRTP, BungeeGuard, Chunky, Confiscate, CoreProtect, DeluxeCoinflip, DeluxeMenus, DiscordSRV, DungeonSystem, dynmap, eco, EcoEnchants, EcoEnchantsGUI, EnderVaults, Essentials, EssentialsChat, EssentialsSpawn, ExcellentCrates, FarmControl, floodgate, GriefPrevention, GSit, HolographicDisplays, Insights, InventoryRollbackPlus, ItemEdit, LevelledMobs, LibsDisguises, LiteBans, LuckPerms, MMOItems, Multiverse-Core, MythicLib, MythicMobs, NexEngine, OpenInv, OreAnnouncer, PlaceholderAPI, PlayerOnlineSync*, PlayerPoints, PlugManX (PlugMan), ProtocolLib, PvPManager, QuickShop, ShopGUIPlus, ShopGUIPlus-SellGUI, Shopkeepers, SilkSpawners, SimpFileSync*, SimpScoreboard*, spark, StaffIPAccount*, TAB, Thesieutoc, TheSieuToc-MCPE, unemojis, Vault, ViaBackwards, ViaVersion, Vulcan, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags, zAuctionHouseV3




[08:50:08 INFO]: Current: git-Pearl-"1662437" (MC: 1.18.2)*
Previous: git-Pearl-"664da17" (MC: 1.18.2)
* You are 1 version(s) behind
Download the new version at: https://github.com/Pearl-Project/Pearl/releases

**Comment by TypicalShavonne** [comment]
my server jar isnt the cause of it if i'm aware of it :) 
it doesnt modify anything related to inventories and stuff
upstreamed purpur btw

**Comment by Camotoy** [comment]
Are you able to try with the latest Paper anyway for debugging purposes? This fork is new to me. 
Otherwise, try removing all backend server plugins to try to find a root cause.

**Comment by TypicalShavonne** [comment]
> Are you able to try with the latest Paper anyway for debugging purposes? This fork is new to me. Otherwise, try removing all backend server plugins to try to find a root cause.

ok

**Comment by TypicalShavonne** [comment]
after few testing, it sometimes do work, sometimes doesnt,(smelting item in furnace)

**Comment by TypicalShavonne** [comment]
im also getting this on my backend server,
i believe that it is related to geyser packet thingy
`[05:51:38 ERROR]: Packet encoding of packet ID 20 threw (skippable? false)
java.lang.NullPointerException: null
[05:51:38 INFO]: [floodgate] Floodgate player logged in as SalineChimp1869 disconnected
[05:51:38 INFO]: SalineChimp1869 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException`

**Comment by TypicalShavonne** [comment]
Somewhat related to Containers packet i assume ?
https://streamable.com/up921z
If a player tapped on right/left side of the chest, their inventory got blanked out,
But when tapped/opened on the others side, they dont get it ?

**Comment by TypicalShavonne** [comment]
git-ViaVersion-4.2.2-SNAPSHOT:823eb1f3
git-ViaBackwards-4.2.1-SNAPSHOT:eda8abf
My ViaVersion and ViaBackwards version :)

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If it does, send a new Geyser dump.

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
