### ISSUE TITLE
Players can't reconnect when the server jar kicks the player before they are connected.

### ISSUE THREAD

**Issue by Tom18314** [GeyserMC/Geyser#2964]
### Describe the bug

Our server is using XCord (https://www.mc-market.org/resources/16843/). This bungeecord jar makes sure players cannot connect when for example they are using a VPN. The first time they connect, they get disconnected with the error message “You can’t use a VPN.” But when they try to connect after VPN kick (without VPN), they get an error (ClosedChannelException). 

### To Reproduce

1. Use XCord (Or any bungeecord fork that supports anti VPN)
2. Connect to server (you get kicked because you are not allowed to use an vpn)
3. Disable your VPN and reconnect to the server (you get the ClosedChannelException)

### Expected behaviour

I really don't know, stop this disconnect from happening?

### Screenshots / Videos

Server logs:

**First connect attempt (with VPN)**
[10:57:44] [epollEventLoopGroup-3-18/INFO]: [/[PLAYER-IP]:0] <-> InitialHandler has connected
[10:57:44] [epollEventLoopGroup-3-18/INFO] [floodgate]: Floodgate player logged in as [PLAYER-NAME] joined (UUID: 00000000-0000-0000-0009-[PLAYER-UUID])
[10:57:44] [epollEventLoopGroup-3-18/INFO]: [[PLAYER-NAME]] disconnected with: VPN/Proxy's zijn niet toegestaan
[10:57:44] [epollEventLoopGroup-3-18/INFO] [floodgate]: Floodgate player logged in as [PLAYER-NAME] disconnected
[10:57:44] [defaultEventLoopGroup-7-7/INFO] [Geyser-BungeeCord]: [PLAYER-NAME] has disconnected from the Java server because of VPN/Proxy's zijn niet toegestaan
[10:57:44] [epollEventLoopGroup-3-18/INFO]: [/[PLAYER-IP]:0|[PLAYER-NAME]] -> UpstreamBridge has disconnected

**Seconds connect attempt (without VPN)**
[10:58:00] [Network Listener - #10/INFO] [Geyser-BungeeCord]: /[PLAYER-IP]:65248 tried to connect!
[10:58:01] [Network Listener - #9/INFO] [Geyser-BungeeCord]: Player connected with username [PLAYER-NAME]
[10:58:01] [defaultEventLoopGroup-7-8/INFO] [Geyser-BungeeCord]: [PLAYER-NAME] (logged in as: [PLAYER-NAME]) has connected to the Java server
[10:58:01] [defaultEventLoopGroup-7-8/INFO] [Geyser-BungeeCord]: [PLAYER-NAME] has disconnected from the Java server because of java.nio.channels.ClosedChannelException
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: java.nio.channels.ClosedChannelException
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.local.LocalChannel.doWrite(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.ChannelDuplexHandler.flush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.write(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannel.writeAndFlush(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:249)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:139)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:145)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:346)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.local.LocalChannel$3.run(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source)
[10:58:01] [defaultEventLoopGroup-7-8/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:831)

### Server Version and Plugins

git-Paper-dd2f0a0 (MC: 1.16.5)

Plugins (all custom except):

- ProtocolLib
- Holograpic Displays
- Spark
- HeadDatabase
- ViaVersion
- VoidGen
- Floodgate
- Luckperms
- Litebans

### Geyser Dump

https://dump.geysermc.org/mXhRxszowoU5ueATyRIMwVpCrUFpvTDU

### Geyser Version

2.0.3-SNAPSHOT

**Comment by AnhNguyenlost13** [comment]
Sadly we don't support paid forks of software, probably because it's hard to recreate the problem.

**Comment by Tom18314** [comment]
> Sadly we don't support paid forks of software, probably because it's hard to recreate the problem.

I can give you a server with the jar installed if you want. It's a really big problem for my server. If I don't use this jar with inbuild antiddos etc we get ddosed every day.

**Comment by Tom18314** [comment]
Possible fix:

**com/github/steveice10/packetlib/tcp/TcpSession.java**
```
    @Override
    public void send(Packet packet) {
        if(this.channel == null) { //<- change to if(this.channel == null || this.disconnected) {
            return;
        }

        PacketSendingEvent sendingEvent = new PacketSendingEvent(this, packet);
        this.callEvent(sendingEvent);

        if (!sendingEvent.isCancelled()) {
            final Packet toSend = sendingEvent.getPacket();
            this.channel.writeAndFlush(toSend).addListener((ChannelFutureListener) future -> {
                if(future.isSuccess()) {
                    callPacketSent(toSend);
                } else {
                    exceptionCaught(null, future.cause());
                }
            });
        }
    }
```

**Comment by Konicai** [comment]
Does this occur on FlameCord?

**Comment by Jens-Co** [comment]
Any updates on this issue?

**Comment by Konicai** [comment]
Without any updates and the usage of a paid server software, there isn't much we can do about this issue report.
