### ISSUE TITLE
GeyserMc Crashing on startup

### ISSUE THREAD

**Issue by myxxmikeyxx** [GeyserMC/Geyser#2969]
### Describe the bug

`java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
        at org.geysermc.geyser.skin.ProvidedSkin.<init>(ProvidedSkin.java:44) ~[?:?]
        at org.geysermc.geyser.skin.SkinProvider.<clinit>(SkinProvider.java:63) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:210) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.<init>(GeyserImpl.java:169) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:540) ~[?:?]
        at org.geysermc.geyser.platform.spigot.GeyserSpigotPlugin.onEnable(GeyserSpigotPlugin.java:166) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3481-Spigot-42b6152-e87f2e3]
        at java.lang.Thread.run(Thread.java:833) [?:?]
`
This is what I am seeing every time I start my Spigot Minecraft server now

### To Reproduce

I tried deleting the config file and I also tried downloading the latest jar from the website and I am still getting this.

### Expected behaviour

Not a crash, is it because its a snapshot?

### Geyser Version

 Geyser-Spigot v2.0.3-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Spigot 1.18.2

**Comment by myxxmikeyxx** [comment]
I did and it just says 

> Analysis
Server software:
Spigot
Minecraft version:
1.18.2
 The plugin 'Geyser-Spigot' could not be enabled.
[ Line #748](https://mclo.gs/KeppWEK#L748)
Solutions
Install a different version of the plugin 'Geyser-Spigot'.
Remove the plugin 'Geyser-Spigot'.
I attached the log file
[error.log](https://github.com/GeyserMC/Geyser/files/8681084/error.log)

PS I know worldedit is having problems but it is not crashing the server.
With geyers problems bedrock players can't join

**Comment by Camotoy** [comment]
Are you self-hosting this, or are you running this with a server provider?

**Comment by myxxmikeyxx** [comment]
self-hosting on docker pterodactyl, or well that's my goal. 
Right now I just have a folder on my Linux desktop with the files. 
It use to work but i updated my plugins and server and it doesn't now

**Comment by rtm516** [comment]
`javax.imageio.ImageIO` being missing should be impossible as its built into java and this error seems to suggest you're java install is broken
```
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
```
Why not just run it from within pterodactyl currently? or just use docker on your machine to replicate the environment?

**Comment by myxxmikeyxx** [comment]
@rtm516 I will try to recreate the container then and see if that works.

**Comment by myxxmikeyxx** [comment]
After reinstalling the container it didn't work still. I manually imported the worlds again using multiverse and now I think its working.

Does Geyser have to be online? I am getting this message now: `[07:54:27 WARN]: [Geyser-Spigot] Failed to load locale asset cache: Unrecognized token 'Connection': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`

**Comment by myxxmikeyxx** [comment]
Also for some reason I had to purge and then reinstall  openjdk-17-jdk on my linuxbox

**Comment by rtm516** [comment]
> Does Geyser have to be online?

It has to grab the locale files from Mojang on initial boot, I suggest just allowing it internet access if you can.

**Comment by rtm516** [comment]
> Also for some reason I had to purge and then reinstall openjdk-17-jdk on my linuxbox

Closing issue as its now resolved
