### ISSUE TITLE
Unable to connect using Geyser-BungeeCord

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3013]
### Describe the bug

Since updating to the latest version of BungeeCord and Geyser to support 1.19, I've been unable to connect to the Proxy using Bedrock.

I'm not sure if there's anything you can do here, but I thought I'd open an issue in the event you could/knew anything about it.

### To Reproduce

1. Create a Bungeecord server, with the latest Geyser-Bungeecord, Floodgate-Bungee and ViaVersion
2. Attempt to connect to the server
3. Client gets stuck on "Generating world", with an eventual time out

### Expected behaviour

The player should connect as normal.

### Screenshots / Videos

The following error is given in the console when a Bedrock 1.19 player tries to connect:

```
20:26:26 [WARNING] A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@3bb06df1
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.connection.LoginResult.getProperties()" because the return value of "net.md_5.bungee.connection.InitialHandler.access$900(net.md_5.bungee.connection.InitialHandler)" is null
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:553)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

### Server Version and Plugins

Proxy (BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:eccdf87:1637) is running:
- ViaVersion-4.3.0.jar
- Build 65 of Floodgate
- Build 1108 of Geyser-Bungeecord

### Geyser Dump

https://dump.geysermc.org/wYngVr059pbyUHnimFIifjYW2GP1mJ1a

### Geyser Version

2.0.4-SNAPSHOT (git-master-78bb69b)

### Minecraft: Bedrock Edition Device/Version

1.19 - tested on Windows, iOS and Android

**Comment by Camotoy** [comment]
Thanks for the report. We probably have to do something about it. We'll look into it.

**Comment by Camotoy** [comment]
Seems like this is still on Bungee's end for now - they pushed a fix for offline mode but I think it's incomplete at the moment.

**Comment by eleksploded** [comment]
Bungee just made a commit further fixing offline. Does that solve this issue?

**Comment by Camotoy** [comment]
Looks like it does. Thanks for bringing it to my attention.

**Comment by eleksploded** [comment]
git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:5972fd2:1642 is still having issues, due to the LoginResult packet properties field being changed from `net.md_5.bungee.connection.LoginResult$Property` to net.md_5.bungee.protocol.Property`
```
java.lang.NoSuchMethodError: 'void net.md_5.bungee.connection.LoginResult.<init>(java.lang.String, java.lang.String, net.md_5.bungee.connection.LoginResult$Property[])'
    at org.geysermc.floodgate.pluginmessage.BungeeSkinApplier.applySkin(BungeeSkinApplier.java:73)
    at org.geysermc.floodgate.listener.BungeeListener.onPostLogin(BungeeListener.java:132)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
    at bungeepluginmanager.ModifiedPluginEventBus.post(ModifiedPluginEventBus.java:33)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:557)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by eleksploded** [comment]
afaik the `PlayerListitem` packet had similar treatment and may cause issues as well.
