### ISSUE TITLE
ApplySkin Floodgate Error on Join

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3016]
### Describe the bug

When I attempt to connect to my Geyser-Bungeecord server, I'm given an error in the console that seems to mention skin application.

### To Reproduce

1. Create a Geyser-Bungeecord server 
2. Connect to it
3. Get error in console

### Expected behaviour

There shouldn't be any errors.

### Screenshots / Videos

```
05:49:18 [WARNING] Error dispatching event PostLoginEvent(player=Gamertag) to listener org.geysermc.floodgate.listener.BungeeListener@38ba8b45
java.lang.NoSuchMethodError: 'void net.md_5.bungee.connection.LoginResult.<init>(java.lang.String, java.lang.String, net.md_5.bungee.connection.LoginResult$Property[])'
    at org.geysermc.floodgate.pluginmessage.BungeeSkinApplier.applySkin(BungeeSkinApplier.java:73)
    at org.geysermc.floodgate.listener.BungeeListener.onPostLogin(BungeeListener.java:132)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:557)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

### Server Version and Plugins

BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:5972fd2:1642

- ViaVersion-4.3.1
- Build 65 of Floodgate
- Build 1108 of Geyser-Bungeecord

### Geyser Dump

https://dump.geysermc.org/uYbpBCWWk3MAD2X7JdhuHTky9qkTCKXK

### Geyser Version

2.0.4-SNAPSHOT (git-master-78bb69b)

### Minecraft: Bedrock Edition Device/Version

1.19 - tested on Windows, iOS and Android

**Comment by Camotoy** [comment]
We're aware of this issue and it should be tracked over at https://github.com/GeyserMC/Floodgate/issues/312.
