### ISSUE TITLE
Error java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by DimaSergeew** [GeyserMC/Geyser#3065]
### Describe the bug

I noticed this weird bug not long ago. Such an error does not occur with PC players, such an error occurs with some GeyserMC players, sometimes after an error they cannot even enter the server. Until I completely reset their account. I would like to understand its origin and understand where its source is

### To Reproduce

I don't know, they sometimes happen randomly with Geyser players

### Expected behaviour

I expect this should not happen.I expect the developers to tell me where to look for its cause

### Screenshots / Videos

![Screenshot_1](https://user-images.githubusercontent.com/75163645/174283194-c61affc4-7e02-42fd-bf2e-4fc3e2d2c8b7.png)

### Server Version and Plugins

Velocity 153

### Geyser Version

This server is running Geyser version 2.0.3-SNAPSHOT (git-master-c83eb7f) (Java: 1.18.2, Bedrock: 1.18.0/1.18.1/1.18.2 - 1.18.30/1.18.31)

**Comment by onebeastchris** [comment]
I'm experiencing a similar issue, here's the log file attached -
[link to the log](https://paste.gg/p/anonymous/cdac9246b4aa469bb85486ad9e5c4436) 

same velocity version, newest geyser, newest floodgate -

**Comment by Camotoy** [comment]
Can Java 1.19 players connect?

**Comment by Camotoy** [comment]
onebeastchris: I don't think your error is related as you're not using this LimboAuth thing.

**Comment by onebeastchris** [comment]
oh, my bad - shall i open a new bug report for that? for me, it happens occasionally, and not limited to bedrock

**Comment by Camotoy** [comment]
It's probably not related to us then unless it doesn't occur without Floodgate.

**Comment by onebeastchris** [comment]
my bad, I'll post it as a bug for velocity
sorry :(

**Comment by DimaSergeew** [comment]
This is quite strange, we used to use Bungeecord and we didn’t have such an error when we switched to Velocity and all my friends who also run servers sometimes have it.

**Comment by DimaSergeew** [comment]
> It's probably not related to us then unless it doesn't occur without Floodgate.

I contacted the Velocity developer with this problem and he answered me like this
![Screenshot_2](https://user-images.githubusercontent.com/75163645/174435480-76558082-918d-4206-8cd1-d822a28ba462.png)

**Comment by BingYanchi** [comment]
I also encountered the same problem, the latest Velocity, the latest Geyser.

**Comment by BingYanchi** [comment]
```
[23:00:28 INFO] [geyser]: Geyser正在启动 0.0.0.0:19132
[23:00:28 INFO] [geyser]: 完成 (5.906s)! 执行/geyser help 来获取帮助信息!
[23:03:04 INFO] [geyser]: /192.168.0.139:65065 尝试连接!
[23:03:05 INFO] [geyser]: 玩家以 Bing Yanchi 的用户名建立了连接
[23:03:54 INFO] [geyser]: Bing Yanchi (登录为: Bing_Yanchi) 已连接到 Java 服务器
[23:03:54 INFO] [geyser]: Bing Yanchi 因为 java.nio.channels.ClosedChannelException 与 Java 版服务器 断开了连接
[23:03:54 ERROR]: java.nio.channels.ClosedChannelException
[23:03:54 ERROR]:       at io.netty.channel.local.LocalChannel.doWrite(LocalChannel.java:368)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
[23:03:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
[23:03:54 ERROR]:       at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[23:03:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[23:03:54 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:249)
[23:03:54 ERROR]:       at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:140)
[23:03:54 ERROR]:       at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[23:03:54 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:145)
[23:03:54 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:346)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[23:03:54 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[23:03:54 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[23:03:54 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[23:03:54 ERROR]:       at org.geysermc.geyser.network.netty.LocalSession$2.channelActive(LocalSession.java:136)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[23:03:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
[23:03:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[23:03:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[23:03:54 ERROR]:       at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
[23:03:54 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[23:03:54 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[23:03:54 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:03:54 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:03:54 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23:03:54 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:889)
```
This issue occurs after the player has finished logging in, using the latest Velocity and Java 17

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser? If it does, please send a new Geyser dump.

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
