### ISSUE TITLE
Failed to verify username

### ISSUE THREAD

**Issue by seb303** [GeyserMC/Geyser#3068]
### Describe the bug

Connecting bedrock client via Velocity proxy to 1.17.1 Paper server no longer works with latest Geyser/Floodgate.

Client reports "Failed to verify username"

Velocity logs show:
```
[21:19:56 INFO] [geyser]: /127.0.0.1:62968 tried to connect!
[21:19:56 INFO] [geyser]: Player connected with username seb30303
[21:19:56 INFO] [geyser]: seb30303 (logged in as: seb30303) has connected to the Java server
[21:19:56 INFO] [floodgate]: Floodgate player who is logged in as .seb30303 00000000-0000-0000-0009-01f65009eec0 joined
[21:19:56 INFO]: [connected player] .seb30303 (/127.0.0.1:0) has connected
[21:19:56 INFO]: [server connection] .seb30303 -> minigames has connected
[21:19:57 INFO]: [server connection] .seb30303 -> minigames has disconnected
[21:19:57 ERROR]: [connected player] .seb30303 (/127.0.0.1:0): disconnected while connecting to minigames: Failed to verify username!
[21:19:57 INFO]: [connected player] .seb30303 (/127.0.0.1:0) has disconnected: Unable to connect to minigames: Failed to verify username!
[21:19:57 INFO] [floodgate]: Floodgate player logged in as seb30303 disconnected
[21:19:57 INFO] [geyser]: seb30303 has disconnected from the Java server because of Unable to connect to minigames: Failed to verify username!
```

Paper logs show:
```
[21:19:57 INFO]: Disconnecting com.mojang.authlib.GameProfile@c420a14[id=00000000-0000-0000-0009-01f65009eec0,name=.seb30303,properties={},legacy=false] (/127.0.0.1:60693): Failed to verify username!
[21:19:57 WARN]: Exception verifying .seb30303
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[patched_1.17.1.jar:git-Paper-411]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:199) ~[patched_1.17.1.jar:git-Paper-411]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[patched_1.17.1.jar:git-Paper-411]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:186) ~[patched_1.17.1.jar:git-Paper-411]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[patched_1.17.1.jar:git-Paper-411]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:191) ~[patched_1.17.1.jar:git-Paper-411]
        at com.destroystokyo.paper.profile.CraftPlayerProfile.complete(CraftPlayerProfile.java:184) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:396) ~[app:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.lambda$handleCustomQueryPacket$2(ServerLoginPacketListenerImpl.java:458) ~[app:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[21:19:57 INFO]: com.mojang.authlib.GameProfile@c420a14[id=00000000-0000-0000-0009-01f65009eec0,name=.seb30303,properties={},legacy=false] (/127.0.0.1:60693) lost connection: Failed to verify username!
```

### To Reproduce

1. Install:
velocity-3.1.2-SNAPSHOT-153
Geyser 2.0.4-SNAPSHOT (git-master-71c489b)
Floodgate 2.2.0-SNAPSHOT (b70-6e2c19f)
ViaVersion 4.3.2-SNAPSHOT
ViaBackwards 4.3.1-SNAPSHOT
2. Connect to Paper 1.17.1-411 using Bedrock client

### Expected behaviour

This used to work very recently until updating to latest versions.

The exact same Velocity setup works fine to connect to a Fabric 1.17.1 backend using Fabric Proxy Lite.

### Server Version and Plugins

velocity-3.1.2-SNAPSHOT-153
Geyser 2.0.4-SNAPSHOT (git-master-71c489b)
Floodgate 2.2.0-SNAPSHOT (b70-6e2c19f)
ViaVersion 4.3.2-SNAPSHOT
ViaBackwards 4.3.1-SNAPSHOT

git-Paper-411 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 6625db3 on ver/1.17.1)

### Geyser Dump

https://dump.geysermc.org/IPstrVSgtlvEWwPNWQERgtJVDlvFrU9j

### Geyser Version

2.0.4-SNAPSHOT (git-master-71c489b)

### Minecraft: Bedrock Edition Device/Version

Minecraft for Windows

**Comment by seb303** [comment]
Have done some more testing with relation to this bug.

I found that if I set a secondary backend running Fabric / Fabric Proxy Lite then the bedrock client connects to this ok, and from here the client can run the command "/server minigames" (which is the paper server) and they will connect ok.

Weirdly, once they have connected to the paper server in this way, they can then connect to the paper server first time, and the error does not re-occur.

I've tested this with various combinations of backends with the same exact thing happening each time:

Primary backend: paper-1.17.1-411
Secondary backend: Fabric 1.17.1

Primary backend: paper-1.17.1-411
Secondary backend: Fabric 1.19

Primary backend: paper-1.18.2-386
Secondary backend: Fabric 1.19

**Comment by Marcof2004** [comment]
No

**Comment by seb303** [comment]
Further note: the trick of joining a Fabric backend first, and then switching to the Paper backend, seems to only work sometimes.  At other times I get the same error when switching to the Paper backend using the /server command.  If I retry then it eventually connects and afterwards can connect to the Paper backend every time (at least for a few hours anyway).

**Comment by Camotoy** [comment]
Is Floodgate present on the backend server / do you have `send-floodgate-data` enabled?

**Comment by seb303** [comment]
Ah that might well be the problem.  We used to have Floodgate on the backend but removed it as it didn't seem to do anything.  But we hadn't set send-floodgate-data back to false.  Have done this now and will see if the problem persists.

Thank you!

**Comment by seb303** [comment]
Setting send-floodgate-data false fixed the issue :)

**Comment by JP123BEAST7169YT** [comment]
i also have this issue

**Comment by onebeastchris** [comment]
https://wiki.geysermc.org/floodgate/issues/#failed-to-verify-username-with-paper
I'd recommend to check our wiki :)
