### ISSUE TITLE
[12:36:16 ERROR]: Could not load 'plugins/floodgate-spigot.jar' in folder 'plugins' org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

### ISSUE THREAD

**Issue by professional-tdi** [GeyserMC/Geyser#3104]
### Describe the bug

This is a bug whenever I start my server,
```
[12:36:16 ERROR]: Could not load 'plugins/floodgate-spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:154) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:419) ~[paper-1.19.jar:git-Paper-41]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-41]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-41]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.zip.ZipException: zip END header not found
        at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469) ~[?:?]
        at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477) ~[?:?]
        at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315) ~[?:?]
        at java.util.zip.ZipFile$Source.get(ZipFile.java:1277) ~[?:?]
        at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
        at java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
        at java.util.jar.JarFile.<init>(JarFile.java:284) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 6 more
```

### To Reproduce

1. Download geyser-paper-floodgate.json egg for the pterodactyl panel.
2. Install the server
3. Running the server for the first time will give you said error.

### Expected behaviour

No error occurring when I start my server.

### Screenshots / Videos

<img width="885" alt="Screen Shot 2022-07-01 at 2 45 38 PM" src="https://user-images.githubusercontent.com/79174456/176897137-b6d312a5-664f-4461-9e6d-7717870cde40.png">

### Server Version and Plugins

```
[12:46:15 INFO]: Checking version, please wait...
[12:46:15 INFO]: This server is running Paper version git-Paper-41 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: a22eb67)
You are running the latest version
```

### Geyser Dump

When running geyser dump, ```[12:46:56 WARN]: Unexpected exception while parsing console command "geyser dump" org.bukkit.command.CommandException: Cannot execute command 'geyser' in plugin Geyser-Spigot v2.0.4-SNAPSHOT - plugin is disabled.         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]         at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.19.jar:git-Paper-41]         at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:870) ~[paper-1.19.jar:git-Paper-41]         at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:473) ~[paper-1.19.jar:git-Paper-41]         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.jar:git-Paper-41]         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-41]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-41]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-41]         at java.lang.Thread.run(Thread.java:833) ~[?:?]```

### Geyser Version

1.19-R0.1-SNAPSHOT (Git: a22eb67)

**Comment by byquanton** [comment]
Looks like your Floodgate Jar is broken. Redownload it and try again

**Comment by Camotoy** [comment]
While it's not impossible to be something else, I'm going to assume this is a result of a corrupt download. Try reinstalling Floodgate and if the issue persists multiple times let us know.

**Comment by johahauf** [comment]
I observe the same. Similar paper and geyser versions. I re-downloaded the last stable floodgate-geyser.jar already, but error persists. Geyser dump: https://dump.geysermc.org/FX5mSUEaP9gjrBTwyKw2yu1AyMqpUgBS
