### ISSUE TITLE
Couldn't look up profile properties issue

### ISSUE THREAD

**Issue by sanegaming** [GeyserMC/Geyser#3108]
### Describe the bug

The server is constantly spamming the console chat with various player profiles with the following error:

[17:56:20 WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@6a736d2e[id=00000000-0000-0000-0009-01fd43ae45cf,name=.E1ectroxity,properties={},legacy=false]
java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.5.41.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:203) ~[authlib-3.5.41.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[paper-1.19.jar:git-Paper-42]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:175) ~[authlib-3.5.41.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$3(SkullBlockEntity.java:142) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:460) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$6(SkullBlockEntity.java:139) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Unsure, this server was upgraded from 1.18 to 1.19 and has had this issue since 1.19

### Expected behaviour

I would expect if the profile is invalid to delete it, or automatically add the Name/ID as it is requesting.

### Geyser Dump

https://dump.geysermc.org/rhFyiwjFn7s16YFjKlbs97t4NKiytdMf

### Geyser Version

2.0.4-SNAPSHOT (git-master-f2f894b) 

### Minecraft: Bedrock Edition Device/Version

All devices

**Comment by Camotoy** [comment]
This has to do with looking up player heads. It's safe to ignore, and is technically a Floodgate issue.
