### ISSUE TITLE
[Geyser-Spigot] cant translate package ClientboundContainerSetContentPacket

### ISSUE THREAD

**Issue by LFMJUN** [GeyserMC/Geyser#3115]
### Describe the bug

[Geyser-Spigot] 无法翻译数据包 ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Spigot.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

Openning menu plugins like TrMenu, the menu displayed wrongly.

### Expected behaviour

The menu should be correctly display.

### Server Version and Plugins

This server is running Paper version git-Paper-387 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: df630a2 on ver/1.18.2)
You are running the latest version

### Geyser Dump

https://dump.geysermc.org/SXGUtrdpLkKaZCPWYLEvGAen1PGt8bDz

### Geyser Version

2.0.4-SNAPSHOT (git-master-dc810f1)

### Minecraft: Bedrock Edition Device/Version

1.19

### Additional Context

java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Spigot.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Camotoy** [comment]
Has this error changed in the latest Geyser build?

**Comment by mclk623** [comment]
Nothing Change

**Comment by LFMJUN** [comment]
> Has this error changed in the latest Geyser build?

NO, This error still occurred

**Comment by HEMO313** [comment]
i get this error too

**Comment by DimaSergeew** [comment]
> Изменилась ли эта ошибка в последней сборке Geyser?

I have the latest build of Geyser for today but this problem is still not solved!
![Screenshot_2](https://user-images.githubusercontent.com/75163645/192482123-1592d316-c70e-48a5-b640-9ec166ffceea.png)

Geyser: #1198
Server: 1.19.2

**Comment by onebeastchris** [comment]
Does this issue still occur with the latest version of Geyser and floodgate?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
