### ISSUE TITLE
[Geyser-Spigot] Missing MC locale file: en_us

### ISSUE THREAD

**Issue by Z735803792** [GeyserMC/Geyser#3153]
### Describe the bug

```
[15:49:19 WARN]: [Geyser-Spigot] Failed to load locale asset cache: zip file closed
[15:49:19 INFO]: [Geyser-Spigot] Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)
[15:49:19 WARN]: [Geyser-Spigot] Unable to download and extract en_us locale!
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at org.geysermc.geyser.text.MinecraftLocale.downloadEN_US(MinecraftLocale.java:266) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.downloadLocale(MinecraftLocale.java:189) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.downloadAndLoadLocale(MinecraftLocale.java:139) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.lambda$static$0(MinecraftLocale.java:59) ~[Geyser-Spigot.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:49:19 WARN]: [Geyser-Spigot] Missing MC locale file: en_us
```

### To Reproduce

java -Xms4G -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs -jar server.jar

### Expected behaviour

Unable to download and extract en_us locale，
I think I should download it myself.

### Screenshots / Videos

![Uploading image.png…]()

### Server Version and Plugins

paper-spigot1.19,
Geyser-Spigot;floodgate;ViaVersion;ViaBackwards

### Geyser Dump

https://dump.geysermc.org/DWWVipNzt1Bt13cznizDJQMpiMXPPda3

### Geyser Version

2.0.5-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Java1.19,ubuntu20.04.4 LTS

**Comment by Camotoy** [comment]
Are you able to attach a full set of startup logs?

**Comment by Konicai** [comment]
Contact us on Discord if you still experience this
