### ISSUE TITLE
spam in console

### ISSUE THREAD

**Issue by amarcais53** [GeyserMC/Geyser#3164]
### Describe the bug

im getting spammed with stack trace on proxy console

### To Reproduce

instal geyser and velocity 
and error come on the console

### Expected behaviour

no errors

### Screenshots / Videos

[13:40:52 ERROR]: java.lang.IllegalArgumentException: Value cannot be outside of accepted range.
[13:40:52 ERROR]:       at com.github.steveice10.mc.protocol.data.game.chunk.BitStorage.set(BitStorage.java:92)
[13:40:52 ERROR]:       at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.set(DataPalette.java:59)
[13:40:52 ERROR]:       at org.geysermc.geyser.session.cache.ChunkCache.updateBlock(ChunkCache.java:107)
[13:40:52 ERROR]:       at org.geysermc.geyser.util.ChunkUtils.updateBlock(ChunkUtils.java:127)
[13:40:52 ERROR]:       at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:48)
[13:40:52 ERROR]:       at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:40)
[13:40:52 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[13:40:52 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[13:40:52 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[13:40:52 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[13:40:52 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[13:40:52 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:40:52 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[13:40:52 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:831)
[13:40:53 ERROR] [geyser]: Could not translate packet ClientboundBlockUpdatePacket
java.lang.IllegalArgumentException: Value cannot be outside of accepted range.
        at com.github.steveice10.mc.protocol.data.game.chunk.BitStorage.set(BitStorage.java:92) ~[?:?]
        at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.set(DataPalette.java:59) ~[?:?]
        at org.geysermc.geyser.session.cache.ChunkCache.updateBlock(ChunkCache.java:107) ~[?:?]
        at org.geysermc.geyser.util.ChunkUtils.updateBlock(ChunkUtils.java:127) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:48) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:40) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.1.2-SNAPSHOT (git-e8bf6ab5-b161)]
        at java.lang.Thread.run(Thread.java:831) [?:?]

### Geyser Dump

https://dump.geysermc.org/7bvYXT51mc0UigkIBLPjxVsb8rtD2WP1

### Geyser Version

version 2.0.5-SNAPSHOT

**Comment by Konicai** [comment]
Can you provide more detailed steps for reproducing this issue? When specifically does this error occur?

**Comment by amarcais53** [comment]
well i have no idea sometimes this errors is being spammed on console and then suddently stop

**Comment by amarcais53** [comment]
bedrock users was complaining about not being able to drop sometimes not sure if this is related

**Comment by Konicai** [comment]
Update Geyser to fix that
