### ISSUE TITLE
Unable to download and extract en_us locale!

### ISSUE THREAD

**Issue by DerpyPlayz18** [GeyserMC/Geyser#3165]
### Describe the bug

Whenever I open the server, Geyser after starting and saying `Done (6,141s)! Run /geyser help for help!`, it starts `Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)`. Then almost instantly it gives a bunch of errors that say `Unable to download and extract en_us locale!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.MinecraftLocale$VersionDownload.getUrl()" because "org.geysermc.geyser.text.MinecraftLocale.clientJarInfo" is null`.

Server logs:
`[15:52:40] [Network Listener - #1/INFO]: Started Geyser on 0.0.0.0:19132
[15:52:40] [Server thread/INFO]: Done (6,141s)! Run /geyser help for help!
[15:52:40] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6393ms or 127 ticks behind
[15:52:50] [ForkJoinPool.commonPool-worker-1/ERROR]: Failed to load locale asset cache: Unrecognized token 'Read': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Read timed out"; line: 1, column: 5]
[15:52:50] [ForkJoinPool.commonPool-worker-1/INFO]: Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)
[15:52:50] [ForkJoinPool.commonPool-worker-1/ERROR]: Unable to download and extract en_us locale!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.MinecraftLocale$VersionDownload.getUrl()" because "org.geysermc.geyser.text.MinecraftLocale.clientJarInfo" is null
        at org.geysermc.geyser.text.MinecraftLocale.downloadEN_US(MinecraftLocale.java:266) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.downloadLocale(MinecraftLocale.java:189) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.downloadAndLoadLocale(MinecraftLocale.java:139) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.lambda$static$0(MinecraftLocale.java:59) ~[Geyser-Fabric.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) [?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[15:52:50] [ForkJoinPool.commonPool-worker-1/WARN]: Missing MC locale file: en_us`

### To Reproduce

1. Create and open a server with Geyser (in my case it is fabric with the mod Geyser-Fabric)
2. Wait for it to load
3. After `Done (6,141s)! Run /geyser help for help!`, it starts giving the errors.

### Expected behaviour

The server should successfully download the locale files without giving errors.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/80034339/180444612-d5d1ecd5-6b02-45f4-92f6-4ed21e7abb9f.png)

### Server Version and Plugins

fabric-server-mc.1.19-loader.0.14.6-launcher.0.11.0 
cloth-config-7.0.65-fabric
fabric-api-0.55.2+1.19
fabric-carpet-1.19-1.4.79+v220607
floodgate-fabric
Geyser-Fabric
lithium-fabric-mc1.19-0.8.0
phosphor-fabric-mc1.19.x-0.8.1
textile_backup-2.3.1-1.19

### Geyser Dump

https://dump.geysermc.org/flrxz9dIIyEhMFibBgr6Lk8YrqYssbMC

### Geyser Version

This server is running Geyser version 2.0.5-SNAPSHOT (git-0efd04dd87183064f51de93bc93b7058aeec9b69-0efd04d) (Java: 1.19, Bedrock: 1.19.0/1.19.2 - 1.19.10)

### Additional Context

Apparently it also fails checking for updates?
(I do have an internet connection and the server works)

`geyser version
[16:02:49] [Server thread/INFO]: This server is running Geyser version 2.0.5-SNAPSHOT (git-0efd04dd87183064f51de93bc93b7058aeec9b69-0efd04d) (Java: 1.19, Bedrock: 1.19.0/1.19.2 - 1.19.10)
[16:02:49] [Server thread/INFO]: Checking version, please wait...
[16:02:49] [Server thread/ERROR]: Failed to check for updates
java.lang.AssertionError: buildNumber missing
        at org.geysermc.geyser.command.defaults.VersionCommand.execute(VersionCommand.java:95) ~[Geyser-Fabric.jar:?]
        at org.geysermc.platform.fabric.command.GeyserFabricCommandExecutor.run(GeyserFabricCommandExecutor.java:81) ~[Geyser-Fabric.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:261) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_44252(class_2170.java:254) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:305) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:290) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zcc000$modifiedRunLoop(MinecraftServer.java:3380) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[16:02:49] [Server thread/INFO]: Failed to check for updates`

**Comment by Konicai** [comment]
Considering your server failed to download both the minecraft locale and the latest build # from our Jenkins, my guess is that you're probably suffering from some sort of DNS or firewall issue

**Comment by Konicai** [comment]
Stale, consider contacting us on Discord if you still experience this
