### ISSUE TITLE
Bedrock Edition cannot receive chat content

### ISSUE THREAD

**Issue by kangming06** [GeyserMC/Geyser#3170]
When I use the bedrock edition to send message, the Java edition can receive it correctly. When the bedrock edition is used to receive message, this message will become "chat.type.text".
![微信图片_20220723164157](https://user-images.githubusercontent.com/74850890/180597650-40df17bb-324f-4a26-bc89-e17fe131b6ca.jpg)
log:
`[16:32:07] [ForkJoinPool.commonPool-worker-1/ERROR]: Failed to load locale asset cache: Unrecognized token 'Read': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Read timed out"; line: 1, column: 5]
[16:32:07] [ForkJoinPool.commonPool-worker-1/INFO]: Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)
[16:32:07] [ForkJoinPool.commonPool-worker-1/ERROR]: Unable to download and extract en_us locale!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.MinecraftLocale$VersionDownload.getUrl()" because "org.geysermc.geyser.text.MinecraftLocale.clientJarInfo" is null
        at org.geysermc.geyser.text.MinecraftLocale.downloadEN_US(MinecraftLocale.java:266) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.downloadLocale(MinecraftLocale.java:189) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.downloadAndLoadLocale(MinecraftLocale.java:139) ~[Geyser-Fabric.jar:?]
        at org.geysermc.geyser.text.MinecraftLocale.lambda$static$0(MinecraftLocale.java:59) ~[Geyser-Fabric.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) [?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[16:32:07] [ForkJoinPool.commonPool-worker-1/WARN]: Missing MC locale file: en_us`

**Comment by Konicai** [comment]
Possible duplicate of https://github.com/GeyserMC/Geyser/issues/3165

Can you share your full server logs after a fresh start through https://mclo.gs? Also share the link that running the command `/geyser dump` provides you

**Comment by onebeastchris** [comment]
Closing due to no response.
