### ISSUE TITLE
Unable to display blood strips, satiety

### ISSUE THREAD

**Issue by xiaobao4909** [GeyserMC/Geyser#3176]
### Describe the bug

Players can't see the display of blood bars, satiety

### To Reproduce

Players join the server

### Expected behaviour

Normal display of blood strips and satiety

### Screenshots / Videos

Nothing

### Server Version and Plugins

I use Geyser standalone

### Geyser Dump

https://dump.geysermc.org/69iMoFpALGOsr19v6aFCDVPxTcSb3sOF

### Geyser Version

Build #1157 (2022年7月25日 上午12:41:22)

### Minecraft: Bedrock Edition Device/Version

1.19+

### Additional Context

Nothing

**Comment by Camotoy** [comment]
Can you send a picture of what you're talking about?

**Comment by xiaobao4909** [comment]
> Can you send a picture of what you're talking about?

What do you mean? I used translation software, which may not translate well

**Comment by Camotoy** [comment]
Can you send a picture of what Bedrock sees and then send a picture of what Java sees?

**Comment by xiaobao4909** [comment]
> 你能发送一张基岩看到的图片，然后发送一张Java看到的图片吗？

ok

**Comment by xiaobao4909** [comment]
> 你能发送一张基岩看到的图片，然后发送一张Java看到的图片吗？

wait a moment

**Comment by xiaobao4909** [comment]
> Can you send a picture of what Bedrock sees and then send a picture of what Java sees?
![{2}(EGBU}T${_2 $T7~CH}I](https://user-images.githubusercontent.com/92622663/181073297-79be7330-0f69-4fa9-abdf-967d7f6e2578.jpg)
![87L51CKUZLV5(`EX1WH@F7](https://user-images.githubusercontent.com/92622663/181073310-f95c9d3c-481b-44e9-a669-d527945db8d6.png)

**Comment by xiaobao4909** [comment]
> Can you send a picture of what Bedrock sees and then send a picture of what Java sees?

I have forwarded it to you

**Comment by Camotoy** [comment]
Are you referring to hearts being missing? Can you try without your modded Bedrock client?

**Comment by xiaobao4909** [comment]
> Are you referring to hearts being missing? Can you try without your modded Bedrock client?

The same is true of those that have not been modified, but my mobile phone can only use the modified terminal

**Comment by xiaobao4909** [comment]
> Are you referring to hearts being missing? Can you try without your modded Bedrock client?

Everyone on my server is reporting that they can't see the blood bar and satiety

**Comment by xiaobao4909** [comment]
> 你指的是心形缺失吗？你能在没有修改后的基岩客户端的情况下尝试吗？



> 你指的是心形缺失吗？你能在没有修改后的基岩客户端的情况下尝试吗？

Yes, it's lack of heart shape

**Comment by Camotoy** [comment]
Are you able to try with no other plugins because Floodgate and ViaVersion if relevant on your server?

**Comment by xiaobao4909** [comment]
> Floodgate

After testing, it is in a server with only viaversion and floodgate. There will still be this bug

**Comment by Camotoy** [comment]
What is the output of `/version` on the server?

**Comment by xiaobao4909** [comment]
> 服务器上的输出是什么？`/version`

On the sub service in the picture, it's like this:
> version
[01:54:23 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[01:54:23 INFO]: Checking version, please wait...
[01:54:28 WARN]: java.lang.NumberFormatException: For input string: ""
[01:54:28 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[01:54:28 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:668)
[01:54:28 WARN]:        at java.base/java.lang.Integer.valueOf(Integer.java:973)
[01:54:28 WARN]:        at java.base/java.lang.Integer.decode(Integer.java:1458)
[01:54:28 WARN]:        at org.bukkit.command.defaults.VersionCommand.getFromJenkins(VersionCommand.java:295)
[01:54:28 WARN]:        at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:266)
[01:54:28 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:214)
[01:54:28 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:37)
[01:54:28 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:199)
[01:54:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:54:28 INFO]: Unknown version
>

**Comment by xiaobao4909** [comment]
> 服务器上的输出是什么？`/version`

Why don't you reply to me? My server may not be able to link to the Internet server
