### ISSUE TITLE
"Unable to translate packet clientboundcontainersetcontentpacket" appears in the background

### ISSUE THREAD

**Issue by xiaobao4909** [GeyserMC/Geyser#3190]
### Describe the bug

This error occurs in the background:
[21:19:04 ERROR] 无法翻译数据包 ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111) ~[Geyser.jar:?]
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
> java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111)
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55)
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73)
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
[21:19:04 ERROR] 无法翻译数据包 ClientboundContainerSetContentPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111) ~[Geyser.jar:?]
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
> java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:111)
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55)
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:73)
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetContentTranslator.translate(JavaContainerSetContentTranslator.java:38)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

unknown

### Expected behaviour

No error will be reported and the problem will be solved

### Screenshots / Videos

Nothing

### Server Version and Plugins

I use the independent Geyser

### Geyser Dump

[22:30:25 INFO] 我们已转储了有用的信息, 报告您的问题并提供以下网址: https://dump.geysermc.org/8YVLGbj0jTWdFfWMI3qCYwh1jzbVDXYg

### Geyser Version

2.0.6-SNAPSHOT (git-master-d826949)

### Minecraft: Bedrock Edition Device/Version

1.19.10

### Additional Context

Nothing

**Comment by Camotoy** [comment]
The easiest way for us to address this is to know how to reproduce it.

**Comment by Konicai** [comment]
If you can provide detailed instructions of how to consistently reproduce this issue/error please append it here: https://github.com/GeyserMC/Geyser/issues/3115
