### ISSUE TITLE
Possibility that the version to "Fix form responses on 1.19.20" creates another error

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3221]
### Describe the bug

My Bungeecord console is being spammed with this error when a player tries to close a Bedrock menu:

```
13:41:53 [WARNING] [Geyser-BungeeCord] Error while processing form response!
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "response" is null
    at org.geysermc.geyser.translator.protocol.java.JavaCustomPayloadTranslator.lambda$translate$0(JavaCustomPayloadTranslator.java:75)
    at org.geysermc.cumulus.form.util.impl.FormCodecImpl.lambda$setRawResponseConsumer$0(FormCodecImpl.java:83)
    at org.geysermc.cumulus.form.impl.FormImpl.callRawResponseConsumer(FormImpl.java:56)
    at org.geysermc.cumulus.form.impl.FormDefinition.callRawResponseConsumer(FormDefinition.java:69)
    at org.geysermc.cumulus.form.impl.FormDefinition.handleFormResponse(FormDefinition.java:60)
    at org.geysermc.geyser.session.cache.FormCache.handleResponse(FormCache.java:98)
    at org.geysermc.geyser.network.UpstreamPacketHandler.lambda$handle$0(UpstreamPacketHandler.java:181)
    at org.geysermc.geyser.session.GeyserSession.lambda$executeInEventLoop$8(GeyserSession.java:1076)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

1. Create a plugin that uses a Bedrock menu
2. Connect to the server, open the menu and press the "X" in the menu
3. See the error

### Expected behaviour

This didn't happen prior to 1.19.20 and the newest versions of Geyser. This wouldn't be plugin related since the only plugin updated in the last 72 hours has been Geyser.

### Server Version and Plugins

Bungeecord - latest
ViaVersion - latest
Geyser-Bungeecord - latest
Spigot - 1.12.2

### Geyser Version

Geyser version 2.0.7-SNAPSHOT (git-master-25a18a2)

### Minecraft: Bedrock Edition Device/Version

1.19.20 - tested on Windows

**Comment by Camotoy** [comment]
Konica linked their issue that will fix this.
