### ISSUE TITLE
Bug with Log, Cobblestone

### ISSUE THREAD

**Issue by Bossbirdyman51** [GeyserMC/Geyser#3224]
### Describe the bug

We have problem when the player have Spruce log, acacia_log or another, he see only oak_log
it's same with cobblestone, stockbrick slab stairs ...

Thank for help ;)

CONSOLE executed command: /geyser dump
Collecting dump info
ERROR00:06:03
Exception in thread "main" java.lang.AssertionError: Unable to find resource: git.properties
at org.geysermc.geyser.GeyserBootstrap.getResource(GeyserBootstrap.java:157)
at org.geysermc.geyser.dump.DumpInfo.<init>(DumpInfo.java:92)
at org.geysermc.geyser.command.defaults.DumpCommand.execute(DumpCommand.java:93)
at org.geysermc.geyser.platform.bungeecord.command.GeyserBungeeCommandExecutor.execute(GeyserBungeeCommandExecutor.java:71)
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:181)
at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### To Reproduce

Give spruce_log to a bedrock player

### Expected behaviour

We have problem when the player have Spruce log, acacia_log or another, he see only oak_log

CONSOLE executed command: /geyser dump
Collecting dump info
ERROR00:06:03
Exception in thread "main" java.lang.AssertionError: Unable to find resource: git.properties
at org.geysermc.geyser.GeyserBootstrap.getResource(GeyserBootstrap.java:157)
at org.geysermc.geyser.dump.DumpInfo.<init>(DumpInfo.java:92)
at org.geysermc.geyser.command.defaults.DumpCommand.execute(DumpCommand.java:93)
at org.geysermc.geyser.platform.bungeecord.command.GeyserBungeeCommandExecutor.execute(GeyserBungeeCommandExecutor.java:71)
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:212)
at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:163)
at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30)
at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87)
at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:181)
at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143)
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72)
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Screenshots / Videos

https://user-images.githubusercontent.com/13882938/184028923-9d06d7cb-f978-43e7-aa53-a12fa649256a.mp4

https://user-images.githubusercontent.com/13882938/184028929-12f0b2a0-51a5-4fb4-b9b0-0015cacce893.mov

### Server Version and Plugins

Previous: git-Paper-81 (MC: 1.19)
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads

### Geyser Version

Latest version #1174

### Minecraft: Bedrock Edition Device/Version

All version 1.19.20

**Comment by Camotoy** [comment]
We have literally just pushed that build. Try actually updating - if you're using extensions that'll be fixed soon.

**Comment by Bossbirdyman51** [comment]
Yes it's work with latest version thanks ;)
