### ISSUE TITLE
Bedrock Users can't see Crafting Recipe

### ISSUE THREAD

**Issue by Taerutawnoi** [GeyserMC/Geyser#3245]
### Describe the bug

When Bedrock player wants to craft something, the crafting recipe does not show up and they need to craft it by themself.

### To Reproduce

1.bedrock user connected to server 
2.the console says
```
[Geyser-Spigot] Could not translate packet ClientboundUpdateRecipesPacket
java.lang.NullPointerException: Cannot invoke "com.github.steveice10.mc.protocol.data.game.entity.metadata.ItemStack.getId()" because "itemStack" is null
	at org.geysermc.geyser.registry.type.ItemMappings.getMapping(ItemMappings.java:80) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.lambda$translate$0(JavaUpdateRecipesTranslator.java:169) ~[?:?]
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469) ~[?:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1306) ~[?:?]
	at java.util.ArrayList.sort(ArrayList.java:1721) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.translate(JavaUpdateRecipesTranslator.java:168) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.translate(JavaUpdateRecipesTranslator.java:66) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[?:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[patched_1.16.5.jar:git-Paper-794]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Paper-794]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Paper-794]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```
3.use the crafting table
4.no any crafting recipe exist

### Expected behaviour

the crafting table show the crafting recipe

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/75173164/185905353-83e65250-7318-4490-bef3-98df09fe2ac3.png)

![image](https://user-images.githubusercontent.com/75173164/185901688-44664071-a171-4fd5-a6af-88e6bc89c21d.png)

### Server Version and Plugins

This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Plugins (11): BestTools, BetterBackpacks, ChestSort, Geyser-Spigot, ImageMaps, LuckPerms, NBTAPI, RoseStacker, SkinsRestorer, ViaVersion, ViaVersionStatus

### Geyser Dump

https://dump.geysermc.org/oeEhxn8pKvjpcg2ZGc6SKpUyWkFMaP2R

### Geyser Version

2.0.7-SNAPSHOT (git-master-d499e22)

### Minecraft: Bedrock Edition Device/Version

1.19.20 Windows/Android/ios

**Comment by Camotoy** [comment]
Are you using any datapacks? Otherwise, can you try with no other plugins? It's likely one of those two, and once the plugin in question is figured out I'll be able to reproduce it on my end.

**Comment by onebeastchris** [comment]
Closing due to no response.
