### ISSUE TITLE
When modifying the WINDOW_ITEMS packet for bedrock players, it doesn't work

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#3249]
### Describe the bug

When I modify the WINDOW_ITEMS packet for java players, it works fine. When I try and do it for bedrock players, it doesn't work.

It WAS working while I was using an older geyser version, older protocollib, older paper spigot.

I just recently updated to the latest of all 3 software above, and no the bug is occuring.

### To Reproduce

Modify WINDOW_ITEMS packet for bedrock & java. Then check if the modification worked on java, and then bedrock on the latest version of Geyser Velocity, paper 1.19.2, protocollib 5.0.0 b598 

### Expected behaviour

Modifying the packet should work for bedrock players

### Server Version and Plugins

MC: 1.19.2 puffer fish-32 GIT: 254c002

### Geyser Dump

https://dump.geysermc.org/Q44CdKabWTJH9mvVQMFhFz0IFcECJ23c

### Geyser Version

 [01:43:20 INFO]: This server is running Geyser version 2.0.7-SNAPSHOT (git-master-8dde4b4) (Java: 1.19.1 - 1.19.2, Bedrock: 1.19.0/1.19.2 - 1.19.21) [01:43:20 INFO]: Checking version, please wait...

### Minecraft: Bedrock Edition Device/Version

ALL

**Comment by Camotoy** [comment]
As said in the Discord it's easier if we have a code snippet.

For giggles I would also try with 1.19.1 instead of 1.19.2... 
And do you have Floodgate on your backend server?

**Comment by spookymgmt** [comment]
package me.rages.inventoryfix;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolLibrary;
import com.comphenix.protocol.events.ListenerPriority;
import com.comphenix.protocol.events.PacketAdapter;
import com.comphenix.protocol.events.PacketEvent;
import com.comphenix.protocol.wrappers.WrappedChatComponent;
import com.google.common.collect.ImmutableSet;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import me.lucko.helper.Events;
import me.lucko.helper.plugin.ExtendedJavaPlugin;
import me.lucko.helper.plugin.ap.Plugin;
import net.md_5.bungee.api.chat.BaseComponent;
import net.md_5.bungee.chat.ComponentSerializer;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryType;
import org.bukkit.inventory.AnvilInventory;
import org.bukkit.inventory.ItemStack;
import org.geysermc.floodgate.api.FloodgateApi;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Plugin(
        name = "BedrockInventoryFix",
        hardDepends = {"helper", "ProtocolLib",
                "floodgate"
        },
        apiVersion = "1.19"
)
public final class BedrockInventoryFix extends ExtendedJavaPlugin {

    private HashSet<String> ignoredInventories = new HashSet<>();
    private HashSet<Player> cachedPlayers = new HashSet<>();

    private static final Set<Material> BAD_BEDROCK_MATERIALS = ImmutableSet.of(Material.WHITE_STAINED_GLASS_PANE, Material.ORANGE_STAINED_GLASS_PANE, Material.MAGENTA_STAINED_GLASS_PANE, Material.LIGHT_BLUE_STAINED_GLASS_PANE, Material.YELLOW_STAINED_GLASS_PANE, Material.LIME_STAINED_GLASS_PANE, Material.PINK_STAINED_GLASS_PANE, Material.GRAY_STAINED_GLASS_PANE, Material.LIGHT_GRAY_STAINED_GLASS_PANE, Material.CYAN_STAINED_GLASS_PANE, Material.PURPLE_STAINED_GLASS_PANE, Material.BLUE_STAINED_GLASS_PANE, Material.BROWN_STAINED_GLASS_PANE, Material.GREEN_STAINED_GLASS_PANE, Material.RED_STAINED_GLASS_PANE, Material.BLACK_STAINED_GLASS_PANE);

    @Override
    protected void enable() {
        this.saveDefaultConfig();
        getConfig().getStringList("ignored-inventories").forEach(str -> this.ignoredInventories.add(ChatColor.stripColor(ChatColor.translateAlternateColorCodes('&', str.toLowerCase()))));

        ProtocolLibrary.getProtocolManager().addPacketListener(new PacketAdapter(this, ListenerPriority.HIGHEST, PacketType.Play.Server.WINDOW_ITEMS, PacketType.Play.Server.OPEN_WINDOW) {
            @Override
            public void onPacketSending(PacketEvent event) {
                Player player = event.getPlayer();
                if (FloodgateApi.getInstance().isFloodgateId(player.getUniqueId())) {
                    if (event.getPacketType() == PacketType.Play.Server.OPEN_WINDOW) {
                        WrappedChatComponent component = event.getPacket().getChatComponents().read(0);
                        JsonObject jsonObject = new Gson().fromJson(component.getJson(), JsonObject.class);
                        if (jsonObject.has("text") && ignoredInventories.contains(ChatColor.stripColor(BaseComponent.toLegacyText(ComponentSerializer.parse(component.getJson())).toLowerCase()))) {
                            cachedPlayers.add(event.getPlayer());
                        }
                    } else if (event.getPacketType() == PacketType.Play.Server.WINDOW_ITEMS) {
                        if (!cachedPlayers.contains(player)) {
                            List<ItemStack> items = new ArrayList<>();
                            event.getPacket().getItemListModifier().modify(0, input -> {
                                input.forEach(itemStack -> {
                                    if (isFillerPane(itemStack)) {
                                        items.add(new ItemStack(Material.AIR));
                                    } else {
                                        items.add(itemStack);
                                    }
                                });
                                return items;
                            });
                        } else {
                            cachedPlayers.remove(player);
                        }
                    }
                }
            }
        });

        // prevent players from making invisible glass panes
        Events.subscribe(InventoryClickEvent.class)
                .filter(event -> event.getInventory() instanceof AnvilInventory)
                .filter(event -> event.getCurrentItem() != null)
                .filter(event -> BAD_BEDROCK_MATERIALS.contains(event.getCurrentItem()))
                .filter(event -> event.getSlotType() == InventoryType.SlotType.RESULT)
                .handler(event -> {
                    if (((AnvilInventory) event.getInventory()).getRenameText().equals(" ")) {
                        event.setCancelled(true);
                    }
                }).bindWith(this);

    }

    private boolean isFillerPane(ItemStack itemStack) {
        return BAD_BEDROCK_MATERIALS.contains(itemStack.getType()) && itemStack.hasItemMeta() && (itemStack.getItemMeta().getDisplayName().equals(" "));
    }

}

and yes I'm using flootgate

**Comment by Camotoy** [comment]
I can't reproduce this. ProtocolLib build 600 with Floodgate forwarding enabled.

**Comment by spookymgmt** [comment]
I receive this error when trying the above plugin

[01:14:01 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutWindowItems@51ac89a1[
    a=0
    b=674
    c=[4 oak_planks, 9 oak_log, 1 air, 1 air, 1 air, 1 leather_helmet, 1 leather_chestplate, 1 leather_leggings, 1 leather_boots, 16 torch, 8 stick, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 stone_pickaxe, 1 stone_axe, 1 stone_shovel, 1 stone_sword, 6 tnt, 64 oak_planks, 6 oak_sapling, 1 air, 16 bread, 1 air]
    d=1 air
  ]

[01:14:01 ERROR]: [BedrockInventoryFix] Unhandled exception number 32 occurred in onPacketSending(PacketEvent) for BedrockInventoryFix
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, com.google.common.base.Function)'
        at me.rages.inventoryfix.BedrockInventoryFix$1.onPacketSending(BedrockInventoryFix.java:66) ~[original-BedrockInventoryFix-1.0-SNAPSHOT (7).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:570) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:473) ~[ProtocolLib (5).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib (5).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:432) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:379) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2167) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2153) ~[?:?]
        at net.minecraft.server.level.ServerPlayer$1.sendInitialData(ServerPlayer.java:282) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.sendAllDataToRemote(AbstractContainerMenu.java:201) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.broadcastFullState(AbstractContainerMenu.java:278) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3384) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1362) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1339) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1332) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1310) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1198) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-32]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by spookymgmt** [comment]
Yep figured it out, sorry for waste of time 😢
