### ISSUE TITLE
Error to geyser

### ISSUE THREAD

**Issue by xTheKingMX** [GeyserMC/Geyser#3264]
### Describe the bug

[Server] [WARN] [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$11670/0x0000000803371a58@28aaf61
[02.09 11:33:06] [Server] java.lang.RuntimeExceptionUnable to inflate buffer data
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02.09 11:33:06] [Server] Caused byjava.util.zip.DataFormatException: invalid stored block lengths
[02.09 11:33:06] [Server] 	at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
[02.09 11:33:06] [Server] 	at java.util.zip.Inflater.inflate(Inflater.java:546) ~[?:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	... more
[02.09 11:33:06] [Server] [WARN] [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$11670/0x0000000803371a58@1f536e47
[02.09 11:33:06] [Server] java.lang.RuntimeExceptionUnable to inflate buffer data
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
[02.09 11:33:06] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02.09 11:33:06] [Server] Caused byjava.util.zip.DataFormatException: invalid block type
[02.09 11:33:06] [Server] 	at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
[02.09 11:33:06] [Server] 	at java.util.zip.Inflater.inflate(Inflater.java:546) ~[?:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser-Spigot (2).jar:?]
[02.09 11:33:06] [Server] 	... more

### To Reproduce

does anyone know how to fix it?

### Expected behaviour

Until a few days ago it worked correctly, users could enter and play without problem now they enter and cannot interact with anything as if they were laggy

### Server Version and Plugins

Minecraft 1.19.2 

### Geyser Version

geyser 1.19.2

### Minecraft: Bedrock Edition Device/Version

1.19.2

**Comment by Camotoy** [comment]
Please supply the version you're trying to connect with on Bedrock, and a Geyser dump:

Run `geyser dump` (server console) / `/geyser dump` (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. A Geyser dump is a way of providing us with a bunch of useful information about your server and Geyser config. This doesn't include any IPs or sensitive data.

**Comment by xTheKingMX** [comment]
https://dump.geysermc.org/xf2LEiq2GVJqJfxSHzaMUh0RUp59QZx1

**Comment by Camotoy** [comment]
Please see #2861. Thanks!
