### ISSUE TITLE
Velocity can't connect, big warn in console

### ISSUE THREAD

**Issue by frop1k** [GeyserMC/Geyser#3290]
### Describe the bug

When I try to connect I get an eternal loading screen on client side, server side theres a big warn spam idk what it means...

### To Reproduce

1. Install geyser on velocity
2. try to connect 

### Expected behaviour

[18:22:23 INFO] [geyser]: /95.180.103.24:37672 tried to connect!
[18:22:23 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$2704/0x0000000801894cc8@6f63051d
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:283) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.1.2-SNAPSHOT (git-213f3f88-b183)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
        at java.util.zip.Inflater.inflate(Inflater.java:546) ~[?:?]
        at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[?:?]
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[?:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[?:?]
        ... 9 more
[18:22:53 INFO] [geyser]: Bedrock user with ip: /95.180.103.24 has disconnected for reason Bedrock client disconnected

### Server Version and Plugins

Server is Velocity 3.1.2 snapshot 183

### Geyser Dump

https://dump.geysermc.org/wjOquCU3xrhHOBWUMAja0KFm3FNj258p

### Geyser Version

2.0.7-SNAPSHOT (git-master-a16fc9c)

### Minecraft: Bedrock Edition Device/Version

1.19.40

**Comment by Camotoy** [comment]
> 1.19.40

You're using a beta version which Geyser doesn't support.
