### ISSUE TITLE
Bedrock has recipes in the crafting table ! was working before 1.19.30

### ISSUE THREAD

**Issue by shawn695** [GeyserMC/Geyser#3295]
### Describe the bug

bedrock users dont have the crafting recipe list, they got to do it like java players

### To Reproduce

open crafting table, no recipes 

### Expected behaviour

bedrock craftingtable acts like java crafting table

### Screenshots / Videos

https://user-images.githubusercontent.com/92684055/191413798-1410e44a-a72f-484a-9e00-ccb4c556018a.mp4

### Geyser Dump

https://dump.geysermc.org/YxrUbjQ6xxRxGwor43HKlS3S9K7Dwv28

### Geyser Version

Current: git-Purpur-1783 (MC: 1.19.2)* Previous: git-Purpur-1763 (MC: 1.19.2) * You are running the latest version

### Minecraft: Bedrock Edition Device/Version

bedrock on all devices

**Comment by selfslaughter** [comment]
We have the same problem since updating to Geyser-Bungeecord 1192.

Players have no recipes unlocked, and manually crafting something apparently adds a broken recipe:

`Example, I made stone stairs, it appears in my recipe, I needed more, clicked in the short cut, it made stone walls instead`

Console throws this error when a bedrock player connects.

Dump: [https://dump.geysermc.org/dOzLFSOmlbiyrEBr47lF0VdidMRk8P2J](url)

```
16:10:05 [WARNING] [Geyser-BungeeCord] Could not translate packet ClientboundUpdateRecipesPacket
java.lang.ClassCastException: class com.nukkitx.protocol.bedrock.data.inventory.descriptor.InvalidDescriptor cannot be cast to class com.nukkitx.protocol.bedrock.data.inventory.descriptor.DefaultDescriptor (com.nukkitx.protocol.bedrock.data.inventory.descriptor.InvalidDescriptor and com.nukkitx.protocol.bedrock.data.inventory.descriptor.DefaultDescriptor are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @68702e03)
    at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.lambda$combinations$3(JavaUpdateRecipesTranslator.java:224)
    at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1142)
    at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.combinations(JavaUpdateRecipesTranslator.java:224)
    at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.translate(JavaUpdateRecipesTranslator.java:120)
    at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.translate(JavaUpdateRecipesTranslator.java:70)
    at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
    at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
16:10:05 [SEVERE] java.lang.ClassCastException: class com.nukkitx.protocol.bedrock.data.inventory.descriptor.InvalidDescriptor cannot be cast to class com.nukkitx.protocol.bedrock.data.inve
ntory.descriptor.DefaultDescriptor (com.nukkitx.protocol.bedrock.data.inventory.descriptor.InvalidDescriptor and com.nukkitx.protocol.bedrock.data.inventory.descriptor.DefaultDescriptor are
 in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @68702e03)

16:10:05 [SEVERE]     at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.lambda$combinations$3(JavaUpdateRecipesTranslator.java:224)

16:10:05 [SEVERE]     at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1142)

16:10:05 [SEVERE]     at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)

16:10:05 [SEVERE]     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)

16:10:05 [SEVERE]     at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)

16:10:05 [SEVERE]     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)

16:10:05 [SEVERE]     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)

16:10:05 [SEVERE]     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)

16:10:05 [SEVERE]     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

16:10:05 [SEVERE]     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)

16:10:05 [SEVERE]     at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.combinations(JavaUpdateRecipesTranslator.java:224)

16:10:05 [SEVERE]     at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.translate(JavaUpdateRecipesTranslator.java:120)

16:10:05 [SEVERE]     at org.geysermc.geyser.translator.protocol.java.JavaUpdateRecipesTranslator.translate(JavaUpdateRecipesTranslator.java:70)

16:10:05 [SEVERE]     at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)

16:10:05 [SEVERE]     at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)

16:10:05 [SEVERE]     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

16:10:05 [SEVERE]     at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

16:10:05 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)

16:10:05 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

16:10:05 [SEVERE]     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

16:10:05 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Camotoy** [comment]
Can you please try the latest Geyser build?

**Comment by shawn695** [comment]
It is working again

**Comment by Camotoy** [comment]
Great to hear.
