### ISSUE TITLE
Error dispatching event PluginMessageEvent

### ISSUE THREAD

**Issue by Serial1990** [GeyserMC/Geyser#3306]
### Describe the bug

When i use the newest update von jenkins (#1194/#1195/#1996) the server is running with the following error messages:

`[12:03:04] [Netty Worker IO Thread #61/WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@1c6c3ec7, receiver=bifilulz), cancelled=false, tag=btlp:bridge) to listener codecrafter47.bungeetablistplus.bridge.BukkitBridge@6e3ca6a2
java.lang.NoSuchMethodError: 'org.geysermc.api.session.Connection org.geysermc.api.GeyserApiBase.connectionByUuid(java.util.UUID)'
	at codecrafter47.bungeetablistplus.util.GeyserCompat.lambda$static$0(GeyserCompat.java:26) ~[?:?]
	at codecrafter47.bungeetablistplus.util.GeyserCompat.isBedrockPlayer(GeyserCompat.java:49) ~[?:?]
	at codecrafter47.bungeetablistplus.bridge.BukkitBridge.onPluginMessage(BukkitBridge.java:137) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:289) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxy.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### To Reproduce

1. Update to the newest Jenkins Build #1996
2. Start Server with Waterfall #504

### Expected behaviour

idk :D

### Server Version and Plugins

Waterfall #504

### Geyser Version

2.0.7-SNAPSHOT #1195

**Comment by Camotoy** [comment]
This is an issue with the BungeeTabListPlus Bridge code, not on our end. They have to fix this on their end. Rest assured that this API in its current state is something we're happy with and do not plan to change for a very long time.
