### ISSUE TITLE
Task BungeeTask

### ISSUE THREAD

**Issue by Gafnaraja** [GeyserMC/Geyser#3312]
### Describe the bug

06:54:28 [SEVERE] [Geyser-BungeeCord] Failed to start Geyser on 0.0.0.0:25573
06:54:28 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@6bea52d4, id=48, owner=org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin@36e9794c, task=org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin$$Lambda$1289/0x0000000800f3d9b0@78a0d664, delay=0, period=0, running=true) encountered an exception
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
    at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
    at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
    at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498)
    at java.base/java.util.concurrent.CompletableFuture.unipush(CompletableFuture.java:593)
    at java.base/java.util.concurrent.CompletableFuture.bipush(CompletableFuture.java:1247)
    at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1522)
    at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1517)
    at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1517)
    at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2419)
    at com.nukkitx.network.util.Bootstraps.allOf(Bootstraps.java:118)
    at com.nukkitx.network.raknet.RakNetServer.bindInternal(RakNetServer.java:84)
    at com.nukkitx.network.raknet.RakNet.bind(RakNet.java:46)
    at com.nukkitx.protocol.bedrock.Bedrock.bind(Bedrock.java:37)
    at org.geysermc.geyser.GeyserImpl.startInstance(GeyserImpl.java:311)
    at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:200)
    at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:637)
    at org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin.postStartup(GeyserBungeePlugin.java:185)
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

### To Reproduce

a

### Expected behaviour

please help me

### Screenshots / Videos

![Screenshot 2022-06-23 065805](https://user-images.githubusercontent.com/90326055/192213128-348652c4-f843-4ce4-928c-a48ee177c34d.JPG)

### Geyser Version

https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/1196/

**Comment by Jens-Co** [comment]
Hello there, the error is being caused by; Address already in use. It's a common error when the query port and Geyser port are the same, if that's the case you can disable the query port or change it into something else other then 25573.

**Comment by Gafnaraja** [comment]
> Hello there, the error is being caused by; Address already in use. It's a common error when the query port and Geyser port are the same, if that's the case you can disable the query port or change it into something else other then 25573.

still can't

**Comment by Gafnaraja** [comment]
when i use geyser on versions prior to support update 1.19.30 can still when i update support 1.19.30 i experience this

**Comment by Jens-Co** [comment]
Can you please upload full server logs ? You can use https://mclo.gs and paste the link here.

**Comment by Gafnaraja** [comment]
> Can you please upload full server logs ? You can use https://mclo.gs and paste the link here.

https://mclo.gs/AoqMQ1M

**Comment by gamer50082** [comment]
For my experience I have issue with nantibot (free) with geyser

**Comment by gamer50082** [comment]
Is query enabled? For the port cause I had the same issue

**Comment by gamer50082** [comment]
And yes  I think their new update broke geyser

**Comment by Gafnaraja** [comment]
Please fix this bug before update Please fix this port bug, I used to use the old version before the 1.19.30 update mcpe support still works but when the 1.19.30 update can't be used
