### ISSUE TITLE
Bedrock players do not load chunks at all [Standalone]

### ISSUE THREAD

**Issue by Kashalls** [GeyserMC/Geyser#3369]
### Describe the bug

Upon entry to the world, everything loads for the player except blocks (the entire world). Entities spawn in, but are not moving.

Geyser seems to emit an error regarding ClientboundLevelChunkWithLightPacket errors.
```
Oct 26 12:14:50 phaseaway startup.sh[97811]: [12:14:50 ERROR] Could not translate packet ClientboundLevelChunkWithLightPacket
Oct 26 12:14:50 phaseaway startup.sh[97811]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithL>
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithL>
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[geyser.jar:?]
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[geyse>
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [geyser.jar:?]
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [geyser.jar:?]
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [geyser.jar:?]
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [geyser.jar:?]
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [geyser.jar:?]
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at java.lang.Thread.run(Thread.java:833) [?:?]
Oct 26 12:14:50 phaseaway startup.sh[97811]: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithL>
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithL>
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Oct 26 12:14:50 phaseaway startup.sh[97811]:         at java.base/java.lang.Thread.run(Thread.java:833)
```

Possible duplicate of #3363 

### To Reproduce

1. Login
2. Wait
3. No world.

### Expected behaviour

1. Login
2. Happy happy fun time.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/948004872358346772/1034719479453728788/ADA0CC91-008E-46BB-8935-B7D0DB8FC355.jpg
https://cdn.discordapp.com/attachments/948004872358346772/1034863139025600542/A231E295-45C2-42A0-A12F-FCF9A3C34413.jpg

### Server Version and Plugins

I do not control the remote server, afaik it is running paper 1.18.2 with ViaVersion that goes to 1.19.2. 
had no issue going before 1.19.40

### Geyser Dump

https://dump.geysermc.org/xTiMAKCqFDIaYikHx7pqMshDw1XLH3uf

### Geyser Version

2.1.0-SNAPSHOT (git-master-e9b99b2)

### Minecraft: Bedrock Edition Device/Version

1.19.40 NS & PS4

**Comment by SmokinShark** [comment]
I can confirm that Bug! Got the same Issue on my Server.
Tested with PS4, Bedrock on PC and Bedrock on Mobile.

**Comment by CitizenPrayer** [comment]
Confirmed as well.

**Comment by ijescobarj** [comment]
i have the same issue, but i can tell aditionally i saw this message on log, when starting geyser console.

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

**Comment by Camotoy** [comment]
I get that log message as well but I still load chunks. 

I've just fixed one instance of this issue, but I don't think I've fixed every instance.

**Comment by Jerry12228** [comment]
我将geyser版本退回了2.1.0-SNAPSHOT (git-master-f4b8105)暂时性解决了这个问题

**Comment by SmokinShark** [comment]
This Bug was fixed with the latest Version 1223.
After Download it restart (not reload) the Server!

**Comment by Kashalls** [comment]
Fixed in latest patch, thanks guys!
