### ISSUE TITLE
Add Enchantment in Anvil dows not work

### ISSUE THREAD

**Issue by ronsuper** [GeyserMC/Geyser#3430]
### Describe the bug

With Bedrock Version it is not possible to use the anvil.
Console output:
 [17:53:48 WARN]: [Geyser-Spigot] Could not translate packet ItemStackRequestPacket
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.geysermc.geyser.translator.inventory.AnvilInventoryTranslator.translateSpecialRequest(AnvilInventoryTranslator.java:63) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:160) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Spigot.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:53:48 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
[17:53:48 WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.AnvilInventoryTranslator.translateSpecialRequest(AnvilInventoryTranslator.java:63)
[17:53:48 WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:160)
[17:53:48 WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[17:53:48 WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[17:53:48 WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
[17:53:48 WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[17:53:48 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:53:48 WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[17:53:48 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[17:53:48 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:53:48 WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:53:48 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

Use Anvil

### Expected behaviour

Use Anvil

### Server Version and Plugins

paper 1.19.2 300
geycer 2.1.0 Snaoshot (git master 49d3254)
Java 1.19.1- 1.19.2, Bedrock: 1.19.20-1.19.50

### Geyser Version

2.1.0-Sbnapshot (git-master-49d3254

### Minecraft: Bedrock Edition Device/Version

1.19.50

**Comment by Konicai** [comment]
This was fixed in a recent build of Geyser, please update to the newer version :)
