### ISSUE TITLE
END & NETHER DIMENSION DONT LOAD on latest version

### ISSUE THREAD

**Issue by spookymgmt** [GeyserMC/Geyser#3440]
### Describe the bug

Zero blocks load in, you cant do anything if you go from overworld to nether, or overworld to end.

### To Reproduce

Latest version geyser standalone, join on bedrock, /warp nether.

### Expected behaviour

see blocks

### Server Version and Plugins

paper 1.19.2, velocity build 188, latest geyser.

### Geyser Dump

https://dump.geysermc.org/lDeDUPiCHZu3AGbXdZLTTb5Pm7Fxg8fW

### Geyser Version

latest

### Minecraft: Bedrock Edition Device/Version

latest

### Additional Context

not sure if related, but also this

[22:33:57 ERROR] Could not translate packet ClientboundLevelChunkWithLightPacket
java.lang.IndexOutOfBoundsException: readerIndex(16614) + length(2) exceeds writerIndex(16614): UnpooledHeapByteBuf(ridx: 16614, widx: 16614, cap: 16614/16614)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[Geyser-Standalone%20(12).jar:?]
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749) ~[Geyser-Standalone%20(12).jar:?]
        at com.github.steveice10.mc.protocol.codec.MinecraftCodecHelper.readChunkSection(MinecraftCodecHelper.java:691) ~[Geyser-Standalone%20(12).jar:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:112) ~[Geyser-Standalone%20(12).jar:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78) ~[Geyser-Standalone%20(12).jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Standalone%20(12).jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone%20(12).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone%20(12).jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone%20(12).jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone%20(12).jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone%20(12).jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone%20(12).jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
> java.lang.IndexOutOfBoundsException: readerIndex(16614) + length(2) exceeds writerIndex(16614): UnpooledHeapByteBuf(ridx: 16614, widx: 16614, cap: 16614/16614)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
        at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
        at com.github.steveice10.mc.protocol.codec.MinecraftCodecHelper.readChunkSection(MinecraftCodecHelper.java:691)
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:112)
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Camotoy** [comment]
Does Java Edition 1.19.3 work fine?

**Comment by Camotoy** [comment]
This is likely fixed with the latest CI build.

**Comment by spookymgmt** [comment]
fixed, now fix packet delay :P
