### ISSUE TITLE
geyser standalone issue (ig)

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3449]
### Describe the bug

[12:16:41 ERROR] Could not translate packet ClientboundLevelChunkWithLightPacket
java.lang.NullPointerException: Cannot invoke "com.github.steveice10.opennbt.tag.builtin.Tag.getValue()" because the return value of "com.github.steveice10.opennbt.tag.builtin.CompoundTag.get(String)" is null
	at org.geysermc.geyser.translator.level.block.entity.SpawnerBlockEntityTranslator.translateTag(SpawnerBlockEntityTranslator.java:73) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:46) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:271) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
java.lang.NullPointerException: Cannot invoke "com.github.steveice10.opennbt.tag.builtin.Tag.getValue()" because the return value of "com.github.steveice10.opennbt.tag.builtin.CompoundTag.get(String)" is null
	at org.geysermc.geyser.translator.level.block.entity.SpawnerBlockEntityTranslator.translateTag(SpawnerBlockEntityTranslator.java:73)
	at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:46)
	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:271)
	at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:78)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)

### To Reproduce

i just downloaded latest geyser standalone (#1252) and seeing this error msg

### Expected behaviour

it just happening randomly ig

### Server Version and Plugins

paper-1.19.3-319 & geyser-standalone #1252

### Geyser Dump

https://dump.geysermc.org/Fh49xioAzxQOnpTqdxP8MHWLX6pO24qR

### Geyser Version

eyser-standalone #1252

**Comment by Konicai** [comment]
A spawner block is causing this, can you identify which it is?

**Comment by Camotoy** [comment]
This might be easy to identify, as spawner blocks can now have no entity attached to them and I believe this is the default behavior in 1.19.3.
