### ISSUE TITLE
Error Loading Geyser

### ISSUE THREAD

**Issue by Y0hh** [GeyserMC/Geyser#3472]
### Describe the bug

When I go to turn on my server, after the geyser is loaded after a few minutes an error appears when loading the assets and the cache, and when the geyser tries to download and extract "en_us" it simply cannot and the error happens.

### To Reproduce

1. Turn on the Server and wait approximately 2 minutes.

### Expected behaviour

I was hoping that it would happen normally, that it could load everything right, and not that this error would happen.

### Screenshots / Videos

```
[16:15:42] [ForkJoinPool.commonPool-worker-3/WARN]: [Geyser-Spigot] Failed to load locale asset cache: Unrecognized token 'Connect': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
at [Source: (String)"Connect timed out"; line: 1, column: 8]
[16:15:42] [ForkJoinPool.commonPool-worker-3/INFO]: [Geyser-Spigot] Downloading Minecraft JAR to extract en_us locale, please wait... (this may take some time depending on the speed of your internet connection)
[16:15:42] [ForkJoinPool.commonPool-worker-3/WARN]: [Geyser-Spigot] Unable to download and extract en_us locale!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.text.MinecraftLocale$VersionDownload.getUrl()" because "org.geysermc.geyser.text.MinecraftLocale.clientJarInfo" is null
at org.geysermc.geyser.text.MinecraftLocale.downloadEN_US(MinecraftLocale.java:266) ~[?:?]
at org.geysermc.geyser.text.MinecraftLocale.downloadLocale(MinecraftLocale.java:189) ~[?:?]
at org.geysermc.geyser.text.MinecraftLocale.downloadAndLoadLocale(MinecraftLocale.java:139) ~[?:?]
at org.geysermc.geyser.text.MinecraftLocale.lambda$static$0(MinecraftLocale.java:59) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) [?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) [?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) [?:?]
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
[16:15:42] [ForkJoinPool.commonPool-worker-3/WARN]: [Geyser-Spigot] Missing MC locale file: en_us
[16:15:42] [ForkJoinPool.commonPool-worker-1/WARN]: [Geyser-Spigot] Error whilst checking for Geyser update!
java.net.SocketTimeoutException: Connect timed out
at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333) ~[?:?]
at java.net.Socket.connect(Socket.java:645) ~[?:?]
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:290) ~[?:?]
at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
at sun.net.www.http.HttpClient.openServer(HttpClient.java:497) ~[?:?]
at sun.net.www.http.HttpClient.openServer(HttpClient.java:600) ~[?:?]
at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265) ~[?:?]
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379) ~[?:?]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[?:?]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[?:?]
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120) ~[?:?]
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[?:?]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653) ~[?:?]
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[?:?]
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
at org.geysermc.geyser.util.WebUtils.getJson(WebUtils.java:78) ~[?:?]
at org.geysermc.geyser.util.VersionCheckUtils.lambda$checkForGeyserUpdate$0(VersionCheckUtils.java:60) ~[?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) [?:?]
at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) [?:?]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
```

### Server Version and Plugins

Server Version: 1.17
Plugins: Floodgate, GeyserMC and ViaVersion

### Geyser Dump

https://dump.geysermc.org/FHsawp58JKLn7rxrq6RVqo3VQHMGGUuE

### Geyser Version

2.1.0-SNAPSHOT (git-master-03390b9)

### Minecraft: Bedrock Edition Device/Version

Last Version

**Comment by Y0hh** [comment]
Well, the error stopped appearing, I don't know what happened, but if the error persuades in the future, I'll leave this topic open for now.

**Comment by Ordinaryserver** [comment]
I'm also having this issue!

**Comment by Ordinaryserver** [comment]
oooh...Is there any way to fix it!

**Comment by Ordinaryserver** [comment]
please comment my!

**Comment by onebeastchris** [comment]
The error you got, "Connect timed out", would imply that you are either not online, or have a spotty internet connection - we can't fix that for you :/

**Comment by onebeastchris** [comment]
Forgot to close before; my bad
