### ISSUE TITLE
Unexpected exception while parsing console command "geyser"

### ISSUE THREAD

**Issue by DeviousFusion** [GeyserMC/Geyser#3478]
### Describe the bug

An unhandled exception occurs when typing `/geyser` after reloading the plugin.

> geyser version
[03:05:01 INFO]: This server is running Geyser version 2.1.0-SNAPSHOT (git-master-486e2fc) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.50/1.19.51)
geyser reload
[03:05:10 INFO]: Reloading Geyser configurations... all connected bedrock clients will be kicked.
[03:05:10 INFO]: [Geyser-Spigot] Shutting down Geyser.
[03:05:10 INFO]: [Geyser-Spigot] Geyser shutdown successfully.
[03:05:10 INFO]: [Geyser-Spigot] Started Geyser on 0.0.0.0:19132
[03:05:10 INFO]: [Geyser-Spigot] The skin uploader has been closed
geyser
[03:05:17 WARN]: Unexpected exception while parsing console command "geyser"
org.bukkit.command.CommandException: Unhandled exception executing command 'geyser' in plugin Geyser-Spigot v2.1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchServerCommand(CraftServer.java:892) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:494) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:441) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-350]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.command.GeyserCommand.execute(org.geysermc.geyser.session.GeyserSession, org.geysermc.geyser.command.GeyserCommandSource, String[])" because the return value of "org.geysermc.geyser.platform.spigot.command.GeyserSpigotCommandExecutor.getCommand(String)" is null
        at org.geysermc.geyser.platform.spigot.command.GeyserSpigotCommandExecutor.onCommand(GeyserSpigotCommandExecutor.java:74) ~[Geyser-Spigot.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 9 more
geyser shutdown
[03:05:29 INFO]: The command you specified doesn't exist!
geyser reload
[03:05:35 INFO]: The command you specified doesn't exist!

### To Reproduce

In console, type:
`/geyser reload`
and once it finishes reloading, type:
`/geyser`

### Expected behaviour

Exception should be handled gracefully.

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/2919871/209455838-85540168-e013-44c9-b633-c28a3a70db64.png)

### Server Version and Plugins

`/version`
```
[03:16:02 INFO]: Checking version, please wait...
[03:16:03 INFO]: This server is running Paper version git-Paper-350 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 048ee58)
You are 8 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-345 (MC: 1.19.3)
```

`/plugins`
`[03:16:20 INFO]: Plugins (5): DiscordSRV, dynmap, floodgate, Geyser-Spigot, Graves`

### Geyser Dump

Unable to dump
`geyser dump`
`[03:15:34 INFO]: The command you specified doesn't exist!`

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-486e2fc)

### Minecraft: Bedrock Edition Device/Version

paper-1.19.3.jar:git-Paper-350

### Additional Context

I understand that this is similar to #1956, but no `/geyser stop` was used.

**Comment by raisandesu** [comment]
i am also having this problem
