### ISSUE TITLE
Unable to inflate buffer data

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3507]
### Describe the bug

[22:08:49 WARN] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$1044/0x00000008012011f8@72815319
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:87) ~[Geyser-Standalone.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:305) ~[Geyser-Standalone.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser-Standalone.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.zip.DataFormatException: invalid distance too far back
        at java.util.zip.Inflater.inflateBufferBuffer(Native Method) ~[?:?]
        at java.util.zip.Inflater.inflate(Inflater.java:546) ~[?:?]
        at com.nukkitx.natives.zlib.Java11Inflater.inflate(Java11Inflater.java:21) ~[Geyser-Standalone.jar:?]
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:56) ~[Geyser-Standalone.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV9_10.deserialize(BedrockWrapperSerializerV9_10.java:61) ~[Geyser-Standalone.jar:?]
        ... 9 more

### To Reproduce

it's randomly appearing on consol

### Expected behaviour

idk what to say

### Server Version and Plugins

[00:02:59 INFO]: This server is running Paper version git-Paper-379 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 567ff90)
You are running the latest version

### Geyser Dump

https://dump.geysermc.org/2y9ayASE8Q77Xh6mwtzLjwHj67nxSHuK

### Geyser Version

1271 Build

**Comment by onebeastchris** [comment]
Are you attempting to join with a beta/preview client?

**Comment by adalmo** [comment]
> Are you attempting to join with a beta/preview client?

Bruh no

**Comment by adalmo** [comment]
hmm is there a way to i can do something for fix this?

**Comment by onebeastchris** [comment]
Is this issue still occurring with the latest version of Geyser? If yes, provide a Geyser dump.

**Comment by onebeastchris** [comment]
closing due to no response.

**Comment by adalmo** [comment]
yes still it does

**Comment by adalmo** [comment]
https://dump.geysermc.org/0ILpfpbpLwjQpGTYFXh07xgDhHSXox5j

**Comment by adalmo** [comment]
https://github.com/GeyserMC/Geyser/assets/88581750/80a369f6-8531-4410-99de-b254132efeef

this is when i tried to load new chunks with 1.20.73 (window 10 edition) on 1.12.2 server 
(
