### ISSUE TITLE
 An error occurs when starting the fabric server.

### ISSUE THREAD

**Issue by crowkiki** [GeyserMC/Geyser#3524]
### Describe the bug

Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[10:50:10] [main/INFO]: Loading Minecraft 1.19.3 with Fabric Loader 0.14.13
[10:50:11] [main/WARN]: Mod resolution failed
[10:50:11] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE geyser-fabric 2.1.0-SNAPSHOT {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE geyser-fabric 2.1.0-SNAPSHOT]
[10:50:11] [main/INFO]: Reason: [HARD_DEP geyser-fabric 2.1.0-SNAPSHOT {depends fabric @ [*]}, HARD_DEP fabric-permissions-api-v0 0.2-SNAPSHOT {depends fabric-api-base @ [*]}]
[10:50:11] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)]), add:fabric-api-base 1 ([(-∞,∞)])], remove [], replace []
[10:50:11] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, any version.
         - Install fabric-api-base, any version.
Unmet dependency listing:
         - Mod 'Geyser-Fabric' (geyser-fabric) 2.1.0-SNAPSHOT requires any version of fabric, which is missing!
         - Mod 'fabric-permissions-api' (fabric-permissions-api-v0) 0.2-SNAPSHOT requires any version of fabric-api-base, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.13.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.13.jar:?]

### To Reproduce

Minecraft 1.19.3
Fabric Loader 0.14.13
geyser-fabric 2.1.0

### Expected behaviour

Occurs at server startup

### Screenshots / Videos

-

### Server Version and Plugins

Minecraft 1.19.3
Fabric Loader 0.14.13

### Geyser Version

geyser-fabric 2.1.0

**Comment by crowkiki** [comment]
If it doesn't support fabric 0.14.13, please tell me your minecraft server version and fabric version

**Comment by Camotoy** [comment]
You need to install the Fabric API dependency,
