### ISSUE TITLE
Server render distance over 96 chunks crashes Bedrock clients on join

### ISSUE THREAD

**Issue by cllCush** [GeyserMC/Geyser#3529]
### Describe the bug

While using Geyser and floodgate on a Fabric server, iOS and Nintendo Switch clients crash immediately after world generation. Java clients and Bedrock clients on PC or Xbox series do not experience this issue and can play as normal. 
This issue was also not present when connecting to a Spigot server configured the exact same way.
Have not been able to test on clients using android, Xbox one/360, or Playstation 4/5.

### To Reproduce

1. Set up a Minecraft server using the Fabric mod loader
2. Install Geyser, Floodgate, and the Fabric API
3. Attempt to connect via mobile client on iOS or Nintendo Switch

### Expected behaviour

Client is expected not to crash after connecting to the server and generating the world. 

### Geyser Dump

https://dump.geysermc.org/BEpkE6CYvZRzY2g5duJz5IJZnArDEJEE

### Geyser Version

2.1.0-SNAPSHOT (git-master-c909b2b)

### Minecraft: Bedrock Edition Device/Version

1.19.51, iOS and Nintendo Switch

**Comment by Kas-tle** [comment]
```log
[19:36:33 DEBUG]: Error occurred whilst decoding packet
com.nukkitx.protocol.bedrock.exception.PacketSerializeException: Error whilst deserializing UpdateSoftEnumPacket(softEnum=CommandEnumData(name=Geyser_Teams, values=[?HoloApiFakeTeam], isSoft=true), type=null)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:66) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV11.deserialize(BedrockWrapperSerializerV11.java:69) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:305) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:34) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:277) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:403) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:383) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:371) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:252) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.pipeline.ClientMessageHandler.channelRead0(ClientMessageHandler.java:46) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.network.raknet.pipeline.ClientMessageHandler.channelRead0(ClientMessageHandler.java:13) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(34) + length(4) exceeds writerIndex(35): UnpooledSlicedByteBuf(ridx: 34, widx: 35, cap: 35/35, unwrapped: PooledUnsafeDirectByteBuf(ridx: 249660, widx: 679954, cap: 1048576))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at io.netty.buffer.AbstractByteBuf.readIntLE(AbstractByteBuf.java:817) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.v291.serializer.UpdateSoftEnumSerializer_v291.deserialize(UpdateSoftEnumSerializer_v291.java:24) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.v291.serializer.UpdateSoftEnumSerializer_v291.deserialize(UpdateSoftEnumSerializer_v291.java:11) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketSerializer.deserialize(BedrockPacketSerializer.java:21) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:64) ~[proxypass-1.0.0-SNAPSHOT.jar:?]
        ... 26 more
[19:36:39 DEBUG]: Selector.select() returned prematurely 3 times in a row for Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@168253e6.
```

**Comment by Camotoy** [comment]
Is your ProxyPass up-to-date?

**Comment by Kas-tle** [comment]
Yeah that's probably the issue... also tried with a build that comments out your scoreboard team updated and same difference. So unrelated anyways.

**Comment by Kas-tle** [comment]
Here is packet dump
[packets.log](https://github.com/GeyserMC/Geyser/files/10564619/packets.log)

**Comment by Kas-tle** [comment]
Update: issue seems to be due to setting the server render distance to 128. @Camotoy I assume we should add some sort of check to cap this for non-desktop clients?

**Comment by onebeastchris** [comment]
Should be resolved in the latest commit. Thanks for reporting the issue!
