### ISSUE TITLE
Can´t Interact With Bedrock Properly

### ISSUE THREAD

**Issue by Dikalon10** [GeyserMC/Geyser#3550]
### Describe the bug

Hello. I Made A Geyser Server: Minecraft 1.19.3, Paper, Geyser And Floodgate. The Server Isnt Cracked Because If I Understood Right I Dont Need It Then Using Floodgate. It Uses Same IP For Java And Bedrock. My Problem Is, That If I Try To /gamemode Or /tp To My Bedrock Account, It Suggests It In The Auto Complete, But When I Do It Says Incorrect Argument Or Command. It Also Has A Trade Plugin weeTrade, Where I Can Request A Trade But If I Accept It says that An Internal Error Occured Whilst Trying To Perform That Command. In The Console, It Said: 
[20:56:19 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trade' in plugin weeTrade v1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-372]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-372]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-372]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-372]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-372]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-372]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-372]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-372]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-372]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-372]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'byte org.bukkit.DyeColor.getData()'
        at nl.dubehh.TradeInventory.getPane(TradeInventory.java:121) ~[weeTrade-TradingPlugin18x-S6046-22939.jar:?]
        at nl.dubehh.TradeInventory.getDefaultInventory(TradeInventory.java:104) ~[weeTrade-TradingPlugin18x-S6046-22939.jar:?]
        at nl.dubehh.TradeInventory.<init>(TradeInventory.java:28) ~[weeTrade-TradingPlugin18x-S6046-22939.jar:?]
        at nl.dubehh.Trade.<init>(Trade.java:23) ~[weeTrade-TradingPlugin18x-S6046-22939.jar:?]
        at nl.dubehh.command.TradeCommand.onCommand(TradeCommand.java:64) ~[weeTrade-TradingPlugin18x-S6046-22939.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
... 23 more

I Dont Know What To Do. It Has Following Plugins: CoreProtect, floodgate-spigot, Geyser-Spigot, LuckPerms, tpa* and  weeTrade*
I Also Dont Know Why There Are Those Stars.
The Full Paper Version Is Git-paper-372  (MC: 1.19.3)
I Hope That This Has A Solution
I Wish A Great Afternoon!

### To Reproduce

Install Paper 372 MC 1.19.3
Install Plugin  weeTrade*
Install Geyser And Floodgate
Turn On That It Uses The Same IP For Java And Bedrock
Join The Server With Java And Bedrock
Use /trade Or /tp with Java/Bedrock To The Opposite
Look At The Error
![Screenshot 2023-02-11 221512](https://user-images.githubusercontent.com/78260761/218281392-0ddf7047-7769-4fd9-b1f1-152d8b1dfd2b.png)
![Screenshot 2023-02-11 221611](https://user-images.githubusercontent.com/78260761/218281395-b1fe314b-8da0-4e4f-9a6c-36a61144c8b9.png)

### Expected behaviour

I Expected, That It Lets Me Tp To My Bedrock Account And That The Trade Has Been Accepted And The GUI Has Been Opened

### Server Version and Plugins

Plugins: CoreProtect, floodgate-spigot, Geyser-Spigot, LuckPerms, tpa* and  weeTrade*
Paper Version: Git-paper-372  (MC: 1.19.3)

### Geyser Dump

https://dump.geysermc.org/pPEwQ3frTgKnhQcShCV7MQevXCPgADSl

### Geyser Version

version 2.1.0-SNAPSHOT (git-master-f9705c1) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.60)

### Minecraft: Bedrock Edition Device/Version

Windows PC, Bedrock 1.19.60

### Additional Context

It Happened On A Server With Active Whitelist And Online Mode Enabled

**Comment by Camotoy** [comment]
` Caused by: java.lang.NoSuchMethodError: 'byte org.bukkit.DyeColor.getData()'`

I don't think this is our error. I think you're just trying to use a really old plugin. If you continue having issues, try setting the prefix in your Floodgate config back to `.`

**Comment by Dikalon10** [comment]
But Why Does /tp Dont Work Too?

**Comment by Dikalon10** [comment]
> ` Caused by: java.lang.NoSuchMethodError: 'byte org.bukkit.DyeColor.getData()'`
> 
> I don't think this is our error. I think you're just trying to use a really old plugin. If you continue having issues, try setting the prefix in your Floodgate config back to `.`

Thank You! Changing Back The Prefix Worked And I Use Another Plugin Now With That It Works! Geyser Is A Really Great Plugin!
