### ISSUE TITLE
1.19.62 unable to move or see

### ISSUE THREAD

**Issue by ErrorGamer2000** [GeyserMC/Geyser#3560]
### Describe the bug

So I'm running a paper server for me and two of my friends, one of which plays on bedrock. As of the 15th, everything was fine. Yesterday (the 16th) they told me that their Minecraft had updated to 1.19.62. So, of course, I download a new version. When they log in to the server, they are unable to move or see any blocks, however the Java players were able to see the bedrock player. They could not see their inventory, aside from their armor. They could punch, but not hit a player directly in front of them. Wanting to see if it would make a difference, we had them take off said armor and killed them. They did *not* take knock back. Up on death, they could not respawn, and we're instead presented with "Generating world". Relogging respawned them, and this time they were able to turn, and we could see them turn and shield. When hitting them again, still no nockback.

### To Reproduce

1. Update to bedrock 1.19.62
2. Join a geyser server with the latest version

### Expected behaviour

They should be able to move around and see.

### Screenshots / Videos

Up on logging in and waiting for a few minutes
![log in](https://cdn.discordapp.com/attachments/1067975892149735554/1075937057215623198/659805d3-d42a-4152-bbd6-6b09291e9d81.png)

Up on death
![death](https://cdn.discordapp.com/attachments/1067975892149735554/1075937057509216276/97f64e39-5aff-4768-b708-6a1ad9eb850d.png)

### Server Version and Plugins

Server version: `git-Paper-307 (MC: 1.19.2)`

Plugins:
- ViaVersion
- Floodgate
- Geyser

### Geyser Dump

https://dump.geysermc.org/YsRkusxEJP1khmSi5aiw1sDJLF8hNhfM

### Geyser Version

2.1.0-SNAPSHOT (git-master-30277d5)

### Additional Context

Server logs when the bedrock player joins:

```
[18:01:50 INFO]: .PsycoKitten6641 joined the game
[18:01:50 INFO]: .PsycoKitten6641[/50.88.254.66:0] logged in with entity id 12222 at ([world]-197.5, 67.0, -133.5)
[18:01:50 WARN]: [io.netty.util.concurrent.AbstractEventExecutor] A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockSession$$Lambda$7662/0x00000008021b2f78@19be87eb
java.lang.NoSuchMethodError: 'boolean com.nukkitx.protocol.bedrock.data.skin.SerializedSkin.isOverridingPlayerAppearance()'
	at com.nukkitx.protocol.bedrock.v567.BedrockPacketHelper_v567patch.writeSkin(BedrockPacketHelper_v567patch.java:75) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.v390.serializer.PlayerListSerializer_v390.serialize(PlayerListSerializer_v390.java:32) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.v390.serializer.PlayerListSerializer_v390.serialize(PlayerListSerializer_v390.java:14) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockPacketSerializer.serialize(BedrockPacketSerializer.java:13) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryEncode(BedrockPacketCodec.java:85) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.wrapper.BedrockWrapperSerializerV11.serialize(BedrockWrapperSerializerV11.java:34) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.sendWrapped(BedrockSession.java:143) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.sendWrapped(BedrockSession.java:128) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.sendQueued(BedrockSession.java:219) ~[Geyser-Spigot.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onTick(BedrockSession.java:197) ~[Geyser-Spigot.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:02:35 INFO]: [floodgate] Floodgate player logged in as .PsycoKitten6641 disconnected
[18:02:35 INFO]: [Geyser-Spigot] PsycoKitten6641 has disconnected from the Java server because of Bedrock client disconnected
[18:02:35 INFO]: .PsycoKitten6641 lost connection: Disconnected
[18:02:35 INFO]: .PsycoKitten6641 left the game
```

**Comment by Camotoy** [comment]
Please update to the latest Geyser build. Thanks!

**Comment by ErrorGamer2000** [comment]
Looking at the dump, 1.19.60 is repeated twice, and there is not 1.19.62
```json
           "bedrockVersions": [
                "1.19.20",
                "1.19.21/1.19.22",
                "1.19.30/1.19.31",
                "1.19.40/1.19.41",
                "1.19.50/1.19.51",
                "1.19.60",
                "1.19.60"
            ],
```

**Comment by BE-Code** [comment]
@ErrorGamer2000 Did you figure it out? I am also having this problem.

**Comment by onebeastchris** [comment]
update to the latest version of geyser

**Comment by BE-Code** [comment]
oh I see. I really thought I was on the latest version
