### ISSUE TITLE
Unable to join the server with IPv4 or IPv6 using proxy protocol

### ISSUE THREAD

**Issue by GoodLucky777** [GeyserMC/Geyser#3575]
### Describe the bug

I installed Geyser plugin in Velocity server, and installed [Infrared (v2.0.0-alpha.13)](https://github.com/haveachin/infrared) to use it as proxy server for it. I set `bedrock.enable-proxy-protocol: true` to get IP, it was working with IPv4 however the error occurs when I try to connect with IPv6. The error was
```
[19:42:54 INFO] [geyser]: (Player Name) has disconnected from the Java server because of java.lang.IllegalArgumentException: invalid IPv6 address: 127.0.0.1
[19:42:54 ERROR]: java.lang.IllegalArgumentException: invalid IPv6 address: 127.0.0.1
[19:42:54 ERROR]:       at io.netty.handler.codec.haproxy.HAProxyMessage.checkAddress(HAProxyMessage.java:455)
[19:42:54 ERROR]:       at io.netty.handler.codec.haproxy.HAProxyMessage.<init>(HAProxyMessage.java:105)
[19:42:54 ERROR]:       at io.netty.handler.codec.haproxy.HAProxyMessage.<init>(HAProxyMessage.java:79)
[19:42:54 ERROR]:       at org.geysermc.geyser.network.netty.LocalSession$2.channelActive(LocalSession.java:132)
[19:42:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262)
[19:42:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[19:42:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[19:42:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[19:42:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
[19:42:54 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[19:42:54 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[19:42:54 ERROR]:       at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
[19:42:54 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[19:42:54 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[19:42:54 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:42:54 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:42:54 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[19:42:54 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```
It seems it is because `remote.address: 127.0.0.1` is not IPv6. When I change it to `remote.address: ::1`, it works with IPv6 client but the error occurs with IPv4 like this.
```
[19:31:30 INFO] [geyser]: (Player Name) has disconnected from the Java server because of java.lang.IllegalArgumentException: invalid IPv4 address: 0:0:0:0:0:0:0:1
[19:31:30 ERROR]: java.lang.IllegalArgumentException: invalid IPv4 address: 0:0:0:0:0:0:0:1
[19:31:30 ERROR]:       at io.netty.handler.codec.haproxy.HAProxyMessage.checkAddress(HAProxyMessage.java:450)
[19:31:30 ERROR]:       at io.netty.handler.codec.haproxy.HAProxyMessage.<init>(HAProxyMessage.java:105)
[19:31:30 ERROR]:       at io.netty.handler.codec.haproxy.HAProxyMessage.<init>(HAProxyMessage.java:79)
[19:31:30 ERROR]:       at org.geysermc.geyser.network.netty.LocalSession$2.channelActive(LocalSession.java:132)
[19:31:30 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262)
[19:31:30 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[19:31:30 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[19:31:30 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[19:31:30 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
[19:31:30 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[19:31:30 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[19:31:30 ERROR]:       at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
[19:31:30 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[19:31:30 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[19:31:30 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:31:30 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:31:30 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[19:31:30 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

1. Try to join the server with IPv6.
2. The error occurs.

### Expected behaviour

Able to join with IPv4 and IPv6 when I set `remote.address: auto`.

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT (git-48acbb32-b229)

### Geyser Dump

https://dump.geysermc.org/IUt1L8fk3MaRnNVYFbTcydAh6xQchDuB

### Geyser Version

2.1.0-SNAPSHOT (git-master-e7b8b4e) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.62)

### Minecraft: Bedrock Edition Device/Version

1.19.62 Android, 1.19.62 Windows 10

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/issues/3547
It looks like it boils down to the same feature request as the linked issue - aka simultaneous IPv4 & IPv6 support

**Comment by onebeastchris** [comment]
Closing in favor of https://github.com/GeyserMC/Geyser/issues/3547 - boils down to the lack of simultaneous ipv4 and ipv6 support.

**Comment by Kas-tle** [comment]
Of note: https://docs.oracle.com/javase/8/docs/technotes/guides/net/ipv6_guide/
Java does not support dual stack networking for loopback (`::1` /  `127.0.0.1`) addresses, but it does for the wildcard `::` if dual stack networking is supported by the host OS.

**Comment by Outfit8TSB** [comment]
try using Geyser-Standalone if you don't have dual stack in the Host OS
