### ISSUE TITLE
Unable to download and save file

### ISSUE THREAD

**Issue by 1470429149** [GeyserMC/Geyser#3589]
### Describe the bug

When the Bedrock Edition player enters, the server will report an error as follows

FunnyMoney82851 has disconnected from the Java server because of java.lang.AssertionError: Unable to download and save file: plugins/Geyser-Spigot/locales/zh_cn.json (https://resources.download.minecraft.net/54/54c68a79c3cb6d390002e46ba75d10043317a65a)
[15:40:24 WARN]: java.lang.AssertionError: Unable to download and save file: plugins/Geyser-Spigot/locales/zh_cn.json (https://resources.download.minecraft.net/54/54c68a79c3cb6d390002e46ba75d10043317a65a)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.util.WebUtils.downloadFile(WebUtils.java:94)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.text.MinecraftLocale.downloadLocale(MinecraftLocale.java:126)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.text.MinecraftLocale.downloadAndLoadLocale(MinecraftLocale.java:93)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.session.GeyserSession$1.connected(GeyserSession.java:983)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:145)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:346)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[15:40:24 WARN]:        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[15:40:24 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
[15:40:24 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
[15:40:24 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
[15:40:24 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[15:40:24 WARN]:        at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
[15:40:24 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[15:40:24 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[15:40:24 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:40:24 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:40:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[15:40:24 WARN]: Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[15:40:24 WARN]:        at java.base.security.ssl.Alert.createSSLException(Alert.java:131)
[15:40:24 WARN]:        at java.base.security.ssl.Alert.createSSLException(Alert.java:117)
[15:40:24 WARN]:        at java.base.security.ssl.TransportContext.fatal(TransportContext.java:358)
[15:40:24 WARN]:        at java.base.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
[15:40:24 WARN]:        at java.base.security.ssl.TransportContext.dispatch(TransportContext.java:204)
[15:40:24 WARN]:        at java.base.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[15:40:24 WARN]:        at java.base.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510)
[15:40:24 WARN]:        at java.base.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425)
[15:40:24 WARN]:        at java.base.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[15:40:24 WARN]:        at java.base.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[15:40:24 WARN]:        at java.base.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
[15:40:24 WARN]:        at java.base.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
[15:40:24 WARN]:        at java.base.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1668)
[15:40:24 WARN]:        at java.base.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1592)
[15:40:24 WARN]:        at java.base.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[15:40:24 WARN]:        at Geyser-Spigot (1).jar//org.geysermc.geyser.util.WebUtils.downloadFile(WebUtils.java:91)
[15:40:24 WARN]:        ... 24 more
>

### To Reproduce

1. start server
2. Let Bedrock Edition players join server
3. View server error

### Expected behaviour

null

### Screenshots / Videos

null

### Server Version and Plugins

 This server is running Geyser version 2.1.0-SNAPSHOT (git-master-fca726c) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.62)
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-402 (MC: 1.17.1)

### Geyser Dump

https://dump.geysermc.org/TJT3YRDlw9sO8HBRBrjBDV3sdWfFl8M7

### Geyser Version

 This server is running Geyser version 2.1.0-SNAPSHOT (git-master-fca726c) (Java: 1.19.3, Bedrock: 1.19.20 - 1.19.62)

### Minecraft: Bedrock Edition Device/Version

1.19.20

### Additional Context

null

**Comment by 1470429149** [comment]
Is it possible that my server cannot connect to the geyser server? But I have noticed that geyser can check for newer versions normally, which makes me not sure what I think

**Comment by 1470429149** [comment]
I have found the reason it's because I use zulu java, when I use oracle java the problem is solved

**Comment by 1470429149** [comment]
I am very strange that there is a zh_cn.json file in my server, but the server still prompts me that the save file cannot be downloaded

**Comment by 1470429149** [comment]
To add, Geyser will prompt the following code at startup
[Geyser-Spigot] 无法获取本地附件缓存 Unrecognized token 'Read': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Read timed out"; line: 1, column: 5]
