### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by frogglen** [GeyserMC/Geyser#3602]
### Describe the bug

sometimes, some of my users are kicked out by the server and I get this error in the proxy console, this has been happening in the last 3 days, I have received some reports of this kind of kickouts

### To Reproduce

```
[19:20:33 ERROR]: [connected player] .Generaljasonp exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@797c9e4f
java.nio.channels.ClosedChannelException: null
        at io.netty.channel.local.LocalChannel.doWrite(LocalChannel.java:368) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:967) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:254) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at org.geysermc.geyser.network.netty.ChannelWrapper.flush(ChannelWrapper.java:213) ~[?:?]
        at com.velocitypowered.proxy.connection.MinecraftConnection.flush(MinecraftConnection.java:244) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.readCompleted(BackendPlaySessionHandler.java:329) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelReadComplete(MinecraftConnection.java:161) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:486) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:456) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelReadComplete(AutoReadHolderHandler.java:69) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:484) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:456) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.handler.timeout.IdleStateHandler.channelReadComplete(IdleStateHandler.java:295) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:484) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:456) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:358) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:486) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:456) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1415) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:820) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-e08ffa10-b232)]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Expected behaviour

sometimes, some of my users are kicked out by the server and I get this error in the proxy console, this has been happening in the last 3 days, I have received some reports of this kind of kickouts

### Geyser Version

Geyser versión 2.1.0-SNAPSHOT (git-master-a5a4f5c)

**Comment by onebeastchris** [comment]
Closing due to no response.
