### ISSUE TITLE
ClientboundUpdateTagsPacket error

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3607]
### Describe the bug

This error has been displaying as of the new Minecraft update.
The player is joining a 1.12.2 server once going through the Proxy.
This appears in the Bungee console when a player joins:

```
20:09:00 [WARNING] [Geyser-BungeeCord] Could not translate packet ClientboundUpdateTagsPacket
java.lang.NullPointerException: Cannot read the array length because "a" is null
    at it.unimi.dsi.fastutil.ints.IntList.of(IntList.java:405)
    at org.geysermc.geyser.session.cache.TagCache.loadPacket(TagCache.java:77)
    at org.geysermc.geyser.translator.protocol.java.JavaUpdateTagsTranslator.translate(JavaUpdateTagsTranslator.java:38)
    at org.geysermc.geyser.translator.protocol.java.JavaUpdateTagsTranslator.translate(JavaUpdateTagsTranslator.java:33)
    at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
    at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
20:09:00 [SEVERE] java.lang.NullPointerException: Cannot read the array length because "a" is null

20:09:00 [SEVERE]     at it.unimi.dsi.fastutil.ints.IntList.of(IntList.java:405)

20:09:00 [SEVERE]     at org.geysermc.geyser.session.cache.TagCache.loadPacket(TagCache.java:77)

20:09:00 [SEVERE]     at org.geysermc.geyser.translator.protocol.java.JavaUpdateTagsTranslator.translate(JavaUpdateTagsTranslator.java:38)

20:09:00 [SEVERE]     at org.geysermc.geyser.translator.protocol.java.JavaUpdateTagsTranslator.translate(JavaUpdateTagsTranslator.java:33)

20:09:00 [SEVERE]     at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)

20:09:00 [SEVERE]     at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)

20:09:00 [SEVERE]     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

20:09:00 [SEVERE]     at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

20:09:00 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

20:09:00 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

20:09:00 [SEVERE]     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

20:09:00 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

1. Put Geyser on a BungeeCord server
2. Join server on newest Bedrock version
3. See error in console

### Expected behaviour

The error shouldn't appear.

### Server Version and Plugins

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:f9712cb:1680

Geyser-BungeeCord
ViaVersion 4.6.0

### Geyser Dump

https://dump.geysermc.org/6B7J3aYj8EGm36rPbLWDcfJTZgQMQZiy

### Geyser Version

2.1.0-SNAPSHOT (git-master-6ec7326)

### Minecraft: Bedrock Edition Device/Version

1.19.70, Windows 10

### Additional Context

Hasn't happened prior to today's updates.

**Comment by pinkpig58** [comment]
Also happening when a player is switching between servers

**Comment by Ulises00** [comment]
The same thing happens to me, I use java 17 in ubuntu

**Comment by pinkpig58** [comment]
> The same thing happens to me, I use java 17 in ubuntu

This has been fixed in the latest version. Give that a try.
