### ISSUE TITLE
Error thrown in Player event loop!

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3617]
### Describe the bug

[20:57:16 ERROR] Error thrown in Rudy0727's event loop!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getGeyserId()" because "currentVehicle" is null
        at org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockInteractTranslator.lambda$translate$0(BedrockInteractTranslator.java:87) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.session.GeyserSession.lambda$scheduleInEventLoop$9(GeyserSession.java:1111) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### To Reproduce

[20:57:16 ERROR] Error thrown in Rudy0727's event loop!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getGeyserId()" because "currentVehicle" is null
        at org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockInteractTranslator.lambda$translate$0(BedrockInteractTranslator.java:87) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.session.GeyserSession.lambda$scheduleInEventLoop$9(GeyserSession.java:1111) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Expected behaviour

[20:57:16 ERROR] Error thrown in Rudy0727's event loop!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getGeyserId()" because "currentVehicle" is null
        at org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockInteractTranslator.lambda$translate$0(BedrockInteractTranslator.java:87) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.session.GeyserSession.lambda$scheduleInEventLoop$9(GeyserSession.java:1111) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Screenshots / Videos

[20:57:16 ERROR] Error thrown in Rudy0727's event loop!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getGeyserId()" because "currentVehicle" is null
        at org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockInteractTranslator.lambda$translate$0(BedrockInteractTranslator.java:87) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.session.GeyserSession.lambda$scheduleInEventLoop$9(GeyserSession.java:1111) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Server Version and Plugins

Current: git-Purpur-1933 (MC: 1.19.3)*

### Geyser Dump

https://dump.geysermc.org/IP7JxkHKb4oBkKctDP5x4EEFpfstRq1Y

### Geyser Version

2.1.0-SNAPSHOT (git-master-d7c6865)

**Comment by onebeastchris** [comment]
does this error still occur on the latest version of Geyser?

**Comment by onebeastchris** [comment]
Closing due to no response.
