### ISSUE TITLE
Geyser Error When Using Geyserhacks

### ISSUE THREAD

**Issue by lolgam3r** [GeyserMC/Geyser#3629]
### Describe the bug

When A Player Gets Kicked Off An Entity While In The Water, Specifically Pigs Or Horses The Geyser Will Spam The Following Error:
[01:34:42 ERROR] [geyser]: Error thrown in lolgam3r4671's event loop!
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.entity.type.Entity.getGeyserId()" because "currentVehicle" is null
    at org.geysermc.geyser.translator.protocol.bedrock.entity.player.BedrockInteractTranslator.lambda$translate$0(BedrockInteractTranslator.java:87) ~[?:?]
    at org.geysermc.geyser.session.GeyserSession.lambda$scheduleInEventLoop$9(GeyserSession.java:1111) ~[?:?]
    at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[velocity.jar:3.2.0-SNAPSHOT (git-b4e04204-b241)]
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[velocity.jar:3.2.0-SNAPSHOT (git-b4e04204-b241)]
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.2.0-SNAPSHOT (git-b4e04204-b241)]
    at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.2.0-SNAPSHOT (git-b4e04204-b241)]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-b4e04204-b241)]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-b4e04204-b241)]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-b4e04204-b241)]
    at java.lang.Thread.run(Thread.java:833) [?:?]

### To Reproduce

1. Tame, Mount And Ride A Horse/pig
2. Go In a 3 Block Deep Or More Water Area
3. Wait For The Pig/Horse To Sink
4. Error

### Expected behaviour

N/A

### Server Version and Plugins

Velocity Proxy

### Geyser Dump

https://dump.geysermc.org/jTFcQQxu1MXVysg8ghXAevFr5iYMjDEH

### Geyser Version

2.1.0-SNAPSHOT (git-master-d7c6865)

### Minecraft: Bedrock Edition Device/Version

N/A

**Comment by Camotoy** [comment]
I wasn't able to reproduce this, but the next Geyser build should have the fix for this.

**Comment by lolgam3r** [comment]
> I wasn't able to reproduce this, but the next Geyser build should have the fix for this.

alright!
