### ISSUE TITLE
Exception  on join

### ISSUE THREAD

**Issue by Outfluencer** [GeyserMC/Geyser#3634]
### Describe the bug

can't join

### To Reproduce

join the server

### Expected behaviour

not get kicked

### Screenshots / Videos

https://prnt.sc/lADPp3FmOK5C

### Server Version and Plugins

gyser on bungeecord with flood gate

### Geyser Dump

https://dump.geysermc.org/RBwnp9clVTK9okNvGJiX3qzVgVKUdhKR

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-7ef0050) (Java: 1.19.4, Bedrock: 1.19.30/1.19.31 - 1.19.70/1.19.71)

### Minecraft: Bedrock Edition Device/Version

Windows

### Additional Context

bungeecord is in online mod and has proxy protocol enabled

20:54:12 [SEVERE] com.github.steveice10.mc.protocol.data.UnexpectedEncryptionException: Cannot reply to ClientboundHelloPacket without profile and access token.

20:54:12 [SEVERE]     at com.github.steveice10.mc.protocol.ClientListener.packetReceived(ClientListener.java:56)

20:54:12 [SEVERE]     at com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:157)

20:54:12 [SEVERE]     at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:388)

20:54:12 [SEVERE]     at com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:29)

20:54:12 [SEVERE]     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

20:54:12 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)

20:54:12 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)

20:54:12 [SEVERE]     at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

20:54:12 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)

20:54:12 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)

20:54:12 [SEVERE]     at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

20:54:12 [SEVERE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)

20:54:12 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)

20:54:12 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)

20:54:12 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

20:54:12 [SEVERE]     at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)

20:54:12 [SEVERE]     at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)

20:54:12 [SEVERE]     at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)

20:54:12 [SEVERE]     at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)

20:54:12 [SEVERE]     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

20:54:12 [SEVERE]     at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)

20:54:12 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

20:54:12 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

20:54:12 [SEVERE]     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

20:54:12 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by Outfluencer** [comment]
floodgate default configuration

**Comment by Outfluencer** [comment]
ouh i found out in debug mode whats the problem
