### ISSUE TITLE
Error reported after upgrading geyser 

### ISSUE THREAD

**Issue by Chun-QiuCC** [GeyserMC/Geyser#3654]
### Describe the bug

When I upgrade geyser to the latest version, players report an error after joining the server

### To Reproduce

1.putting the latest version of Geyser into the Plugging folder
2.player uses the latest version of Bedlock Edition to enter the game,
3.client error message 
```
Cannot invoke "org.geysermc.geyser levelWorldManager.hasOwnChunkCache()" because the return value of "org.geysermc.geyser.GeyserImpl.getWorldManager()" is null
```

4.The server console reported an error message
```
[12:03:08] [Network Listener - #1/INFO]: [Geyser-Spigot] /192.168.0.2:58530 尝试连接!
[12:03:08] [Network Listener - #1/WARN]: [Geyser-Spigot] Error occurred while initializing player!
>java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.level.WorldManager.hasOwnChunkCache()" because the return value of "org.geysermc.geyser.GeyserImpl.getWorldManager()" is null
at org.geysermc.geyser.session.cache.ChunkCache.<init>(ChunkCache.java:56) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.session.GeyserSession.<init>(GeyserSession.java:565) ~[Geyser-Spigot.jar:?]
at org.geysermc.geyser.network.ConnectorServerEventHandler.onSessionCreation(ConnectorServerEventHandler.java:182) [Geyser-Spigot.jar:?]
at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$Server.onSessionChangeState(BedrockRakNetSessionListener.java:98) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetSession.setState(RakNetSession.java:976) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetServerSession.onNewIncomingConnection(RakNetServerSession.java:96) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetServerSession.onPacket(RakNetServerSession.java:36) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:280) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:403) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:383) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:376) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:252) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.pipeline.ServerDatagramHandler.channelRead0(ServerDatagramHandler.java:43) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.pipeline.ServerDatagramHandler.channelRead0(ServerDatagramHandler.java:14) [Geyser-Spigot.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at com.nukkitx.network.raknet.pipeline.ServerMessageHandler.channelRead0(ServerMessageHandler.java:34) [Geyser-Spigot.jar:?]
at com.nukkitx.network.raknet.pipeline.ServerMessageHandler.channelRead0(ServerMessageHandler.java:10) [Geyser-Spigot.jar:?]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Expected behaviour

Players join the server normally

### Server Version and Plugins

Spigot 1.16.5

### Geyser Version

Build #44.2023/3/31

### Minecraft: Bedrock Edition Device/Version

1.19.73

**Comment by emkashy** [comment]
RUS:срорее всего тебе мешает плагин viaversion или похожии, после того как я удалил их, все заработало
