### ISSUE TITLE
cant show skin for bedrock player

### ISSUE THREAD

**Issue by Papklp** [GeyserMC/Geyser#3655]
### Describe the bug

player's skin is purple black.

### To Reproduce

1. found a player
2. see error

### Expected behaviour

it just happened

### Screenshots / Videos

![XGB`LXA8PLOKJF NOKM3{UL](https://user-images.githubusercontent.com/66307812/229265891-bd1bd16e-8394-45e6-be56-f0404848ce54.jpg)

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT (git-93b6376b-b246)
plugins：botsentry, commandsync, fallbackservervelocity, floodgate, geyser, luckperms, skinsrestorer, snap, trchat, viaversion, viabackwards

### Geyser Dump

 https://dump.geysermc.org/vmnUKPP2C8IW2d71eRfkhdXLtB0F77BF

### Geyser Version

2.1.0-SNAPSHOT (git-master-e253510)

### Minecraft: Bedrock Edition Device/Version

1.19.62 Android

**Comment by Papklp** [comment]
bedrock device is windows,I wrote it wrong.

**Comment by TERMZL0ckd0wn** [comment]
**I have this problem too on my minecraft paper server.**

I looked into the server files and ....

/[05:05:25] [WebSocketConnectReadThread-47/WARN]: [Geyser-Spigot] Got an error
java.net.UnknownHostException: api.geysermc.org
	at java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1524) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1381) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1305) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1255) ~[?:?]
	at org.java_websocket.client.WebSocketClient$1.resolve(WebSocketClient.java:210) ~[Geyser-Spigot.jar:?]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:460) ~[Geyser-Spigot.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:05:25] [Server thread/INFO]: [Geyser-Spigot] Done (15.515s)! Run /geyser help for help!
[05:05:25] [Thread-10/WARN]: [Geyser-Spigot] Error whilst checking for Geyser update!
java.net.UnknownHostException: api.geysermc.org
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:531) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:636) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at org.geysermc.geyser.util.WebUtils.getJson(WebUtils.java:78) ~[Geyser-Spigot.jar:?]
	at org.geysermc.geyser.util.VersionCheckUtils.lambda$checkForGeyserUpdate$0(VersionCheckUtils.java:63) ~[Geyser-Spigot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:05:25] [Server thread/INFO]: Running delayed init tasks
[05:05:25] [Server thread/INFO]: Done (26.261s)! For help, type "help"
[05:05:25] [Server thread/INFO]: Timings Reset
[05:05:44] [Thread-7/WARN]: [Geyser-Spigot] Failed to load locale asset cache: Unrecognized token 'launchermeta': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"launchermeta.mojang.com"; line: 1, column: 13]
[05:05:44] [Thread-7/WARN]: [Geyser-Spigot] Missing MC locale file: en_us
[05:05:58] [WebSocketConnectReadThread-54/WARN]: [Geyser-Spigot] Got an error
java.net.UnknownHostException: api.geysermc.org: Temporary failure in name resolution
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1534) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1524) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1381) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1305) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1255) ~[?:?]
	at org.java_websocket.client.WebSocketClient$1.resolve(WebSocketClient.java:210) ~[Geyser-Spigot.jar:?]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:460) ~[Geyser-Spigot.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:06:05] [User Authenticator #0/INFO]: UUID of player sai_rockstar is 98a504e3-7231-3499-8208-dbcd492b7803
[05:06:05] [Server thread/INFO]: sai_rockstar joined the game
[05:06:06] [Server thread/INFO]: sai_rockstar[/103.88.236.202:60609] logged in with entity id 293 at ([world]-450.5, 72.0, -317.5)
[05:06:32] [WebSocketConnectReadThread-63/WARN]: [Geyser-Spigot] Got an error
java.net.UnknownHostException: api.geysermc.org: Temporary failure in name resolution
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933) ~[?:?]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1534) ~[?:?]
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852) ~[?:?]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1524) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1381) ~[?:?]
	at java.net.InetAddress.getAllByName(InetAddress.java:1305) ~[?:?]
	at java.net.InetAddress.getByName(InetAddress.java:1255) ~[?:?]
	at org.java_websocket.client.WebSocketClient$1.resolve(WebSocketClient.java:210) ~[Geyser-Spigot.jar:?]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:460) ~[Geyser-Spigot.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]/


This is what i found. It seems it wants to access `api.geysermc.org` but fails to do so.

**Comment by Papklp** [comment]
wtf why u send issue in my issue

**Comment by Kas-tle** [comment]
Is this still an issue on the latest version?

**Comment by onebeastchris** [comment]
Closing due to no response.

**Comment by Piecuuu** [comment]
I am also experiencing this issue on Geyser Spigot, with Bedrock on Windows. I have version 1.20.31 installed.
