### ISSUE TITLE
Could not translate packet BookEditPacket

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3658]
### Describe the bug

[19:44:41 ERROR] Could not translate packet BookEditPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:122) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:120) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:46) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
> java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:122)
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55)
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:120)
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:46)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)

### To Reproduce

am not sure what they did on server but it's new error msg to me

### Expected behaviour

[19:44:41 ERROR] Could not translate packet BookEditPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:122) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:120) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:46) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
> java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
        at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:122)
        at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55)
        at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:120)
        at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:46)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)

### Server Version and Plugins

Current: git-Purpur-1952 (MC: 1.19.4)*
![image](https://user-images.githubusercontent.com/88581750/229501157-51a550a9-e8ca-4b81-8195-61bec1d9a393.png)

### Geyser Dump

https://dump.geysermc.org/6IPQd4LQrXSbbgPkcanKxBsfl022Y7C0

### Geyser Version

2.1.0-SNAPSHOT (git-master-0f99abc)

**Comment by onebeastchris** [comment]
Could you try updating to the latest version of Geyser, and see if the issue persists?
If it does, send a new Geyser dump by running "geyser dump" in your server console.

**Comment by onebeastchris** [comment]
Closing due to no response.
