### ISSUE TITLE
Could not translate packet ClientboundAnimatePacket

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3659]
### Describe the bug

[16:05:52 ERROR] Could not translate packet ClientboundAnimatePacket
java.lang.NullPointerException: Cannot invoke "com.github.steveice10.mc.protocol.data.game.entity.player.Animation.ordinal()" because the return value of "com.github.steveice10.mc.protocol.packet.ingame.clientbound.entity.ClientboundAnimatePacket.getAnimation()" is null
        at org.geysermc.geyser.translator.protocol.java.entity.JavaAnimateTranslator.translate(JavaAnimateTranslator.java:52) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.translator.protocol.java.entity.JavaAnimateTranslator.translate(JavaAnimateTranslator.java:41) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[Geyser-Standalone.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
>       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        t io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[       at java.base/java.lang.Thread.run(Thread.java:1589)
Kjava.lang.NullPointerException: Cannot invoke "com.github.steveice10.mc.protocol.data.game.entity.player.Animation.ordinal()" because the return value of "com.github.steveice10.mc.protocol.packet.ingame.clientbound.entity.ClientboundAnimatePacket.getAnimation()" is null

### To Reproduce

this is third new issue to me not sure how is it works 

### Expected behaviour

[17:30:40 ERROR] Could not translate packet ClientboundAnimatePacket
java.lang.NullPointerException: null
ava.lang.NullPointerException

### Server Version and Plugins

git-Purpur-1952 (MC: 1.19.4)
![image](https://user-images.githubusercontent.com/88581750/229501543-7d4bc992-5ffa-47a9-8aab-ee9f04b3d957.png)

### Geyser Dump

https://dump.geysermc.org/6IPQd4LQrXSbbgPkcanKxBsfl022Y7C0

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-0f99abc)

**Comment by Camotoy** [comment]
I haven't seen this error yet - are you able to see if this error happens with no plugins besides Geyser and Floodgate?

**Comment by adalmo** [comment]
https://github.com/PaperMC/Paper/commit/dc08c74 Remove duplicate animate packet for records (#8600) ig this issue was came from papermc but not sure

**Comment by onebeastchris** [comment]
Does the error keep getting spammed after updating paper?

**Comment by onebeastchris** [comment]
Closing due to no response.
