### ISSUE TITLE
Can't join the server

### ISSUE THREAD

**Issue by TechnicalityMods** [GeyserMC/Geyser#3733]
### Describe the bug

Once I try to join through bedrock, i get this error:
16:30:26 INFO]: [Geyser-Spigot] (IP) tried to connect!
[16:30:27 INFO]: [Geyser-Spigot] Player connected with username (username)
[16:30:27 INFO]: [Geyser-Spigot] (username) (logged in as: (username)) has connected to the Java server
[16:30:27 WARN]: [Geyser-Spigot] Failed to encrypt message
java.security.InvalidKeyException: Invalid AES key length: 102 bytes
        at com.sun.crypto.provider.AESCrypt.init(AESCrypt.java:90) ~[?:?]
        at com.sun.crypto.provider.GaloisCounterMode.init(GaloisCounterMode.java:167) ~[?:?]
        at com.sun.crypto.provider.GaloisCounterMode.engineInit(GaloisCounterMode.java:293) ~[?:?]
        at javax.crypto.Cipher.implInit(Cipher.java:871) ~[?:?]
        at javax.crypto.Cipher.chooseProvider(Cipher.java:929) ~[?:?]
        at javax.crypto.Cipher.init(Cipher.java:1444) ~[?:?]
        at javax.crypto.Cipher.init(Cipher.java:1375) ~[?:?]
        at org.geysermc.floodgate.crypto.AesCipher.encrypt(AesCipher.java:64) ~[Geyser-Spigot.jar:?]
        at org.geysermc.floodgate.crypto.FloodgateCipher.encryptFromString(FloodgateCipher.java:80) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.session.GeyserSession$1.packetSending(GeyserSession.java:927) ~[Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketSendingEvent.call(PacketSendingEvent.java:79) ~[Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146) ~[Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:246) ~[Geyser-Spigot.jar:?]
        at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:140) ~[Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31) ~[Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146) ~[Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:357) ~[Geyser-Spigot.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:30:27 INFO]: [Geyser-Spigot] Technicality760 has disconnected from the Java server because of geyser.auth.floodgate.encryption_fail

### To Reproduce

Attempt to follow the basic startup steps provided by you guys
Attempt to join using the proper ip and port
Get The error

### Expected behaviour

I expectet to be able to join the server without an error.

### Server Version and Plugins

1.19.4
Plugins:
AdvancedBan
BanItem
BetterRTP
BuycraftX
Clearlag
CoreProtect
DiSky
EssentialsX
FAWE
Holographic Displays
LuckPerms
SkBee
SkQuery
Skript
Skript-gui
Skript-placeholders
PlaceHolderAPI
Geyser
Floodgate
TAB
Vault
ViaBackwards
ViaVersion
Vulcan
WG
WG Extra Flags

### Geyser Version

Build #99 May 1, 2023

### Minecraft: Bedrock Edition Device/Version

1.19.81, Windows

**Comment by onebeastchris** [comment]
Please send a Geyser dump:
run "geyser dump" in the Minecraft server console, and send the link you get here.

**Comment by TechnicalityMods** [comment]
> Please send a Geyser dump: run "geyser dump" in the Minecraft server console, and send the link you get here.

https://dump.geysermc.org/BcgBOHXiGsvycNAPLUT2ydjDmuvZAsbg

**Comment by onebeastchris** [comment]
#2861
Could you try the fix mentioned in the linked issue?

**Comment by onebeastchris** [comment]
Closing due to no response & likely being fixed.
