### ISSUE TITLE
Failed to decode packet Error whilst deserializing VideoStreamConnectPacket(address=null, screenshotFrequency=0.0, action=null, width=0, height=0)

### ISSUE THREAD

**Issue by frogglen** [GeyserMC/Geyser#3735]
### Describe the bug

actually I am not sure why this is happening, but it is happening after the last changes they made to the nbt tags.

### To Reproduce

No idea

### Expected behaviour

no error in console

### Server Version and Plugins

Geyser Build #1359
velocity-3.2.0-SNAPSHOT-252

### Geyser Version

Geyser versión 2.1.0-SNAPSHOT (git-master-71e091c)

### Additional Context

```
[15:29:25 INFO] [org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec]: Failed to decode packet
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing VideoStreamConnectPacket(address=null, screenshotFrequency=0.0, action=null, width=0, height=0)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:59) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: index: 3, length: 255 (expected: range(0, 9))
        at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.PooledSlicedByteBuf.getBytes(PooledSlicedByteBuf.java:234) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1281) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.getCharSequence(AbstractByteBuf.java:513) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.readCharSequence(AbstractByteBuf.java:518) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at org.cloudburstmc.protocol.bedrock.codec.BaseBedrockCodecHelper.readString(BaseBedrockCodecHelper.java:101) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v361.serializer.VideoStreamConnectSerializer_v361.deserialize(VideoStreamConnectSerializer_v361.java:25) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v361.serializer.VideoStreamConnectSerializer_v361.deserialize(VideoStreamConnectSerializer_v361.java:10) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:57) ~[?:?]
        ... 39 more
[15:29:25 WARN] [io.netty.channel.DefaultChannelPipeline]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing VideoStreamConnectPacket(address=null, screenshotFrequency=0.0, action=null, width=0, height=0)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing VideoStreamConnectPacket(address=null, screenshotFrequency=0.0, action=null, width=0, height=0)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:59) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        ... 35 more
Caused by: java.lang.IndexOutOfBoundsException: index: 3, length: 255 (expected: range(0, 9))
        at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.PooledSlicedByteBuf.getBytes(PooledSlicedByteBuf.java:234) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1281) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.getCharSequence(AbstractByteBuf.java:513) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.buffer.AbstractByteBuf.readCharSequence(AbstractByteBuf.java:518) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at org.cloudburstmc.protocol.bedrock.codec.BaseBedrockCodecHelper.readString(BaseBedrockCodecHelper.java:101) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v361.serializer.VideoStreamConnectSerializer_v361.deserialize(VideoStreamConnectSerializer_v361.java:25) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v361.serializer.VideoStreamConnectSerializer_v361.deserialize(VideoStreamConnectSerializer_v361.java:10) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
        ... 35 more
```

**Comment by Konicai** [comment]
Geyser dump please

**Comment by frogglen** [comment]
> Geyser dump please

https://dump.geysermc.org/NEq4fjSwZqIFiTvNty1UMyKsafcsgIgX
