### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by MissGamerz** [GeyserMC/Geyser#3736]
### Describe the bug

disconnected on join

### To Reproduce

idk

### Expected behaviour

join server

### Screenshots / Videos

[05:12:33 INFO] [Geyser-BungeeCord]: MissGamerz6368 has disconnected from the Java server because of 
[05:12:33 WARN] [Geyser-BungeeCord]: Downstream packet error! String buffer is longer than maximum allowed length
[05:12:33 ERROR]: java.lang.IllegalArgumentException: String buffer is longer than maximum allowed length
[05:12:33 ERROR]:       at com.github.steveice10.packetlib.codec.BasePacketCodecHelper.readString(BasePacketCodecHelper.java:151)
[05:12:33 ERROR]:       at com.github.steveice10.packetlib.codec.BasePacketCodecHelper.readString(BasePacketCodecHelper.java:144)
[05:12:33 ERROR]:       at com.github.steveice10.mc.protocol.packet.login.clientbound.ClientboundHelloPacket.<init>(ClientboundHelloPacket.java:26)
[05:12:33 ERROR]:       at com.github.steveice10.mc.protocol.codec.MinecraftPacketSerializer.deserialize(MinecraftPacketSerializer.java:21)
[05:12:33 ERROR]:       at com.github.steveice10.mc.protocol.codec.MinecraftPacketSerializer.deserialize(MinecraftPacketSerializer.java:10)
[05:12:33 ERROR]:       at com.github.steveice10.packetlib.codec.PacketDefinition.newInstance(PacketDefinition.java:54)
[05:12:33 ERROR]:       at com.github.steveice10.packetlib.packet.PacketProtocol.createClientboundPacket(PacketProtocol.java:159)
[05:12:33 ERROR]:       at com.github.steveice10.mc.protocol.MinecraftProtocol.createClientboundPacket(MinecraftProtocol.java:187)
[05:12:33 ERROR]:       at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:62)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[05:12:33 ERROR]:       at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[05:12:33 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[05:12:33 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[05:12:33 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[05:12:33 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[05:12:33 ERROR]:       at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[05:12:33 ERROR]:       at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[05:12:33 ERROR]:       at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[05:12:33 ERROR]:       at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[05:12:33 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[05:12:33 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[05:12:33 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[05:12:33 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[05:12:33 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[05:12:33 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[05:12:33 INFO] [floodgate]: Floodgate player logged in as .MissGamerz6368 disconnected

### Geyser Version

build 101 released 5/1/2023

**Comment by Jens-Co** [comment]
Can you please upload Geyser dump and a full server log? For a dump you can do console command ( geyser dump ) and your logs you can upload using https://mclo.gs which also distort all sensitive data (ip's).

**Comment by MissGamerz** [comment]
https://mclo.gs/g59S6gt

https://dump.geysermc.org/vj1XEqRly3ngfwCFhcUL0RvgfEycvyQ2

**Comment by Jens-Co** [comment]
This might be caused by nullcord ( which is know ) to break Geyser logging in. Would you mind use if bungeecord/waterfall to test? You might also remove that nullcord bridge plugin for a min then.

**Comment by MissGamerz** [comment]
well that worked, i guess il go annoy nullcord about the issue then

**Comment by MissGamerz** [comment]
UPDATE: setting "disable-compression" to false in config.yml fixes this incompatibility issue with nullcord

**Comment by Jens-Co** [comment]
> UPDATE: setting "disable-compression" to false in config.yml fixes this incompatibility issue with nullcord

Thanks for your feedback!

**Comment by xIsm4** [comment]
> well that worked, i guess il go annoy nullcord about the issue then

This happens because NullCordX replaces compression stuff and breaks default geyser hook for the option called "disable-compression". 
How ever im going to investigate and fix it as soon o can.

Thanks for it - Ismael.
