### ISSUE TITLE
Failed to parse message BUG when enable plugin HappyHUD

### ISSUE THREAD

**Issue by Sy1rKimihiro** [GeyserMC/Geyser#3743]
### Describe the bug

**Reiteration**
- Everytime a Bedrock Edition player join the server
**Disappear**
- Everytime BE player leave the server
**How to fix**
- Delete the plugin: HappyHUD

I can just fix the error report in console, hope u can fix the plugin bug. :)
(Maybe its because the resousepack?I'm still learning convert the JE resousepack to BE, so maybe the unconvert rp cause this?)

**Here is the dump and log file**
</br>

dump:https://dump.geysermc.org/fQeZRP6cz7t1VhRGXWI2EDqBWei8ISFh

file:
[2023-05-04-21.log](https://github.com/GeyserMC/Geyser/files/11398823/2023-05-04-21.log)

### To Reproduce

- Everytime a Bedrock Edition player join the server

### Expected behaviour

none

### Server Version and Plugins

- Server software : purpur 1.19.3 1933
- Java version : Alibaba Dragonwell Java 17
- Minecraft version : 1.19.3
- Plugin list:
[23:02:48 INFO]: Bukkit Plugins: (85):
[23:02:48 INFO]:  - Aboleth, AuthMe, AutoFishing, BedrockPlayerSupport, ChestProtect, ChestSort, Chunky, Citizens, CMI, *CMIEInjector
[23:02:48 INFO]:  CMILib, ConsoleSpamFix, CoreProtect, CrossplatForms, DungeonParties, EasyItem, ExcellentEnchants, floodgate, Floodgate-Skript, Geyser-Spigot
[23:02:48 INFO]:  GeyserHacks, GeyserSkinManager, *GiveItem, HolographicDisplays, ILoreEdit, InteractionVisualizer, Invero, Iris, ItemCommand, ItemNBTEdit
[23:02:48 INFO]:  ItemsAdder, Law, LibsDisguises, LiteAnnouncer, LiteSignIn, LoneLibs, LuckPerms, MagicCosmetics, MangoQuest, MiaoBoard
[23:02:48 INFO]:  MiaoNashorn, MiaoReport, MMOCore, MMOItems, ModelEngine, MonsterPlus, MoveLight, Multiverse-Core, MyPet, MythicDungeons
[23:02:48 INFO]:  MythicLib, MythicMobs, MythicMobsGUI, NBTAPI, NeigeItems, NexEngine, PistonMOTD, PlaceholderAPI, PlayerIntensify, PlayerRace
[23:02:48 INFO]:  PlayerTask, PlayerTitle, PlayerTop, PlugManX, ProtocolLib, PsudoCommand, QuickSave, Residence, ResidenceForm, SakuraBind
[23:02:48 INFO]:  ScriptBlockPlus, ScriptEntityPlus, ServerUtils, SkinsRestorer, Skript, *skript-placeholders, skript-yaml, spark, Tpa, UltimateAutoRestart
[23:02:48 INFO]:  UltimateTimber, Vault, Vulpecula, WorldEdit, WorldEditSUI

### Geyser Dump

https://dump.geysermc.org/fQeZRP6cz7t1VhRGXWI2EDqBWei8ISFh

### Geyser Version

2.1.0-SNAPSHOT (git-master-48d7872)

### Minecraft: Bedrock Edition Device/Version

Bedrock Edition 1.19.50

**Comment by Camotoy** [comment]
Or try starting up your server with the following argument before `-jar`: `-Dfile.encoding=UTF-8`

**Comment by Sy1rKimihiro** [comment]
> Or try starting up your server with the following argument before `-jar`: `-Dfile.encoding=UTF-8`
Sorry for reply so late, it's too busy these days. I followed u comment and here is the new log:

</br>
[2023-05-07-6.log](https://github.com/GeyserMC/Geyser/files/11415114/2023-05-07-6.log)
</br>

Geyser error report begins at row 1126.

I also copied the report here for u to easier check:
`[21:18:09] [Geyser player thread-3-1/WARN]: [Geyser-Spigot] Failed to parse message
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "text" is null
	at org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl$Cereal.component(LegacyComponentSerializerImpl.java:365) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.flattener.ComponentFlattenerImpl.lambda$flattener$2(ComponentFlattenerImpl.java:114) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten0(ComponentFlattenerImpl.java:92) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.flattener.ComponentFlattenerImpl.flatten(ComponentFlattenerImpl.java:75) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.serialize(LegacyComponentSerializerImpl.java:306) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.translator.text.MessageTranslator.convertMessage(MessageTranslator.java:110) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.translator.protocol.java.title.JavaSetActionBarTextTranslator.translate(JavaSetActionBarTextTranslator.java:44) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.translator.protocol.java.title.JavaSetActionBarTextTranslator.translate(JavaSetActionBarTextTranslator.java:35) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:86) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[G[间歇泉]Geyser-Spigot.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`  
</br>

This error will show up every time I enable the happyHUD even just use the default config and default resources pack.
I think its not a Geyser error, just caused by JE resources pack so I decide to disable happyHUD. But this is just my speculation.

**Comment by Sy1rKimihiro** [comment]
[2023-05-07-6.log](https://github.com/GeyserMC/Geyser/files/11415150/2023-05-07-6.log)

**Comment by Hahaa13** [comment]
+1 error

**Comment by onebeastchris** [comment]
Is this still an issue with the latest version of Geyser?

**Comment by Strovo** [comment]
anyone solve?

**Comment by Konicai** [comment]
I'm 99% sure that this is superseded by #4017.

#3803 should fix this issue, which I would appreciate testing of. If you're not sure how to download a PR build, ask on our Discord.
