### ISSUE TITLE
io.netty.handler.codec.DecoderException

### ISSUE THREAD

**Issue by KioProject123** [GeyserMC/Geyser#3749]
### Describe the bug

When some Bedrock Edition players join the server, tens of thousands of the same error reports appear, which makes the log file very large.
Take a section of it:
`[08:28:09] [nioEventLoopGroup-6-9/WARN] [io.netty.channel.DefaultChannelPipeline]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing PlayerSkinPacket(uuid=4cadc30b-d986-337e-a217-df7bb629d079, skin=SerializedSkin(skinId=persona-8bc4d4bd6b711af4-0, playFabId=8bc4d4bd6b711af4, geometryName=geometry.persona_8bc4d4bd6b711af4-0, skinResourcePatch={
   "geometry" : {
      "animated_face" : "geometry.animated_face_persona-8bc4d4bd6b711af4-0",
      "default" : "geometry.persona_8bc4d4bd6b711af4-0"
   }
}
, skinData=ImageData(width=256, height=256), animations=[AnimationData(image=ImageData(width=32, height=64), textureType=FACE, frames=2.0, expressionType=BLINKING)], capeData=ImageData(width=0, height=0), geometryDataEngineVersion=1.14.0, animationData=, premium=false, persona=true, capeOnClassic=false, primaryUser=true, capeId=, fullSkinId=persona-8bc4d4bd6b711af4-0, armSize=wide, skinColor=#ffebd0b0, personaPieces=[PersonaPieceData(id=83c940ce-d7b8-4603-8d73-c1234e322cce, type=persona_mouth, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=1042557f-d1f9-44e3-ba78-f404e8fb7363, type=persona_body, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=8f96d1f8-e9bb-40d2-acc8-eb79746c5d7c, type=persona_skeleton, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=80eda582-cda7-4fce-9d6f-89a60f2448f1, type=persona_top, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=96db6e5b-dc69-4ebc-bd36-cb1b08ffb0f4, type=persona_bottom, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=5f64b737-b88a-40ea-be1f-559840237146, type=persona_feet, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=0948e089-6f9c-40c1-886b-cd37add03f69, type=persona_skin, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=70be0801-a93f-4ce0-8e3f-7fdeac1e03b9, type=persona_hair, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=a0f263b3-e093-4c85-aadb-3759417898ff, type=persona_eyes, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=)], tintColors=[PersonaPieceTintData(type=persona_mouth, colors=[#0, #0, #ffefbbb1, #0]), PersonaPieceTintData(type=persona_hair, colors=[#ffeb983f, #0, #0, #0]), PersonaPieceTintData(type=persona_eyes, colors=[#ff236224, #ffeb983f, #ffe9ecec, #0])], overridingPlayerAppearance=true), newSkinName=null, oldSkinName=null, trustedSkin=false)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing PlayerSkinPacket(uuid=4cadc30b-d986-337e-a217-df7bb629d079, skin=SerializedSkin(skinId=persona-8bc4d4bd6b711af4-0, playFabId=8bc4d4bd6b711af4, geometryName=geometry.persona_8bc4d4bd6b711af4-0, skinResourcePatch={
   "geometry" : {
      "animated_face" : "geometry.animated_face_persona-8bc4d4bd6b711af4-0",
      "default" : "geometry.persona_8bc4d4bd6b711af4-0"
   }
}
, skinData=ImageData(width=256, height=256), animations=[AnimationData(image=ImageData(width=32, height=64), textureType=FACE, frames=2.0, expressionType=BLINKING)], capeData=ImageData(width=0, height=0), geometryDataEngineVersion=1.14.0, animationData=, premium=false, persona=true, capeOnClassic=false, primaryUser=true, capeId=, fullSkinId=persona-8bc4d4bd6b711af4-0, armSize=wide, skinColor=#ffebd0b0, personaPieces=[PersonaPieceData(id=83c940ce-d7b8-4603-8d73-c1234e322cce, type=persona_mouth, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=1042557f-d1f9-44e3-ba78-f404e8fb7363, type=persona_body, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=8f96d1f8-e9bb-40d2-acc8-eb79746c5d7c, type=persona_skeleton, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=80eda582-cda7-4fce-9d6f-89a60f2448f1, type=persona_top, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=96db6e5b-dc69-4ebc-bd36-cb1b08ffb0f4, type=persona_bottom, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=5f64b737-b88a-40ea-be1f-559840237146, type=persona_feet, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=0948e089-6f9c-40c1-886b-cd37add03f69, type=persona_skin, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=70be0801-a93f-4ce0-8e3f-7fdeac1e03b9, type=persona_hair, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=), PersonaPieceData(id=a0f263b3-e093-4c85-aadb-3759417898ff, type=persona_eyes, packId=2099de18-429a-465a-a49b-fc4710a17bb3, isDefault=true, productId=)], tintColors=[PersonaPieceTintData(type=persona_mouth, colors=[#0, #0, #ffefbbb1, #0]), PersonaPieceTintData(type=persona_hair, colors=[#ffeb983f, #0, #0, #0]), PersonaPieceTintData(type=persona_eyes, colors=[#ff236224, #ffeb983f, #ffe9ecec, #0])], overridingPlayerAppearance=true), newSkinName=null, oldSkinName=null, trustedSkin=false)
	at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:59) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	... 35 more
Caused by: java.lang.IndexOutOfBoundsException: index: 328898, length: 115 (expected: range(0, 328939))
	at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.buffer.PooledSlicedByteBuf.getBytes(PooledSlicedByteBuf.java:234) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1281) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.buffer.AbstractByteBuf.getCharSequence(AbstractByteBuf.java:513) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.buffer.AbstractByteBuf.readCharSequence(AbstractByteBuf.java:518) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at org.cloudburstmc.protocol.bedrock.codec.BaseBedrockCodecHelper.readString(BaseBedrockCodecHelper.java:101) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.codec.v388.serializer.PlayerSkinSerializer_v388.deserialize(PlayerSkinSerializer_v388.java:26) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.codec.v390.serializer.PlayerSkinSerializer_v390.deserialize(PlayerSkinSerializer_v390.java:23) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.codec.v390.serializer.PlayerSkinSerializer_v390.deserialize(PlayerSkinSerializer_v390.java:10) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:57) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[?:?]
	at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[?:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[velocity.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	... 35 more
`

### To Reproduce

Only Bedrock Edition players need to join

### Expected behaviour

no error

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT build #252
    - Geyser 2.1.0-SNAPSHOT (git-master-f801dc0) (Java: 1.19.4, Bedrock: 1.19.40/1.19.41 - 1.19.80/1.19.81
    - floodgate 2.2.2-SNAPSHOT (b82-2702bc3) (branch: master)

Paper 1.19.4 build #521
    - floodgate 2.2.2-SNAPSHOT (b82-2702bc3) (branch: master)

### Geyser Dump

https://dump.geysermc.org/dXMFrYLnJv9buepNvNfZuJvaUKOZZvwF

### Geyser Version

2.1.0-SNAPSHOT (git-master-f801dc0)

### Additional Context

Happened when I upgraded from old version geyser to new version
old version: build #1350
new version: build #1366

**Comment by onebeastchris** [comment]
Does this issue still occur when updating to the latest Geyser version?

**Comment by KioProject123** [comment]
> Does this issue still occur when updating to the latest Geyser version?

Yes, the problem still exists.
Using 2.1.0-SNAPSHOT (git-master-246ebdd)
