### ISSUE TITLE
Cannot invoke "org.cloudburstmc.netty.channel.raknet.packet.RakDatagramPacket.getNextSend()" because "datagram" is null

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3767]
### Describe the bug

somehow this error msg shows up when someone joined 

### To Reproduce

i found this error msg on geyser-standalone 1379 build (latest)

### Expected behaviour

Error while ticking RakSessionCodec state=CONNECTED channelActive=true
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.netty.channel.raknet.packet.RakDatagramPacket.getNextSend()" because "datagram" is null
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.sendStaleDatagrams(RakSessionCodec.java:502) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onTick(RakSessionCodec.java:437) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.tryTick(RakSessionCodec.java:382) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser-Standalone.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

### Screenshots / Videos

Error while ticking RakSessionCodec state=CONNECTED channelActive=true ![image](https://github.com/GeyserMC/Geyser/assets/88581750/0353f8e3-c7b1-4a4a-916c-4af2357b4812)

### Server Version and Plugins

[15:25:30 INFO]: Checking version, please wait...
[15:25:30 INFO]: Current: git-Purpur-1969 (MC: 1.19.4)*
Previous: git-Purpur-1968 (MC: 1.19.4)
* You are running the latest version
* 
![image](https://github.com/GeyserMC/Geyser/assets/88581750/d4417a2d-4d18-4318-a01a-1de84b34ec53)

### Geyser Dump

https://dump.geysermc.org/LnmDGUudHQtst1MJljhsv9qOQ5VfzByK

### Geyser Version

2.1.0-SNAPSHOT git-master-870a838

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
