### ISSUE TITLE
Failed to decode packet / An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

### ISSUE THREAD

**Issue by adalmo** [GeyserMC/Geyser#3768]
### Describe the bug

[14:11:47 INFO] Failed to decode packet
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing RequestChunkRadiusPacket(radius=12, maxRadius=0)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:59) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser-Standalone.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(1) exceeds writerIndex(2): PooledSlicedByteBuf(ridx: 2, widx: 2, cap: 2/2, unwrapped: PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 8192))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[Geyser-Standalone.jar:?]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[Geyser-Standalone.jar:?]
        at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:744) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v582.serializer.RequestChunkRadiusSerializer_v582.deserialize(RequestChunkRadiusSerializer_v582.java:23) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v582.serializer.RequestChunkRadiusSerializer_v582.deserialize(RequestChunkRadiusSerializer_v582.java:10) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:57) ~[Geyser-Standalone.jar:?]
        ... 39 more
[14:11:47 WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing RequestChunkRadiusPacket(radius=12, maxRadius=0)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser-Standalone.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser-Standalone.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst deserializing RequestChunkRadiusPacket(radius=12, maxRadius=0)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:59) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Geyser-Standalone.jar:?]
        ... 35 more
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(1) exceeds writerIndex(2): PooledSlicedByteBuf(ridx: 2, widx: 2, cap: 2/2, unwrapped: PooledUnsafeDirectByteBuf(ridx: 3, widx: 3, cap: 8192))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[Geyser-Standalone.jar:?]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[Geyser-Standalone.jar:?]
        at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:744) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v582.serializer.RequestChunkRadiusSerializer_v582.deserialize(RequestChunkRadiusSerializer_v582.java:23) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v582.serializer.RequestChunkRadiusSerializer_v582.deserialize(RequestChunkRadiusSerializer_v582.java:10) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryDecode(BedrockCodec.java:57) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:57) ~[Geyser-Standalone.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.decode(BedrockPacketCodec.java:19) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[Geyser-Standalone.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Geyser-Standalone.jar:?]
        ... 35 more

### To Reproduce

when someone tried to join this error msg shows up (not happening to everyone i mean some of players)

### Expected behaviour

when someone tried to join this error msg shows up (not happening to everyone i mean some of players)

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/88581750/4cf5393e-fea3-441d-acec-e81a6c88cd21)
![image](https://github.com/GeyserMC/Geyser/assets/88581750/e69f5c5a-4dac-4e67-84e8-c8a1fd4f0e83)

### Server Version and Plugins

Current: git-Purpur-1969 (MC: 1.19.4)*
Previous: git-Purpur-1968 (MC: 1.19.4)
* You are running the latest version
* 
![image](https://github.com/GeyserMC/Geyser/assets/88581750/2c2c4b40-48b3-432a-9847-13c14da5da20)

### Geyser Dump

https://dump.geysermc.org/CQqDL43spn6HaqUee2o5rHfLhWR3oZlr

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-870a838)

**Comment by onebeastchris** [comment]
Does this issue still occur when updating to the latest Geyser version?

**Comment by onebeastchris** [comment]
Closing this issue due to no response. If you still experience the issue you described here, please open a new issue with updated information, like a Geyser dump and reproduction steps.
