### ISSUE TITLE
Geyser Reload Crashes Geyser on Velocity

### ISSUE THREAD

**Issue by Joao-Victor-Liporini** [GeyserMC/Geyser#3788]
### Describe the bug

When I type `geyser reload` in the console of my velocity server it crashes the geyser plugin, and gives the following error:

```diff
>....[17:24:03 INFO]: Reloading Geyser configurations... all connected bedrock clients will be kicked.
[17:24:03 INFO] [geyser]: Shutting down Geyser.
[17:24:03 INFO] [geyser]: Geyser shutdown successfully.
[17:24:03 INFO] [geyser]: The skin uploader has been closed
>... geyser
[17:24:16 ERROR]: An error occurred while running this command.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command geyser for com.velocitypowered.proxy.console.VelocityConsole@1b24a716
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command geyser for com.velocitypowered.proxy.console.VelocityConsole@1b24a716
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226) ~[velocity.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:240) ~[velocity.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.command.GeyserCommand.execute(org.geysermc.geyser.session.GeyserSession, org.geysermc.geyser.command.GeyserCommandSource, String[])" because the return value of "org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.getCommand(String)" is null
        at org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.execute(GeyserVelocityCommandExecutor.java:71) ~[?:?]
        at org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.execute(GeyserVelocityCommandExecutor.java:43) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:213) ~[velocity.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:240) ~[velocity.jar:3.2.0-SNAPSHOT (git-6a125bd0-b247)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
```

### To Reproduce

1. Type on velocity console: `geyser reload`
2. Wait for partial reload.
3. Type any command on console related to geyser.
4. See the error.

### Expected behaviour

a successful reload of the geyser

### Server Version and Plugins

```c
>....[17:37:46 INFO]: Velocity 3.2.0-SNAPSHOT (git-6a125bd0-b247)
[17:37:46 INFO]: Copyright 2018-2023 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[17:37:46 INFO]: velocitypowered.com - GitHub
```
```c
[17:38:22 INFO]: ------------=[ ServerUtils Plugins ]=-------------
[17:38:22 INFO]:  Plugins (13): floodgate, Geyser-Velocity, LuckPerms, NamelessMC, nAntiBot, nChat, nLogin, NuVotifier, PixelMOTD, ServerUtils, SkinsRestorer, Snap and VelocityTools
[17:38:22 INFO]: -------------------------------------------------
```

### Geyser Version

Geyser version 2.1.0-SNAPSHOT (git-master-178fb21)

**Comment by onebeastchris** [comment]
was able to reproduce this on a supported, online mode velocity setup. Seems like Geyser stops, but doesnt start up again

**Comment by gamer50082** [comment]
Geyser reload doesn’t reload but just off server still runs
