### ISSUE TITLE
EC KeyPairGenerator not available

### ISSUE THREAD

**Issue by 3328429240** [GeyserMC/Geyser#3800]
### Describe the bug

player join game

### To Reproduce

join game

### Expected behaviour

No join

### Screenshots / Videos

`[08:51:08 [33;1mWARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
>java.lang.AssertionError: Unable to initialize required encryption
at org.cloudburstmc.protocol.bedrock.util.EncryptionUtils.<clinit>(EncryptionUtils.java:58) ~[Geyser.jar:?]
at org.geysermc.geyser.util.LoginEncryptionUtils.validateChainData(LoginEncryptionUtils.java:92) ~[Geyser.jar:?]
at org.geysermc.geyser.util.LoginEncryptionUtils.encryptConnectionWithCert(LoginEncryptionUtils.java:131) ~[Geyser.jar:?]
at org.geysermc.geyser.util.LoginEncryptionUtils.encryptPlayerConnection(LoginEncryptionUtils.java:124) ~[Geyser.jar:?]
at org.geysermc.geyser.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:169) ~[Geyser.jar:?]
at org.cloudburstmc.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:22) ~[Geyser.jar:?]
at org.cloudburstmc.protocol.bedrock.packet.BedrockPacketHandler.handlePacket(BedrockPacketHandler.java:9) ~[Geyser.jar:?]
at org.cloudburstmc.protocol.bedrock.BedrockSession.onPacket(BedrockSession.java:123) ~[Geyser.jar:?]
at org.cloudburstmc.protocol.bedrock.BedrockPeer.onBedrockPacket(BedrockPeer.java:66) ~[Geyser.jar:?]
at org.cloudburstmc.protocol.bedrock.BedrockPeer.channelRead(BedrockPeer.java:251) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser.jar:?]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser.jar:?]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser.jar:?]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Geyser.jar:?]
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser.jar:?]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[Geyser.jar:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Geyser.jar:?]
at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[Geyser.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser.jar:?]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser.jar:?]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [Geyser.jar:?]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser.jar:?]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
>Caused by: java.security.NoSuchAlgorithmException: EC KeyPairGenerator not available
at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:236) ~[?:?]
at org.cloudburstmc.protocol.bedrock.util.EncryptionUtils.<clinit>(EncryptionUtils.java:54) ~[Geyser.jar:?]
... 44 more`

### Geyser Dump

>Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.security.ssl.SSLContextImpl$DefaultSSLContext at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:375) at java.base/java.security.Provider$Service.getImplClass(Provider.java:1933) at java.base/java.security.Provider$Service.getDefaultConstructor(Provider.java:1964) at java.base/java.security.Provider$Service.newInstanceOf(Provider.java:1878) at java.base/java.security.Provider$Service.newInstanceUtil(Provider.java:1886) at java.base/java.security.Provider$Service.newInstance(Provider.java:1861) at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236) at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164) at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185) at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110) at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:83) at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:336) at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292) at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:81) at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62) at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57) at java.base/java.net.URL.openConnection(URL.java:1094) at org.geysermc.geyser.util.WebUtils.post(WebUtils.java:108) at org.geysermc.geyser.command.defaults.DumpCommand.execute(DumpCommand.java:123) at org.geysermc.geyser.command.GeyserCommandManager.runCommand(GeyserCommandManager.java:185) at org.geysermc.geyser.platform.standalone.GeyserStandaloneLogger.runCommand(GeyserStandaloneLogger.java:47) at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:181) at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:143) at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:233) at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onEnable(GeyserStandaloneBootstrap.java:170) at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:164)

### Geyser Version

new

### Minecraft: Bedrock Edition Device/Version

1.19

**Comment by rtm516** [comment]
Please provide a Geyser Dump and full logs

> Run geyser dump logs (server console) / /geyser dump logs (ingame chat) on your Geyser instance or server, then copy the link it will give you and paste it here. This will automatically upload the server logs to [mclo.gs](https://mclo.gs/) and add the link in the dump.

**Comment by rtm516** [comment]
> Hello, I'm in Chinese Mainland. It seems that you can't upload here. Is there any other way?

You shouldn't have an issue copying and pasting the link the command generates, if it errors please just do `geyser dump`

**Comment by Camotoy** [comment]
If it errors, run `geyser dump offline`

**Comment by Camotoy** [comment]
Send that `dump.json` file our way?

**Comment by Konicai** [comment]
please just upload the file itself

**Comment by Konicai** [comment]
Closing this issue as it's stale - let us know if you're still having this issue
