### ISSUE TITLE
Geyser won't start on Bungee

### ISSUE THREAD

**Issue by pinkpig58** [GeyserMC/Geyser#3819]
### Describe the bug

Unable to start Geyser on the latest version of Bungeecord.

```
[WARNING] Error loading plugin Geyser-BungeeCord
java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)'
    at org.geysermc.geyser.platform.bungeecord.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:191)
    at org.geysermc.geyser.platform.bungeecord.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:504)
    at org.geysermc.geyser.platform.bungeecord.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:392)
    at org.geysermc.geyser.platform.bungeecord.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:15)
    at org.geysermc.geyser.platform.bungeecord.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3542)
    at org.geysermc.geyser.util.FileUtils.loadConfig(FileUtils.java:57)
    at org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin.onLoad(GeyserBungeePlugin.java:99)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:345)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

### To Reproduce

1. Create a Bungeecord server
2. Add Geyser-Bungeecord
3. Start server

### Expected behaviour

Server should start

### Geyser Version

Geyser-BungeeCord

**Comment by Kas-tle** [comment]
Hi could you please check if the attached build artifact resolves the issue for you? It will be available here (must be unzipped to obtain jar): https://github.com/Kas-tle/Geyser/actions/runs/5202996580

**Comment by pinkpig58** [comment]
Seems to work - thank you!
