### ISSUE TITLE
Bedrock users unable to connect after a while when using BungeeCord; Broken pipe

### ISSUE THREAD

**Issue by mibby** [GeyserMC/Geyser#384]
**Describe the bug**
It seems after a while, bedrock users are unable to connect and everyone gets broken pipe messages. Once a broken pipe message occurs, no bedrock users are able to connect. Java users are able to reconnect fine.

Need to completely restart BungeeCord for bedrock connections to work again.

**To Reproduce**
1) Login to server with Bedrock client.
2) Run around for a little. Teleport around.
3) Get broken pipe error sent to BungeeCord. 
4) Disconnected, no longer able to connect with Bedrock PC or Mobile.

**Expected behavior**
Being able to connect with Bedrock.

**Server Version**
Paper dev 201 (Spigot 1.15.2)
Waterfall dev 327 (BungeeCord 1.15.2)

**Geyser Version**
Geyser inventory dev 24 (Using as BungeeCord Plugin)
Floodgate development dev 5 (Using as BungeeCord Plugin)

**Minecraft: Bedrock Edition Version**
Minecraft Bedrock 1.14.60

**Additional Context**

Java 11.0.7 (AdoptOpenJDK LTS)
Centos 8 (Linux)

```
[19:05:29] [nioEventLoopGroup-1131-1/INFO] [Geyser-BungeeCord]: brynhilll (logged in as: brynhilll) has connected to remote java server on address 127.0.0.1
[19:05:29] [nioEventLoopGroup-1131-1/INFO] [Geyser-BungeeCord]: brynhilll has disconnected from remote java server on address 127.0.0.1 because of java.io.IOException: Broken pipe
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: java.io.IOException: Broken pipe
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:50)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:466)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1384)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1037)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:293)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:222)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.mc.protocol.ClientListener.packetSent(ClientListener.java:126)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.event.session.PacketSentEvent.call(PacketSentEvent.java:51)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:148)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:226)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession$1.operationComplete(TcpSession.java:222)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:222)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:136)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:148)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:334)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:272)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1410)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:907)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[19:05:29] [nioEventLoopGroup-1131-1/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[19:05:30] [Network Listener - #1/INFO] [Geyser-BungeeCord]: Bedrock user with ip: /censored has disconnected for reason CLOSED_BY_REMOTE_PEER
```

Edit: This also happens if users intentionally disconnect and try logging in again. Such as switching from mobile bedrock to pc bedrock. They get broken pipe and can't connect.

**Comment by mibby** [comment]
For reference if it's a thread-pool issue;

```
ping-passthrough: true
general-thread-pool: 32
allow-third-party-capes: true
``

**Comment by ForumPlayer** [comment]
I've been affected by this bug too but on 1.13.2 with ViaVersion

**Comment by MrPowerGamerBR** [comment]
I'm having the same issue, but with the standalone proxy version.

Restarting the proxy fixes the issue, proxy is connected to Waterfall.

**Comment by RednedEpic** [comment]
Gotten some reports that disabling ping passthrough fixes the issue. Could anyone else having this problem confirm that?

**Comment by MrPowerGamerBR** [comment]
Can confirm that disabling ping passthrough fixed the issue (or maybe it was one of the recents commits)

**Comment by applebee1558** [comment]
Confirmed that disabling ping passthrough fixes it, having it on breaks geyser.

**Comment by DoctorMacc** [comment]
@applebee1558 What server software are you using?

**Comment by applebee1558** [comment]
@DoctorMacc Spigot 1.15.2

**Comment by SeqSEE** [comment]
Also confirming that disabling ping passthrough fixes it.
Waterdog proxy to Geyser on Bungeecord

**Comment by Artuto** [comment]
Perhaps related to #427

**Comment by DoctorMacc** [comment]
@applebee1558 Only Spigot? No BungeeCord?

For anyone else: What is your MOTD? Online mode/offline mode/Floodgate?

**Comment by applebee1558** [comment]
Actually, sorry I do have bungeecord in the middle, forgot about it.

**Comment by DoctorMacc** [comment]
https://github.com/GeyserMC/Geyser/pull/464 may fix this, PLEASE TEST!
