### ISSUE TITLE
Numerous errors in the console

### ISSUE THREAD

**Issue by Mill-ton** [GeyserMC/Geyser#3850]
### Describe the bug

When a Bedrock user connects, it causes the errors shown below

*I apologize in advance for spelling mistakes. I am a Russian-speaking user.

### To Reproduce

1. Starting the server
2. I enter the server from the Bedrock version of mintcraft
3. An error appears in the console
4. After a long time, the player is still not allowed on the server

### Expected behaviour

Expected a player to be able to log on to the server and everything would be fine. But, it wasn't.

### Screenshots / Videos

Error 1
```
[org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec]: Error encoding packet ResourcePacksInfoPacket(behaviorPackInfos=[], resourcePackInfos=[], forcedToAccept=true, scriptingEnabled=false, forcingServerPacksEnabled=false)
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.protocol.bedrock.codec.BedrockPacketDefinition.getId()" because the return value of "org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.getPacketDefinition(java.lang.Class)" is null
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.getPacketId(BedrockPacketCodec.java:75) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:37) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.onTick(BedrockPeer.java:87) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

error 2
```
[org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec]: Error encoding packet ServerToClientHandshakePacket(jwt=eyJ4NXUiOiJNSFl3RUFZSEtvWkl6ajBDQVFZRks0RUVBQ0lEWWdBRU41UVJGODIzMDVETzFqMnNoRFNjc2dUczEraGtpOUtFUVRyVEhXUWQ4UVpydm04aGdLSGY2V3RRV2JZZTBNSzRHSlFoNEVOWFlVWkdXclN3VzZSSjRtR2ZERmhQUzAxbXUwUjRKQWdGUkY5RytwdGNjWktkN2p0YUI4N0ZHcXcwIiwiYWxnIjoiRVMzODQifQ.eyJzYWx0IjoiVGNuQ1RKdUtOcjJ1UzhuZ2U1T3hwZz09In0.qjnJ_SMt7rv-7hl9Xy344Z0zItMCJ3vfH3Vk-gOl3wGJ39Aw2i04Cm7UBkG2hNeeFACeHYbzQ7lMh2SbMjvCYChfATsyt4P4kSv3fwJaqz3s_xmEOohTR72nkPzZsYtP)
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.protocol.bedrock.codec.BedrockPacketDefinition.getId()" because the return value of "org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.getPacketDefinition(java.lang.Class)" is null
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.getPacketId(BedrockPacketCodec.java:75) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:37) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.sendPacketImmediately(BedrockPeer.java:111) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.BedrockSession.sendPacketImmediately(BedrockSession.java:53) ~[?:?]
        at org.geysermc.geyser.session.UpstreamSession.sendPacketImmediately(UpstreamSession.java:56) ~[?:?]
        at org.geysermc.geyser.session.GeyserSession.sendUpstreamPacketImmediately(GeyserSession.java:1594) ~[?:?]
        at org.geysermc.geyser.util.LoginEncryptionUtils.startEncryptionHandshake(LoginEncryptionUtils.java:211) ~[?:?]
        at org.geysermc.geyser.util.LoginEncryptionUtils.encryptConnectionWithCert(LoginEncryptionUtils.java:187) ~[?:?]
        at org.geysermc.geyser.util.LoginEncryptionUtils.encryptPlayerConnection(LoginEncryptionUtils.java:142) ~[?:?]
        at org.geysermc.geyser.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:155) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:22) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.packet.BedrockPacketHandler.handlePacket(BedrockPacketHandler.java:9) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.BedrockSession.onPacket(BedrockSession.java:123) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.onBedrockPacket(BedrockPeer.java:66) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.channelRead(BedrockPeer.java:251) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[bungeecord.jar:3.2.0-SNAPSHOT (git-e0cf2e21-b257)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Server Version and Plugins

Version: Velocity 
Java: 18
Plugins: floodgate-velocity, Geyser-Velocity, LuckPerms-Velocity, velocity_tools

### Geyser Dump

https://dump.geysermc.org/j5epUCOP1StZoK7rTvtcWCHGaEgwq0Re

### Geyser Version

Build #175

### Minecraft: Bedrock Edition Device/Version

1.18.33 and 1.20х, PC and Phone

### Additional Context

Please help me to sort this out as a matter of urgency. I need to know now what the problem is and where to fix it

**Comment by onebeastchris** [comment]
This was fixed in the latest build released a few minutes ago, please update.
