### ISSUE TITLE
Index error while retrieving chunk section that BlockEntityInfo belongs to

### ISSUE THREAD

**Issue by Virgil692** [GeyserMC/Geyser#3863]
### Describe the bug

This is the error message
...
[15:57:36 WARN]: [Geyser-Spigot] 无法翻译数据包 ClientboundLevelChunkWithLightPacket
java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 0
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:265) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:80) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:85) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:65) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.93.Final.jar:4.1.93.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.93.Final.jar:4.1.93.Final]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[15:57:36 WARN]: java.lang.ArrayIndexOutOfBoundsException: Index -2 out of bounds for length 0
[15:57:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:265)
[15:57:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:80)
[15:57:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:85)
[15:57:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:65)
[15:57:36 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:57:36 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[15:57:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:57:36 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:57:36 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[15:57:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
...

### To Reproduce

According to player feedback, the connection server has been loading

### Expected behaviour

I hope players in the bedrock version can enter the server tool normally

### Screenshots / Videos

[QQ视频20230613164618.zip](https://github.com/GeyserMC/Geyser/files/11732754/QQ.20230613164618.zip)

### Server Version and Plugins

core:
https://github.com/Winds-Studio/Leaf
about 1.20

### Geyser Dump

https://dump.geysermc.org/Dx4AAp4doYdROzBGq5a6ewLI9iSLr5Vw

### Geyser Version

1.20

### Minecraft: Bedrock Edition Device/Version

1.20.0.01

**Comment by Konicai** [comment]
Does this occur with Paper instead of Gale/Leaf ?

**Comment by onebeastchris** [comment]
Closing due to no response.
