### ISSUE TITLE
Console error when geyser player tries to connect.

### ISSUE THREAD

**Issue by jefflima1** [GeyserMC/Geyser#3873]
### Describe the bug

The player tries to connect and the error is shown on the console, many times he is able to enter, sometimes not, The problem happens in plugin versions, standalone geyser does not generate this error.

### To Reproduce

Put Geyser in the plugins folder,

install floodgate

start the server, when a massive amount of people start trying to enter the error is generated.

### Expected behaviour

It doesn't flood the console with error information.

### Screenshots / Videos

[io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: Cannot read the array length because "supportedProtocols" is null
        at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.onOpenConnectionRequest2(RakServerOfflineHandler.java:180) ~[Geyser-Spigot.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(RakServerOfflineHandler.java:101) ~[Geyser-Spigot.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(RakServerOfflineHandler.java:42) ~[Geyser-Spigot.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:45) ~[Geyser-Spigot.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at org.geysermc.geyser.network.netty.handler.RakConnectionRequestHandler.channelRead(RakConnectionRequestHandler.java:80) ~[Geyser-Spigot.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(ProxyInboundRouter.java:66) ~[Geyser-Spigot.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]

### Server Version and Plugins

[23:38:03 INFO]: Checking version, please wait...
[23:38:05 INFO]: This server is running Paper version git-Paper-19 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 837cc25)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-18 (MC: 1.20.1)
> pl
[23:38:06 INFO]: Server Plugins (54):
[23:38:06 INFO]: Paper Plugins:
[23:38:06 INFO]:  - BKCommonLib
[23:38:06 INFO]: Bukkit Plugins:
[23:38:06 INFO]:  - AngelChest, AureliumSkills, AuthMe, *AutoViaUpdater, *ChatCooldown, ChestSort, ChunkSpawnerLimiter, Chunky, ChunkyBorder, CommandWhitelist
[23:38:06 INFO]:  CoreProtect, DecentHolograms, DiscordSRV, Drop2InventoryPlus, Essentials, EssentialsSpawn, FastLogin, FireworkDeath, floodgate, GeyserHacks
[23:38:06 INFO]:  GSit, InvSeePlusPlus, LevelledMobs, LuckPerms, M0-AntiAnvilRename, MiniMOTD, Multiverse-Core, My_Worlds, PlaceholderAPI, Plan
[23:38:06 INFO]:  PlayerKits, ProtocolLib, RedProtect, RePlant, ServerBackup, SimpleUtils, SkinsRestorer, Skript, sleep-most, Slimefun
[23:38:06 INFO]:  StreamingDrops, SuperLobby, TradeSystem, UltimateAutoRestart, UTitleAuth, Vault, ViaBackwards, ViaRewind, ViaRewind-Legacy-Support, ViaVersion
[23:38:06 INFO]:  WarpSystem, WorldEdit, WorldGuard

### Geyser Version

[23:38:43 INFO] Este servidor está executando a Geyser versão 2.1.1-SNAPSHOT (git-master-446d3c2) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)

### Minecraft: Bedrock Edition Device/Version

1.20/1.20.10

**Comment by Konicai** [comment]
Share your full logs using a paste website, and the link provided by `/geyser dump` please.

**Comment by jefflima1** [comment]
I don't know if it helps, but I believe it is a login attempt by a version not supported by geysermc, which generates the error mentioned above

**Comment by Konicai** [comment]
longer logs please

**Comment by jefflima1** [comment]
https://mclo.gs/cdY5ttD

**Comment by Konicai** [comment]
Closing in favour of #3905
