### ISSUE TITLE
Unexpected problem occured during version sanity check

### ISSUE THREAD

**Issue by BackSam6348** [GeyserMC/Geyser#3887]
### Describe the bug

Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
        at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:331)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:172)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
        at io.netty.util.internal.logging.Slf4JLoggerFactory.<init>(Slf4JLoggerFactory.java:42)
        at io.netty.util.internal.logging.Slf4JLoggerFactory$NopInstanceHolder.<clinit>(Slf4JLoggerFactory.java:63)
        at io.netty.util.internal.logging.Slf4JLoggerFactory.getInstanceWithNopCheck(Slf4JLoggerFactory.java:59)
        at io.netty.util.internal.logging.InternalLoggerFactory.useSlf4JLoggerFactory(InternalLoggerFactory.java:62)
        at io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(InternalLoggerFactory.java:42)
        at io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory(InternalLoggerFactory.java:111)
        at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:134)
        at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:127)
        at io.netty.util.ResourceLeakDetector.<clinit>(ResourceLeakDetector.java:101)
        at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:86)

### To Reproduce

Just start latest build

### Expected behaviour

Error immediately after execution

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/47339652/0ebe6056-2f06-49b0-8f4a-dd7308572fd9)

### Server Version and Plugins

Purpur 1.19.4 (git-Purpur-1985)

Floodgate Latest Version
Geyser-Standalone latest

### Geyser Dump

https://dump.geysermc.org/eTrtndykRKgNbhXsPlTWOKniHMEsHsaR

### Geyser Version

2.1.1-SNAPSHOT (git-master-f272ed9)

### Additional Context

I want to fix that error.

**Comment by BackSam6348** [comment]
And I am using Java 20.
