### ISSUE TITLE
Cannot read the array length because "supportedProtocols" is null

### ISSUE THREAD

**Issue by gre3x** [GeyserMC/Geyser#3905]
### Describe the bug

Sometimes (seems random?), my Geyser Standalone server will stop accepting players joining and spams the console with:
```
22.06 18:22:06 [Server] [WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
22.06 18:22:06 [Server] [INFO] java.lang.NullPointerException: Cannot read the array length because "supportedProtocols" is null
```

When players try to join after this happens, the console gets these messages and does not allow the player to join the server:
```
22.06 18:24:33 [Server] [INFO] Stardog7578 has disconnected from remote Java server on address 192.99.XXX.XXX because of io.netty.channel.unix.Errors$NativeIoException: sendAddress(..) failed: Broken pipe
22.06 18:24:33 [Server] [INFO] io.netty.channel.unix.Errors$NativeIoException: sendAddress(..) failed: Broken pipe
```

The only way to fix it is by restarting Geyser Standalone

Full logs: https://mclo.gs/F8qUxi2

### To Reproduce

1. Run latest version for a few hours while having many players join
2. Wait 2-36 hours for players to be affected

### Expected behaviour

No error messages and players are able to join

### Server Version and Plugins

- Geyser Standalone version 2.1.1-SNAPSHOT (git-master-50d7f56) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.0)
- Flamecord is bungee proxy with Floodgate for Bungee installed. However, they never connect to that server.
- Hub server that they are first connecting to is Paper 1.12.2 with latest Floodgate for spigot and ViaVersion installed. However, they never connect to that server.

### Geyser Dump

https://dump.geysermc.org/YIOWNLdjNxqsHzlBlG2Z6d7yjliZ5Lxz

### Geyser Version

2.1.1-SNAPSHOT (git-master-50d7f56)

### Minecraft: Bedrock Edition Device/Version

1.20.0

### Additional Context

Full logs: https://mclo.gs/F8qUxi2

This user seems to also be getting this issue: https://github.com/GeyserMC/Geyser/issues/3873

The full exception might look like this (although I'm not 100% sure):
```
[18:22:10.294 epollEventLoopGroup-3-4/WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: java.lang.IllegalStateException: Invalid frame ID: 19
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[Geyser.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Geyser.jar:?]
	at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60) ~[Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Invalid frame ID: 19
	at org.cloudburstmc.protocol.bedrock.netty.codec.FrameIdCodec.decode(FrameIdCodec.java:48) ~[Geyser.jar:?]
	at org.cloudburstmc.protocol.bedrock.netty.codec.FrameIdCodec.decode(FrameIdCodec.java:13) ~[Geyser.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[Geyser.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Geyser.jar:?]
	... 17 more
[18:22:10.296 epollEventLoopGroup-3-1/WARN] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException: Cannot read the array length because "supportedProtocols" is null
	at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.onOpenConnectionRequest2(RakServerOfflineHandler.java:180) ~[Geyser.jar:?]
	at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(RakServerOfflineHandler.java:101) ~[Geyser.jar:?]
	at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(RakServerOfflineHandler.java:42) ~[Geyser.jar:?]
	at org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:45) ~[Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [Geyser.jar:?]
	at org.geysermc.geyser.network.netty.handler.RakConnectionRequestHandler.channelRead(RakConnectionRequestHandler.java:80) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [Geyser.jar:?]
	at org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(ProxyInboundRouter.java:66) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [Geyser.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:648) [Geyser.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:683) [Geyser.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:55) [Geyser.jar:?]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:522) [Geyser.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:425) [Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by gre3x** [comment]
I am opening this because I am using the build after this one, which I assume was supposed to fix this: https://github.com/GeyserMC/Geyser/commit/50d3945477d928b2e3f486f7fb5ca2a56e9bd837

**Comment by gre3x** [comment]
Continues to happen daily

**Comment by gre3x** [comment]
Taking a closer look, it seems that the server is running out of memory. I have given it 25 GB of memory though... Is there any way to fix this:?

**Comment by jefflima1** [comment]
I have the same problem, my server's memory is good, this happens with the standalone version and the plugin version

**Comment by Camotoy** [comment]
We're aware of this issue and may have a fix soon.

**Comment by gre3x** [comment]
Are there any updates on this? I have been having to restart my server every few hours for weeks due to this and it is very inconvenient for my staff and players.

**Comment by gre3x** [comment]
Is anyone looking into this? Does anyone have any workarounds for this? 
You said over a week ago that you "may have a fix soon", but have given no updates since then.

**Comment by Camotoy** [comment]
I'm afraid there are no updates at this time.

**Comment by gre3x** [comment]
So no one is looking into it and there are no workarounds? We just have to accept that we will have to restart the server every few hours indefinitely?

**Comment by Camotoy** [comment]
There will be a fix for this. We know where it happens in the codebase, but I'm unsure of the proper fix myself and am requesting the assistance of someone more familiar with the library.
