### ISSUE TITLE
Error encoding packet SetScorePacket(action=REMOVE, infos=[null])

### ISSUE THREAD

**Issue by QATimer** [GeyserMC/Geyser#3934]
### Describe the bug

I don't know what the problem is. I use a geyser on my server on Aternos and had a lot of the same errors today when my friend connected to the server. 
Log : https://mclo.gs/CHKlFze

### To Reproduce

1. Load server
2. Enter server with minecraft pocket edition 1.20.01

### Expected behaviour

no errors

### Server Version and Plugins

PaperMC 1.20-R0.1-SNAPSHOT

### Geyser Dump

https://dump.geysermc.org/2gvkDmJqK76RyvzrxNXb7t3WBG4brXik

### Geyser Version

Geyser-Spigot v2.1.1-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

PE 1.20.01 on Android

### Additional Context

Please excuse me for my poor English and for my lack of understanding in general. I gave you everything I could give

**Comment by rtm516** [comment]
```
[20:48:03] [epollEventLoopGroup-3-2/ERROR]: [org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec] Error encoding packet SetScorePacket(action=REMOVE, infos=[null])
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst serializing SetScorePacket(action=REMOVE, infos=[null])
	at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:80) ~[Geyser-Spigot.jar:?]
	at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:39) ~[Geyser-Spigot.jar:?]
	at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19) ~[Geyser-Spigot.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-codec-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at org.cloudburstmc.protocol.bedrock.BedrockPeer.onTick(BedrockPeer.java:91) ~[Geyser-Spigot.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.protocol.bedrock.data.ScoreInfo.getScoreboardId()" because "scoreInfo" is null
	at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.SetScoreSerializer_v291.lambda$serialize$0(SetScoreSerializer_v291.java:25) ~[Geyser-Spigot.jar:?]
	at org.cloudburstmc.protocol.bedrock.codec.BaseBedrockCodecHelper.writeArray(BaseBedrockCodecHelper.java:238) ~[Geyser-Spigot.jar:?]
	at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.SetScoreSerializer_v291.serialize(SetScoreSerializer_v291.java:24) ~[Geyser-Spigot.jar:?]
	at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.SetScoreSerializer_v291.serialize(SetScoreSerializer_v291.java:14) ~[Geyser-Spigot.jar:?]
	at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[Geyser-Spigot.jar:?]
	... 23 more
```

**Comment by QATimer** [comment]
I understand why this is happening. This is a bug that triggered by another plugin. This plugin called "WhatIsThis". If in this plugin in the config you change this to true: "auto_display: true" , ​​then an error will be triggered in the geyser. Because WhatIsThis is trying to get information not from the java player, which does not have a normal cursor.

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/commit/58ff00db961641164411564fe1c6d9406750f991
should fix this
