### ISSUE TITLE
Cannot encode FEELING_HAPPY flag for 1.20.10

### ISSUE THREAD

**Issue by DarkChromaMC** [GeyserMC/Geyser#3966]
### Describe the bug

An exception is being thrown and continuously spammed in the console, specifically related to the SetEntityDataPacket. The error is linked to encoding an unknown identifier "FEELING_HAPPY" as part of the entity's metadata, which is not recognized by the server. This error occurred after updating to 1.20.10 GeyserMC

### To Reproduce

Currently, it's not clear what exact steps trigger this error. The log simply states it's related to the SetEntityDataPacket

### Expected behaviour

No console errors

### Screenshots / Videos

[10:14:12 ERROR] [org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec]: Error encoding packet SetEntityDataPacket(metadata={FLAGS=[CAN_SHOW_NAME, SILENT, CAN_CLIMB, HAS_COLLISION, HAS_GRAVITY, FEELING_HAPPY], , runtimeEntityId=3048, tick=0, properties=EntityProperties(intProperties=[], floatProperties=[]))
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst serializing SetEntityDataPacket(metadata={FLAGS=[CAN_SHOW_NAME, SILENT, CAN_CLIMB, HAS_COLLISION, HAS_GRAVITY, FEELING_HAPPY], , runtimeEntityId=3048, tick=0, properties=EntityProperties(intProperties=[], floatProperties=[]))
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:80) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:39) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19) ~[?:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.onTick(BedrockPeer.java:91) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-37fedf50-b260)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Failed to encode EntityData 0 of java.util.EnumSet
        at org.cloudburstmc.protocol.bedrock.codec.v361.BedrockCodecHelper_v361.writeEntityData(BedrockCodecHelper_v361.java:138) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.SetEntityDataSerializer_v291.serialize(SetEntityDataSerializer_v291.java:19) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:13) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:9) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[?:?]
        ... 23 more
Caused by: java.lang.IllegalArgumentException: No id found for FEELING_HAPPY
        at org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:207) ~[?:?]
        at org.cloudburstmc.protocol.common.util.TypeMap.getId(TypeMap.java:39) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.transformer.FlagTransformer.serialize(FlagTransformer.java:28) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.transformer.FlagTransformer.serialize(FlagTransformer.java:14) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v361.BedrockCodecHelper_v361.writeEntityData(BedrockCodecHelper_v361.java:104) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.SetEntityDataSerializer_v291.serialize(SetEntityDataSerializer_v291.java:19) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:13) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:9) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[?:?]
        ... 23 more

### Server Version and Plugins

PROXY: Velocity 3.2.0-SNAPSHOT (git-37fedf50-b260)

HUB server: Paper version git-Paper-189 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ec76e36)
Main servers: git-Purpur-2005 (MC: 1.20.1)*

### Geyser Dump

https://dump.geysermc.org/hdOD8CFqFfB3SOC5lPIexQzaqb3PX13q

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-3a0c1b7) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Additional Context

This console error spam did not show up until updating to the latest GEYSERMC version 1.20.10

**Comment by onebeastchris** [comment]
Please send a full log via mclo.gs

**Comment by shawn695** [comment]
i also had this happen to me running the gesyer dump command in my proxy

**Comment by shawn695** [comment]
https://mclo.gs/CNZnBEQ

**Comment by DarkChromaMC** [comment]
https://mclo.gs/vcyb573

**Comment by onebeastchris** [comment]
I think they replied to the wrong github post; it was relevant for https://github.com/GeyserMC/Geyser/issues/3967

**Comment by Konicai** [comment]
Fixed in c1d8009b4066c8e09b1b1e42ff7d61e0af8b9898

**Comment by shawn695** [comment]
this sint fixed it just started to happen again

**Comment by onebeastchris** [comment]
provide a geyser dump pls?
```geyser dump``` in the server console & send the link here

**Comment by shawn695** [comment]
https://dump.geysermc.org/QiLItgnwC4OSlSPNNpAOhknRDt6jReYm

**Comment by onebeastchris** [comment]
that's not the latest geyser version

**Comment by shawn695** [comment]
hmmm let me redownload 237
