### ISSUE TITLE
Cannot encode TABLE_USE sound

### ISSUE THREAD

**Issue by PedroMPagani** [GeyserMC/Geyser#3969]
### Describe the bug

[14:41:22 ERROR] Error encoding packet LevelSoundEvent2Packet(sound=TABLE_USE, position=(-65830.5, -57.5, -51172.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst serializing LevelSoundEvent2Packet(sound=TABLE_USE, position=(-65830.5, -57.5, -51172.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:80) ~[Geyser.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:39) ~[Geyser.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19) ~[Geyser.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[Geyser.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[Geyser.jar:?]
        at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[Geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[Geyser.jar:?]
        at org.cloudburstmc.protocol.bedrock.BedrockPeer.onTick(BedrockPeer.java:91) ~[Geyser.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [Geyser.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) [Geyser.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [Geyser.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No id found for TABLE_USE
        at org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:207) ~[Geyser.jar:?]
        at org.cloudburstmc.protocol.common.util.TypeMap.getId(TypeMap.java:39) ~[Geyser.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v332.serializer.LevelSoundEventSerializer_v332.serialize(LevelSoundEventSerializer_v332.java:18) ~[Geyser.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.v332.serializer.LevelSoundEventSerializer_v332.serialize(LevelSoundEventSerializer_v332.java:12) ~[Geyser.jar:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[Geyser.jar:?]
        ... 23 more
[14:41:23 INFO] OMKAR 

### To Reproduce

no idea

### Expected behaviour

no exception?

### Server Version and Plugins

100 shards, different types of shards different lists, none of the plugins are affecting this, this is related to the update.

### Geyser Dump

https://dump.geysermc.org/sv5djPw3xa6hz13fQA6SuXdVzPZQppfk

### Geyser Version

>....[14:41:46 INFO] This server is running Geyser version 2.1.2-SNAPSHOT (git-master-3a0c1b7) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

**Comment by jefflima1** [comment]
I'm getting this same error on the console, I'm using the latest version of geyser-spigot and papermc

**Comment by SonnenPingu** [comment]
```diff
- [Thu 14:00:11 ERROR org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec] Error encoding packet LevelSoundEvent2Packet(sound=TABLE_USE, position=(-725.5, 63.5, 388.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
org.cloudburstmc.protocol.bedrock.codec.PacketSerializeException: Error whilst serializing LevelSoundEvent2Packet(sound=TABLE_USE, position=(-725.5, 63.5, 388.5), extraData=-1, identifier=:, babySound=false, relativeVolumeDisabled=false)
	at Geyser-Spigot (9).jar//org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:80)
	at Geyser-Spigot (9).jar//org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:39)
	at Geyser-Spigot (9).jar//org.cloudburstmc.protocol.bedrock.netty.codec.packet.BedrockPacketCodec.encode(BedrockPacketCodec.java:19)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
	at Geyser-Spigot (9).jar//org.cloudburstmc.protocol.bedrock.BedrockPeer.onTick(BedrockPeer.java:91)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty```

**Comment by zhou-hack** [comment]
Seems like Geyser cannot transafer the correct sound id to another client.

**Comment by zhou-hack** [comment]
To Reproduce, you can make a bedrock player and a java player in a same room with a Enchant table, While someone used the table, the bug will reproduce in console, then server will crash down
