### ISSUE TITLE
Proxy spammed

### ISSUE THREAD

**Issue by Yertled** [GeyserMC/Geyser#3977]
### Describe the bug

Console on Velocity Proxy is getting spammed with: (and similar)

```
Caused by: java.lang.IllegalArgumentException: No id found for SEARCHING
--
35 | at org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:207) ~[?:?]
36 | at org.cloudburstmc.protocol.common.util.TypeMap.getId(TypeMap.java:39) ~[?:?]
37 | at org.cloudburstmc.protocol.bedrock.transformer.FlagTransformer.serialize(FlagTransformer.java:28) ~[?:?]
38 | at org.cloudburstmc.protocol.bedrock.transformer.FlagTransformer.serialize(FlagTransformer.java:14) ~[?:?]
39 | at org.cloudburstmc.protocol.bedrock.codec.v361.BedrockCodecHelper_v361.writeEntityData(BedrockCodecHelper_v361.java:104) ~[?:?]
40 | at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.SetEntityDataSerializer_v291.serialize(SetEntityDataSerializer_v291.java:19) ~[?:?]
41 | at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:13) ~[?:?]
42 | at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:9) ~[?:?]
43 | at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[?:?]
44 | ... 23 more

<!--EndFragment-->
</body>
</html>Caused by: java.lang.IllegalArgumentException: No id found for SEARCHING
        at org.cloudburstmc.protocol.common.util.Preconditions.checkArgument(Preconditions.java:207) ~[?:?]
        at org.cloudburstmc.protocol.common.util.TypeMap.getId(TypeMap.java:39) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.transformer.FlagTransformer.serialize(FlagTransformer.java:28) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.transformer.FlagTransformer.serialize(FlagTransformer.java:14) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v[36](https://mclo.gs/bhvEqS6#L36)1.BedrockCodecHelper_v361.writeEntityData(BedrockCodecHelper_v361.java:104) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v291.serializer.SetEntityDataSerializer_v291.serialize(SetEntityDataSerializer_v291.java:19) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:13) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.v557.serializer.SetEntityDataSerializer_v557.serialize(SetEntityDataSerializer_v557.java:9) ~[?:?]
        at org.cloudburstmc.protocol.bedrock.codec.BedrockCodec.tryEncode(BedrockCodec.java:78) ~[?:?]
        ... 23 more
```

### To Reproduce

No idea, boot up latest Geyser update. I suspect people emoting on bedrock? No idea.

### Expected behaviour

No spam.

### Screenshots / Videos

https://mclo.gs/bhvEqS6

### Server Version and Plugins

Geyser version 2.1.2-SNAPSHOT (git-master-340be2d) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)
Current: git-Purpur-2014 (MC: 1.20.1)*

### Geyser Dump

https://dump.geysermc.org/ptNzsCyiJjl6cKr06hFTsIzLaka5c0WZ

### Geyser Version

2.1.2-SNAPSHOT (git-master-340be2d)

**Comment by onebeastchris** [comment]
You are running one commit/version behind; this was likely fixed in the commit linked below - please update.
https://github.com/GeyserMC/Geyser/compare/340be2d...master
