### ISSUE TITLE
NPE on stale datagrams while ticking RakSessionCodec

### ISSUE THREAD

**Issue by BackSam6348** [GeyserMC/Geyser#3984]
### Describe the bug

[22:59:11 INFO] /182.219.169.17:57131에서 접속을 시도했습니다!
[22:59:26 ERROR] [/182.219.169.17:57131] Error while ticking RakSessionCodec state=CONNECTED channelActive=true
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.netty.channel.raknet.packet.RakDatagramPacket.getNextSend()" because "datagram" is null
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.sendStaleDatagrams(RakSessionCodec.java:501) ~[server.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onTick(RakSessionCodec.java:436) ~[server.jar:?]
        at org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.tryTick(RakSessionCodec.java:381) ~[server.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [server.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) [server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [server.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) [server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [server.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [server.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [server.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[22:59:26 INFO] IP /182.219.169.17 Bedrock 사용자가 사유 disconnect.lost로 인해 접속이 종료되었습니다.

### To Reproduce

I don't know the exact way.

### Expected behaviour

disconnect.lost and Error while ticking RakSessionCodec

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/47339652/b018350e-b65a-4a62-a0f8-f85f97688254)

### Server Version and Plugins

git-Purpur-2015 (MC: 1.20.1)*

[03:30:49 INFO]: Bukkit Plugins: (34):
[03:30:49 INFO]:  - AntiCheatAddition, BlockLocker, Chunky, CrazyEnvoys, dynmap, Essentials, EssentialsChat, EssentialsDiscord, EssentialsDiscordLink, floodgate
[03:30:49 INFO]:  Floodgate-Skript, FreedomChat, HeadDrop, LuckPerms, *MaxBans, OldCombatMechanics, OpenInv, *ProtocolChanger, ProtocolLib, *RealTimeWeather
[03:30:49 INFO]:  Skript, *skUtilities, spark, TabTPS, Themis, TradeSystem, Vault, ViaBackwards, ViaVersion, voicechat
[03:30:49 INFO]:  VotifierPlus, VotingPlugin, WorldBorder, WorldEdit

### Geyser Dump

https://dump.geysermc.org/AVb2YKce6PjiqdGeW4ryY9fySlrMdVs7

### Geyser Version

Geyser-Standalone 2.1.2-SNAPSHOT (git-master-c1d8009)

### Minecraft: Bedrock Edition Device/Version

1.20.10 / Mobile and Windows 10/11

**Comment by inpos** [comment]
Same issue here.
Client: Nintendo Switch version 10.20.10

**Comment by muazhari** [comment]
i have this error too, please fix it :D
```
[10:56:07 ERROR] [org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec]: [/g0:37218] Error while ticking RakSessionCodec state=CONNECTED channelActive=true
```

**Comment by onebeastchris** [comment]
Hey, please send a Geyser dump if you're still getting this issue.

To get a dump, run `geyser dump` in the server console & send the link you get here

**Comment by TycothePug** [comment]
I am also getting this issue. Here is my geyser dump: https://dump.geysermc.org/bD2X2CURWhTPzVQQu9LCsQ75EXvXa2Gr

**Comment by onebeastchris** [comment]
@TycothePug Please send a full log via mclo.gs

**Comment by onebeastchris** [comment]
Hey y'all, could you update Geyser to the latest version and see if the issue persists? we've just bumped our cloudburst network dependencies, which might resolve the issue

**Comment by onebeastchris** [comment]
Closing due to no further response.

**Comment by lodzen** [comment]
I am facing the same issues while connecting over the Swich with the latest Minecraft version 1.23.1
