### ISSUE TITLE
Update detection error

### ISSUE THREAD

**Issue by chu025** [GeyserMC/Geyser#3995]
### Describe the bug

[07:55:59] [Thread-14/ERROR]: Error whilst checking for Geyser update!
java.net.SocketTimeoutException: Connect timed out
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:532) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:637) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at org.geysermc.geyser.util.WebUtils.getJson(WebUtils.java:78) ~[%5B间歇泉%5DGeyser-Fabric.jar:?]
	at org.geysermc.geyser.util.VersionCheckUtils.lambda$checkForGeyserUpdate$0(VersionCheckUtils.java:94) ~[%5B间歇泉%5DGeyser-Fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

I am in China.

### Expected behaviour

How to turn off automatic detection of updates?

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/129959496/aee2e064-9062-422e-b658-4ce420cfc285)

### Server Version and Plugins

![image](https://github.com/GeyserMC/Geyser/assets/129959496/bcc7aed4-c9b2-4c90-99c2-7b8ef41c2570)

### Geyser Version

1.20

### Minecraft: Bedrock Edition Device/Version

1.20

**Comment by onebeastchris** [comment]
You can set `notify-on-new-bedrock-update: true` in the Geyser config to false to stop update checking.

**Comment by Chenyu550** [comment]
前几天国内确实连接很不稳定，这两天又基本正常了
