### ISSUE TITLE
Console spammed with org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.LegacyFormattingDetected

### ISSUE THREAD

**Issue by the456gamer** [GeyserMC/Geyser#4005]
### Describe the bug

When system property `net.kyori.adventure.text.warnWhenLegacyFormattingDetected=true`, the console is spammed when the geyser user is kicked, and custom advancements (with coloured text/descriptions) are sent with

### To Reproduce

1. Install geyser, floodgate, a data pack with custom advancements, and a plugin that kicks the player with a component on papermc (for the adventure apis)
2. Login and get kicked
3. Note the warning + long stack trace in console

### Expected behaviour

No warning in console

### Screenshots / Videos

Relevant log (redacted)
```
[03:21:09] [Geyser Spigot connection thread-5-3/INFO]: [floodgate] Floodgate player logged in as the456gamer disconnected
[03:21:09] [Server thread/INFO]: com.mojang.authlib.GameProfile@36acdbaf[id=5f2898b3-b7a0-4ca6-9511-d82c4523505f,name=the456gamer,properties={textures=[com.mojang.authlib.properties.Property@2af392e6]},legacy=false] (/**.**.**.**:0) lost connection: You must link your Slack account to join the server!

Please run /minecraft link 09dbb4 in the #minecraft channel in the Slack (https://slack.example.com) to link your account.

This code will expire after 600 seconds.
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information. Component: TextComponentImpl{content="§r§c§lYou must link your Slack account to join the server!\n\n§r§f§lPlease run §r§6§l/minecraft link 09dbb4§r§f§l in the #minecraft channel in the Slack (https://slack.example.com) to link your account.§r§c§l\n\n§r§f§l§oThis code will expire after 600 seconds.", style=StyleImpl{obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, color=null, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl.warnWhenLegacyFormattingDetected(TextComponentImpl.java:80)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:70)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl.create(TextComponentImpl.java:55)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.Component.text(Component.java:818)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.Component.text(Component.java:805)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.disconnect(TcpSession.java:262)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.session.DownstreamSession.disconnect(DownstreamSession.java:45)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession.disconnect(GeyserSession.java:1092)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.JavaLoginDisconnectTranslator.translate(JavaLoginDisconnectTranslator.java:66)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.JavaLoginDisconnectTranslator.translate(JavaLoginDisconnectTranslator.java:42)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:87)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:65)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession$1.packetReceived(GeyserSession.java:1069)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:157)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:388)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:29)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.LegacyFormattingDetected: Legacy formatting codes have been detected in a component - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information. Component: TextComponentImpl{content="§r§c§lYou must link your Slack account to join the server!\n\n§r§f§lPlease run §r§6§l/minecraft link 09dbb4§r§f§l in the #minecraft channel in the Slack (https://slack.example.com) to link your account.§r§c§l\n\n§r§f§l§oThis code will expire after 600 seconds.", style=StyleImpl{obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, color=null, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl.warnWhenLegacyFormattingDetected(TextComponentImpl.java:80)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl.<init>(TextComponentImpl.java:70)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl.create(TextComponentImpl.java:55)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl$BuilderImpl.build(TextComponentImpl.java:164)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.TextComponentImpl$BuilderImpl.build(TextComponentImpl.java:132)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.renderer.TranslatableComponentRenderer.optionallyRenderChildrenAppendAndBuild(TranslatableComponentRenderer.java:230)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.renderer.TranslatableComponentRenderer.mergeStyleAndOptionallyDeepRender(TranslatableComponentRenderer.java:223)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.renderer.TranslatableComponentRenderer.renderText(TranslatableComponentRenderer.java:169)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.shaded.net.kyori.adventure.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:48)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.text.MessageTranslator.convertMessage(MessageTranslator.java:155)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.text.MessageTranslator.convertMessage(MessageTranslator.java:201)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession$1.disconnected(GeyserSession.java:1052)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.event.session.DisconnectedEvent.call(DisconnectedEvent.java:56)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:146)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.lambda$disconnect$1(TcpSession.java:286)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.disconnect(TcpSession.java:285)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.disconnect(TcpSession.java:272)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.disconnect(TcpSession.java:262)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.session.DownstreamSession.disconnect(DownstreamSession.java:45)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession.disconnect(GeyserSession.java:1092)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.JavaLoginDisconnectTranslator.translate(JavaLoginDisconnectTranslator.java:66)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.JavaLoginDisconnectTranslator.translate(JavaLoginDisconnectTranslator.java:42)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:87)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:65)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession$1.packetReceived(GeyserSession.java:1069)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.callPacketReceived(TcpSession.java:157)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:388)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at Geyser-Spigot.jar//com.github.steveice10.packetlib.tcp.TcpSession.channelRead0(TcpSession.java:29)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[03:21:09] [defaultEventLoopGroup-6-2/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[03:21:09] [defaultEventLoopGroup-6-2/INFO]: [Geyser-Spigot] <bedrock username> has disconnected from the Java server because of §r§c§lYou must link your Slack account to join the server!

§r§f§lPlease run §r§6§l/minecraft link 09dbb4§r§f§l in the #minecraft channel in the Slack (https://slack.example.com) to link your account.§r§c§l

§r§f§l§oThis code will expire after 600 seconds.
```

### Server Version and Plugins

Paper version git-Paper-550 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

[ViaVersion] Loading server plugin ViaVersion v4.7.1-SNAPSHOT

floodgate v2.2.2-SNAPSHOT (b59-2278589)

UltimateAdvancementAPI v2.2.5

HCCore v1.10.0-dev.2.uncommitted+9521fc4 (custom)

ProtocolLib] Enabling ProtocolLib v5.0.0

### Geyser Dump

unfortunately I have already stopped the server and am on mobile atm

### Geyser Version

Geyser version 2.1.2-SNAPSHOT (git-master-ea2bac4)

### Minecraft: Bedrock Edition Device/Version

1.20.12 android

### Additional Context

It still works fine including colours (it's just a warning)
I'm on mobile, so information may not be 100% accurate

**Comment by Camotoy** [comment]
It seems like Adventure now has system properties definable per-plugin? So we might be able to fix this by silencing the error (which is fine for us to do - we can't control that Components are created with legacy formatting since they come from the server). Low-priority fix though since there is a workaround.

**Comment by Konicai** [comment]
They also mentioned in Discord
> using the run-server task in ide sets the system property net.kyori.adventure.text.warnWhenLegacyFormattingDetected by default

**Comment by onebeastchris** [comment]
Not setting the property seems to be the only way to not get warnings - there doesn't seem to be any per-plugin configuration there that would allow suppressing the errors for just Geyser
See [here (kyori discord) for reference:](https://discord.com/channels/319355592605040642/923037274176913409/1169983646673936495)

Closing this since we can't really do anything here
