### ISSUE TITLE
NPE on ClientboundAnimatePacket due to null `animation`

### ISSUE THREAD

**Issue by AlekseyTitov99** [GeyserMC/Geyser#4023]
### Describe the bug

We are getting spammed with an error that is causing our server to run out of memory and crash.

[13:26:06.408 Geyser player thread-4-2/ERROR] Could not translate packet ClientboundAnimatePacket
java.lang.NullPointerException: Cannot invoke "com.github.steveice10.mc.protocol.data.game.entity.player.Animation.ordinal()" because the return value of "com.github.steveice10.mc.protocol.packet.ingame.clientbound.entity.ClientboundAnimatePacket.getAnimation()" is null
	at org.geysermc.geyser.translator.protocol.java.entity.JavaAnimateTranslator.translate(JavaAnimateTranslator.java:52) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.entity.JavaAnimateTranslator.translate(JavaAnimateTranslator.java:41) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:87) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13:26:06.657 Geyser player thread-4-2/ERROR] Could not translate packet ClientboundAnimatePacket
java.lang.NullPointerException: Cannot invoke "com.github.steveice10.mc.protocol.data.game.entity.player.Animation.ordinal()" because the return value of "com.github.steveice10.mc.protocol.packet.ingame.clientbound.entity.ClientboundAnimatePacket.getAnimation()" is null
	at org.geysermc.geyser.translator.protocol.java.entity.JavaAnimateTranslator.translate(JavaAnimateTranslator.java:52) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.entity.JavaAnimateTranslator.translate(JavaAnimateTranslator.java:41) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:87) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67) ~[Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [Geyser-Standalone.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

### To Reproduce

Happens when specific players login, not too sure which ones.

### Expected behaviour

Not error

### Server Version and Plugins

[14:46:31 INFO] This server is running Geyser version 2.1.2-SNAPSHOT (git-master-7725651) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

Standalone

### Geyser Dump

 https://dump.geysermc.org/OhiCEAeC4L6lgyzo9eD0wt8AH6vEABd8

### Geyser Version

2.1.2-SNAPSHOT (git-master-7725651)

**Comment by Konicai** [comment]
Your server is sending a ClientboundAnimatePacket with an invalid animation ID. The vanilla java client handles this gracefully though, so this will be fixed.
