### ISSUE TITLE
Could not pass event AsyncPlayerSendCommandsEvent to Geyser-Spigot v2.1.2-SNAPSHOT 

### ISSUE THREAD

**Issue by CrazzyGamesBR** [GeyserMC/Geyser#4075]
### Describe the bug

When a player enters the server or console for the first time, the following error is triggered:

[13:52:57 ERROR]: Could not pass event AsyncPlayerSendCommandsEvent to Geyser-Spigot v2.2.0-SNAPSHOT
java.util.ConcurrentModificationException: null
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]
        at java.util.TreeMap$ValueIterator.next(TreeMap.java:1531) ~[?:?]
        at org.geysermc.geyser.platform.spigot.command.GeyserPaperCommandListener.onCommandSend(GeyserPaperCommandListener.java:56) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1184.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.CommandDispatcher.sendAsync(CommandDispatcher.java:368) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.CommandDispatcher.lambda$a$4(CommandDispatcher.java:344) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

### To Reproduce

1. Login to the server with a new account, it has to be the first login
2. Watch the error appear in the console

### Expected behaviour

This error should not appear in the console

### Screenshots / Videos

![evidency](https://github.com/GeyserMC/Geyser/assets/79768367/dc156f08-2a8b-4e89-b87e-b908a707a646)

### Server Version and Plugins

[14:05:05 INFO]: This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Error obtaining version information
Previous version: git-Airplane-4 (MC: 1.16.5)

### Geyser Dump

https://dump.geysermc.org/Bc5hPrNdMQJU7sa7P6rreSzy0Zyz4P4O

### Geyser Version

This server is running Geyser version 2.2.0-SNAPSHOT (git-master-9ddfdf9) (Java: 1.20, Bedrock: 1.19.80/1.19.81 - 1.20.10)

### Minecraft: Bedrock Edition Device/Version

1.16.5 with viaversion

**Comment by Kas-tle** [comment]
Please try removing all plugins and see if the issue persists.

**Comment by CrazzyGamesBR** [comment]
Removing all plugins is not feasible, I removed all the last ones added and the problem persists, is there any other way?

**Comment by Kas-tle** [comment]
No given that it could be caused by one of your plugins that's needed to isolate the issue.

**Comment by onebeastchris** [comment]
Closing due to not enough information to debug this further (and no response). If you can isolate the plugin that causes the issue, feel free to reopen this issue/create a new one - with the amount of plugins you are using, it is unfeasible for us to debug this.
