### ISSUE TITLE
Couldn't pass ListenerBoundEvent to geyser on Geyser

### ISSUE THREAD

**Issue by SolarBAM404** [GeyserMC/Geyser#4077]
### Describe the bug

```
[17:06:04 ERROR]: Couldn't pass ListenerBoundEvent to geyser
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.event.HoverEvent$ShowEntity net.kyori.adventure.text.event.HoverEvent$ShowEntity.showEntity(net.kyori.adventure.key.Key, java.util.UUID)'
        at org.geysermc.geyser.text.DummyLegacyHoverEventSerializer.<init>(DummyLegacyHoverEventSerializer.java:43) ~[?:?]
        at org.geysermc.geyser.translator.text.MessageTranslator.<clinit>(MessageTranslator.java:95) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:198) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:713) ~[?:?]
        at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.postStartup(GeyserVelocityPlugin.java:130) ~[?:?]
        at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onProxyBound(GeyserVelocityPlugin.java:201) ~[?:?]
        at org.geysermc.geyser.platform.velocity.Lmbda$6.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

This error appears just after geyser register a bunch of stuff

### To Reproduce

Just start the server.

### Expected behaviour

The plugin to show that it has completed loaded and allowing bedrock users to join

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT 
floodgate 2.2.2-SNAPSHOT (b59-2278589)

### Geyser Version

2.2.0-SNAPSHOT (git-master-9ddfdf9)

**Comment by onebeastchris** [comment]
Update Velocity; we use an updated version of the adventure library, which Velocity only recently started using.
