### ISSUE TITLE
Players cannot see blocks

### ISSUE THREAD

**Issue by Jeffrey131313** [GeyserMC/Geyser#4084]
### Describe the bug

When I used coreprotect to restore the world, the bedrock version players were unable to see the restored blocks, while the Java version had no problems

### To Reproduce

co rollback r:20 t:8h

### Expected behaviour

Players cannot see blocks

### Screenshots / Videos

![Screenshot_2023-08-27-19-40-38-739_com mojang min](https://github.com/GeyserMC/Geyser/assets/78954987/ae3fbfd3-31f4-48f9-bb3d-4c830a0c99bc)
![Q74})EBA5BS{4PIF1G7X82W](https://github.com/GeyserMC/Geyser/assets/78954987/178d17a1-447e-45de-a731-b213afaecd1a)
![)JNMSX4}VU17%OAGIG C~PS](https://github.com/GeyserMC/Geyser/assets/78954987/a9ed5b29-1757-417a-8e8a-81fabe11cacc)

### Geyser Dump

https://dump.geysermc.org/bTeNce51TsX2QKQ0msF1aw2N9rjzKIGQ

### Geyser Version

2.2.0-SNAPSHOT (git-master-9ddfdf9)

### Minecraft: Bedrock Edition Device/Version

1.20.15.01, Android

### Additional Context

[19:36:36 WARN]: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "texturesProperty" is null
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.session.cache.SkullCache.putSkull(SkullCache.java:85)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.level.block.entity.SkullBlockEntityTranslator.translateSkull(SkullBlockEntityTranslator.java:110)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:426)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:84)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:87)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[19:36:36 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[19:36:36 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[19:36:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:36:36 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:36:36 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[19:36:36 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[19:36:36 WARN]: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "texturesProperty" is null
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.session.cache.SkullCache.putSkull(SkullCache.java:85)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.level.block.entity.SkullBlockEntityTranslator.translateSkull(SkullBlockEntityTranslator.java:110)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:426)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:84)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:87)
[19:36:36 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:67)
[19:36:36 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[19:36:36 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[19:36:36 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:36:36 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:36:36 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[19:36:36 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Jeffrey131313** [comment]
In Screenshots, the screenshot of the Java version is located in the same location as the screenshot of the bedrock version, which is completely invisible

**Comment by onebeastchris** [comment]
Please try updating Geyser to the latest master build, the PR for custom blocks was merged into Geyser - and I believe the issue if chunks being not loaded due to corrupt/broken skulls is fixed anyways

**Comment by Jeffrey131313** [comment]
> Please try updating Geyser to the latest master build, the PR for custom blocks was merged into Geyser - and I believe the issue if chunks being not loaded due to corrupt/broken skulls is fixed anyways请尝试更新间歇泉到最新的主构建，自定义块的PR被合并到间歇泉中-我相信如果块由于损坏/破碎的头骨而未加载的问题无论如何都是固定的

I have updated to the latest geyser
https://dump.geysermc.org/8JSF5FUoZwn4z9ifmkzT7Z9LzQR4th9q
![image](https://github.com/GeyserMC/Geyser/assets/78954987/0e05681d-9a77-4ee6-bb7e-0e72d38c4152)

**Comment by onebeastchris** [comment]
The dump you've sent is not the main branch, please download Geyser from [here](http://download.geysermc.org/) - we don't provide support for custom forks.
Additionally, please send the full latest.log via mclo.gs and send the link here

**Comment by Jeffrey131313** [comment]
> The dump you've sent is not the main branch, please download Geyser from [here](http://download.geysermc.org/) - we don't provide support for custom forks. Additionally, please send the full latest.log via mclo.gs and send the link here
> 
> 
> 您发送的转储不是主分支，请从[这里](http://download.geysermc.org/)下载Geyser-我们不提供自定义分支支持。 此外，请通过mclo.gs发送完整的latest.log，并在此处发送链接

https://mclo.gs/SWQu0Y8

**Comment by onebeastchris** [comment]
Could you run `geyser dump logs` in the console and send the link you get here? That would include a dump and a log with all needed info
