### ISSUE TITLE
ClientboundContainerClosePacket (cant connect after this error)

### ISSUE THREAD

**Issue by Razlousek** [GeyserMC/Geyser#4141]
### Describe the bug

```
[07:10:56] [Geyser player thread-4-6/WARN] [Geyser-BungeeCord]: Selhalo přeložení paketu ClientboundContainerClosePacket
java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @700f518a)
	at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:154) ~[?:?]
	at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:123) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at java.lang.Thread.run(Unknown Source) [?:?]
[07:10:56] [Geyser player thread-4-6/ERROR]: java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @700f518a)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:154)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:123)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[07:10:56] [Geyser player thread-4-6/WARN] [Geyser-BungeeCord]: Selhalo přeložení paketu ClientboundContainerClosePacket
java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @700f518a)
	at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:154) ~[?:?]
	at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:123) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall-1.20-536.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at java.lang.Thread.run(Unknown Source) [?:?]
[07:10:56] [Geyser player thread-4-6/ERROR]: java.lang.ClassCastException: class org.geysermc.geyser.inventory.PlayerInventory cannot be cast to class org.geysermc.geyser.inventory.Container (org.geysermc.geyser.inventory.PlayerInventory and org.geysermc.geyser.inventory.Container are in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @700f518a)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.translator.inventory.chest.DoubleChestInventoryTranslator.closeInventory(DoubleChestInventoryTranslator.java:154)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.util.InventoryUtils.closeInventory(InventoryUtils.java:123)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:41)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerCloseTranslator.translate(JavaContainerCloseTranslator.java:34)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[07:10:56] [Geyser player thread-4-6/ERROR]: 	at java.base/java.lang.Thread.run(Unknown Source)
```

### To Reproduce

1. Join with bedrock on lobby server
2. From lobby join to other servers

### Expected behaviour

After restart Bungee is working all good, but after error no one can connect, its only saying "Locating world". We try lower mtu number, but without fix
 

### Screenshots / Videos

-

### Server Version and Plugins

![obrazek](https://github.com/GeyserMC/Geyser/assets/95584870/d59d7992-9e55-431d-a516-abe9fd4efc8e)

### Geyser Dump

https://dump.geysermc.org/dWu1kJUTj71xAy0K4j093d64CvrMH5jU

### Geyser Version

Latest (from 20/9/2023)

### Minecraft: Bedrock Edition Device/Version

1.20.30 but no one cant connect from android, ios, win10

**Comment by onebeastchris** [comment]
Please try updating Geyser to the latest version - if you continue to see this error, please enable `debug-mode` in the Geyser config, restart the server/reload Geyser to apply the change, and send a log via `mclo.gs` with the error.

**Comment by Kas-tle** [comment]
Closing this issue as it does not have specific reproduction steps. If you are still experiencing this issue, please follow the steps below to determine the minimum plugin setup required to reproduce this issue and specifying this in the new issue:
- Temporarily removing/moving half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find the problematic plugin.
