### ISSUE TITLE
Question:После перезагрузки плагина он выключается Velocity

### ISSUE THREAD

**Issue by MootComb9620292** [GeyserMC/Geyser#4152]
Question on: _docs/geyser/common-issues.md
[21:44:28 INFO]: Перезагрузка конфигураций Geyser... все подключенные клиенты bedrock будут отключены.
[21:44:28 INFO] [geyser]: Выключение Geyser.
[21:44:28 INFO] [geyser]: Geyser успешно выключен.
[21:44:28 INFO] [geyser]: The skin uploader has been closed
[21:44:30 ERROR]: Invalid number found for Geyser remote port in config!
[21:44:31 INFO]: Exception occurred while running command for MootComb9620292
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command geyser for [connected player] MootComb9620292 (/94.140.135.137:8584)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command geyser for [connected player] MootComb9620292 (/94.140.135.137:8584)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:239) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:264) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.command.GeyserCommand.execute(org.geysermc.geyser.session.GeyserSession, org.geysermc.geyser.command.GeyserCommandSource, String[])" because the return value of "org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.getCommand(String)" is null
        at org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.execute(GeyserVelocityCommandExecutor.java:71) ~[?:?]
        at org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.execute(GeyserVelocityCommandExecutor.java:43) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:264) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/issues/3788
Known issue.
In the future, please open issues in english - additionally, to openiny issues on the right repository (aka GeyserMC/Geyser instead of our wiki, GeyserMC/Geyser). Thanks!
