### ISSUE TITLE
Reloading Geyser Velocity doesn't work

### ISSUE THREAD

**Issue by MootComb9620292** [GeyserMC/Geyser#4153]
Question on: _docs/geyser/fixing-unable-to-connect-to-world.md
```
[09:36:46 ERROR]: An error occurred while running this command.
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command geyser for com.velocitypowered.proxy.console.VelocityConsole@37ee71f0
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command geyser for com.velocitypowered.proxy.console.VelocityConsole@37ee71f0
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:239) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:253) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.command.GeyserCommand.execute(org.geysermc.geyser.session.GeyserSession, org.geysermc.geyser.command.GeyserCommandSource, String[])" because the return value of "org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.getCommand(String)" is null
        at org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.execute(GeyserVelocityCommandExecutor.java:71) ~[?:?]
        at org.geysermc.geyser.platform.velocity.command.GeyserVelocityCommandExecutor.execute(GeyserVelocityCommandExecutor.java:43) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:226) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:253) ~[server.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        ... 4 more
```

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/issues/3788
Known issue, closing as duplicate.

For the meantime, restart the Velocity proxy instead of using `/geyser reload`.
In, please open issues on the right repository (aka GeyserMC/Geyser instead of our wiki, GeyserMC/Geyser). Thanks!
