### ISSUE TITLE
Protocol can no longer handle custom packets

### ISSUE THREAD

**Issue by ImDaBigBoss** [GeyserMC/Geyser#4167]
### Describe the bug

I have a pretty complicated server setup, with a Velocity proxy for Java and a WaterdogPE proxy for bedrock. Geyser is running on the Fabric 1.20.2 backends. Ever since I updated to 1.20.2 from 1.20.1, bedrock players can't join because of this error:
```
[08:55:01] [epollEventLoopGroup-3-1/INFO]: /192.168.96.2:47022 tried to connect!
[08:55:02] [epollEventLoopGroup-3-2/INFO]: Is player data signed? false
[08:55:02] [epollEventLoopGroup-3-2/INFO]: Could not find packet for ClientToServerHandshakePacket
[08:55:02] [epollEventLoopGroup-3-2/INFO]: Could not find packet for ClientCacheStatusPacket
[08:55:02] [epollEventLoopGroup-3-2/INFO]: Player connected with username .imdabigboss
[08:55:02] [tcpClientSession-5-1/INFO]: .imdabigboss (logged in as: .imdabigboss) has connected to remote java server on address 192.168.96.4
[08:55:02] [tcpClientSession-5-1/INFO]: Downloading and loading locale: en_us
[08:55:02] [tcpClientSession-5-1/INFO]: Could not find packet for ClientboundLoginCompressionPacket
[08:55:02] [tcpClientSession-5-1/WARN]: Downstream packet error! Cannot read the array length because "src" is null
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]: java.lang.NullPointerException: Cannot read the array length because "src" is null
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1081)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at com.github.steveice10.mc.protocol.packet.login.serverbound.ServerboundCustomQueryAnswerPacket.serialize(ServerboundCustomQueryAnswerPacket.java:29)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at com.github.steveice10.mc.protocol.codec.MinecraftPacketSerializer.serialize(MinecraftPacketSerializer.java:16)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at com.github.steveice10.mc.protocol.codec.MinecraftPacketSerializer.serialize(MinecraftPacketSerializer.java:10)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:36)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at com.github.steveice10.packetlib.tcp.TcpPacketCodec.encode(TcpPacketCodec.java:15)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.handler.codec.ByteToMessageCodec$Encoder.encode(ByteToMessageCodec.java:172)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.handler.codec.ByteToMessageCodec.write(ByteToMessageCodec.java:108)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:252)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at org.geysermc.geyser.session.DownstreamSession.sendPacket(DownstreamSession.java:41)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at org.geysermc.geyser.session.GeyserSession.sendDownstreamPacket0(GeyserSession.java:1670)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at org.geysermc.geyser.session.GeyserSession.lambda$sendDownstreamPacket$9(GeyserSession.java:1662)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[08:55:02] [tcpClientSession-5-1/INFO]: [STDERR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[08:55:32] [Server thread/INFO]: Disconnecting .imdabigboss (/192.168.96.4:42343): Took too long to log in
[08:55:32] [Server thread/INFO]: .imdabigboss (/192.168.96.4:42343) lost connection: Took too long to log in
[08:55:32] [tcpClientSession-5-1/INFO]: .imdabigboss has disconnected from remote Java server on address 192.168.96.4 because of Took too long to log in
[08:55:32] [Server thread/WARN]: handleDisconnection() called twice
```

### What I've figured out

**I've now found out the reason for this error**, it's due to the custom velocity packet being sent by the Fabric server asking for some information about players. [See here](https://github.com/ImDaBigBoss/FabricProxy-Lite-Geyser/blob/8c02f22fafcad5e41acd30f10a799a9eca2dbcdf/src/main/java/one/oktw/FabricProxyLite.java#L57). This used to be handled fine by MCProtocol, but for some reason, with the update, it isn't.

### To Reproduce

1. Get a build of [WaterdogPE](https://github.com/WaterdogPE/WaterdogPE), and prepare for one backend server.
2. Setup a backend Fabric server **with 1.20.2**.
3. Install the latest Geyser build as a Fabric mod for the backend server.
4. Install [my fork of FabricProxy-Lite](https://github.com/ImDaBigBoss/FabricProxy-Lite-Geyser) with default config options, allowing bedrock players to join (on my setup server, it also handles skins, but that's beside the point).
5. Attempt to join the network, and you should see the error when the client gives up trying to connect.

### Expected behaviour

In theory, it should be expected to continue doing as before, not creating errors that stop the players from joining.

### Geyser Dump

https://dump.geysermc.org/2pnpncGfZpCT1ZOS22MzVyE80QLxX7Ph

### Geyser Version

2.2.0-SNAPSHOT (git-master-34ff8c1)

### Additional Context

If you try joining that same network setup with Java (through velocity with ViaVersion), nothing happens at all for a bit until the client gives up joining.

**Comment by ImDaBigBoss** [comment]
Update: I've got [a fix](https://github.com/ImDaBigBoss/FabricProxy-Lite/blob/5e2a58fead3fded58be74fe177259ce0edff3baf/src/main/java/one/oktw/FabricProxyLite.java#L36) on the mod's end. It means that there's not even a packet sent anymore.
