### ISSUE TITLE
It seems can not register Block Item for NonVanillaBlock

### ISSUE THREAD

**Issue by PengLx** [GeyserMC/Geyser#4174]
### Describe the bug

I write a block for my project.
```
CustomBlockComponents components = CustomBlockComponents.builder()
                .materialInstance("up", MaterialInstance.builder().texture("starsnature-baobab_log_top").renderMethod("opaque").ambientOcclusion(true).faceDimming(true).build())
                .materialInstance("down", MaterialInstance.builder().texture("starsnature-baobab_log_top").renderMethod("opaque").ambientOcclusion(true).faceDimming(true).build())
                .materialInstance("north", MaterialInstance.builder().texture("starsnature-baobab_log").renderMethod("opaque").ambientOcclusion(true).faceDimming(true).build())
                .materialInstance("south", MaterialInstance.builder().texture("starsnature-baobab_log").renderMethod("opaque").ambientOcclusion(true).faceDimming(true).build())
                .materialInstance("east", MaterialInstance.builder().texture("starsnature-baobab_log").renderMethod("opaque").ambientOcclusion(true).faceDimming(true).build())
                .materialInstance("west", MaterialInstance.builder().texture("starsnature-baobab_log").renderMethod("opaque").ambientOcclusion(true).faceDimming(true).build())
                .tags(Collections.emptySet())
                .lightEmission(0)
                .placeAir(false)
                .lightDampening(0)
                .friction(1f)
                .unitCube(true)
                .build();

        NonVanillaCustomBlockData block = NonVanillaCustomBlockData.builder()
                .name("acacia_planks_carved")
                .components(components)
                .permutations(Collections.emptyList())
                .creativeCategory(CreativeCategory.CONSTRUCTION)
                .namespace(StarsNature.NAMESPACE + ":baobab_log")
                .build();

        event.register(block);
        event.registerOverride(
                JavaBlockState.builder()
                        .identifier(StarsNature.NAMESPACE + ":baobab_log")
                        .javaId(Blocks.getId(StarsNature.NAMESPACE,"baobab_log"))
                        .build(),
                block.defaultBlockState()
        );
        event.registerItemOverride(StarsNature.NAMESPACE+":baobab_log", block);
```
And it true registered a block in game and I can see the block in bedrock minecraft game.
But I can not see my items in game. And got error in conolse
```
[09:44:12 WARN]: [Geyser-Spigot] 无法翻译数据包 ClientboundContainerSetSlotPacket
java.lang.IndexOutOfBoundsException: Index 1255 out of bounds for length 1255
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at org.geysermc.geyser.inventory.GeyserItemStack.asItem(GeyserItemStack.java:119) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.inventory.item.ItemTranslator.getBedrockItemDefinition(ItemTranslator.java:392) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.inventory.Inventory.updateItemNetId(Inventory.java:153) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.inventory.Inventory.setItem(Inventory.java:135) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:98) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:54) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:44:12 WARN]: java.lang.IndexOutOfBoundsException: Index 1255 out of bounds for length 1255
[09:44:12 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[09:44:12 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[09:44:12 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[09:44:12 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[09:44:12 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.inventory.GeyserItemStack.asItem(GeyserItemStack.java:119)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.item.ItemTranslator.getBedrockItemDefinition(ItemTranslator.java:392)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.inventory.Inventory.updateItemNetId(Inventory.java:153)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.inventory.Inventory.setItem(Inventory.java:135)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:98)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:54)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[09:44:12 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[09:44:12 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[09:44:12 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[09:44:12 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[09:44:12 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:44:12 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[09:44:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

or other items
```
[09:46:03 INFO]: Gave 1 [block.starsnature.baobab_leaves] to Peng_Lx
[09:46:03 WARN]: [Geyser-Spigot] 无法翻译数据包 ClientboundContainerSetSlotPacket
java.lang.IndexOutOfBoundsException: Index 1258 out of bounds for length 1255
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at org.geysermc.geyser.inventory.GeyserItemStack.asItem(GeyserItemStack.java:119) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.inventory.item.ItemTranslator.getBedrockItemDefinition(ItemTranslator.java:392) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.inventory.Inventory.updateItemNetId(Inventory.java:153) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.inventory.Inventory.setItem(Inventory.java:135) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:98) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:54) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[Geyser-Spigot.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:46:03 WARN]: java.lang.IndexOutOfBoundsException: Index 1258 out of bounds for length 1255
[09:46:03 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[09:46:03 WARN]:        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[09:46:03 WARN]:        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
[09:46:03 WARN]:        at java.base/java.util.Objects.checkIndex(Objects.java:359)
[09:46:03 WARN]:        at java.base/java.util.ArrayList.get(ArrayList.java:427)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.inventory.GeyserItemStack.asItem(GeyserItemStack.java:119)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.item.ItemTranslator.getBedrockItemDefinition(ItemTranslator.java:392)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.inventory.Inventory.updateItemNetId(Inventory.java:153)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.inventory.Inventory.setItem(Inventory.java:135)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:98)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.java.inventory.JavaContainerSetSlotTranslator.translate(JavaContainerSetSlotTranslator.java:54)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[09:46:03 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[09:46:03 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[09:46:03 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[09:46:03 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[09:46:03 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[09:46:03 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[09:46:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

1. Write a NonVanillaCustomBlockData
2. register Block
3. register Override for non vannilla block
4. register Item override

### Expected behaviour

It should can transalte packet for bedrock version

### Server Version and Plugins

This server is running Paper version git-Paper-207 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 38376f4)
You are running the latest version

I used NMS to register Block and Items, so it is non vanilla block and do not use fabric

### Geyser Dump

https://dump.geysermc.org/dDAvKUQTGmIQuFHcbVWczt5DZku4r4ZR

### Geyser Version

2.2.0-SNAPSHOT (git-master-be5b437)

### Minecraft: Bedrock Edition Device/Version

1.20.30

**Comment by Kas-tle** [comment]
Hello, registerItemOverride is not really intended for use with modded blocks. Its purpose is to allow the override of existing vanilla items in inventory with the specified custom block rather than the vanilla block. But given that a modded block has been added by you anyways, there is no reason to do this as the modded block you registered is what will be displayed anyways.
