### ISSUE TITLE
Unable to join server

### ISSUE THREAD

**Issue by linj80912** [GeyserMC/Geyser#4202]
### Describe the bug
[01:18:52 WARN]: Failed to initialize a channel. Closing: org.geysermc.geyser.network.netty.ChannelWrapper@4f504c4c
java.lang.IllegalArgumentException: Duplicate handler name: via-encoder
	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at com.viaversion.viaversion.bukkit.handlers.BukkitChannelInitializer.afterChannelInitialize(BukkitChannelInitializer.java:88) ~[?:?]
	at com.viaversion.viaversion.bukkit.handlers.BukkitChannelInitializer.initChannel(BukkitChannelInitializer.java:75) ~[?:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[01:18:52 WARN]: java.nio.channels.ClosedChannelException
[01:17:27 WARN]: 	at io.netty.channel.local.LocalChannel.doWrite(LocalChannel.java:368)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895)
[01:17:27 WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
[01:17:27 WARN]: 	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[01:17:27 WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[01:17:27 WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:254)
[01:17:27 WARN]: 	at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:158)
[01:17:27 WARN]: 	at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
[01:17:27 WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:150)
[01:17:27 WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:365)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:262)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[01:17:27 WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
[01:17:27 WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
[01:17:27 WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
[01:17:27 WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
[01:17:27 WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
[01:17:27 WARN]: 	at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:185)
[01:17:27 WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[01:17:27 WARN]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[01:17:27 WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[01:17:27 WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[01:17:27 WARN]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[01:17:27 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)

### To Reproduce

join my server
see error java.nio.channels.ClosedChannelException

### Expected behaviour

join server successfully

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/91480551/c5e2043d-8cf8-4852-8a67-67325fa8a719)

### Server Version and Plugins

spigot 1.20.2
latest geyser
latest floodgate
viaversion 4.8.1

### Geyser Dump

https://dump.geysermc.org/zU8sLz2PpC8wVgenUpopqTB7eCbgLRcb

### Geyser Version

2.2.0-SNAPSHOT (git-master-3f0e366)

### Minecraft: Bedrock Edition Device/Version

windows/1.20.32

**Comment by onebeastchris** [comment]
Please send a full log via mclo.gs

**Comment by onebeastchris** [comment]
Can you send it via https://mcpaste.io/ instead?
Maybe that one works for you

**Comment by linj80912** [comment]
https://mcpaste.io/92dcae79b2bda66b

**Comment by onebeastchris** [comment]
This looks like a ViaVersion issue, looks like it registers a duplicate via-encoder handler. As a workaround, try using Paper instead of spigot; but ultimately, this is likely a Viaversion issue :/
