### ISSUE TITLE
Getting "An exceptionCaught() event was fired.... Index 0 out of bounds for length 0.." on velocity With MiniMOTD plugin and MOTD pass through enabled

### ISSUE THREAD

**Issue by c00ldude1oo** [GeyserMC/Geyser#4223]
### Describe the bug

I just swapped to velocity from waterfall, and I am getting this error as soon as velocity finishes starting. It happens every minute or so to every other second. When a bedrock player is online, it sends it every 5-10 sec

**after adding and removing plugins, i found that when having minimodt and geyser installed is when it happens**

```
[11:45:53] [epollEventLoopGroup-7-1/WARN] [io.netty.channel.DefaultChannelPipeline]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.geysermc.geyser.network.netty.GeyserServer.onQuery(GeyserServer.java:246) ~[?:?]
	at org.geysermc.geyser.network.netty.handler.RakPingHandler.channelRead0(RakPingHandler.java:48) ~[?:?]
	at org.geysermc.geyser.network.netty.handler.RakPingHandler.channelRead0(RakPingHandler.java:37) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.onUnconnectedPing(RakServerOfflineHandler.java:112) ~[?:?]
	at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(RakServerOfflineHandler.java:96) ~[?:?]
	at org.cloudburstmc.netty.handler.codec.raknet.server.RakServerOfflineHandler.channelRead0(RakServerOfflineHandler.java:43) ~[?:?]
	at org.cloudburstmc.netty.handler.codec.raknet.AdvancedChannelInboundHandler.channelRead(AdvancedChannelInboundHandler.java:45) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at org.geysermc.geyser.network.netty.handler.RakConnectionRequestHandler.channelRead(RakConnectionRequestHandler.java:80) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(ProxyInboundRouter.java:66) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:662) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:697) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:56) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:536) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-SNAPSHOT-276.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### To Reproduce

Start server

### Expected behaviour

no error

### Server Version and Plugins

Velocity 3.2.0-SNAPSHOT (git-81b183ac-b276)

floodgate 2.2.2-SNAPSHOT (b85-71acc6c)

Geyser-Velocity 2.2.0-SNAPSHOT (git-master-6b67e43)

MiniMOTD 2.0.14

PlasmoVoice 2.0.7

pv-addon-groups 1.0.3

spark 1.10.55

### Geyser Dump

https://dump.geysermc.org/dwYWMtaCC04O6FUw90VR9IKB77G0T9kO

### Geyser Version

2.2.0-SNAPSHOT (git-master-6b67e43)

### Additional Context

It does not happen with geyser and flood gate removed

and it doesn't happen with just floodgate & geyser

**Comment by Kas-tle** [comment]
Please try without the voice plugin.

**Comment by Kas-tle** [comment]
In that case try disabling MOTD pass through in the Geyser config.

**Comment by Kas-tle** [comment]
Ok, so it's the voice plugin

**Comment by onebeastchris** [comment]
Is your MOTD empty by chance?
If yes, i could see [this](https://github.com/GeyserMC/Geyser/blob/8d2ebcf69bee0b329c6c748845113836f160319e/core/src/main/java/org/geysermc/geyser/network/netty/GeyserServer.java#L247-L249) failing due to the spli() function returning an empty array.

**Comment by onebeastchris** [comment]
Thanks for testing :)
Once https://github.com/GeyserMC/Geyser/pull/4259 builds, can you try using the Geyser-Velocity artifact found under "Checks" and see if that resolves the issue?

**Comment by onebeastchris** [comment]
Pushed a new commit to the PR, please try that one once it builds.
Should fix this issue, and fallback to config values when e.g. MiniMOTD is hiding player counts

**Comment by onebeastchris** [comment]
fixed that one already, wait for the new build

**Comment by onebeastchris** [comment]
Sure, you can do that for now. Once the PR is merged, you should start using the main builds found on https://geysermc.org/download though :)
