### ISSUE TITLE
User cannot join

### ISSUE THREAD

**Issue by gamingcodedev** [GeyserMC/Geyser#4225]
### Describe the bug

Handy version can't join and java 1.20.2 as well

### To Reproduce

Start Minecraft Pocket or Java 1.20.2
Try to join the network

### Expected behaviour

Joinable

### Screenshots / Videos

[18:13:58 ERROR]: [connected player] louisde193 (/188.210.57.46:0): exception encountered in com.velocitypowered.proxy.connection.client.AuthSessionHandler@115d4ca0
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.chat.SystemChat in CLIENTBOUND protocol 1.20.2 phase LOGIN
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Unable to find id for packet of type com.velocitypowered.proxy.protocol.packet.chat.SystemChat in CLIENTBOUND protocol 1.20.2 phase LOGIN
        at com.velocitypowered.proxy.protocol.StateRegistry$PacketRegistry$ProtocolRegistry.getPacketId(StateRegistry.java:697) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:52) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        ... 11 more

### Server Version and Plugins

None other

### Geyser Version

newest from 15.10.2023

**Comment by onebeastchris** [comment]
This is a velocity error, not a Geyser one. Some plugin you have is trying to send a client bound system chat packet while the client is in the login phase - this should never happen. Try removing your plugins on the proxy/backends one by one until you find the one sending a system chat packet during login; and contact that plugin author.

**Comment by gamingcodedev** [comment]
This issue is based of floodgate for velocity if i remove this everything is working...
