### ISSUE TITLE
players cannot log in without java and bedrock

### ISSUE THREAD

**Issue by nikitaku221** [GeyserMC/Geyser#4251]
### Describe the bug

when a player logs in from any client, he is kicked and spammed with an error

### To Reproduce

Don't know

### Expected behaviour

for the player to log in, enter the password and continue playing

### Screenshots / Videos

[23:35:58 ERROR]: java.lang.reflect.InvocationTargetException
[23:35:58 ERROR]:       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[23:35:58 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[23:35:58 ERROR]:       at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[23:35:58 ERROR]:       at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[23:35:58 ERROR]:       at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[23:35:58 ERROR]:       at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[23:35:58 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[23:35:58 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[23:35:58 ERROR]:       at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[23:35:58 ERROR]:       at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[23:35:58 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[23:35:58 ERROR]:       at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[23:35:58 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[23:35:58 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[23:35:58 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[23:35:58 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[23:35:58 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[23:35:58 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:35:58 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[23:35:58 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:35:58 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:35:58 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23:35:58 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1589)
[23:35:58 ERROR]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[23:35:58 ERROR]:       at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[23:35:58 ERROR]:       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[23:35:58 ERROR]:       ... 22 more

### Server Version and Plugins

I don't know the exact version. but I can tell you when I downloaded it. 20.15
10/28/23
Geyser and floodgate
velocity core.

### Geyser Dump

https://dump.geysermc.org/ZlYpTPNoEecK6OTROj2n5ZEMgxX66Wna

### Geyser Version

build #340

### Additional Context

please answer as soon as possible

**Comment by onebeastchris** [comment]
Update Floodgate.

**Comment by nikitaku221** [comment]
I downloaded a new one from the site and the same thing

**Comment by onebeastchris** [comment]
If Java players can't enter, it's not related to Floodgate/Geyser. From the part of the stack trace that you've sent, it looks like floodgate threw an error - it's not a full one. If this issue persists in online/floodgate mode - offline mode is not supported - open a new issue in GeyserMC/Floodgate and attach a complete log file via mclo.gs .

**Comment by nikitaku221** [comment]
listen, I made a mistake here and there’s another mistake and there’s a follow-up to it

new:

[23:54:36 ERROR]: java.lang.reflect.InvocationTargetException
[23:54:36 ERROR]:       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
[23:54:36 ERROR]:       at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[23:54:36 ERROR]:       at org.geysermc.floodgate.util.ReflectionUtils.invoke(ReflectionUtils.java:509)
[23:54:36 ERROR]:       at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:103)
[23:54:36 ERROR]:       at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[23:54:36 ERROR]:       at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[23:54:36 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[23:54:36 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[23:54:36 ERROR]:       at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[23:54:36 ERROR]:       at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[23:54:36 ERROR]:       at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[23:54:36 ERROR]:       at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[23:54:36 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[23:54:36 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[23:54:36 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[23:54:36 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[23:54:36 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[23:54:36 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:54:36 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
[23:54:36 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:54:36 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:54:36 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23:54:36 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1589)
[23:54:36 ERROR]: Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
[23:54:36 ERROR]:       at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70)
[23:54:36 ERROR]:       at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[23:54:36 ERROR]:       ... 22 more
