### ISSUE TITLE
NPE: GeyserInjector is null on Velocity

### ISSUE THREAD

**Issue by emesan22** [GeyserMC/Geyser#4275]
### Describe the bug

I was getting another error, but after updating, I no longer get that error, but I get this error when connecting and cannot connect to the server.

```
[10:24:41 ERROR]: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.platform.velocity.GeyserVelocityInjector.getServerSocketAddress()" because "this.geyserInjector" is null
[10:24:41 ERROR]:       at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.getSocketAddress(GeyserVelocityPlugin.java:222)
[10:24:41 ERROR]:       at org.geysermc.geyser.session.GeyserSession.connectDownstream(GeyserSession.java:866)[10:24:41 ERROR]:       at org.geysermc.geyser.session.GeyserSession.authenticate(GeyserSession.java:707)
[10:24:41 ERROR]:       at org.geysermc.geyser.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:206)
[10:24:41 ERROR]:       at org.cloudburstmc.protocol.bedrock.packet.ResourcePackClientResponsePacket.handle(ResourcePackClientResponsePacket.java:20)
[10:24:41 ERROR]:       at org.cloudburstmc.protocol.bedrock.packet.BedrockPacketHandler.handlePacket(BedrockPacketHandler.java:9)
[10:24:41 ERROR]:       at org.cloudburstmc.protocol.bedrock.BedrockSession.onPacket(BedrockSession.java:123)
[10:24:41 ERROR]:       at org.cloudburstmc.protocol.bedrock.BedrockPeer.onBedrockPacket(BedrockPeer.java:66)
[10:24:41 ERROR]:       at org.cloudburstmc.protocol.bedrock.BedrockPeer.channelRead(BedrockPeer.java:261)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[10:24:41 ERROR]:       at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[10:24:41 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[10:24:41 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[10:24:41 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[10:24:41 ERROR]:       at org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60)
[10:24:41 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[10:24:41 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[10:24:41 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[10:24:41 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[10:24:41 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[10:24:41 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[10:24:41 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[10:24:41 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
```

### To Reproduce

1. connecting the server

### Expected behaviour

Connect the server

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/89179378/b3ed261b-0beb-4693-a1c2-c6e753ae3ecc)
(This screen says at the top that a world is being generated and at the bottom that a server is being searched for.)
![image](https://github.com/GeyserMC/Geyser/assets/89179378/494160dd-5c6c-4740-b820-a9876414d838)

### Server Version and Plugins

- Proxy Server Velocity ``3.2.0-SNAPSHOT (git-8dcc7ee3-b294)``
- Lobby server purpur ``git-Purpur-2062 (MC: 1.20.1)*``
  - Geyser **NOT** installed.

### Geyser Dump

https://dump.geysermc.org/Z79YgW2kzqB6ni187eR1pYWgr3cNKt8W

### Geyser Version

version 2.2.0-SNAPSHOT (git-master-574dad0) (Java: 1.20.2, Bedrock: 1.20.0/1.20.1 - 1.20.40)

**Comment by onebeastchris** [comment]
Did this occur after using `/geyser reload`, or just after starting the server normally?

Additionally, please send a full log via mclo.gs

**Comment by emesan22** [comment]
https://mclo.gs/P2O0sZ3

**Comment by onebeastchris** [comment]
Could you set `debug-mode` in Geyser's config.yml to `true`, restart, and send a new log?

**Comment by emesan22** [comment]
https://mclo.gs/nIGEKVi

**Comment by emesan22** [comment]
I was can to connect to a server!

**Comment by onebeastchris** [comment]
Excellent, thanks for testing :)
