### ISSUE TITLE
Purpur 1.20.2 Players cannot join the game

### ISSUE THREAD

**Issue by mangocraft** [GeyserMC/Geyser#4288]
### Describe the bug

When a Bedrock Edition player joins the game, an error message appears:
[12:39:41 WARN]: java.lang.NoClassDefFoundError: io/netty/handler/codec/dns/DnsQuestion
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession.connectDownstream(GeyserSession.java:887)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.session.GeyserSession.authenticate(GeyserSession.java:721)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:206)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.cloudburstmc.protocol.bedrock.packet.ResourcePackClientResponsePacket.handle(ResourcePackClientResponsePacket.java:20)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.cloudburstmc.protocol.bedrock.packet.BedrockPacketHandler.handlePacket(BedrockPacketHandler.java:9)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.cloudburstmc.protocol.bedrock.BedrockSession.onPacket(BedrockSession.java:123)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.cloudburstmc.protocol.bedrock.BedrockPeer.onBedrockPacket(BedrockPeer.java:66)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.cloudburstmc.protocol.bedrock.BedrockPeer.channelRead(BedrockPeer.java:261)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:39:41 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[12:39:41 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[12:39:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[12:39:41 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[12:39:41 WARN]:        at Geyser-Spigot.jar//org.cloudburstmc.netty.channel.raknet.RakChannelPipeline.lambda$onUnhandledInboundMessage$0(RakChannelPipeline.java:60)
[12:39:41 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[12:39:41 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[12:39:41 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[12:39:41 WARN]:        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
[12:39:41 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[12:39:41 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:39:41 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[12:39:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[12:39:41 WARN]: Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.dns.DnsQuestion
[12:39:41 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199)
[12:39:41 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166)
[12:39:41 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[12:39:41 WARN]:        ... 47 more

### To Reproduce

When a Bedrock Edition player joins the game, an error message appears

### Expected behaviour

Player can Join the game

### Server Version and Plugins

git-Purpur-2090 (MC: 1.20.2)

### Geyser Version

2.2.0-SNAPSHOT (git-master-81178ba)

### Minecraft: Bedrock Edition Device/Version

1.20.41

**Comment by mangocraft** [comment]
When I tried to reset the config.yaml file, the problem was solved. I suspected that 1.20.2 modified the network packet sending problem.
