### ISSUE TITLE
服务端报错

### ISSUE THREAD

**Issue by Adogs1** [GeyserMC/Geyser#4323]
### Describe the bug

我上周使用它时还是正常的，但刚刚启动服务端时出现这样的报错：
[23:03:48] [Server thread/INFO]: Starting minecraft server version 1.20.2
[23:03:48] [Server thread/INFO]: Loading properties
[23:03:48] [Server thread/INFO]: Default game type: SURVIVAL
[23:03:48] [Server thread/INFO]: Generating keypair
[23:03:48] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:03:48] [Server thread/INFO]: Using default channel type
[23:03:48] [Server thread/WARN]: **** FAILED TO BIND TO PORT!
[23:03:48] [Server thread/WARN]: The exception was: java.net.BindException: Address already in use: bind
[23:03:48] [Server thread/WARN]: Perhaps a server is already running on that port?
[23:03:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Failed to initialize server
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:680) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:03:48] [Server thread/ERROR]: This crash report has been saved to: E:\GVS_Minecraft server start\server\.\crash-reports\crash-2023-12-02_23.03.48-server.txt
[23:03:48] [Server thread/INFO]: Geyser关闭中
[23:03:48] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledExecutorService.shutdown()" because "this.scheduledThread" is null
	at org.geysermc.geyser.GeyserImpl.shutdown(GeyserImpl.java:591) ~[geyser-fabric-2.2.0-SNAPSHOT+build.357.jar:?]
	at org.geysermc.geyser.platform.fabric.GeyserFabricMod.onDisable(GeyserFabricMod.java:206) ~[geyser-fabric-2.2.0-SNAPSHOT+build.357.jar:?]
	at org.geysermc.geyser.platform.fabric.GeyserFabricMod.lambda$onEnable$1(GeyserFabricMod.java:126) ~[geyser-fabric-2.2.0-SNAPSHOT+build.357.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:63) ~[fabric-lifecycle-events-v1-2.2.2+b1792f7da0-6534456d0dd033b3.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cgc000$fabric-lifecycle-events-v1$beforeShutdownServer(MinecraftServer.java:7856) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:542) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:699) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### To Reproduce

如上启动服务端

### Expected behaviour

如上不会出现报错，成功启动服务器

### Geyser Version

geyser-fabric-2.2.0-SNAPSHOT+build.357

**Comment by Adogs1** [comment]
我找到问题的原因了，我刚刚使用Python的MCDReforged添加了插件：https://github.com/kmcsr/smart_servertime_mcdr/tree/master
及其3个依赖似乎占用了什么
我无法解决这个问题
