### ISSUE TITLE
IO error while trying to use legacy ping passthrough

### ISSUE THREAD

**Issue by Olen** [GeyserMC/Geyser#4330]
### Describe the bug

Uncaught exception:

```
[10:03:12 ERROR] IO error while trying to use legacy ping passthrough
java.net.UnknownHostException: proxy.skogliv.no.
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:572) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at org.geysermc.geyser.ping.GeyserLegacyPingPassthrough.run(GeyserLegacyPingPassthrough.java:84) [Geyser-Standalone.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

### To Reproduce

Happening if there are intermittent network issues.
The exception sould probably be caught.

### Expected behaviour

Better error message

### Geyser Version

Geyser version 2.2.0-SNAPSHOT (git-master-94a1cbe)

**Comment by onebeastchris** [comment]
Can you try the linked build? A jar can be found & downloaded in the linked pr under `Checks`. That should catch the exception and only print to debug
