### ISSUE TITLE
Compatibility issues between RealIP-MC and Geyser

### ISSUE THREAD

**Issue by pkki** [GeyserMC/Geyser#4342]
### Describe the bug

When RealIp is added, geyser will not work properly and bedrock players will not be able to enter.

### To Reproduce

1.Install RealIP
2.protocollib

### Expected behaviour

Improve the compatibility of RealIP and geyser to enable to join an bedrock version of the player.

### Server Version and Plugins

  [Sat 15:13:24 INFO ] Checking version, please wait...
  [Sat 15:13:25 INFO ] This server is running Paper version git-Paper-132 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: eb8f2bb)
You are 64 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-550 (MC: 1.19.4)

### Geyser Dump

https://dump.geysermc.org/PRhcxVdtXvzxKjv4RNOAQlCczsP6r2KD

### Geyser Version

2.2.0-SNAPSHOT (git-master-6e56666)

### Minecraft: Bedrock Edition Device/Version

newest all device

**Comment by onebeastchris** [comment]
Can you share a log or anything that shows in what way it's incompatible?
What's the behavior without, and what with it?

**Comment by pkki** [comment]
This is logs when geyser reload.

[12:26:59] [Server thread/INFO]: PeriodKun issued server command: /geyser reload
[12:26:59] [Geyser Scheduled Thread-2-1/INFO]: [Geyser-Spigot] Geyser をシャットダウンしています。
[12:26:59] [Geyser Scheduled Thread-2-1/INFO]: [Geyser-Spigot] Geyser は正常にシャットダウンしました。
[12:26:59] [nioEventLoopGroup-8-1/INFO]: [Geyser-Spigot] Geyser を 0.0.0.0 で開始しました: 19132
[12:26:59] [Geyser Spigot connection thread-10-2/WARN]: [io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: org.geysermc.geyser.network.netty.ChannelWrapper@249343e2
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotInjector$1.initChannel(GeyserSpigotInjector.java:120) ~[Geyser-Spigot.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.geysermc.geyser.network.netty.ChannelWrapper cannot be cast to class io.netty.channel.socket.SocketChannel (org.geysermc.geyser.network.netty.ChannelWrapper is in unnamed module of loader 'Geyser-Spigot.jar' @228ebf5c; io.netty.channel.socket.SocketChannel is in unnamed module of loader java.net.URLClassLoader @5fcfe4b2)
	at cc.nohit.realip.netty.NettyChannelInitializer.initChannel(NettyChannelInitializer.java:19) ~[RealIP-MC.jar:?]
	... 22 more
[12:26:59] [Geyser Spigot connection thread-10-2/WARN]: [io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: org.geysermc.geyser.network.netty.ChannelWrapper@249343e2
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at org.geysermc.floodgate.addon.data.SpigotDataAddon.onInject(SpigotDataAddon.java:60) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.inject.CommonPlatformInjector.injectAddonsCall(CommonPlatformInjector.java:77) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector$2$1.initChannel(SpigotInjector.java:119) ~[floodgate-spigot.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:26:59] [WebSocketConnectReadThread-6406/INFO]: [Geyser-Spigot] The skin uploader has been closed

This is logs when I join the server

[12:23:55] [nioEventLoopGroup-3-1/INFO]: [Geyser-Spigot] /126.214.35.185:48501 が接続しようとしました！
[12:23:55] [nioEventLoopGroup-3-4/INFO]: [Geyser-Spigot] ユーザー名 Periodkubsub で接続しました
[12:23:55] [defaultEventLoopGroup-6-4/INFO]: [Geyser-Spigot] Periodkubsub ( Periodkubsub としてログイン中) が Java サーバーに接続しました
[12:23:55] [Geyser Spigot connection thread-5-1/WARN]: [io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: org.geysermc.geyser.network.netty.ChannelWrapper@6e7b75af
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.geysermc.geyser.platform.spigot.GeyserSpigotInjector$1.initChannel(GeyserSpigotInjector.java:120) ~[Geyser-Spigot.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:480) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:89) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:83) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:215) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at ac.grim.grimac.shaded.io.github.retrooper.packetevents.injector.connection.ServerChannelHandler.channelRead(ServerChannelHandler.java:68) ~[grimac-2.3.43.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector$2.channelRead(SpigotInjector.java:113) ~[floodgate-spigot.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at com.comphenix.protocol.injector.netty.manager.InjectionChannelInitializer.channelRead(InjectionChannelInitializer.java:26) ~[ProtocolLib (1).jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel.readInbound(LocalServerChannel.java:159) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel.serve0(LocalServerChannel.java:178) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel.access$000(LocalServerChannel.java:37) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel$3.run(LocalServerChannel.java:143) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassCastException: class org.geysermc.geyser.network.netty.ChannelWrapper cannot be cast to class io.netty.channel.socket.SocketChannel (org.geysermc.geyser.network.netty.ChannelWrapper is in unnamed module of loader 'Geyser-Spigot.jar' @228ebf5c; io.netty.channel.socket.SocketChannel is in unnamed module of loader java.net.URLClassLoader @5fcfe4b2)
	at cc.nohit.realip.netty.NettyChannelInitializer.initChannel(NettyChannelInitializer.java:19) ~[RealIP-MC.jar:?]
	... 50 more
[12:23:55] [defaultEventLoopGroup-6-4/INFO]: [Geyser-Spigot] Connection closed. が原因で、Periodkubsub は Java サーバーから切断されました
[12:23:55] [Geyser Spigot connection thread-5-1/WARN]: [io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: org.geysermc.geyser.network.netty.ChannelWrapper@6e7b75af
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at org.geysermc.floodgate.addon.data.SpigotDataAddon.onInject(SpigotDataAddon.java:60) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.inject.CommonPlatformInjector.injectAddonsCall(CommonPlatformInjector.java:77) ~[floodgate-spigot.jar:?]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector$2$1.initChannel(SpigotInjector.java:119) ~[floodgate-spigot.jar:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at org.geysermc.floodgate.inject.spigot.SpigotInjector$2.channelRead(SpigotInjector.java:116) ~[floodgate-spigot.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at com.comphenix.protocol.injector.netty.manager.InjectionChannelInitializer.channelRead(InjectionChannelInitializer.java:26) ~[ProtocolLib (1).jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel.readInbound(LocalServerChannel.java:159) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel.serve0(LocalServerChannel.java:178) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel.access$000(LocalServerChannel.java:37) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.local.LocalServerChannel$3.run(LocalServerChannel.java:143) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by pkki** [comment]
![Screenshot_20231217-124931](https://github.com/GeyserMC/Geyser/assets/80244807/d98cf383-db47-46f9-80ad-fb5b373215a1)
It seems like I can get the status, but I can't join it.

**Comment by Konicai** [comment]
I told this user to create this report. A few things:
1. https://github.com/nohit-cc/RealIP-MC is the plugin in question
2. It expects a SocketChannel, but when Geyser is directly injecting, it is not one

Disabling direct connection avoids this issue, which I told pkki to do yesterday.

**Comment by Camotoy** [comment]
Paper natively implements proxy protocol now, I believe, and as far as I'm aware there is no incompatibility when that is used in tandem with Geyser and proxy protocol settings enabled on our end. I don't see why this plugin is necessary.

**Comment by Camotoy** [comment]
Closing with the above rationale. If I remember correctly, we cannot implement SocketChannel when using direct connection, and even if Paper's proxy protocol does not work correctly, I don't think this is worth the effort to work around.
