### ISSUE TITLE
FakeHeadProvider

### ISSUE THREAD

**Issue by godtitangod** [GeyserMC/Geyser#4392]
### Describe the bug

This error is usual and where there many players my CPU starts going up.

### To Reproduce

1. Have geyser on your proxy
2. Get many bedrock players

### Expected behaviour

07:28:35] [pool-15-thread-8/WARN] [Geyser-BungeeCord]: Couldn't merge skin of .TIGOGI with head skin url https://textures.minecraft.net/texture/128fd5d7a55cce30a660445f653946ae4dd09c514860417811415b6ae9fc81bb
java.util.concurrent.ExecutionException: java.lang.Exception: Couldn't load player's original skin
    at com.google.common.util.concurrent.AbstractFuture.getDoneValue(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.util.concurrent.AbstractFuture.get(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.cache.LocalCache$Segment.getAndRecordStats(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.cache.LocalCache$Segment.loadSync(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.cache.LocalCache$Segment.get(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.cache.LocalCache.get(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.cache.LocalCache.getOrLoad(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    at org.geysermc.geyser.skin.FakeHeadProvider.lambda$loadHead$1(FakeHeadProvider.java:139) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.Exception: Couldn't load player's original skin
    at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:65) ~[?:?]
    at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:59) ~[?:?]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(Unknown Source) ~[xcord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:1a27fb8:unknown]
    ... 10 more

### Geyser Dump

https://dump.geysermc.org/VwGEzvBse9USsELm82A72Kpo3xAn3uyd

### Geyser Version

2.2.0-SNAPSHOT

**Comment by godtitangod** [comment]
Updated proxy software and geyser, still having this issue.
java.util.concurrent.ExecutionException: java.lang.Exception: Couldn't load player's original skin
    at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:551) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:111) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:247) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2346) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2314) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2190) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2080) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache.get(LocalCache.java:4012) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at org.geysermc.geyser.skin.FakeHeadProvider.lambda$loadHead$1(FakeHeadProvider.java:139) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.Exception: Couldn't load player's original skin
    at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:65) ~[?:?]
    at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:59) ~[?:?]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3571) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2313) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
    ... 9 more

**Comment by Kas-tle** [comment]
X-Cord is not supported.

**Comment by onebeastchris** [comment]
Furthermore, please provide proper replication steps in future bug reports - a part of a stacktrace doesn't help us to reproduce & fix the issue at hand.
