### ISSUE TITLE
Geyser to not work on newest velocity

### ISSUE THREAD

**Issue by gamingcodedev** [GeyserMC/Geyser#4410]
### Describe the bug

geyser could not enable on the newest velocity currently 343

### To Reproduce

1. Download newest Velocity
2. Download newest geyser
3. try to start

### Expected behaviour

geyser starts

### Geyser Version

newest from 24.01.2024

### Additional Context

[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  java.lang.ClassNotFoundException: com.velocitypowered.proxy.protocol.packet.Handshake
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:87)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:64)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at java.base/java.lang.Class.forName0(Native Method)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at java.base/java.lang.Class.forName(Class.java:375)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at org.geysermc.floodgate.util.ReflectionUtils.getClass(ReflectionUtils.java:87)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at org.geysermc.floodgate.util.ReflectionUtils.getPrefixedClass(ReflectionUtils.java:63)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.<clinit>(VelocityProxyDataHandler.java:66)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at org.geysermc.floodgate.addon.data.VelocityDataAddon.onInject(VelocityDataAddon.java:83)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at org.geysermc.floodgate.inject.CommonPlatformInjector.injectAddonsCall(CommonPlatformInjector.java:77)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:105)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[23:43:14] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]:  	at java.base/java.lang.Thread.run(Thread.java:833)
[23:43:14] [Netty epoll Worker #0/WARN] [io.netty.channel.ChannelInitializer]:  Failed to initialize a channel. Closing: [id: 0x6ed85c6e, L:/45.81.235.94:25565 - R:/217.82.132.109:60082]
java.lang.ExceptionInInitializerError: null
	at org.geysermc.floodgate.addon.data.VelocityDataAddon.onInject(VelocityDataAddon.java:83) ~[?:?]
	at org.geysermc.floodgate.inject.CommonPlatformInjector.injectAddonsCall(CommonPlatformInjector.java:77) ~[?:?]
	at org.geysermc.floodgate.inject.velocity.VelocityInjector$VelocityChannelInitializer.initChannel(VelocityInjector.java:105) ~[?:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Handshake packet class cannot be null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[velocity.jar:3.3.0-SNAPSHOT (git-b9b11665-b343)]
	at org.geysermc.floodgate.addon.data.VelocityProxyDataHandler.<clinit>(VelocityProxyDataHandler.java:67) ~[?:?]
	... 22 more

**Comment by onebeastchris** [comment]
Update Floodgate, that should resolve the issue.
