### ISSUE TITLE
Bedrock players are kicked with Failed to encrypt message

### ISSUE THREAD

**Issue by CCSNova** [GeyserMC/Geyser#4446]
### Describe the bug

Bedrock players cannot join the server, they get kicked with the message Failed to encrypt message

In the console there is the error
java.security.InvalidKeyException: Invalid AES key length: 27 bytes

### To Reproduce

1. Set-up Geyser on a proxy with Floodgate
2. Try join on Bedrock
3. Get kicked

### Expected behaviour

To be able to join

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/100384210/8ddfe466-aab6-46e2-ba87-9fad51202f66)

### Server Version and Plugins

- GeyserMC
- Floodgate
- ViaVersion
- ViaBackwards
- Maintenance

Velocity 3.3.0-SNAPSHOT Build 359

### Geyser Dump

https://dump.geysermc.org/mTr3FqCYjBtrElxq5QrpJ1fgO1RO0kdr

### Geyser Version

2.2.2-SNAPSHOT (git-master-e97258f)

### Minecraft: Bedrock Edition Device/Version

1.20.60 Windows

**Comment by onebeastchris** [comment]
This is likely a result of improper floodgate setup. 
Is `send-floodgate-data` set to true in the Floodgate config?

If it is, you also need to ensure that the Floodgate key.pem files match across all Floodgate installs.

**Comment by CCSNova** [comment]
Stacktrace:
```
java.security.InvalidKeyException: Invalid AES key length: 27 bytes
	at java.base/com.sun.crypto.provider.AESCrypt.makeSessionKey(AESCrypt.java:1329) ~[?:?]
	at java.base/com.sun.crypto.provider.AESCrypt.init(AESCrypt.java:1053) ~[?:?]
	at java.base/com.sun.crypto.provider.GaloisCounterMode.init(GaloisCounterMode.java:178) ~[?:?]
	at java.base/com.sun.crypto.provider.GaloisCounterMode.engineInit(GaloisCounterMode.java:304) ~[?:?]
	at java.base/javax.crypto.Cipher.implInit(Cipher.java:876) ~[?:?]
	at java.base/javax.crypto.Cipher.chooseProvider(Cipher.java:934) ~[?:?]
	at java.base/javax.crypto.Cipher.init(Cipher.java:1466) ~[?:?]
	at java.base/javax.crypto.Cipher.init(Cipher.java:1393) ~[?:?]
	at org.geysermc.floodgate.crypto.AesCipher.encrypt(AesCipher.java:64) ~[?:?]
	at org.geysermc.floodgate.crypto.FloodgateCipher.encryptFromString(FloodgateCipher.java:81) ~[?:?]
	at org.geysermc.geyser.session.GeyserSession$1.packetSending(GeyserSession.java:943) ~[?:?]
	at com.github.steveice10.packetlib.event.session.PacketSendingEvent.call(PacketSendingEvent.java:79) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:150) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:250) ~[?:?]
	at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:158) ~[?:?]
	at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:150) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:365) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:271) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.local.LocalChannel$3.run(LocalChannel.java:186) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-ecf936f3-b359)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

`send-floodgate-data` is set to true and key.pem files match

Thanks for the quick response too

**Comment by CCSNova** [comment]
Issue is also present on a Nintendo Switch on 1.20.61

**Comment by computer-catt** [comment]
ive replicated the issue

**Comment by CCSNova** [comment]
on the same server...
😭

**Comment by onebeastchris** [comment]
Please try and re-copy the key.pem. Don't try and edit/copy the contents, we'd recommend to copy the full file.

Additionally, the following may matter regarding FTP clients (from discord:)
```
This error is caused by a Floodgate key.pem mismatch, most likely between your proxy and your backend servers.
Make sure that the key.pem file in every Floodgate config folder is the same file.
If this still doesn't work and you're using an FTP client, try using the [WinSCP](https://winscp.net/eng/index.php) client.```

**Comment by CCSNova** [comment]
Copying didn't work but deleting the key.pem file so it regenerated and now it works, something must have modified it to break it, thank you so much with the help! This is a great project :)

**Comment by Shadowshot2456** [comment]
We don’t have a config for floodgate and it isn’t generating one
