### ISSUE TITLE
[geyser]: Packet violation warning sent from client! PacketViolationWarningPacket(type=UNKNOWN, severity=WARNING, packetCauseId=156, context=Server sent a ContainerClosePacket response packet when it should have sent the server initiated packet)

### ISSUE THREAD

**Issue by CayanNet** [GeyserMC/Geyser#4497]
### Describe the bug

[23:03:57 ERROR] [geyser]: Packet violation warning sent from client! PacketViolationWarningPacket(type=UNKNOWN, severity=WARNING, packetCauseId=156, context=Server sent a ContainerClosePacket response packet when it should have sent the server initiated packet)
![image](https://github.com/GeyserMC/Geyser/assets/153404271/5588dd32-8572-43b9-823d-28165522761a)

### To Reproduce

its randomly showing in velocity terminal 
![image](https://github.com/GeyserMC/Geyser/assets/153404271/02242ac1-4692-4884-8ce7-7666ace9389b)

### Expected behaviour

am not sure why this is showing up

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/153404271/957d88c0-16fa-4d5b-885c-eb243df059ba)

### Server Version and Plugins

[23:39:19 INFO]: Current: git-Purpur-2155 (MC: 1.20.4)*
Previous: git-Purpur-2153 (MC: 1.20.4)
* You are running the latest version

[23:39:34 INFO]: Paper Plugins: (3):
[23:39:34 INFO]:  - EconomyShopGUI, MiniPlaceholders, PCGF_PluginLib
[23:39:34 INFO]: Bukkit Plugins: (59):
[23:39:34 INFO]:  - ajLeaderboards, antiRedstoneClock, BetterRTP, BetterRTPAddons, BetterTeams, BetterTridents, *BetterWorldStats, ChatColor2, ChatFormatter, ChestSort
[23:39:34 INFO]:  Citizens, CMILib, CommandWhitelist, DecentHolograms, DeluxeMenus, DiscordSRV, DreamCoinFlip, Drop2InventoryPlus, Econoblocks, Economobs
[23:39:34 INFO]:  eGlow, Essentials, EssentialsSpawn, Exyron-FastCrystals, FastAsyncWorldEdit, floodgate, GeyserHacks, GrapplingHook, GSit, HeadDrop
[23:39:34 INFO]:  InstantRestock, Jobs, LifeSteal-Smp-Plugin, LiteAntiCheat, LogicalChat, LuckPerms, MarriageMaster, Minepacks, NotBounties, *OldschoolKill
[23:39:34 INFO]:  OSManager, PlaceholderAPI, PlayerAuctions, PlayerPoints, PlayerStats, PlayerWarps, ProtocolLib, PvPManager, SimplePortals, Skoice
[23:39:34 INFO]:  spark, Stats2Discord, TAB, TimeIsMoney, TradeSystem, Vault, VotifierPlus, VotingPlugin, WorldGuard

### Geyser Dump

https://dump.geysermc.org/QCduYTutYA8vb3NEZgF2RweKv0lCLMEg

### Geyser Version

[23:40:50 INFO]: This server is running Geyser version 2.2.2-SNAPSHOT (git-master-a9467cf) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70/1.20.71)

**Comment by onebeastchris** [comment]
Do you have any reproduction steps you could share? 
Unfortunately, this doesn't give us enough info here unless we're able to reproduce it

**Comment by CayanNet** [comment]
[2024-03-14-1.log.gz](https://github.com/GeyserMC/Geyser/files/14604216/2024-03-14-1.log.gz)
am not really sure since of its just randomly saying

**Comment by onebeastchris** [comment]
I have an idea where this might originate from; I'll send a debug build in a second.

As for reproduction steps - is this something that occurs constantly? Is it always that player/is it a specific menu/when switching servers/ etc?

Furthermore, Geyser's `debug` mode *might* show something more informative here

**Comment by onebeastchris** [comment]
Could you try the linked pull request build and see if that resolves the issue? 
You can download it in the `Checks` tab of the linked pull request.

**Comment by CayanNet** [comment]
sure

**Comment by CayanNet** [comment]
do i need to turn on the debug mode in pr build of geyser velocity?

**Comment by onebeastchris** [comment]
you don't have to, but if the error occurs again, it won't hurt :)

**Comment by CayanNet** [comment]
ok

**Comment by CayanNet** [comment]
currently i am running with pr build of jar rn how much times i need to wait for post the log in here to check it goes fixed?

**Comment by onebeastchris** [comment]
Well, if you aren't seeing the error for a while, that sounds like a good thing :)

**Comment by CayanNet** [comment]
hmm i think this is new error msg i never seen this with previous jar [geyser]: Could not translate packet ClientboundBlockUpdatePacket
java.lang.IllegalArgumentException: Value cannot be outside of accepted range.
	at com.github.steveice10.mc.protocol.data.game.chunk.BitStorage.set(BitStorage.java:100) ~[?:?]
	at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.resize(DataPalette.java:124) ~[?:?]
	at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.set(DataPalette.java:88) ~[?:?]
	at org.geysermc.geyser.session.cache.ChunkCache.updateBlock(ChunkCache.java:107) ~[?:?]
	at org.geysermc.geyser.util.ChunkUtils.updateBlock(ChunkUtils.java:123) ~[?:?]
	at org.geysermc.geyser.session.cache.WorldCache.updateServerCorrectBlockState(WorldCache.java:168) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:48) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:40) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by onebeastchris** [comment]
Please create a new issue with reproduction steps for that one.

**Comment by CayanNet** [comment]
[latest.log](https://github.com/GeyserMC/Geyser/files/14618226/latest.log)
i think there's no more error msg with [geyser]: Packet violation warning sent from client! PacketViolationWarningPacket(type=UNKNOWN, severity=WARNING, packetCauseId=156, context=Server sent a ContainerClosePacket response packet when it should have sent the server initiated packet) i think

**Comment by CayanNet** [comment]
![image](https://github.com/GeyserMC/Geyser/assets/153404271/2e2f3222-f3f4-471c-8802-00a2037066f2)
[06:18:41 ERROR] [geyser]: Packet violation warning sent from client! PacketViolationWarningPacket(type=UNKNOWN, severity=WARNING, packetCauseId=156, context=Server sent a ContainerClosePacket response packet when it should have sent the server initiated packet)
its happening with pr build 
[latest.log](https://github.com/GeyserMC/Geyser/files/14622492/latest.log)
