### ISSUE TITLE
[geyser]: Could not translate packet ClientboundBlockUpdatePacket & [00:41:39 ERROR]: java.lang.IllegalArgumentException: Value cannot be outside of accepted range.

### ISSUE THREAD

**Issue by CayanNet** [GeyserMC/Geyser#4501]
### Describe the bug

[00:41:39 ERROR] [geyser]: Could not translate packet ClientboundBlockUpdatePacket
java.lang.IllegalArgumentException: Value cannot be outside of accepted range.
	at com.github.steveice10.mc.protocol.data.game.chunk.BitStorage.set(BitStorage.java:100) ~[?:?]
	at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.resize(DataPalette.java:124) ~[?:?]
	at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.set(DataPalette.java:88) ~[?:?]
	at org.geysermc.geyser.session.cache.ChunkCache.updateBlock(ChunkCache.java:107) ~[?:?]
	at org.geysermc.geyser.util.ChunkUtils.updateBlock(ChunkUtils.java:123) ~[?:?]
	at org.geysermc.geyser.session.cache.WorldCache.updateServerCorrectBlockState(WorldCache.java:168) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:48) ~[?:?]
	at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:40) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[00:41:39 ERROR]: java.lang.IllegalArgumentException: Value cannot be outside of accepted range.
[00:41:39 ERROR]: 	at com.github.steveice10.mc.protocol.data.game.chunk.BitStorage.set(BitStorage.java:100)
[00:41:39 ERROR]: 	at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.resize(DataPalette.java:124)
[00:41:39 ERROR]: 	at com.github.steveice10.mc.protocol.data.game.chunk.DataPalette.set(DataPalette.java:88)
[00:41:39 ERROR]: 	at org.geysermc.geyser.session.cache.ChunkCache.updateBlock(ChunkCache.java:107)
[00:41:39 ERROR]: 	at org.geysermc.geyser.util.ChunkUtils.updateBlock(ChunkUtils.java:123)
[00:41:39 ERROR]: 	at org.geysermc.geyser.session.cache.WorldCache.updateServerCorrectBlockState(WorldCache.java:168)
[00:41:39 ERROR]: 	at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:48)
[00:41:39 ERROR]: 	at org.geysermc.geyser.translator.protocol.java.level.JavaBlockUpdateTranslator.translate(JavaBlockUpdateTranslator.java:40)
[00:41:39 ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[00:41:39 ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[00:41:39 ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[00:41:39 ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[00:41:39 ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[00:41:39 ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:41:39 ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[00:41:39 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:840)

[latest.log](https://github.com/GeyserMC/Geyser/files/14618222/latest.log)

### To Reproduce

randomly showing on in velocity terminal

### Expected behaviour

am not sure why this is happening 

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/153404271/eb8477f0-9d92-4612-8b78-43385da7a768)

### Server Version and Plugins

[01:26:05 INFO]: Current: git-Purpur-2155 (MC: 1.20.4)*
Previous: git-Purpur-2153 (MC: 1.20.4)
* You are running the latest version
[01:26:19 INFO]: Paper Plugins: (3):
[01:26:19 INFO]:  - EconomyShopGUI, MiniPlaceholders, PCGF_PluginLib
[01:26:19 INFO]: Bukkit Plugins: (61):
[01:26:19 INFO]:  - ajLeaderboards, antiRedstoneClock, BankPlus, BetterRTP, BetterRTPAddons, BetterTeams, BetterTridents, *BetterWorldStats, ChatColor2, ChatFormatter
[01:26:19 INFO]:  ChestSort, Citizens, CMILib, CommandWhitelist, DecentHolograms, DeluxeMenus, DiscordSRV, *DiscordUtils, DreamCoinFlip, Drop2InventoryPlus
[01:26:19 INFO]:  Econoblocks, Economobs, eGlow, Essentials, EssentialsSpawn, Exyron-FastCrystals, FastAsyncWorldEdit, floodgate, GeyserHacks, GrapplingHook
[01:26:19 INFO]:  GriefPrevention, GSit, HeadDrop, InstantRestock, Jobs, LiteAntiCheat, LogicalChat, LotterySix, LuckPerms, MarriageMaster
[01:26:19 INFO]:  Minepacks, NotBounties, *OldschoolKill, OSManager, PlaceholderAPI, PlayerAuctions, PlayerPoints, PlayerStats, PlayerWarps, ProtocolLib
[01:26:19 INFO]:  PvPManager, SimplePortals, Skoice, spark, TAB, TimeIsMoney, TradeSystem, Vault, VotifierPlus, VotingPlugin
[01:26:19 INFO]:  WorldGuard

### Geyser Dump

https://dump.geysermc.org/vroQXWgqPCncKt9UUpyEqiLr7CDH4qjH

### Geyser Version

This server is running Geyser version 2.2.2-SNAPSHOT (git-DEV-0677b71) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70/1.20.71)

**Comment by onebeastchris** [comment]
Please pin down the plugin that's sending this fun data. You can use the following steps to isolate it:

If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
- Temporarily remove/move half of your plugins from your server's plugins folder.
- If the problem persists, remove another half.
- If the problem goes away, swap that half of your plugins with the other half.
- Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

Furthermore, please test if a 1.20.4 Vanilla Minecraft: Java Edition client is throwing errors/warnings in the client log.

**Comment by CayanNet** [comment]
seems like its fixed on latest geyser build so i will close this and reopen when its showing again
