### ISSUE TITLE
[05:57:47 ERROR] [geyser]: Couldn't merge skin of .ActualSix095004 with head skin url https://textures.minecraft.net/texture/c52b1c8547e6e310291bfe9a7467bd21c0b6be6e93ddf64bf5a218441789ef5c j

### ISSUE THREAD

**Issue by CayanNet** [GeyserMC/Geyser#4503]
### Describe the bug

![image](https://github.com/GeyserMC/Geyser/assets/153404271/f34ee9e8-cb4e-455e-b9a5-fad2ca897518)

05:57:47 ERROR] [geyser]: Couldn't merge skin of .ActualSix095004 with head skin url https://textures.minecraft.net/texture/c52b1c8547e6e310291bfe9a7467bd21c0b6be6e93ddf64bf5a218441789ef5c
java.util.concurrent.ExecutionException: java.lang.Exception: Couldn't load player's original skin
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:244) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$LoadingValueReference.waitForValue(LocalCache.java:3586) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.waitForLoadingValue(LocalCache.java:2179) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2043) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at org.geysermc.geyser.skin.FakeHeadProvider.lambda$loadHead$1(FakeHeadProvider.java:139) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.Exception: Couldn't load player's original skin
	at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:65) ~[?:?]
	at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:59) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	... 7 more
[05:57:47 ERROR] [geyser]: Couldn't merge skin of .ActualSix095004 with head skin url https://textures.minecraft.net/texture/c52b1c8547e6e310291bfe9a7467bd21c0b6be6e93ddf64bf5a218441789ef5c
java.util.concurrent.ExecutionException: java.lang.Exception: Couldn't load player's original skin
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:244) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2317) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2283) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at org.geysermc.geyser.skin.FakeHeadProvider.lambda$loadHead$1(FakeHeadProvider.java:139) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.Exception: Couldn't load player's original skin
	at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:65) ~[?:?]
	at org.geysermc.geyser.skin.FakeHeadProvider$1.load(FakeHeadProvider.java:59) ~[?:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	... 9 more
[latest.log](https://github.com/GeyserMC/Geyser/files/14622486/latest.log)

### To Reproduce

its new error msg to me am not sure why its showing up
![image](https://github.com/GeyserMC/Geyser/assets/153404271/ab37e33f-9f34-4dd0-b0ef-7f5903cdcb08)

### Expected behaviour

![image](https://github.com/GeyserMC/Geyser/assets/153404271/2aeb0b4c-f6bc-4cc4-994d-abe0d62dc941)

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/153404271/09f8604f-5330-4a3d-a1c7-7e5370ae02a9)

### Server Version and Plugins

[14:15:15 INFO]: Current: git-Purpur-2155 (MC: 1.20.4)*
Previous: git-Purpur-2153 (MC: 1.20.4)
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads
[14:15:52 INFO]: Paper Plugins: (3):
[14:15:52 INFO]:  - EconomyShopGUI, MiniPlaceholders, PCGF_PluginLib
[14:15:52 INFO]: Bukkit Plugins: (61):
[14:15:52 INFO]:  - ajLeaderboards, antiRedstoneClock, BankPlus, BetterRTP, BetterRTPAddons, BetterTeams, BetterTridents, *BetterWorldStats, ChatColor2, ChatFormatter
[14:15:52 INFO]:  ChestSort, Citizens, CMILib, CommandWhitelist, DecentHolograms, DeluxeMenus, DiscordSRV, *DiscordUtils, DreamCoinFlip, Drop2InventoryPlus
[14:15:52 INFO]:  Econoblocks, Economobs, eGlow, Essentials, EssentialsSpawn, Exyron-FastCrystals, FastAsyncWorldEdit, floodgate, GeyserHacks, GrapplingHook
[14:15:52 INFO]:  GriefPrevention, GSit, HeadDrop, InstantRestock, Jobs, LiteAntiCheat, LogicalChat, LotterySix, LuckPerms, MarriageMaster
[14:15:52 INFO]:  Minepacks, NotBounties, *OldschoolKill, OSManager, PlaceholderAPI, PlayerAuctions, PlayerPoints, PlayerStats, PlayerWarps, ProtocolLib
[14:15:52 INFO]:  PvPManager, SimplePortals, Skoice, spark, TAB, TimeIsMoney, TradeSystem, Vault, VotifierPlus, VotingPlugin
[14:15:52 INFO]:  WorldGuard

### Geyser Dump

https://dump.geysermc.org/E2rljUE4hCQMmcnN2jBYqfSSDE4JV4BV

### Geyser Version

This server is running Geyser version 2.2.2-SNAPSHOT (git-DEV-0677b71) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70/1.20.71)

**Comment by onebeastchris** [comment]
This error is likely occurring as it took more than 5 seconds to retrieve the skin for a player.
See https://github.com/GeyserMC/Geyser/blob/master/core/src/main/java/org/geysermc/geyser/skin/FakeHeadProvider.java#L62 for reference - it waits for 5 seconds to get the skin, and throws if it can't get it - which is likely what's happening here.

What you could try would be increasing the `cache-image` setting to more than 0 - that would cache skins/other downloaded files for a while, which might reduce the amount of these errors.

**Comment by CayanNet** [comment]
sure but is there a recommend value for more than 0?

**Comment by onebeastchris** [comment]
Well, it's the amount of days it would be cached - try e.g. 1 or 2

**Comment by CayanNet** [comment]
ok i will try it to 2
