### ISSUE TITLE
[05:31:42 ERROR] [geyser]: Could not translate packet BookEditPacket

### ISSUE THREAD

**Issue by CayanNet** [GeyserMC/Geyser#4504]
### Describe the bug

![image](https://github.com/GeyserMC/Geyser/assets/153404271/5cacccbc-2dec-4668-b4af-42a5772824a6)
[05:31:42 ERROR] [geyser]: Could not translate packet BookEditPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:124) ~[?:?]
	at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55) ~[?:?]
	at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56) ~[?:?]
	at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:123) ~[?:?]
	at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:47) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[?:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.3.0-SNAPSHOT-370.jar:3.3.0-SNAPSHOT (git-8891faa5-b370)]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
[05:31:42 ERROR]: java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
[05:31:42 ERROR]: 	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:124)
[05:31:42 ERROR]: 	at org.geysermc.geyser.inventory.updater.ChestInventoryUpdater.updateInventory(ChestInventoryUpdater.java:55)
[05:31:42 ERROR]: 	at org.geysermc.geyser.translator.inventory.chest.ChestInventoryTranslator.updateInventory(ChestInventoryTranslator.java:56)
[05:31:42 ERROR]: 	at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:123)
[05:31:42 ERROR]: 	at org.geysermc.geyser.translator.protocol.bedrock.BedrockBookEditTranslator.translate(BedrockBookEditTranslator.java:47)
[05:31:42 ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[05:31:42 ERROR]: 	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[05:31:42 ERROR]: 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[05:31:42 ERROR]: 	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[05:31:42 ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[05:31:42 ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[05:31:42 ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[05:31:42 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:840)

### To Reproduce

maybe editing the book thing has some problem ig 
![image](https://github.com/GeyserMC/Geyser/assets/153404271/52f09583-f7df-4102-9b4e-b26f082aa297)

### Expected behaviour

![image](https://github.com/GeyserMC/Geyser/assets/153404271/52f09583-f7df-4102-9b4e-b26f082aa297)

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/153404271/52f09583-f7df-4102-9b4e-b26f082aa297)

### Server Version and Plugins

[14:15:15 INFO]: Current: git-Purpur-2155 (MC: 1.20.4)*
Previous: git-Purpur-2153 (MC: 1.20.4)
* You are 3 version(s) behind
Download the new version at: https://purpurmc.org/downloads
[14:15:52 INFO]: Paper Plugins: (3):
[14:15:52 INFO]:  - EconomyShopGUI, MiniPlaceholders, PCGF_PluginLib
[14:15:52 INFO]: Bukkit Plugins: (61):
[14:15:52 INFO]:  - ajLeaderboards, antiRedstoneClock, BankPlus, BetterRTP, BetterRTPAddons, BetterTeams, BetterTridents, *BetterWorldStats, ChatColor2, ChatFormatter
[14:15:52 INFO]:  ChestSort, Citizens, CMILib, CommandWhitelist, DecentHolograms, DeluxeMenus, DiscordSRV, *DiscordUtils, DreamCoinFlip, Drop2InventoryPlus
[14:15:52 INFO]:  Econoblocks, Economobs, eGlow, Essentials, EssentialsSpawn, Exyron-FastCrystals, FastAsyncWorldEdit, floodgate, GeyserHacks, GrapplingHook
[14:15:52 INFO]:  GriefPrevention, GSit, HeadDrop, InstantRestock, Jobs, LiteAntiCheat, LogicalChat, LotterySix, LuckPerms, MarriageMaster
[14:15:52 INFO]:  Minepacks, NotBounties, *OldschoolKill, OSManager, PlaceholderAPI, PlayerAuctions, PlayerPoints, PlayerStats, PlayerWarps, ProtocolLib
[14:15:52 INFO]:  PvPManager, SimplePortals, Skoice, spark, TAB, TimeIsMoney, TradeSystem, Vault, VotifierPlus, VotingPlugin
[14:15:52 INFO]:  WorldGuard

### Geyser Dump

https://dump.geysermc.org/E2rljUE4hCQMmcnN2jBYqfSSDE4JV4BV

### Geyser Version

This server is running Geyser version 2.2.2-SNAPSHOT (git-DEV-0677b71) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70/1.20.71)

**Comment by onebeastchris** [comment]
With which Bedrock client version does this occur with?
What seems to be happening here is that the client is writing/editing a book, but Geyser still thinks the player is in a cheat inventory.. which, seems a bit weird

Do you have any chest-menus that would then open a book? 
Regardless, please share reproduction steps. Without them, we can only guess what's actually causing the issue.

**Comment by CayanNet** [comment]
hmm am not sure how can i check their version i hope log can show the their bedrock version when they tried to join
and i don't think i got the plugin that does job to open book with chest menu ig

**Comment by CayanNet** [comment]
i think its not showing on latest geyser build so i will close this if i get this again i will reopen
