### ISSUE TITLE
"java.lang.NullPointerException" when I try to join via Bedrock Client

### ISSUE THREAD

**Issue by wtlgo** [GeyserMC/Geyser#4541]
### Describe the bug

When I try to join the server via the Bedrock client, the following exception occurs:
```log
02.04 00:59:28 [Server] [WARN] [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
02.04 00:59:28 [Server] [INFO] java.lang.NullPointerException: Cannot invoke "net.jodah.expiringmap.ExpiringMap.get(Object)" because "this.proxiedAddresses" is null
02.04 00:59:28 [Server] [INFO] at org.geysermc.geyser.network.netty.GeyserServer.onConnectionRequest(GeyserServer.java:266) ~[Geyser.jar:?]
02.04 00:59:28 [Server] [INFO] at org.geysermc.geyser.network.netty.handler.RakConnectionRequestHandler.channelRead(RakConnectionRequestHandler.java:87) ~[Geyser.jar:?]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at org.cloudburstmc.netty.handler.codec.raknet.ProxyInboundRouter.channelRead(ProxyInboundRouter.java:66) ~[Geyser.jar:?]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:662) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:697) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:56) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:536) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
02.04 00:59:28 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

1. Start the server
2. Join via Bedrock client
3. It doesn't let me join, an exception occurs in the logs

### Expected behaviour

I can join the server, no exception occurs

### Server Version and Plugins

```log
/version
02.04 01:06:12 [Server] [INFO] Checking version, please wait...
02.04 01:06:13 [Server] [INFO] This server is running Paper version git-Paper-"45d1486" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 45d1486)
02.04 01:06:13 [Server] [INFO] You are running the latest version
02.04 01:06:13 [Server] [INFO] Previous version: git-Paper-"c016e03" (MC: 1.20.1)
```

```log
/plugins
02.04 01:06:46 [Server] [INFO] Server Plugins (9):
02.04 01:06:46 [Server] [INFO] Bukkit Plugins:
02.04 01:06:46 [Server] [INFO] - *AutoUpdatePlugins, ChestSort, FarmControl, floodgate, Geyser-Spigot, GSit, SkinsRestorer, ViaBackwards, ViaVersion
```

### Geyser Dump

https://dump.geysermc.org/0aohwqK7C9pU135iZ8kwltZG95SymqSH

### Geyser Version

Geyser version 2.2.3-SNAPSHOT (git-master-fa441f1) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.70/1.20.72)

### Minecraft: Bedrock Edition Device/Version

1.20.72, iOS

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Geyser/pull/4539 This was just resolved - update Geyser to the latest version. Thanks!
