### ISSUE TITLE
Bedrock players are kicked with Failed to encrypt message

### ISSUE THREAD

**Issue by camilla-ett** [GeyserMC/Geyser#4569]
### Describe the bug

Bedrock players cannot join the server, they get kicked with the message `Failed to encrypt message`

In the console there is the error
```
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.skin.FloodgateSkinUploader.getId()" because "skinUploader" is null
    at org.geysermc.geyser.session.GeyserSession$1.packetSending(GeyserSession.java:959)
    at com.github.steveice10.packetlib.event.session.PacketSendingEvent.call(PacketSendingEvent.java:79)
    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:150)
    at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:250)
    at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:158)
    at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31)
    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:150)
    at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69)
    at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:274)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238)
    at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
    at io.netty.incubator.channel.uring.AbstractIOUringChannel$AbstractUringUnsafe.fulfillConnectPromise(AbstractIOUringChannel.java:407)
    at io.netty.incubator.channel.uring.AbstractIOUringChannel$AbstractUringUnsafe.connectComplete(AbstractIOUringChannel.java:662)
    at io.netty.incubator.channel.uring.IOUringEventLoop.handleConnect(IOUringEventLoop.java:339)
    at io.netty.incubator.channel.uring.IOUringEventLoop.handle(IOUringEventLoop.java:308)
    at io.netty.incubator.channel.uring.UserData.decode(UserData.java:30)
    at io.netty.incubator.channel.uring.IOUringCompletionQueue.process(IOUringCompletionQueue.java:90)
    at io.netty.incubator.channel.uring.IOUringEventLoop.run(IOUringEventLoop.java:222)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:840)
```

### To Reproduce

1. Set-up Geyser on a proxy with Floodgate
2. Try join on Bedrock
3. Get kicked

### Expected behaviour

able to join

### Server Version and Plugins

 - Geysermc-bungeeCord: https://github.com/GeyserMC/geyser/commit/a24f68412315fdabe93053d7722f9c9f15fc6511
 - FloodGate: https://github.com/GeyserMC/floodgate/commit/7f38765010e28afb7fc5f0c7519e654413f11bd6
 - BungeeCord: https://github.com/SpigotMC/BungeeCord/commit/bc528d5d981b237000d49d3cd9b432e9a4709601

### Geyser Version

2.2.3-SNAPSHOT (git-master-a24f684)

### Minecraft: Bedrock Edition Device/Version

Windows v1.20.73

**Comment by onebeastchris** [comment]
Please provide a full server log (latest.log file) via mclo.gs

**Comment by camilla-ett** [comment]
https://mclo.gs/cdj2nS3

![image](https://github.com/GeyserMC/Geyser/assets/25503753/67688bf0-1459-49f8-aa9d-447c4dd4f6c1)

**Comment by onebeastchris** [comment]
Can you try the Geyser build found under the `Checks` section in this PR: https://github.com/GeyserMC/Geyser/pull/4579 ?
That should resolve the issue.

**Comment by camilla-ett** [comment]
thank you so much!

**Comment by meipeter** [comment]
same issue on the lastest(Build #598) Standalone Geyser version
