### ISSUE TITLE
Failed to start Geyser on 0.0.0.0:19132

### ISSUE THREAD

**Issue by yossieJP** [GeyserMC/Geyser#4570]
### Describe the bug

I get this error on startup.
```
[ERROR] [Geyser-BungeeCord]: Failed to start Geyser on 0.0.0.0:19132
[ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@3c5a54b7, id=26, owner=org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin@1fcfcf37, task=org.geysermc.geyser.platform.bungeecord.GeyserBungeePlugin$$Lambda$1232/0x00007fbe1835e410@3ebc6d8b, delay=0, period=0, running=true) encountered an exception
java.util.concurrent.CompletionException: java.net.BindException: Address already in use
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
	at java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162) ~[?:?]
	at org.geysermc.geyser.network.netty.Bootstraps.lambda$allOf$0(Bootstraps.java:115) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at org.cloudburstmc.netty.channel.proxy.ProxyChannel.lambda$correctPromise$0(ProxyChannel.java:57) ~[?:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:564) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at org.cloudburstmc.netty.handler.codec.raknet.ProxyOutboundRouter.bind(ProxyOutboundRouter.java:48) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:606) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at org.cloudburstmc.netty.channel.proxy.ProxyChannel.bind(ProxyChannel.java:188) ~[?:?]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:380) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164) ~[?:?]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:202) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:197) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	... 19 more
```

When I try to join the server with Bedrock Edition, I get this error.
```
[WARN] [Geyser-BungeeCord]: Failed to encrypt message
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.skin.FloodgateSkinUploader.getId()" because "skinUploader" is null
	at org.geysermc.geyser.session.GeyserSession$1.packetSending(GeyserSession.java:959) ~[?:?]
	at com.github.steveice10.packetlib.event.session.PacketSendingEvent.call(PacketSendingEvent.java:79) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:150) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.send(TcpSession.java:250) ~[?:?]
	at com.github.steveice10.mc.protocol.ClientListener.connected(ClientListener.java:158) ~[?:?]
	at com.github.steveice10.packetlib.event.session.ConnectedEvent.call(ConnectedEvent.java:31) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:150) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.channelActive(TcpSession.java:365) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelActive(IdleStateHandler.java:274) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.incubator.channel.uring.AbstractIOUringChannel$AbstractUringUnsafe.fulfillConnectPromise(AbstractIOUringChannel.java:407) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.incubator.channel.uring.AbstractIOUringChannel$AbstractUringUnsafe.connectComplete(AbstractIOUringChannel.java:662) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.incubator.channel.uring.IOUringEventLoop.handleConnect(IOUringEventLoop.java:339) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.incubator.channel.uring.IOUringEventLoop.handle(IOUringEventLoop.java:308) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.incubator.channel.uring.UserData.decode(UserData.java:30) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.incubator.channel.uring.IOUringCompletionQueue.process(IOUringCompletionQueue.java:90) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.incubator.channel.uring.IOUringEventLoop.run(IOUringEventLoop.java:222) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:a8af9f6:unknown]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```

### To Reproduce

1. Set-up Geyser on a proxy with Floodgate
2. Try join on Bedrock

### Expected behaviour

Unable to join server in bedrock edition.

### Server Version and Plugins

Geysermc-bungeeCord: https://github.com/GeyserMC/Geyser/commit/a24f68412315fdabe93053d7722f9c9f15fc6511
FloodGate: https://github.com/GeyserMC/Floodgate/commit/7f38765010e28afb7fc5f0c7519e654413f11bd6

### Geyser Version

2.2.3-SNAPSHOT (git-master-a24f684)

### Minecraft: Bedrock Edition Device/Version

v1.20.73 ios

**Comment by Camotoy** [comment]
Check if you have query enabled in the BungeeCord config. If you do, disable it and try again.

**Comment by yossieJP** [comment]
`query_enabled: false` The query is already invalid.

**Comment by tenoble** [comment]
I have the same problem it tells me that the port is already in use but it changes it and it keeps telling me that

**Comment by onebeastchris** [comment]
Please send a full server log (proxy.log.0 on bungeecord, latest.log for the rest) via mclo.gs

**Comment by seriousfreezing** [comment]
I'm having the same problem, I change the address and it tells me to change it

**Comment by Kas-tle** [comment]
> I'm having the same problem, I change the address and it tells me to change it

Please try this build: https://github.com/GeyserMC/Geyser/actions/runs/8745180547

**Comment by onebeastchris** [comment]
This issue should be resolved in the latest build. Thanks for reporting :)
