### ISSUE TITLE
Signs dissapear after relogging

### ISSUE THREAD

**Issue by InstantlyMoist** [GeyserMC/Geyser#4588]
### Describe the bug

Existing and newly placed signs will get replaced by an empty hitbox when relogged. This means hanging and standing signs

![image](https://github.com/GeyserMC/Geyser/assets/32609460/0a7cad98-ef86-4c75-a07c-1421f401b257)

### To Reproduce

1. Place a sign
2. Relog
3. The sign is now gone, but the hitbox is still there.

### Expected behaviour

The sign should remain there, with text on it.

### Server Version and Plugins

[16:07:19 INFO]: This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[16:07:19 INFO]: Previous version: git-Paper-e3bf31e5f (MC: 1.12.2)
[16:07:19 INFO]: Checking version, please wait...
[16:07:23 WARN]: java.lang.NumberFormatException: For input string: ""
[16:07:23 WARN]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
[16:07:23 WARN]:        at java.base/java.lang.Integer.parseInt(Integer.java:658)
[16:07:23 WARN]:        at java.base/java.lang.Integer.valueOf(Integer.java:963)
[16:07:23 WARN]:        at java.base/java.lang.Integer.decode(Integer.java:1448)
[16:07:23 WARN]:        at org.bukkit.command.defaults.VersionCommand.getFromJenkins(VersionCommand.java:295)
[16:07:23 WARN]:        at org.bukkit.command.defaults.VersionCommand.getDistance(VersionCommand.java:266)
[16:07:23 WARN]:        at org.bukkit.command.defaults.VersionCommand.obtainVersion(VersionCommand.java:214)
[16:07:23 WARN]:        at org.bukkit.command.defaults.VersionCommand.access$000(VersionCommand.java:37)
[16:07:23 WARN]:        at org.bukkit.command.defaults.VersionCommand$1.run(VersionCommand.java:199)
[16:07:23 WARN]:        at java.base/java.lang.Thread.run(Thread.java:835)
[16:07:23 INFO]: Unknown version

### Geyser Dump

https://dump.geysermc.org/RAJgOc30CYC8hj7fQK7ZPn9LXgOIIJxK

### Geyser Version

Geyser versie 2.2.3-SNAPSHOT (git-master-c8475d8)

### Minecraft: Bedrock Edition Device/Version

latest downloaded from the launcher (pc)

**Comment by InstantlyMoist** [comment]
current updates:
- It doesnt appear to be caused by the environment, which was the initial thought. An empty chunk with one sign _can_ lead to this issue too. It's not consistently reproducable within each chunk.
- Might be missing a mapping:
![image](https://github.com/GeyserMC/Geyser/assets/32609460/b5e28cbf-cbd9-458b-ae8d-963494bfa2f4)

- Appears to affect some chunks only, each quartz block has a sign next to them:
![image](https://github.com/GeyserMC/Geyser/assets/32609460/83e41913-027d-44c8-96e4-d1f7da2d3c08)

**Comment by InstantlyMoist** [comment]
> Older Paper versions had a workaround where signs were not sent as part of the chunk data, but updated soon after. I assume this is related to that.
> 
> Do note that, while we will accept fixing this bug, because this bug exists on an older server version, a fix is lower priority.

How does that explain one chunk having them consistently, and one does not? I'd kind of assume none of them would have signs

**Comment by InstantlyMoist** [comment]
relevant patch: https://github.com/PaperMC/Paper/blob/ver/1.12.2/Spigot-Server-Patches/0377-Handle-Excessive-Signs-in-Chunks-creating-too-large-.patch (i think)

**Comment by InstantlyMoist** [comment]
#3004 seems related
