### ISSUE TITLE
Unable to process text in a braces in values of locale JSON

### ISSUE THREAD

**Issue by BUGTeas** [GeyserMC/Geyser#4662]
### Describe the bug

I make a language file like this:
```json
{ "my.test.locale.translation": "This is a word in a braces: {test content}" }
```
and execute `tellraw @a {"translate":"my.test.locale.translation"}` command to show it,
using a resource pack include this language file in Java Edition are no issues with the normal output.

I save this language file as "locales/overrides/zh_cn.json" in geyser directory and execute same command to show it, but I got empty message of empty content in Bedrock client and saw "**Failed to parse message**" error on geyser console.

### To Reproduce

1. Make a language JSON and save as "locales/overrides/zh_cn.json" in geyser directory:
```json
{ "my.test.locale.translation": "This is a word in a braces: {test content}" }
```
2. start server, join it with Bedrock client and execute `tellraw @a {"translate":"my.test.locale.translation"}`
3. got error in log:
```
[16:17:57.159 Geyser player thread-5-1/DEBUG] {"translate":"my.test.locale.translation"}
[16:17:57.163 Geyser player thread-5-1/ERROR] Failed to parse message
java.lang.IllegalArgumentException: can't parse argument number: test content
	at java.text.MessageFormat.makeFormat(Unknown Source) ~[?:?]
	at java.text.MessageFormat.applyPattern(Unknown Source) ~[?:?]
	at java.text.MessageFormat.<init>(Unknown Source) ~[?:?]
	at org.geysermc.geyser.text.MinecraftTranslationRegistry.translate(MinecraftTranslationRegistry.java:88) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.text.MinecraftTranslationRegistry.translate(MinecraftTranslationRegistry.java:41) ~[Geyser-Standalone.jar:?]
	at net.kyori.adventure.text.renderer.TranslatableComponentRenderer.renderTranslatable(TranslatableComponentRenderer.java:181) ~[Geyser-Standalone.jar:?]
	at net.kyori.adventure.text.renderer.AbstractComponentRenderer.render(AbstractComponentRenderer.java:50) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.text.MessageTranslator.convertMessage(MessageTranslator.java:153) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:62) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.translator.protocol.java.JavaSystemChatTranslator.translate(JavaSystemChatTranslator.java:38) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[Geyser-Standalone.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) [Geyser-Standalone.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [Geyser-Standalone.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser-Standalone.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [Geyser-Standalone.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NumberFormatException: For input string: "test content"
	at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	at java.lang.Integer.parseInt(Unknown Source) ~[?:?]
	... 18 more
```
4. I think it is cause by the MessageFormat. So I try to avoid it like this:
```json
{ "my.test.locale.translation": "This is a word in a braces: '{test content}'" }
```
5. Got a same error on log (every character is exactly the same)

### Expected behaviour

In Java Edition they will got normal message `This is a word in a braces: {test content}`
It's should got same result on Bedrock Edition client.

### Screenshots / Videos

https://github.com/GeyserMC/Geyser/assets/99161186/8832a63f-300b-43bb-bc8c-f398d5e39206

### Server Version and Plugins

CraftBukkit version 3871-Spigot-d2eba2c-3f9263b (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

Plugins (1): ViaVersion

### Geyser Dump

https://dump.geysermc.org/dEcdAQljWh1jvsZA89JdvwuCWamQsI0H

### Geyser Version

2.3.0-SNAPSHOT (git-master-86dafbc)

### Minecraft: Bedrock Edition Device/Version

1.20.8x

### Additional Context

This problem has been around for a long time, and it is no different on the Geyser-Spigot

**Comment by onebeastchris** [comment]
Thanks for the excellent reproduction steps! With the linked PR, curly brackets will be sent to the client exactly as they're set in the translation strings.
