### ISSUE TITLE
World and blocks not loading for bedrock players. [Geyser-Velocity] 

### ISSUE THREAD

**Issue by MaxKanoe** [GeyserMC/Geyser#4686]
### Describe the bug

The world is still there but it's invisible. It seems like the only thing the player can see is entities.

### To Reproduce

It happens whenever joining the server so idk

### Expected behaviour

Bedrock players are still kinda able to move, but it's hard to tell where you're going and you lag back every once in a while.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/159600817/955ba852-7c94-4f7a-98a2-0f44f1895506)

### Server Version and Plugins

This server is running Geyser version 2.2.3-SNAPSHOT (git-master-9cb9a14) (Java: 1.20.4, Bedrock: 1.20.40/1.20.41 - 1.20.80)

### Geyser Dump

https://dump.geysermc.org/9VFw5OAkk7mXNi2YQVBFC4wbwRz0VjTA

### Geyser Version

Velocity-Geyser - 1.20.6

### Minecraft: Bedrock Edition Device/Version

Windows 10 edition - 1.20.80

**Comment by onebeastchris** [comment]
you're running your proxy with 600megabytes of RAM, that'll be too little to use with Geyser - I'd recommend trying to assign more and see if that helps. 1.5-3GB should suffice to use Geyser

**Comment by onebeastchris** [comment]
Furthermore, please check your console for errors & send those here, if present

**Comment by MaxKanoe** [comment]
[18:55:36 ERROR]: java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.level.JavaDimension.minY()" because "dimension" is null
[18:55:36 ERROR]:       at org.geysermc.geyser.util.ChunkUtils.loadDimension(ChunkUtils.java:285)
[18:55:36 ERROR]:       at org.geysermc.geyser.translator.protocol.java.JavaLoginTranslator.translate(JavaLoginTranslator.java:145)
[18:55:36 ERROR]:       at org.geysermc.geyser.translator.protocol.java.JavaLoginTranslator.translate(JavaLoginTranslator.java:48)
[18:55:36 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
[18:55:36 ERROR]:       at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
[18:55:36 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[18:55:36 ERROR]:       at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[18:55:36 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:55:36 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:55:36 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[18:55:36 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[18:55:36 ERROR] [geyser]: Could not translate packet ClientboundLevelChunkWithLightPacket
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:407) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:86) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[server.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[server.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.3.0-SNAPSHOT (git-a9a31f69-b385)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by onebeastchris** [comment]
Please send a full latest.log file via mclo.gs

**Comment by onebeastchris** [comment]
You're also running an outdated version of Geyser; please update.

**Comment by onebeastchris** [comment]
Closing due to no further response.
