### ISSUE TITLE
An exception occurred while executing event SkinApplyEventImpl for subscriber org.geysermc.floodgate.event.EventSubscriber

### ISSUE THREAD

**Issue by mzrtamp** [GeyserMC/Geyser#4745]
### Describe the bug

[org.geysermc.floodgate.event.EventBus] An exception occurred while executing event SkinApplyEventImpl for subscriber org.geysermc.floodgate.event.EventSubscriber
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.shared.storage.adapter.StorageAdapter.getPlayerData(java.util.UUID)" because the return value of "net.skinsrestorer.shared.storage.adapter.AdapterReference.get()" is null
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinIdOfPlayer(PlayerStorageImpl.java:51) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayerResult(PlayerStorageImpl.java:112) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.storage.PlayerStorageImpl.getSkinForPlayer(PlayerStorageImpl.java:108) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.floodgate.FloodgateListener.accept(FloodgateListener.java:43) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.shared.floodgate.FloodgateListener.accept(FloodgateListener.java:32) ~[SkinsRestorer.jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fireSilently(EventBusImpl.java:37) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[floodgate-spigot.jar:?]
        at org.geysermc.event.bus.impl.EventBusImpl.fire(EventBusImpl.java:37) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.applySkin0(SpigotSkinApplier.java:85) ~[floodgate-spigot.jar:?]
        at org.geysermc.floodgate.pluginmessage.SpigotSkinApplier.lambda$applySkin0$0(SpigotSkinApplier.java:63) ~[floodgate-spigot.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1679) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:857) ~[?:?]

### To Reproduce

1. Use any version of SkinsRestorer
2. Install SkinsRestorer on the all proxy and backend servers (i also did the vice versa, only install SR on the proxy server)
3. Floodgate to all proxy and backend servers
4. Geyser only installed on the proxy server

### Expected behaviour

The skin should be immediately applied. And this not happening, just like the Java player.

### Server Version and Plugins

- git-Purpur-2176 (MC: 1.20.4)
- SkinsRestorer v15.0.13

### Geyser Dump

https://dump.geysermc.org/SZtXZ1qiXGYTsh99vOpDuOSxI0x2bPSs

### Geyser Version

2.3.1-SNAPSHOT (git-master-66f30a2)

### Minecraft: Bedrock Edition Device/Version

All mobile devices.

**Comment by onebeastchris** [comment]
That is an error on Skinsrestorer's side - they're listening to the floodgate event, but their code runs into some sort of issue. Please report it to them instead. Thanks!
