### ISSUE TITLE
[Geyser Standalone] [Build 561] ClientboundLevelChunkWithLightPacket

### ISSUE THREAD

**Issue by Teslicek** [GeyserMC/Geyser#4758]
### Describe the bug

Upon updating geyser from 549 to 561, a weird light bug started happening at my spawn.
When bedrock players join, there is an area at spawn that is completely broken.
```
[09:40:27 ERROR] Could not translate packet ClientboundLevelChunkWithLightPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.level.physics.Direction.ordinal()" because the return value of "org.geysermc.geyser.level.block.type.BlockState.getValue(org.geysermc.geyser.level.block.property.Property)" is null
        at org.geysermc.geyser.translator.level.block.entity.ShulkerBoxBlockEntityTranslator.translateTag(ShulkerBoxBlockEntityTranslator.java:45) ~[Geyser-Standalone-561.jar:?]
        at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:51) ~[Geyser-Standalone-561.jar:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:406) ~[Geyser-Standalone-561.jar:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:77) ~[Geyser-Standalone-561.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[Geyser-Standalone-561.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[Geyser-Standalone-561.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[Geyser-Standalone-561.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Geyser-Standalone-561.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Geyser-Standalone-561.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Geyser-Standalone-561.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Geyser-Standalone-561.jar:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
>....java.lang.NullPointerException: Cannot invoke "org.geysermc.geyser.level.physics.Direction.ordinal()" because the return value of "org.geysermc.geyser.level.block.type.BlockState.getValue(org.geysermc.geyser.level.block.property.Property)" is null
        at org.geysermc.geyser.translator.level.block.entity.ShulkerBoxBlockEntityTranslator.translateTag(ShulkerBoxBlockEntityTranslator.java:45)
        at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:51)
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:406)
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:77)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### To Reproduce

1. Join lifestealsmp.com from bedrock (preferably on 1.21)
2. Go to /spawn
3. You should see weird glitched chunks in front of you

### Expected behaviour

There should not be a broken chunk area.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/87967222/0a0ec47e-56bf-42ae-a204-1a9722d904e2)

### Server Version and Plugins

1.20.4, UniverseSpigot (fork of paper/pufferfish)
Floodgate Build 107

### Geyser Dump

https://dump.geysermc.org/2R7Oi1FvuaA7lm7S1XowFtMPnn1TksGX

### Geyser Version

Geyser Standalone 561

**Comment by Teslicek** [comment]
Works with this one, thanks.
