### ISSUE TITLE
[Standalone] [1.20.4] ClientboundLevelChunkWithLightPacket

### ISSUE THREAD

**Issue by Teslicek** [GeyserMC/Geyser#4765]
### Describe the bug

Error + broken chunks
```
[11:22:48 ERROR] Could not translate packet ClientboundLevelChunkWithLightPacket
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.geysermc.geyser.level.block.type.BlockState.getValue(org.geysermc.geyser.level.block.property.Property)" is null
        at org.geysermc.geyser.translator.level.block.entity.SkullBlockEntityTranslator.translateTag(SkullBlockEntityTranslator.java:62) ~[Geyser-Standalone-Test.jar:?]
        at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:51) ~[Geyser-Standalone-Test.jar:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:406) ~[Geyser-Standalone-Test.jar:?]
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:77) ~[Geyser-Standalone-Test.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[Geyser-Standalone-Test.jar:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[Geyser-Standalone-Test.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[Geyser-Standalone-Test.jar:?]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Geyser-Standalone-Test.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Geyser-Standalone-Test.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Geyser-Standalone-Test.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Geyser-Standalone-Test.jar:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
>....java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "org.geysermc.geyser.level.block.type.BlockState.getValue(org.geysermc.geyser.level.block.property.Property)" is null
        at org.geysermc.geyser.translator.level.block.entity.SkullBlockEntityTranslator.translateTag(SkullBlockEntityTranslator.java:62)
        at org.geysermc.geyser.translator.level.block.entity.BlockEntityTranslator.getBlockEntityTag(BlockEntityTranslator.java:51)
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:406)
        at org.geysermc.geyser.translator.protocol.java.level.JavaLevelChunkWithLightTranslator.translate(JavaLevelChunkWithLightTranslator.java:77)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89)
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### To Reproduce

Not known.

### Expected behaviour

Normal chunks.

### Screenshots / Videos

![image](https://github.com/GeyserMC/Geyser/assets/87967222/09abbdb6-f43e-4516-82bb-8aa6c21558e9)

### Server Version and Plugins

UniverseSpigot 1.20.4
Floodgate b107

### Geyser Dump

https://dump.geysermc.org/gLsGeKMeqEpbm0l2Ka5hHIoP80q8BcKL

### Geyser Version

29928c2

**Comment by onebeastchris** [comment]
Could you test the linked PR, and see if that resolves the issue?

**Comment by Teslicek** [comment]
Fixed, thanks.
