### ISSUE TITLE
Latest Fabric build crashes prior to 1.21

### ISSUE THREAD

**Issue by macarooni-man** [GeyserMC/Geyser#4767]
### Describe the bug

Historically, using the latest version of Geyser on legacy servers was successful. This holds true using the latest Bukkit version of Geyser on various Bukkit derivatives with 1.20.5/6.

As of the update to 1.21, specifically the latest Fabric version of Geyer refuses to run on legacy servers when historically this wasn't the case. I noticed in the error that it now depends on 1.21 and I'm wondering if this is intentional, or if there is another branch or specific version for legacy servers as I'm unable to locate old downloads on the website. Thanks!

### To Reproduce

1. [Install the latest version of Fabric](https://meta.fabricmc.net/v2/versions/loader/1.21/0.15.11/1.0.1/server/jar)
2. Install Geyser-Fabric 2.4.0 (build #567)

### Expected behaviour

```[23:36:38] [main/WARN]: Mod resolution failed
[23:36:38] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED geyser-fabric 2.4.0-SNAPSHOT {depends minecraft @ [>=1.21]}, ROOT_FORCELOAD_SINGLE geyser-fabric 2.4.0-SNAPSHOT]
[23:36:38] [main/INFO]: Reason: [HARD_DEP geyser-fabric 2.4.0-SNAPSHOT {depends minecraft @ [>=1.21]}]
[23:36:38] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-models-v0, fabric-client-tags-api-v1, fabric-sound-api-v1, fabric-rendering-v0, fabric-screen-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[23:36:38] [main/INFO]: Fix: add [], remove [], replace [[geyser-fabric 2.4.0-SNAPSHOT] -> add:geyser-fabric 1 ([(-∞,∞)])]
[23:36:38] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Geyser-Fabric' (geyser-fabric) 2.4.0-SNAPSHOT with any version that is compatible with:
		 - minecraft 1.20.5
More details:
	 - Mod 'Geyser-Fabric' (geyser-fabric) 2.4.0-SNAPSHOT requires version 1.21 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]
```

### Geyser Version

geyser-fabric 2.4.0-SNAPSHOT

### Minecraft: Bedrock Edition Device/Version

Tested on Fabric and Paper on both 1.21 and 1.20.5/6

### Additional Context

The latest version of Geyser on Bukkit works on both 1.20.5/6 and 1.21. The issue only appears to be present on the Fabric build.

**Comment by onebeastchris** [comment]
This is working as intended - the latest Fabric/NeoForge builds only support 1.21. Unlike Spigot/Paper, it's not simple to maintain one build for multiple versions on Fabric. We're looking into possible ideas though, so that may exist in the future.

For the time being, you can download 1.20.6 compatible Geyser-Fabric builds on our modrinth page (https://modrinth.com/mod/geyser). However, once a new Bedrock version releases, those will unfortunately not receive an update to support that latest version. 
For that case, you'll have to look into:
- either running Geyser on a proxy (with ViaVersion to translate to 1.21 protocol), or
- using Geyser-ViaProxy on a ViaProxy server to then connect to the older fabric server.

**Comment by virtualspan** [comment]
Adding on to the comment above, if you are self-hosting, it's best to just use Geyser-Standalone instead, if you do not need a proxy for any other reason, apart from Geyser. More info is available on the [wiki](https://wiki.geysermc.org/geyser/setup/) (Click on the "Self-Hosting" tab then click on "Standalone" to go to the right page).

**Comment by macarooni-man** [comment]
I appreciate all the information! Thank you! I didn't realize the project was on Modrinth, I'll make something to use that instead. Take care
