### ISSUE TITLE
[Standalone] Could not translate packet InventoryTransactionPacket

### ISSUE THREAD

**Issue by Teslicek** [GeyserMC/Geyser#4768]
### Describe the bug

```
[19:23:55.517 Geyser player thread-5-20/ERROR] Could not translate packet InventoryTransactionPacket
java.lang.ArrayIndexOutOfBoundsException: Index 46 out of bounds for length 46
	at org.geysermc.geyser.inventory.Inventory.getItem(Inventory.java:122) ~[Geyser-Standalone-Test2.jar:?]
	at org.geysermc.geyser.translator.protocol.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:131) ~[Geyser-Standalone-Test2.jar:?]
	at org.geysermc.geyser.translator.protocol.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:90) ~[Geyser-Standalone-Test2.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[Geyser-Standalone-Test2.jar:?]
	at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[Geyser-Standalone-Test2.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[Geyser-Standalone-Test2.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Geyser-Standalone-Test2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Geyser-Standalone-Test2.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Geyser-Standalone-Test2.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Geyser-Standalone-Test2.jar:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```

### To Reproduce

No idea.

### Expected behaviour

No error.

### Server Version and Plugins

UniverseSpigot 1.20.4
Floodgate b107

### Geyser Dump

https://dump.geysermc.org/ArdwsnehOX0dAsAkZldwfFILN705UOVv

### Geyser Version

2827e48

### Additional Context

I found this error while going through the geyser logs. I have no idea what it causes nor how to reproduce it. Was told to report it here just in case.

**Comment by onebeastchris** [comment]
Should be resolved with https://github.com/GeyserMC/Geyser/commit/d63e82c
