### ISSUE TITLE
Empty supported_items throws StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rwnd-bradley** [GeyserMC/Geyser#4843]
### Describe the bug

```
[01:57:35 ERROR] [geyser]: Could not translate packet ClientboundRegistryDataPacket
java.lang.StringIndexOutOfBoundsException: Range [1, 0) out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213) ~[?:?]
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349) ~[?:?]
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4865) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2834) ~[?:?]
        at java.base/java.lang.String.substring(String.java:2807) ~[?:?]
        at org.geysermc.geyser.item.enchantment.Enchantment.read(Enchantment.java:59) ~[?:?]
        at org.geysermc.geyser.session.cache.RegistryCache.lambda$static$5(RegistryCache.java:81) ~[?:?]
        at org.geysermc.geyser.session.cache.RegistryCache.lambda$register$18(RegistryCache.java:170) ~[?:?]
        at org.geysermc.geyser.session.cache.RegistryCache.load(RegistryCache.java:140) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.JavaRegistryDataTranslator.translate(JavaRegistryDataTranslator.java:38) ~[?:?]
        at org.geysermc.geyser.translator.protocol.java.JavaRegistryDataTranslator.translate(JavaRegistryDataTranslator.java:33) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:89) ~[?:?]
        at org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:69) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.3.0-SNAPSHOT (git-c71c6205)]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[velocity.jar:3.3.0-SNAPSHOT (git-c71c6205)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.3.0-SNAPSHOT (git-c71c6205)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.3.0-SNAPSHOT (git-c71c6205)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.3.0-SNAPSHOT (git-c71c6205)]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

https://github.com/GeyserMC/Geyser/blob/7fdb410d26f8759c906d6673eacce9f60d00ff4b/core/src/main/java/org/geysermc/geyser/item/enchantment/Enchantment.java#L59

### To Reproduce

Create a custom enchant using Paper's lifecycle API or through a datapack and provide an empty list for supported_items.

### Expected behaviour

No error.

### Geyser Version

2.4.0-b598 (git-master-7fdb410)

**Comment by Konicai** [comment]
Hi, thanks for looking into the relevant code! This was already reported in #4834 and will soon be fixed by #4836
