### ISSUE TITLE
Error on joining to server via bedrock edition

### ISSUE THREAD

**Issue by Shadodd** [GeyserMC/Geyser#4852]
### Describe the bug

Error when I try to log into the server via bedrock edition
`[18:51:30 WARN]: [io.netty.channel.ChannelInitializer] Failed to initialize a channel. Closing: [id: 0x064753ad, L:/[0:0:0:0:0:0:0:0%0]:16963 ! R:/37.23.167.76:55377]
java.lang.NoClassDefFoundError: Could not initialize class org.cloudburstmc.protocol.bedrock.PacketDirection
        at org.cloudburstmc.protocol.bedrock.netty.initializer.BedrockServerInitializer.preInitChannel(BedrockServerInitializer.java:12) ~[Geyser-Spigot.jar:?]
        at org.cloudburstmc.protocol.bedrock.netty.initializer.BedrockChannelInitializer.initChannel(BedrockChannelInitializer.java:33) ~[Geyser-Spigot.jar:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: 'packet_direction' is already in use [in thread "epollEventLoopGroup-42-1"]
        at io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:108) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.util.ConstantPool.newInstance(ConstantPool.java:90) ~[patched_1.17.1.jar:git-Paper-411]
        at io.netty.util.AttributeKey.newInstance(AttributeKey.java:55) ~[patched_1.17.1.jar:git-Paper-411]
        at org.cloudburstmc.protocol.bedrock.PacketDirection.<clinit>(PacketDirection.java:18) ~[Geyser-Spigot.jar:?]
        ... 20 more
`

### To Reproduce

Idk

### Expected behaviour

I just sat there setting up texture packs, rebooted the server, and then you just Refused to log into the server on the bedrock edition, giving this error,Maybe this is not a geyser error? Could this be due to problems with hosting?

### Server Version and Plugins

Server: 1.17.1 paper
Plugins (52): AdvancedEnchantments, AntiRelog, AuthMe, BanItem, BetterCommandSpy, BetterTalismans, BlockedCmds*, ChatEx, ChestCommands*, Citizens, Clans, CoreProtect, CrazyAuctions, DeluxeMenus, DiscordSRV, DonateCase, EliteRTP, EnotGranter*, Essentials, EssentialsSpawn, ExecutableItems, FastAsyncWorldEdit (WorldEdit), Geyser-Spigot, HeadDatabase, HealthBar*, HideStream*, LiteBans, LuckPerms, Matrix, MobsManager, MyCommand, MyPads, NBTAPI, NoLagg*, Pholo*, PlaceholderAPI, PlayerKits, PlayerManagementPlugin, PlayerPoints, ProHolographicDisplays (HolographicDisplays), ProtocolLib, sBroadcast*, SCore, SkinsRestorer, TAB, Vault, ViaBackwards, ViaVersion, voicechat, WGExtender, WorldGuard, YouTube*

### Geyser Version

Build #599, PaperSpigot version

### Minecraft: Bedrock Edition Device/Version

1.21.2

**Comment by Camotoy** [comment]
This is almost definitely a plugin conflict. Please try the following:

> If you have a possible plugin interfering with Geyser or Floodgate, follow these steps to find the culprit plugin:
>Temporarily remove/move half of your plugins from your server's plugins folder.
>If the problem persists, remove another half.
>If the problem goes away, swap that half of your plugins with the other half.
> Keep repeating this pattern, this time with the half that exhibits the problem, until you find your problematic plugin.

**Comment by onebeastchris** [comment]
Further, did you reload the server? I've seen this happening with reloads; but not every time

**Comment by Shadodd** [comment]
> Further, did you reload the server? I've seen this happening with reloads; but not every time

Yea, i did reload, like reload confirm, maybe i have need restart server? Ill try it tomorrow, now i going sleep

**Comment by onebeastchris** [comment]
Reloading isn't officially supported. Please restart the server, and it'll work

**Comment by Shadodd** [comment]
Thx, it works, onebeastchris, thanks
