### ISSUE TITLE
Problem with limitation of the custom-skulls.yml file?

### ISSUE THREAD

**Issue by thedarkonekiller** [GeyserMC/Geyser#4887]
### Describe the bug

I made a program to retrieve all the hashes from the custom heads, but when I start my proxy I get this error message, so I think there is a limitation, right?

I have 77,895 lines in total, I tried to reduce to 33,000 lines I have no more errors but geyser does not load (impossible to connect)

### To Reproduce

`
[14:23:59 INFO] [geyser]: ******************************************
[14:23:59 INFO] [geyser]: 
[14:23:59 INFO] [geyser]: Loading Geyser version 2.4.0-b617 (git-master-1dd9ba3)
[14:23:59 INFO] [geyser]: 
[14:23:59 INFO] [geyser]: ******************************************
[14:23:59 INFO] [geyser]: Registered 139 custom items
[14:24:00 ERROR] [geyser]: Failed to read/create config.yml! Make sure it's up to date and/or readable+writable!
org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.JsonMappingException: The incoming YAML document exceeds the limit: 3145728 code points.
 at [Source: (File); line: 45924, column: 69] (through reference chain: org.geysermc.geyser.configuration.GeyserCustomSkullConfiguration["skin-hashes"]->java.util.ArrayList[45890])
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:223) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:184) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:27) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3713) ~[?:?]
        at org.geysermc.geyser.util.FileUtils.loadConfig(FileUtils.java:63) ~[?:?]
        at org.geysermc.geyser.registry.populator.CustomSkullRegistryPopulator.populate(CustomSkullRegistryPopulator.java:67) ~[?:?]
        at org.geysermc.geyser.registry.BlockRegistries.<clinit>(BlockRegistries.java:135) ~[?:?]
        at org.geysermc.geyser.registry.populator.CreativeItemRegistryPopulator.populate(CreativeItemRegistryPopulator.java:69) ~[?:?]
        at org.geysermc.geyser.registry.populator.ItemRegistryPopulator.populate(ItemRegistryPopulator.java:173) ~[?:?]
        at org.geysermc.geyser.registry.Registries.<clinit>(Registries.java:171) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.initialize(GeyserImpl.java:238) ~[?:?]
        at org.geysermc.geyser.GeyserImpl.start(GeyserImpl.java:814) ~[?:?]
        at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onGeyserEnable(GeyserVelocityPlugin.java:124) ~[?:?]
        at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onProxyBound(GeyserVelocityPlugin.java:201) ~[?:?]
        at org.geysermc.geyser.platform.velocity.Lmbda$18.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-411.jar:3.3.0-SNAPSHOT (git-a4476253-b411)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.dataformat.yaml.JacksonYAMLParseException: The incoming YAML document exceeds the limit: 3145728 code points.
 at [Source: (File); line: 45924, column: 69]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:443) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.core.JsonParser.nextTextValue(JsonParser.java:1161) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:203) ~[?:?]
        ... 25 more
Caused by: org.geysermc.geyser.platform.velocity.shaded.org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
        at org.geysermc.geyser.platform.velocity.shaded.org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:317) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntryKey.produce(ParserImpl.java:537) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:161) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:170) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:437) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.core.JsonParser.nextTextValue(JsonParser.java:1161) ~[?:?]
        at org.geysermc.geyser.platform.velocity.shaded.com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:203) ~[?:?]
        ... 25 more
`

### Expected behaviour

be able to have all the custom heads

### Server Version and Plugins

velocity-3.3.0-SNAPSHOT-411.jar

### Geyser Version

Geyser-Velocity#617.jar

**Comment by Kas-tle** [comment]
Even if you could do this, it would certainly lead to the Bedrock client crashing on loading the resource pack. I would recommend not exceeding ~1000 heads.

**Comment by onebeastchris** [comment]
You really, really, really should not register anywhere close to that amount of skulls. Each skull in that file will be sent as a custom block to Bedrock, and that's limited to around ~2-3 thousand. And it can be even less due to texture size limits, or weak devices, etc. 

You should only add skulls in that file that must show up in the inventory - skulls not in that file will still render fine when placed on the ground, or when equipped on players.

**Comment by thedarkonekiller** [comment]
ok it's a shame these limitations :( cursed bedrock. The goal was to be able to give them access to head database, so it's dead..... Thank you for your answers
