### ISSUE TITLE
High Ping on Bedrock Client

### ISSUE THREAD

**Issue by superwfox** [GeyserMC/Geyser#4973]
### Describe the bug

After I changed a PC, I started the server and found that the Java player was normal, but the bedrock version of the player's game was extremely delayed and very stuck, and there was an error in the console：

`[14:38:23 ERROR]: [org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec] [/117.152.159.131:19301] Error while ticking RakSessionCodec state=CONNECTED channelActive=true
java.lang.NullPointerException: Cannot invoke "org.cloudburstmc.netty.channel.raknet.packet.RakDatagramPacket.getNextSend()" because "datagram" is null
        at Geyser-Spigot.jar/org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.sendStaleDatagrams(RakSessionCodec.java:527) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.internalFlush(RakSessionCodec.java:462) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.onTick(RakSessionCodec.java:425) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.cloudburstmc.netty.handler.codec.raknet.common.RakSessionCodec.tryTick(RakSessionCodec.java:393) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] `

### To Reproduce

-

### Expected behaviour

Bedrock Player has the right ping,

### Server Version and Plugins

Purpur-1.21.1 with Geyser.jar

### Geyser Version

Latest Release

**Comment by lolwhatdidigetbanned** [comment]
Is your pc near the bedrock players locations? They can be out of range or is forward Minecraft ping on? These can be reasons why :/ try updating geyser see if that fixes it

**Comment by superwfox** [comment]
ah🙏🏿I found that the problem is that the server runs on Intel's E core. My previous PC is on the AMD platform. There is no E and P core. I'm speechless.

**Comment by lolwhatdidigetbanned** [comment]
> ah🙏🏿I found that the problem is that the server runs on Intel's E core. My previous PC is on the AMD platform. There is no E and P core. I'm speechless.

Next time tell your pc name, thx! You may close it as finished or not planned
