### ISSUE TITLE
Bedrock client "end of stream" problem

### ISSUE THREAD

**Issue by whitebear13579** [GeyserMC/Geyser#5007]
### Describe the bug

when the bedrock client attempts to connect, the end of stream screen will pop up and the connection cannot be made
![image](https://github.com/user-attachments/assets/07d9467f-9d22-40c4-9726-f85644b648b9)

### To Reproduce

same as above section

### Expected behaviour

players should connect to the server normally

### Server Version and Plugins

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)* Previous: 1.21.1-2285-abf2f21 (MC: 1.21.1)

Plugins:
AdvancedPortals, BlockLocker, Citizens, ClearLag, CMILib, CoreProtect, DecentHolograms, DiscordSRV, Essentials, EssentialsChat, EssentialsSpawn, FastLeafDecay, floodgate, Geyser-Spigot, GSit, Harbor, HeadDrop, HoloMobHealth, InsaneAnnouncer, InventoryRollbackPlus, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, JukeBox, LuckPerms, Maintenance, Multiverse-Core, Multiverse-NetherPortals, NoPlugins, NoteBlockAPI, PlaceholderAPI, PlugManX, ProtocolLib, Residence, ResourceWorld, ServerListPlus, ShulkerPacks, SmoothTimber, SuperVanish, TabList, TabTPS, UnsignedMessages, Vault, Veinminer, ViaBackwards, ViaRewind, ViaVersion, WorldEdit

### Geyser Dump

https://dump.geysermc.org/nfTmxm82O14KQ8NkYGJEjP2KwXr9JONU

### Geyser Version

Build #658 · 2024/8/28

### Minecraft: Bedrock Edition Device/Version

1.21.2, Android

**Comment by whitebear13579** [comment]
Console log:
```
[17:22:47 INFO]: [Geyser-Spigot] Player connected with username huangpeter 0908
[17:22:47 INFO]: [Geyser-Spigot] huangpeter 0908 (logged in as: huangpeter_0908) has connected to the Java server
[17:22:47 WARN]: java.lang.reflect.InvocationTargetException
[17:22:47 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
[17:22:47 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[17:22:47 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:212)
[17:22:47 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:145)
[17:22:47 WARN]:        at floodgate-spigot.jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInbound(NettyChannelInjector.java:441)
[17:22:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:47)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[17:22:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.InboundProtocolReader.channelRead(InboundProtocolReader.java:25)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
[17:22:47 WARN]:        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[17:22:47 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[17:22:47 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[17:22:47 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[17:22:48 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:22:48 WARN]:        at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299)
[17:22:48 WARN]:        at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834)
[17:22:48 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[17:22:48 WARN]:        at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:144)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:837)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814)
[17:22:48 WARN]:        at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290)
[17:22:48 WARN]:        at io.netty.channel.DefaultChannelConfig.setAutoRead(DefaultChannelConfig.java:341)
[17:22:48 WARN]:        at net.minecraft.network.UnconfiguredPipelineHandler.lambda$setupInboundHandler$0(UnconfiguredPipelineHandler.java:23)
[17:22:48 WARN]:        at net.minecraft.network.UnconfiguredPipelineHandler$Inbound.write(UnconfiguredPipelineHandler.java:48)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:48 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:102)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:48 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:48 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[17:22:48 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.platform.spigot.GeyserSpigotCompressionDisabler.write(GeyserSpigotCompressionDisabler.java:90)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[17:22:48 WARN]:        at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
[17:22:48 WARN]:        at net.minecraft.network.Connection$2.write(Connection.java:771)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[17:22:48 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[17:22:48 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.network.netty.ChannelWrapper.writeAndFlush(ChannelWrapper.java:219)
[17:22:48 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[17:22:48 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[17:22:48 WARN]:        at net.minecraft.network.Connection.setupInboundProtocol(Connection.java:376)
[17:22:48 WARN]:        at net.minecraft.server.network.ServerHandshakePacketListenerImpl.beginLogin(ServerHandshakePacketListenerImpl.java:132)
[17:22:48 WARN]:        at net.minecraft.server.network.ServerHandshakePacketListenerImpl.handleIntention(ServerHandshakePacketListenerImpl.java:47)
[17:22:48 WARN]:        at net.minecraft.network.protocol.handshake.ClientIntentionPacket.handle(ClientIntentionPacket.java:32)
[17:22:48 WARN]:        at net.minecraft.network.protocol.handshake.ClientIntentionPacket.handle(ClientIntentionPacket.java:9)
[17:22:48 WARN]:        at net.minecraft.network.Connection.genericsFtw(Connection.java:325)
[17:22:48 WARN]:        at net.minecraft.network.Connection.channelRead0(Connection.java:306)
[17:22:48 WARN]:        at net.minecraft.network.Connection.channelRead0(Connection.java:70)
[17:22:48 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[17:22:48 WARN]:        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
[17:22:48 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[17:22:48 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[17:22:48 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[17:22:48 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:22:48 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:22:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[17:22:48 WARN]: Caused by: java.lang.IllegalArgumentException: The name of the profile contains invalid characters: P–huangpeter_090
[17:22:48 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
[17:22:48 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.createAuthLibProfile(CraftPlayerProfile.java:274)
[17:22:48 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:41)
[17:22:48 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.clone(CraftPlayerProfile.java:166)
[17:22:48 WARN]:        at com.destroystokyo.paper.profile.CraftPlayerProfile.asAuthlibCopy(CraftPlayerProfile.java:301)
[17:22:48 WARN]:        at net.minecraft.server.network.ServerLoginPacketListenerImpl.callPlayerPreLoginEvents(ServerLoginPacketListenerImpl.java:370)
[17:22:48 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[17:22:48 WARN]:        ... 120 more
[17:22:48 INFO]: [floodgate] Floodgate player logged in as P–huangpeter_090 disconnected
[17:22:48 INFO]: [Geyser-Spigot] huangpeter 0908 has disconnected from the Java server because of End of stream
[17:22:48 INFO]: /XXX.XXX.XXX.XXX:0 lost connection: Disconnected
```

**Comment by onebeastchris** [comment]
Your floodgate prefix `P-` is not valid.
