### ISSUE TITLE
End of Stream in bedrock players when joining 

### ISSUE THREAD

**Issue by JoshuaPHYT** [GeyserMC/Geyser#5027]
### Describe the bug

[05:02:41 WARN]: java.lang.NullPointerException
[05:02:41 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
[05:02:41 WARN]:        at java.base/java.lang.invoke.DirectMethodHandle.checkBase(DirectMethodHandle.java:547)
[05:02:41 WARN]:        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.get(MethodHandleObjectFieldAccessorImpl.java:57)
[05:02:41 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:444)
[05:02:41 WARN]:        at floodgate-spigot (13).jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.checkAndHandleLogin(SpigotDataHandler.java:150)
[05:02:41 WARN]:        at floodgate-spigot (13).jar//org.geysermc.floodgate.addon.data.SpigotDataHandler.channelRead(SpigotDataHandler.java:145)
[05:02:41 WARN]:        at floodgate-spigot (13).jar//org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[05:02:41 WARN]:        at ProtocolLib (13).jar//com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInbound(NettyChannelInjector.java:441)
[05:02:41 WARN]:        at ProtocolLib (13).jar//com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:47)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[05:02:41 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[05:02:41 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[05:02:41 WARN]:        at ProtocolLib (13).jar//com.comphenix.protocol.injector.netty.channel.InboundProtocolReader.channelRead(InboundProtocolReader.java:25)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
[05:02:41 WARN]:        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
[05:02:41 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
[05:02:41 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[05:02:41 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
[05:02:41 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[05:02:41 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[05:02:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### To Reproduce

In the first join after a restart or a long login, my players encounter the error "end of stream." When I look in the console, this is the error message.

### Expected behaviour

they should join normally without error

### Server Version and Plugins

1.21.1-2301-a43711d (MC: 1.21.1)

### Geyser Dump

https://dump.geysermc.org/5vQOAkmgLahwqrkUE3AQctnHWtRYDjL3

### Geyser Version

[05:10:10 INFO]: This server is running Geyser version 2.4.2-b647 (git-master-0bc39d5) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.20)

### Minecraft: Bedrock Edition Device/Version

Latest 1.21/Mobile

**Comment by PxLinee** [comment]
I also have the same problem here, lemme know if we found a fix please

**Comment by pollywantza** [comment]
Also have the same issue

**Comment by GidMinecraft** [comment]
The same! Please, tell, when there will be answer

**Comment by Uuugh** [comment]
Same result on a new server
NeoForge 1.21.1
  Geyser-NeoForge 2.6.0-b744 (1.21.4)
  Floodgate-Neoforge-2.2.4-b38.jar
  viaforge-mc1206-3.9.0
From a Bedrock Client 1.21.4

[00:01:11] [Server thread/INFO] [geyser/]: ******************************************
[00:01:11] [Server thread/INFO] [geyser/]: 
[00:01:11] [Server thread/INFO] [geyser/]: Loading Geyser version 2.6.0-b744 (git-master-1267b2e)
[00:01:11] [Server thread/INFO] [geyser/]: 
[00:01:11] [Server thread/INFO] [geyser/]: ******************************************
[00:01:13] [epollEventLoopGroup-3-1/INFO] [geyser/]: Started Geyser on UDP port 19132
[00:01:13] [Server thread/INFO] [geyser/]: Done (1.45s)! Run /geyser help for help!
[00:01:13] [Server thread/INFO] [floodgate/]: Took 14ms to boot Floodgate
[00:01:21] [epollEventLoopGroup-4-1/INFO] [geyser/]: Player connected with username Uuugh72
[00:01:21] [localSession-7-1/INFO] [geyser/]: Uuugh72 (logged in as: Uuugh72) has connected to the Java server
[00:01:22] [pool-9-thread-1/INFO] [floodgate/]: Floodgate player who is logged in as .Uuugh72 00000000-0000-0000-0009-01f188c3f851 joined
[00:01:22] [localSession-7-1/INFO] [geyser/]: Uuugh72 has disconnected from the Java server because of End of stream
[00:01:22] [Geyser NeoForge connection thread-6-2/INFO] [floodgate/]: Floodgate player logged in as .Uuugh72

**Comment by Uuugh** [comment]
BTW. I get the same result with Geyser version 2.6.0-b744 (git-master-1267b2e)... it's the correct version for 1.21.1

**Comment by Uuugh** [comment]
Also end of stream with viaforge-mc189-3.7.0 & viaforge-mc1204-3.7.0. I'm wondering if Floodgate and viaforge aren't playing nice together.

**Comment by esguelcher** [comment]
Still waiting here, I haven’t found an answer

**Comment by onebeastchris** [comment]
"End of Stream" or ""Unable to connect " can be caused by a number of causes. There's no blanket fix for it, look at your server logs, and that should tell you what's going on. If you need further help with the issue, join the Geyser discord server and ask for help there.
