### ISSUE TITLE
MySQL connection error

### ISSUE THREAD

**Issue by tiredvekster** [GeyserMC/Geyser#5032]
## Issue
Floodgate can't connect to external MySQL server.<br>
MySQL server, Iptables and the configs are fine. My own plugins, a core application and SkinRestorer work without issues.<br>
`Geyser-BungeeCord.jar`, `floodgate-bungee.jar`, `floodgate-mysql-database.jar` are updated to the latest releases.

### mysql.conf

```
hostname: "EXTERNAL_HOST"
database: "main"
username: "root"
password: "PASSWORD"
```

### Logs

```
19:01:02 [WARNING] [floodgate] en_ is not a supported Floodgate language.
19:01:02 [INFO] [floodgate] Connecting to a MySQL-like database...
19:01:33 [SEVERE] [floodgate] Error while loading database
java.sql.SQLSyntaxErrorException: No connection available within the specified time (option 'connectTimeout': 30,000 ms)
	at org.geysermc.floodgate.shaded.org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.geysermc.floodgate.shaded.org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
	at org.geysermc.floodgate.shaded.org.mariadb.jdbc.MariaDbPoolDataSource.getConnection(MariaDbPoolDataSource.java:239)
	at org.geysermc.floodgate.database.MysqlDatabase.load(MysqlDatabase.java:80)
	at org.geysermc.floodgate.link.PlayerLinkHolder.load0(PlayerLinkHolder.java:204)
	at org.geysermc.floodgate.link.PlayerLinkHolder.load(PlayerLinkHolder.java:78)
	at org.geysermc.floodgate.module.CommonModule.playerLink(CommonModule.java:137)
	at org.geysermc.floodgate.module.CommonModule$$FastClassByGuice$$1a20d6.GUICE$TRAMPOLINE(<generated>)
	at org.geysermc.floodgate.module.CommonModule$$FastClassByGuice$$1a20d6.apply(<generated>)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:260)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
	at org.geysermc.floodgate.shadow.com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
	at org.geysermc.floodgate.BungeePlugin.onLoad(BungeePlugin.java:55)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:345)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:314)
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:251)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:284)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.sql.SQLSyntaxErrorException: No connection available within the specified time (option 'connectTimeout': 30,000 ms)
	at org.geysermc.floodgate.shaded.org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.geysermc.floodgate.shaded.org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:176)
	at org.geysermc.floodgate.shaded.org.mariadb.jdbc.internal.util.pool.Pool.getConnection(Pool.java:427)
	at org.geysermc.floodgate.shaded.org.mariadb.jdbc.MariaDbPoolDataSource.getConnection(MariaDbPoolDataSource.java:237)
	... 29 more
19:01:33 [INFO] [floodgate] Took 31,973ms to boot Floodgate
```

### To Reproduce

1. Install Geyser and Foodgate on a BungeeCord server which runs on a VPS with Ubuntu 20.04 installed.
2. Configure the plugin to connect to MySQL server from a dedicated server.
3. Watch..

### Expected behaviour

No error.

### Server Version and Plugins

BungeeCord 1.21. MySQL Server 8.0.39-0ubuntu0.24.04.1.
Plugins:
* Geyser-BungeeCord
* floodgate
* SkinRestorer
* A couple of custom plugins

### Geyser Dump

https://dump.geysermc.org/EvFEORC5VwBG2jS93W6dEjzNrVuxsY4G

### Geyser Version

The latest ones from Jenkins

### Additional Context

OS is Ubuntu 24.04 on both VPS and main server.

**Comment by tiredvekster** [comment]
Oups.. I'll r
