### ISSUE TITLE
Bedrock players unable to join, stuck on connecting to multiplayer game

### ISSUE THREAD

**Issue by Blaze276** [GeyserMC/Geyser#5051]
### Describe the bug

when a bedrock player attempts to join on the latest version of geyser, this error throws in the console

Info:
Server version 1.17.1
CPU: Amd64 ryzen 9 5950x

Plugins: Chunky, discordsrv, discordsrv Utils, GeyserMC, FLoodgate, Onlinetime, Viaversion-5.0.3

(com.phono.srtplight.Log$1:60) ERROR: 1726821330542 AssocRcv1->Checksums don't match ab5b2e71 vs e228b88f
[08:35:30 INFO]: (com.phono.srtplight.Log$1:60) ERROR: 1726821330547 AssocRcv1->for packet 1388aae400000000ab5b2e710100001e8fea1ba300500000ffffffffa9fc3e86c00000048008000682c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[08:35:30 WARN]: pe.pi.sctp4j.sctp.messages.exceptions.ChecksumException
[08:35:30 WARN]:        at pe.pi.sctp4j.sctp.messages.Packet.checkChecksum(Packet.java:196)
[08:35:30 WARN]:        at pe.pi.sctp4j.sctp.messages.Packet.<init>(Packet.java:67)
[08:35:30 WARN]:        at pe.pi.sctp4j.sctp.Association$1.run(Association.java:252)
[08:35:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### To Reproduce

join a java server with geyser

### Expected behaviour

The bedrock player to connect to the server

### Geyser Dump

https://dump.geysermc.org/wTrSlgmIEllKjWQsBtCtdsAXB3pbgA8B

### Geyser Version

Latest (as of 20/09/24, 6:15 PM GMT+9:30)

### Minecraft: Bedrock Edition Device/Version

1.21.30, iPad 9th Generation, iPadOS 17.6.1

**Comment by Blaze276** [comment]
this was an error with mcxboxbroadcast
