### ISSUE TITLE
Bedrock players unable to pull Mushroom Stem block from creative

### ISSUE THREAD

**Issue by sinDeadman** [GeyserMC/Geyser#5062]
### Describe the bug

I have a bedrock player in creative and when he tries to take a mushroom stem from creative mode and use it, it pushes an error message in the server console

### To Reproduce

Player is playing on mobile
Player is in creative
Player opens creative menu
Player tries to take "Mushroom Stem" and add it to his inventory
Item does not move to inventory and triggers an error in the server console

### Expected behaviour

Expected behavior is that the item should be able to be put into the players inventory from the creative menu

### Screenshots / Videos

java.lang.NullPointerException: Cannot invoke "org.geysermc.mcprotocollib.protocol.data.game.item.ItemStack.getAmount()" because "javaCreativeItem" is null
        at Geyser-Spigot.jar/org.geysermc.geyser.translator.inventory.PlayerInventoryTranslator.translateCreativeRequest(PlayerInventoryTranslator.java:500) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:175) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:90) ~[Geyser-Spigot.jar:?]
        at Geyser-Spigot.jar/org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:70) ~[Geyser-Spigot.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:05:42 WARN]: java.lang.NullPointerException: Cannot invoke "org.geysermc.mcprotocollib.protocol.data.game.item.ItemStack.getAmount()" because "javaCreativeItem" is null
[20:05:42 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.PlayerInventoryTranslator.translateCreativeRequest(PlayerInventoryTranslator.java:500)
[20:05:42 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.inventory.InventoryTranslator.translateRequests(InventoryTranslator.java:175)
[20:05:42 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:48)
[20:05:42 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.translator.protocol.bedrock.BedrockItemStackRequestTranslator.translate(BedrockItemStackRequestTranslator.java:38)
[20:05:42 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.translate0(PacketTranslatorRegistry.java:90)
[20:05:42 WARN]:        at Geyser-Spigot.jar//org.geysermc.geyser.registry.PacketTranslatorRegistry.lambda$translate$0(PacketTranslatorRegistry.java:70)
[20:05:42 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[20:05:42 WARN]:        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
[20:05:42 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:05:42 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:05:42 WARN]:        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[20:05:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Server Version and Plugins

Server is on 1.21.1 with Geyser version from 9/17/2024

### Geyser Dump

https://dump.geysermc.org/CI9lW1J4HecnGHNl5zv0vPJK3OVrlJn0

### Geyser Version

7332c6b

### Minecraft: Bedrock Edition Device/Version

Mobile Phone Bedrock 1.21.30

**Comment by onebeastchris** [comment]
related to https://github.com/GeyserMC/Geyser/issues/4367

**Comment by onebeastchris** [comment]
Will be resolved with https://github.com/GeyserMC/Geyser/pull/5603
