### ISSUE TITLE
Exception occurs on latest geyser version (2.4.3-b685 (git-master-ef4acb1))

### ISSUE THREAD

**Issue by xXkguyXx** [GeyserMC/Geyser#5076]
### Describe the bug

An exception occurs when updating to the latest version of geyser.

[23:18:18] [epollEventLoopGroup-4-2/INFO] [geyser]: Player connected with username XXXXX
[23:18:18] [localSession-6-1/WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0x1f4c321f]
java.lang.NullPointerException: Cannot invoke "java.net.InetSocketAddress.getAddress()" because "remoteAddress" is null
	at org.geysermc.geyser.network.netty.LocalSession.initializeHAProxySupport(LocalSession.java:156) ~[?:?]
	at org.geysermc.geyser.network.netty.LocalSession$1.initChannel(LocalSession.java:104) ~[?:?]
	at org.geysermc.geyser.network.netty.LocalSession$1.initChannel(LocalSession.java:95) ~[?:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1130) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[Velocity.jar:3.3.0-SNAPSHOT (git-2016d148-b436)]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[23:18:18] [localSession-6-1/INFO] [geyser]: XXXXX has disconnected from the Java server because of Internal Exception: io.netty.channel.StacklessClosedChannelException

### To Reproduce

Run a proxy with HA Proxy support

### Expected behaviour

It works :D

### Geyser Version

Geyser version 2.4.3-b685 (git-master-ef4acb1)

**Comment by nicolube** [comment]
@xXkguyXx Do u receive or sending  haproxy.

If u receive haproxy (client -> haproxy -> geyser), do u receive v1 or v2 proxy protocol?

**Comment by andrewkm** [comment]
I too have been experiencing this ever since https://github.com/GeyserMC/Geyser/commit/c656e415f36dd04233559e01ed192224f4725d37.
@Camotoy said it would be fixed soon and to instead use https://github.com/GeyserMC/Geyser/commit/482089379228eb93b2a423dd42f97d8138eaf325

**Comment by xXkguyXx** [comment]
Sounds good, thanks

**Comment by onebeastchris** [comment]
fixed with https://github.com/GeyserMC/Geyser/commit/50de9d6867ac66184c459aef104195d10660dcb7 - thanks for reporting the issue!
