### ISSUE TITLE
Packets cannot be translated.

### ISSUE THREAD

**Issue by AsyncProxy** [GeyserMC/Geyser#5077]
### Describe the bug

[17:06:42 ERROR] 无法翻译数据包 ClientboundAddEntityPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.mcprotocollib.protocol.data.game.entity.type.EntityType.name()" because "type" is null
        at org.geysermc.geyser.util.EntityUtils.translatedEntityName(EntityUtils.java:312) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.Entity.standardDisplayName(Entity.java:455) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.Entity.<init>(Entity.java:145) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.living.monster.EnderDragonPartEntity.<init>(EnderDragonPartEntity.java:38) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.living.monster.EnderDragonEntity.spawnEntity(EnderDragonEntity.java:120) ~[Geyser.jar:?]
        at org.geysermc.geyser.session.cache.EntityCache.spawnEntity(EntityCache.java:72) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.entity.spawn.JavaAddEntityTranslator.translate(JavaAddEntityTranslator.java:127) ~[Geyser.jar:?]

### To Reproduce

Not at the moment

### Expected behaviour

Packets are translated normally.

### Geyser Version

1.21.1

### Minecraft: Bedrock Edition Device/Version

paper1.21.1

**Comment by AsyncProxy** [comment]
> ### Describe the bug
> [17:06:42 ERROR] 无法翻译数据包 ClientboundAddEntityPacket java.lang.NullPointerException: Cannot invoke "org.geysermc.mcprotocollib.protocol.data.game.entity.type.EntityType.name()" because "type" is null at org.geysermc.geyser.util.EntityUtils.translatedEntityName(EntityUtils.java:312) ~[Geyser.jar:?] at org.geysermc.geyser.entity.type.Entity.standardDisplayName(Entity.java:455) ~[Geyser.jar:?] at org.geysermc.geyser.entity.type.Entity.(Entity.java:145) ~[Geyser.jar:?] at org.geysermc.geyser.entity.type.living.monster.EnderDragonPartEntity.(EnderDragonPartEntity.java:38) ~[Geyser.jar:?] at org.geysermc.geyser.entity.type.living.monster.EnderDragonEntity.spawnEntity(EnderDragonEntity.java:120) ~[Geyser.jar:?] at org.geysermc.geyser.session.cache.EntityCache.spawnEntity(EntityCache.java:72) ~[Geyser.jar:?] at org.geysermc.geyser.translator.protocol.java.entity.spawn.JavaAddEntityTranslator.translate(JavaAddEntityTranslator.java:127) ~[Geyser.jar:?]
> 
> ### To Reproduce
> Not at the moment
> 
> ### Expected behaviour
> Packets are translated normally.
> 
> ### Screenshots / Videos
> _No response_
> 
> ### Server Version and Plugins
> _No response_
> 
> ### Geyser Dump
> _No response_
> 
> ### Geyser Version
> 1.21.1
> 
> ### Minecraft: Bedrock Edition Device/Version
> paper1.21.1
> 
> ### Additional Context
> _No response_
