### ISSUE TITLE
Unable to translate packets.

### ISSUE THREAD

**Issue by AsyncProxy** [GeyserMC/Geyser#5078]
### Describe the bug

[17:06:42 ERROR] 无法翻译数据包 ClientboundAddEntityPacket
java.lang.NullPointerException: Cannot invoke "org.geysermc.mcprotocollib.protocol.data.game.entity.type.EntityType.name()" because "type" is null
        at org.geysermc.geyser.util.EntityUtils.translatedEntityName(EntityUtils.java:312) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.Entity.standardDisplayName(Entity.java:455) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.Entity.<init>(Entity.java:145) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.living.monster.EnderDragonPartEntity.<init>(EnderDragonPartEntity.java:38) ~[Geyser.jar:?]
        at org.geysermc.geyser.entity.type.living.monster.EnderDragonEntity.spawnEntity(EnderDragonEntity.java:120) ~[Geyser.jar:?]
        at org.geysermc.geyser.session.cache.EntityCache.spawnEntity(EntityCache.java:72) ~[Geyser.jar:?]
        at org.geysermc.geyser.translator.protocol.java.entity.spawn.JavaAddEntityTranslator.translate(JavaAddEntityTranslator.java:127) ~[Geyser.jar:?]

### To Reproduce

Not at the moment.

### Expected behaviour

Translate packets normally.

### Geyser Version

1.21.1

### Minecraft: Bedrock Edition Device/Version

paper1.21.1

**Comment by AsyncProxy** [comment]
> ### 描述 bug
> [17：06：42 错误] 无法翻译数据包 ClientboundAddEntityPacket java.lang.NullPointerException：无法调用 “org.geysermc.mcprotocollib.protocol.data.game.entity.type.EntityType.name（）”，因为 “type” 在 org.geysermc.geyser.util.EntityUtils.translatedEntityName（EntityUtils.java：312） ~[Geyser.jar：？]在 org.geysermc.geyser.entity.type.Entity.standardDisplayName（Entity.java：455） ~[Geyser.jar：？]在 org.geysermc.geyser.entity.type.Entity。（Entity.java：145） ~[Geyser.jar：？]在 org.geysermc.geyser.entity.type.living.monster.EnderDragonPartEntity。（EnderDragonPartEntity.java：38） ~[Geyser.jar：？]在 org.geysermc.geyser.entity.type.living.monster.EnderDragonEntity.spawnEntity（EnderDragonEntity.java：120） ~[Geyser.jar：？]在 org.geysermc.geyser.session.cache.EntityCache.spawnEntity（EntityCache.java：72） ~[Geyser.jar：？]在 org.geysermc.geyser.translator.protocol.java.entity.spawn.JavaAddEntityTranslator.translate（JavaAddEntityTranslator.java：127） ~[Geyser.jar：？]
> 
> ### 重现
> 目前没有。
> 
> ### 预期行为
> 正常转换数据包。
> 
> ### 截图/视频
> _无响应_
> 
> ### 服务器版本和插件
> _无响应_
> 
> ### 间歇泉垃圾场
> _无响应_
> 
> ### 间歇泉版本
> 1.21.1
> 
> ### Minecraft： Bedrock Edition 设备/版本
> 论文1.21.1
> 
> ### 其他上下文
> _无响应_

This happens when entering the End, where a fake block appears when death is reborn in the Overworld.

**Comment by Tim203** [comment]
The latest build (687) should fix this issue
