### ISSUE TITLE
An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists

### ISSUE THREAD

**Issue by Er1one** [GeyserMC/Geyser#5105]
### Describe the bug

After updating floodgate on my server, I can still log into the server from Bedrock (PC) v1.21.41, however, I cannot log into the server from the same version using a mobile device

### To Reproduce

1. Update the floodgate-velocity version to the latest
2. Try to log in to the server from the Mobile version of Bedrock

### Expected behaviour

[15:14:16 ERROR]: java.lang.NumberFormatException: For input string: ""
[15:14:16 ERROR]:       at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[15:14:16 ERROR]:       at java.base/java.lang.Long.parseLong(Long.java:719)
[15:14:16 ERROR]:       at java.base/java.lang.Long.parseLong(Long.java:832)
[15:14:16 ERROR]:       at org.geysermc.floodgate.util.Utils.getJavaUuid(Utils.java:95)
[15:14:16 ERROR]:       at org.geysermc.floodgate.addon.data.HandshakeDataImpl.<init>(HandshakeDataImpl.java:76)
[15:14:16 ERROR]:       at org.geysermc.floodgate.player.FloodgateHandshakeHandler.handlePart2(FloodgateHandshakeHandler.java:216)
[15:14:16 ERROR]:       at org.geysermc.floodgate.player.FloodgateHandshakeHandler.lambda$handle$1(FloodgateHandshakeHandler.java:184)
[15:14:16 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
[15:14:16 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
[15:14:16 ERROR]:       at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[15:14:16 ERROR]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
[15:14:16 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1583)
[15:14:16 INFO]: [initial connection] /80.251.237.74:0 has disconnected: An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists.
[15:14:16 INFO] [geyser]: Testbot отключился от сервера Java по причине An internal error happened while handling Floodgate data. Try logging in again or contact a server administrator if the issue persists.
>

### Server Version and Plugins

> floodgate version 
[15:20:53 INFO]: §7You're currently on §b2.2.3-SNAPSHOT (b112-0360721)§7 (branch: §bmaster§7)
§eFetching latest build info...
[15:20:54 INFO]: §aYou're running the latest version of Floodgate!

> velocity info
[15:21:13 INFO]: Velocity 3.3.0-SNAPSHOT (git-00ed2284-b415)
[15:21:13 INFO]: Copyright 2018-2023 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[15:21:13 INFO]: velocitypowered.com - GitHub

> geyser version
[15:21:31 INFO]: На этом сервере Geyser версии 2.4.4-b696 (git-master-6331cb6) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.40/1.21.41)
[15:21:31 INFO]: Проверка версии, пожалуйста подождите...
[15:21:33 INFO]: Обновлений нет.

### Geyser Dump

https://dump.geysermc.org/rOFLGssFlqTOF5zmYHv4lXkNRNwPTvRS

### Geyser Version

2.4.4-b696 (git-master-6331cb6) (Java: 1.21, Bedrock: 1.20.80/1.20.81 - 1.21.40/1.21.41)

### Minecraft: Bedrock Edition Device/Version

v1.21.41

**Comment by Tim203** [comment]
This one is listed on our wiki: https://geysermc.org/wiki/floodgate/issues#javalangnumberformatexception-for-input-string-
Floodgate requires an Xbox account (aka non-cracked Bedrock) to work. Stock Geyser also doesn't allow you to join without a valid Xbox account.
