### ISSUE TITLE
Bug  -  Error sending packet clientbound/minecraft:disconnect

### ISSUE THREAD

**Issue by WindowsCraft76** [GeyserMC/Geyser#5143]
### Describe the bug

When I start my server, there is this error message, I can still connect with my Java and Bedrock account.

### To Reproduce

```
[13:10:20] [Geyser Spigot connection thread-6-2/ERROR]: Error sending packet clientbound/minecraft:disconnect
--
270 | io.netty.handler.codec.EncoderException: Sending unknown packet 'clientbound/minecraft:disconnect'
271 | at net.minecraft.network.codec.IdDispatchCodec.a(SourceFile:47) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
272 | at net.minecraft.network.codec.IdDispatchCodec.encode(SourceFile:14) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
273 | at net.minecraft.network.PacketEncoder.a(SourceFile:26) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
274 | at net.minecraft.network.PacketEncoder.encode(SourceFile:12) ~[spigot-1.21.3-R0.1-SNAPSHOT.jar:4378-Spigot-e65d67a-8ef9079]
275 | at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
276 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
277 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
278 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
279 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
280 | at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:4.1.97.Final]
281 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
282 | at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
283 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
284 | at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
285 | at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
```
and it repeats itself in a loop but for a moment it stops.

### Expected behaviour

I would like to fix this.

### Server Version and Plugins

_It's a single server._
This server is running Geyser version 2.5.0-b711 (git-master-4598ffe) (Java: 1.21.3, Bedrock: 1.20.80/1.20.81 - 1.21.40 - 1.21.44)

**Plugins:**
- AFKPlus - [site](https://www.spigotmc.org/resources/afk.35065/)
- BossBar Message - [site](https://www.spigotmc.org/resources/boss-bar-message.53561/)
- DiscordSRV - [site](https://www.spigotmc.org/resources/discordsrv.18494/)
- Floodgate - [site](https://geysermc.org/download/?project=floodgate)
- GeyserMC - [site](https://geysermc.org/download/?project=geyser)
- LuckPerms - [site](https://luckperms.net/)
- Maintenance - [site](https://hangar.papermc.io/kennytv/Maintenance)
- MaxBans - [site](https://dev.bukkit.org/projects/maxbans)
- OpenInv - [site](https://dev.bukkit.org/projects/openinv)
- PlaceholderAPI - [site](https://www.spigotmc.org/resources/placeholderapi.6245/)
- Sethome - [site](https://modrinth.com/plugin/sethome-yottaka)
- SimpleSit - [site](https://www.spigotmc.org/resources/simple-sit-spigot-bukkit-1-8-8-through-1-19.14706/)
- SimpleTpa - [site](https://www.spigotmc.org/resources/simple-tpa.64270/)
- SuperVanich - [site](https://www.spigotmc.org/resources/supervanish-be-invisible.1331/)
- Vault - [site](https://www.spigotmc.org/resources/vault.34315/)
- ProtocolLib - [site](https://www.spigotmc.org/resources/protocollib.1997/)
- Orebfuscator - [site](https://www.spigotmc.org/resources/orebfuscator-anti-x-ray.82710/update?update=549545)
- AntiCreeper - [site](https://www.spigotmc.org/resources/anticreeper-1-17-x-1-21-x-prevent-explosions-damage-caused-by-them.32129/)
- JoinMessagePlus - [site](https://www.spigotmc.org/resources/joinmessageplus-1-8-1-12.42137/)
- SupremeChat - [site](https://www.spigotmc.org/resources/%E2%9C%85-supremechat-%E2%9C%85-1-16-1-21.108544/)
- SimpleTabList - [site](https://www.spigotmc.org/resources/%E2%98%86-simple-tablist-%E2%98%86%E3%80%8A1-16-x-1-20-x%E3%80%8B-animated-hex-colors.101989/)

### Geyser Dump

https://dump.geysermc.org/VlGOG0njgUNDM5IwLePCIOoOspTujjQK

### Geyser Version

2.5.0-b711 (git-master-4598ffe)

**Comment by WindowsCraft76** [comment]
ok I will test

**Comment by WindowsCraft76** [comment]
I don't know how but there is no more error, I didn't do anything...

**Comment by WindowsCraft76** [comment]
I found the bug it comes either from the **customcrafting** plugin or from **WolfyUtils**.

**Comment by WindowsCraft76** [comment]
and I also get a very big error message when a player connects. Here are the logs directly: https://mclo.gs/1VmxdGV (the first error is normal and from DiscordSRV too)

**Comment by WindowsCraft76** [comment]
and of course it doesn't do that to me when I'm not customcrafting or WolfyUtils.
