### ISSUE TITLE
IllegalAccessError in Latest Builds

### ISSUE THREAD

**Issue by metalshark** [GeyserMC/Geyser#591]
```
Exception in thread "Thread-584" java.lang.IllegalAccessError: tried to access method com.fasterxml.jackson.databind.node.TextNode.appendQuoted(Ljava/lang/StringBuilder;Ljava/lang/String;)V from class com.fasterxml.jackson.databind.node.ObjectNode
at com.fasterxml.jackson.databind.node.ObjectNode.toString(ObjectNode.java:866)
at org.geysermc.connector.metrics.Metrics.sendData(Metrics.java:210)
at org.geysermc.connector.metrics.Metrics.lambda$submitData$0(Metrics.java:187)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by LegacyGamerHD** [comment]
Update tour config

**Comment by metalshark** [comment]
Do I delete my config, restart, copy in my settings again, restart. Or is there a command to do this?

**Comment by LegacyGamerHD** [comment]
Restart ofc

**Comment by metalshark** [comment]
In the end I just disabled metrics in the config and restarted. Seems to have fixed it.
