### ISSUE TITLE
Geyser fails to translate bedrock shield packets

### ISSUE THREAD

**Issue by D3ATHBRING3R13** [GeyserMC/Geyser#644]
**Describe the bug**

Geyser fails to translate bedrock shield packets

**To Reproduce**

I don't know,  I just saw the error in the log

**Expected behavior**

no error messages

**Screenshots / Videos**

**Server Version**

git-Paper-312

**Geyser Version**

Build #188

**Minecraft: Bedrock Edition Version**

1.14.60

**Additional Context**

The only plugins are worldedit, geyser and floodgate

**Comment by RednedEpic** [comment]
> **Describe the bug**
> 
> Geyser fails to translate bedrock shield packets
> 
> **To Reproduce**
> 
> I don't know, I just saw the error in the log
> 
> **Expected behavior**
> 
> no error messages
> 
> **Screenshots / Videos**
> 
> **Server Version**
> 
> git-Paper-312
> 
> **Geyser Version**
> 
> Build #188
> 
> **Minecraft: Bedrock Edition Version**
> 
> 1.14.60
> 
> **Additional Context**
> 
> The only plugins are worldedit, geyser and floodgate

Please provide the errors from console; there isn't any way we can fix the problem without them.

**Comment by D3ATHBRING3R13** [comment]
Could not translate packet InventoryTransactionPacket
java.lang.NullPointerException: null
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:137) ~[?:?]
	at org.geysermc.connector.network.translators.bedrock.BedrockInventoryTransactionTranslator.translate(BedrockInventoryTransactionTranslator.java:58) ~[?:?]
	at org.geysermc.connector.network.translators.Registry.translate(Registry.java:64) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.translateAndDefault(UpstreamPacketHandler.java:44) ~[?:?]
	at org.geysermc.connector.network.UpstreamPacketHandler.defaultHandler(UpstreamPacketHandler.java:135) ~[?:?]
	at org.geysermc.connector.network.LoggingPacketHandler.handle(LoggingPacketHandler.java:167) ~[?:?]
	at com.nukkitx.protocol.bedrock.packet.InventoryTransactionPacket.handle(InventoryTransactionPacket.java:34) ~[?:?]
	at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:22) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:272) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:405) ~[?:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
	at org.geysermc.platform.bukkit.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
