### ISSUE TITLE
Gamemode 11 exception by joining Vanilla Hardcore

### ISSUE THREAD

**Issue by Ivennn** [GeyserMC/Geyser#663]
**Describe the bug**
When  joining vanilla hardcore on bedrock the game throws a game mode 11 exception 

**To Reproduce**
Join play.dailysurvival.be server on bedrock
type /server hardcore
see exception 

**Expected behavior**
join hardcore 

**Screenshots / Videos**
https://youtu.be/pehdWm0xSGA

**Server Version**
![image](https://user-images.githubusercontent.com/47211504/82885662-bb2bef80-9f45-11ea-986e-f8ca6213c8d2.png)
![image](https://user-images.githubusercontent.com/47211504/82886852-6be6be80-9f47-11ea-8ada-21c39170024c.png)
This server is running Travertine version git:Travertine-Bootstrap:1.15-SNAPSHOT:c00a05e:140 by md_5

**Geyser Version**
v1.14.60
Geyser version 1.0-SNAPSHOT (git-master-43ee7d6) (Tested aswel)
Geyser version 1.0-SNAPSHOT (git-master-14fcd77) 

**Minecraft: Bedrock Edition Version**
v1.14.60

**Additional Context**
The server is using floodgate.
the weird thing is if you join it directly its not a problem. If you join it form the hub it throws an exception

**Comment by rtm516** [comment]
This doesn't occur for me on my local server set to hardcore mode, can you list your plugins and if any alter gamemodes then please specify which.

**Comment by rtm516** [comment]
Also please update paper your behind by 156 updates, this may fix the issue.

**Comment by Ivennn** [comment]
![image](https://user-images.githubusercontent.com/47211504/82888379-8457d880-9f49-11ea-9bfb-69dd08725194.png)

**Comment by lukeeey** [comment]
I’ve experienced this issue multiple times. It seems there is more game types than just the usual.

**Comment by DoctorMacc** [comment]
By the looks of it this is something that needs to be handled with MCProtocolLib - I'll file an issue report there.

**Comment by DoctorMacc** [comment]
Actually, first - update your Geyser. That build is nine days old.

**Comment by Ivennn** [comment]
updated to Loading Geyser version 1.0-SNAPSHOT (git-master-14fcd77) with the same problem

**Comment by DoctorMacc** [comment]
Same error? It should be slightly different now.

**Comment by Ivennn** [comment]
![image](https://user-images.githubusercontent.com/47211504/82909283-597d7c80-9f69-11ea-9cf7-1086621f4738.png)

**Comment by Ivennn** [comment]
It's now an unmapped exception before it was an IlegalArgumentException

**Comment by Ivennn** [comment]
`[21:27:43 INFO] Schreiffaut has disconnected from remote java server on address play.dailysurvival.be because of io.netty.handler.codec.DecoderException: com.github.steveice10.mc.protocol.data.UnmappedValueException: Value 11 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.player.GameMode.
> io.netty.handler.codec.DecoderException: com.github.steveice10.mc.protocol.data.UnmappedValueException: Value 11 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.player.GameMode.
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:473)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.steveice10.mc.protocol.data.UnmappedValueException: Value 11 has no mapping for key class com.github.steveice10.mc.protocol.data.game.entity.player.GameMode.
        at com.github.steveice10.mc.protocol.data.MagicValues.key(MagicValues.java:1209)
        at com.github.steveice10.mc.protocol.packet.ingame.server.ServerRespawnPacket.read(ServerRespawnPacket.java:32)
        at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
        ... 40 more`  




Used version: Geyser version 1.0-SNAPSHOT (git-cb5f4770351b8b0bca486ae1fcff27b4a3813558-cb5f477) 


![image](https://user-images.githubusercontent.com/47211504/82952316-0f1bf000-9fa9-11ea-902b-410c7f6626cb.png)

**Comment by RednedEpic** [comment]
In your `server.properties`, what is the gamemode set to?

**Comment by Ivennn** [comment]
Note: The error will not be thrown if you join the server directly hardcore.dailysurvival.be if you join it form the hub it will trow it.
```
#Minecraft server properties
#Tue May 26 12:06:27 CEST 2020
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=
level-seed=
rcon.port=25575
gamemode=survival
server-port=30008
allow-nether=true
enable-command-block=false
enable-rcon=false
enable-query=false
op-permission-level=4
prevent-proxy-connections=false
generator-settings=
resource-pack=
level-name=world
rcon.password=
player-idle-timeout=0
motd=A Minecraft Server
query.port=25565
debug=false
force-gamemode=false
hardcore=true
white-list=false
broadcast-console-to-ops=true
pvp=true
spawn-npcs=true
generate-structures=true
spawn-animals=true
snooper-enabled=true
difficulty=easy
function-permission-level=2
network-compression-threshold=256
level-type=default
spawn-monsters=true
max-tick-time=60000
enforce-whitelist=false
use-native-transport=true
max-players=20
resource-pack-sha1=
spawn-protection=16
online-mode=false
allow-flight=false
max-world-size=29999984
```

**Comment by Ivennn** [comment]
But I'm able to join the server now form the hub because this bug fix https://github.com/GeyserMC/Geyser/pull/693  but the error still gets thrown by the console

**Comment by Ivennn** [comment]
https://www.youtube.com/watch?v=QJCRvRd-qPo more detailed video joining hardcore at 1:08

**Comment by DoctorMacc** [comment]
Could you test if this is an issue by chance with the new 1.16 builds?

**Comment by Ivennn** [comment]
Okay I will do that over a week I can't get on my pc atm

**Comment by Ivennn** [comment]
It's fixed I guess :)

**Comment by DoctorMacc** [comment]
Thanks for the update!
