### ISSUE TITLE
Failing to start Geyser Connection

### ISSUE THREAD

**Issue by HazardTheDutchAD** [GeyserMC/Geyser#672]
**Describe the bug**
When I start Geyser, it fails to open up a connection, closing constantly. This error continues to show:

`[04:24:09 WARN] Failed to initialize a channel. Closing: [id: 0xfe8671a1]
io.netty.channel.ChannelException: java.net.SocketException: Operation not permitted
        at io.netty.channel.socket.DefaultSocketChannelConfig.setTrafficClass(DefaultSocketChannelConfig.java:267) ~[geyser.jar:?]
        at io.netty.channel.socket.DefaultSocketChannelConfig.setOption(DefaultSocketChannelConfig.java:118) ~[geyser.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig.setOption(NioSocketChannel.java:491) ~[geyser.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpClientSession$1.initChannel(TcpClientSession.java:53) ~[geyser.jar:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [geyser.jar:?]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964) [geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:613) [geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1475) [geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1127) [geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:654) [geyser.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503) [geyser.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416) [geyser.jar:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475) [geyser.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [geyser.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [geyser.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.SocketException: Operation not permitted
        at sun.nio.ch.Net.setIntOption0(Native Method) ~[?:?]
        at sun.nio.ch.Net.setSocketOption(Net.java:372) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:223) ~[?:?]
        at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:280) ~[?:?]
        at sun.nio.ch.SocketAdaptor.setTrafficClass(SocketAdaptor.java:377) ~[?:?]
        at io.netty.channel.socket.DefaultSocketChannelConfig.setTrafficClass(DefaultSocketChannelConfig.java:265) ~[geyser.jar:?]
        ... 21 more`

**Expected behavior**
A connection should be established and a channel should open

**Screenshots / Videos**
![ubuntu2004_RUxZAmKhMM](https://user-images.githubusercontent.com/20299632/82975400-3c31c800-9fd4-11ea-9160-982bca342795.png)

**Server Version**
20.04 LTS (Ubuntu)

**Geyser Version**
Last Successful Artifact (at Wednesday 27th May 2020 04:45Am BST)

**Minecraft: Bedrock Edition Version**
Bedrock 1.14.60

**Comment by TheMasterBlaster** [comment]
Server Version is expected to be the version of Minecraft Java server your trying to have Geyser use.
example: Paper version git-Paper-282 (MC: 1.15.2)

**Comment by HazardTheDutchAD** [comment]
> Server Version is expected to be the version of Minecraft Java server your trying to have Geyser use.
> example: Paper version git-Paper-282 (MC: 1.15.2)

I'm not sure about the server version, but it was CubeCraft Java. I found out that apparently WSL might have something to do with it, as I tried running an Ubuntu/Linux terminal and it was only with that terminal I got the errors. After trying through command prompt, everything seemed to work fine.

**Comment by DoctorMacc** [comment]
This could potentially be a limitation of WSL?

**Comment by DoctorMacc** [comment]
Any update on this issue?

**Comment by RednedEpic** [comment]
Closing due to lack of response and future reports regarding this issue. Likely due to what rtm mentioned above.
