### ISSUE TITLE
Could not translate packet ServerEntityMetadataPacket

### ISSUE THREAD

**Issue by detobel36** [GeyserMC/Geyser#778]
**Describe the bug**

Error in log
```
[Geyser-BungeeCord] Could not translate packet ServerEntityMetadataPacket
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float
        at org.geysermc.connector.entity.PlayerEntity.updateBedrockMetadata(PlayerEntity.java:252)
        at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:48)
        at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:36)
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:400)
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
        at java.lang.Thread.run(Thread.java:745)
```

**To Reproduce**

1. Just start GeyserMc plugin on bungeecord without floodgate and by activate java account.

**Expected behavior**

No error xD

**Server Version**

- BungeeCord-Bootstrap:1.15-SNAPSHOT:f1c32f8:1489
- Spigot version 1.10.2 (with ViaVersion)

**Geyser Version**

Geyser bungeecord plugin Version  1.0-SNAPSHOT (git-master-6388a91)

**Minecraft: Bedrock Edition Version**

Latest: 1.14.60

**Additional Context**

I didn't try to reproduce.  I hope it will though help you...

**Comment by RednedEpic** [comment]
> **Describe the bug**
> 
> Error in log
> 
> ```
> [Geyser-BungeeCord] Could not translate packet ServerEntityMetadataPacket
> java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float
>         at org.geysermc.connector.entity.PlayerEntity.updateBedrockMetadata(PlayerEntity.java:252)
>         at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:48)
>         at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:36)
>         at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
>         at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:400)
>         at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
>         at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
>         at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
>         at java.lang.Thread.run(Thread.java:745)
> ```
> 
> **To Reproduce**
> 
> 1. Just start GeyserMc plugin on bungeecord without floodgate and by activate java account.
> 
> **Expected behavior**
> 
> No error xD
> 
> **Server Version**
> 
> * BungeeCord-Bootstrap:1.15-SNAPSHOT:f1c32f8:1489
> * Spigot version 1.10.2 (with ViaVersion)
> 
> **Geyser Version**
> 
> Geyser bungeecord plugin Version 1.0-SNAPSHOT (git-master-6388a91)
> 
> **Minecraft: Bedrock Edition Version**
> 
> Latest: 1.14.60
> 
> **Additional Context**
> 
> I didn't try to reproduce. I hope it will though help you...

Server is sending invalid metadata to the player; not much we can do here. You may have some luck updating off of 1.10.2 as we've not had any reports specifically of this data failing to translate in future versions.
