### ISSUE TITLE
latest build gives no zlib header in Bungee plugin

### ISSUE THREAD

**Issue by ThEWiZ76** [GeyserMC/Geyser#812]
**Describe the bug**
Users cannot connect 

**To Reproduce**
install latest build (246) Bungee plugin
try to connect, does not work. 
Log gives this output:
<pre>
11:20:16 [SEVERE] Jun 25, 2020 11:20:16 AM com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler exceptionCaught
SEVERE: An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:83)
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:19)
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:271)
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28)
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434)
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412)
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400)
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279)
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.DataFormatException: No zlib header
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:32)
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:64)
        ... 24 more
</pre>

**Expected behavior**
allow connection

**Screenshots / Videos**
N/A

**Server Version**
Bungee git:BungeeCord-Bootstrap:1.16-R0.1-SNAPSHOT:b41e9be:1504

**Geyser Version**
Geyser-BungeeCord version 1.0-SNAPSHOT by GeyserMC
Jenkins build based on this commit https://github.com/GeyserMC/Geyser/commit/e81c6f21bf264a4a38e7c8448121009c3cfdf4a1
**Minecraft: Bedrock Edition Version**
v1.16.0

**Additional Context**

**Comment by toinouH** [comment]
Just that screenshot will "fix" your problem
![image](https://user-images.githubusercontent.com/64892431/85694618-94451280-b6d7-11ea-8863-6127431df922.png)

**Comment by Heath123** [comment]
Bedrock 1.16 isn't supported, please wait for an update to Geyser or downgrade Bedrock.

**Comment by ThEWiZ76** [comment]
Right, I see. Closing issue.
