### ISSUE TITLE
Unable to connect to server due to error

### ISSUE THREAD

**Issue by rickasheye** [GeyserMC/Geyser#830]
**Describe the bug**

A Java Error occurs

**To Reproduce**
Enter local ip adress and the ip adress you want to connect too in config.yml and start the server
Later on connect to the server by using the details in the cmd window
Encounter an error

**Expected behavior**
For it to connect

**Screenshots / Videos**
//Not exactly screenshots or video but the log.
```
[22:58:12 INFO] /192.168.0.41:65029 tried to connect!
[22:58:12 ERROR] An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:83) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:19) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:271) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [Geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [Geyser.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.util.zip.DataFormatException: No zlib header
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:32) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:64) ~[Geyser.jar:?]
        ... 24 more

```
**Server Version**
Mineplex, im connecting to it with this tool.

**Geyser Version**
1.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
v1,16.0

**Comment by Heath123** [comment]
This is because you're using Bedrock 1.16

**Comment by Heath123** [comment]
Try using a build from here: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/feature%252F1.16/

**Comment by DoctorMacc** [comment]
The above is true; you must use those builds in order to connect with Bedrock 1.16.
