### ISSUE TITLE
Im trying to connect to my server from Minecraft for windows 10

### ISSUE THREAD

**Issue by miraficus** [GeyserMC/Geyser#840]
**Describe the bug**
When i try  to connect to my server it starts loading an then error message shows up.
Java.lang.ExceptionInInitializerError
when i connect second time:
java.lang.NoClassDefFoundError: Could not initialize class org.geysermc.platform.bukkit.shaded.netty.resolver.HostsFileEntriesResolver.

**To Reproduce**

1. Open minecraft for windows 10 
2. Click on 'Miraficus server
5. Try it again 
6. See different error

**Expected behavior**
Connect me normaly.

**Screenshots / Videos**
 ![20200628_230940](https://user-images.githubusercontent.com/63237821/85958460-f92d9080-b995-11ea-906b-2107af68a4fa.jpg)

**Server Version**
This server is running CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT).
[23:21:18] [Server thread/INFO]: You are 165 version(s) behind

**Geyser Version**
 I dont know whre to find build number but i have bukkit version downloaded from here: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/ TODAY. My minecraft server and geysermc is running in offline mode.

**Minecraft: Bedrock Edition Version**

**Additional Context**
Text from console whe connecting for the first time:
[23:36:47] [Thread-20/WARN]:    at org.geysermc.connector.network.session.GeyserSession.lambda$authenticate$0(GeyserSession.java:413)
[23:36:47] [Thread-20/WARN]:    at java.lang.Thread.run(Thread.java:748)
[23:36:47] [Thread-20/WARN]: Caused by: java.lang.SecurityException: read permission error: /etc/hosts
[23:36:47] [Thread-20/WARN]:    at com.hicoria.javaSandBox.Main$CustomSecurityManager.checkRead(Main.java:295)
[23:36:47] [Thread-20/WARN]:    at java.io.File.exists(File.java:814)
[23:36:47] [Thread-20/WARN]:    at org.geysermc.platform.bukkit.shaded.netty.resolver.HostsFileParser.parse(HostsFileParser.java:130)
[23:36:47] [Thread-20/WARN]:    at org.geysermc.platform.bukkit.shaded.netty.resolver.HostsFileParser.parseSilently(HostsFileParser.java:89)
[23:36:47] [Thread-20/WARN]:    at org.geysermc.platform.bukkit.shaded.netty.resolver.HostsFileParser.parseSilently(HostsFileParser.java:76)
[23:36:47] [Thread-20/WARN]:    at org.geysermc.platform.bukkit.shaded.netty.resolver.DefaultHostsFileEntriesResolver.parseEntries(DefaultHostsFileEntriesResolver.java:79)
[23:36:47] [Thread-20/WARN]:    at org.geysermc.platform.bukkit.shaded.netty.resolver.DefaultHostsFileEntriesResolver.<init>(DefaultHostsFileEntriesResolver.java:39)
[23:36:47] [Thread-20/WARN]:    at org.geysermc.platform.bukkit.shaded.netty.resolver.HostsFileEntriesResolver.<clinit>(HostsFileEntriesResolver.java:31)
[23:36:47] [Thread-20/WARN]:    ... 8 more
[23:36:47] [Network Listener - #1/INFO]: [Geyser-Bukkit] Bedrock user with ip: /178.56.129.14 has disconnected for reason CLOSED_BY_REMOTE_PEER

Text from server consolewhen connecting x times: 
23:15:43] [Network Listener - #1/INFO]: [Geyser-Bukkit] /178.56.129.14:49760 tried to connect!
[23:15:44] [Network Listener - #1/INFO]: [Geyser-Bukkit] Player connected with username miraficus1269
[23:15:46] [Network Listener - #1/INFO]: [Geyser-Bukkit] Attempting to login using offline mode... authentication is disabled.
[23:15:46] [Thread-25/INFO]: [Geyser-Bukkit] miraficus1269 has disconnected from remote java server on address 95.217.112.144 because of java.lang.NoClassDefFoundError: Could not initialize class org.geysermc.platform.bukkit.shaded.netty.resolver.HostsFileEntriesResolver
[23:15:46] [Thread-25/WARN]: java.lang.NoClassDefFoundError: Could not initialize class org.geysermc.platform.bukkit.shaded.netty.resolver.HostsFileEntriesResolver
[23:15:46] [Thread-25/WARN]:    at org.geysermc.platform.bukkit.shaded.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:59)
[23:15:46] [Thread-25/WARN]:    at com.github.steveice10.packetlib.tcp.TcpClientSession.resolveAddress(TcpClientSession.java:150)
[23:15:46] [Thread-25/WARN]:    at com.github.steveice10.packetlib.tcp.TcpClientSession.access$200(TcpClientSession.java:34)
[23:15:46] [Thread-25/WARN]:    at com.github.steveice10.packetlib.tcp.TcpClientSession$2.run(TcpClientSession.java:114)
[23:15:46] [Thread-25/WARN]:    at com.github.steveice10.packetlib.tcp.TcpClientSession.connect(TcpClientSession.java:132)
[23:15:46] [Thread-25/WARN]:    at com.github.steveice10.packetlib.tcp.TcpSession.connect(TcpSession.java:63)
[23:15:46] [Thread-25/WARN]:    at org.geysermc.connector.network.session.GeyserSession.lambda$authenticate$0(GeyserSession.java:413)
[23:15:46] [Thread-25/WARN]:    at java.lang.Thread.run(Thread.java:748)
[23:15:47] [Network Listener - #1/INFO]: [Geyser-Bukkit] Bedrock user with ip: /178.56.129.14 has disconnected for reason CLOSED_BY_REMOTE_PEER 

I have ProtocolSupport plugin installed.

**Comment by RednedEpic** [comment]
Looks like you're lacking permission to read from file `/etc/hosts`. Seems like the second stacktrace could be related, but try fixing the first problem first then let us know if the issue persists. Also update your Spigot version, you're quite outdated.

**Comment by DoctorMacc** [comment]
Any update on this issue?

**Comment by Trains77** [comment]
Craftbukkit is incompatible with floodgate, I have found the same error before, use PaperMC software as it does work with floodgate and you won't need to redownload any plugins

**Comment by rtm516** [comment]
> Craftbukkit is incompatible with floodgate, I have found the same error before, use PaperMC software as it does work with floodgate and you won't need to redownload any plugins

They are using Spigot, which works fine with Floogate

**Comment by Chew** [comment]
Upstream issue, see https://github.com/Steveice10/PacketLib/issues/23

**Comment by Camotoy** [comment]
This portion of PacketLib should no longer be called in Geyser, so I am closing. Thank you anyway!
