### ISSUE TITLE
1.16 wont work

### ISSUE THREAD

**Issue by itsyecoder** [GeyserMC/Geyser#844]
**Describe the bug**
The Geyser plugin spits out a ton of errors when connecting to it

**To Reproduce**
Load up geyser along with java server and will reproduce bug

**Expected behavior**
It is supposed to let you play with no errors

**Screenshots / Videos**

2020-06-28 21:50:57.441 [main] I - [0m[1m[36;1mAdded loopback exemption to Windows![0m
2020-06-28 21:50:57.859 [main] I - [0m[1m******************************************[0m
2020-06-28 21:50:57.860 [main] I - [0m[1m[0m
2020-06-28 21:50:57.861 [main] I - [0m[1mLoading Geyser version 1.0-SNAPSHOT (git-master-61bfd46)[0m
2020-06-28 21:50:57.861 [main] I - [0m[1m[0m
2020-06-28 21:50:57.864 [main] I - [0m[1m******************************************[0m
2020-06-28 21:51:01.787 [main] I - [0m[1mStarted Geyser on 0.0.0.0:19132[0m
2020-06-28 21:51:01.791 [main] I - [0m[1mDone (3.931s)! Run /geyser help for help![0m
2020-06-28 21:51:07.297 [Network Listener - #1] I - [0m[1m/10.0.1.108:55652 tried to connect![0m
2020-06-28 21:51:07.390 [Network Listener - #1] E - An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
	at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:83) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:19) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:271) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[Geyser.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[Geyser.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[Geyser.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[Geyser.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[Geyser.jar:?]
	at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[Geyser.jar:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [Geyser.jar:?]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [Geyser.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [Geyser.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [Geyser.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.util.zip.DataFormatException: No zlib header
	at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:32) ~[Geyser.jar:?]
	at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:64) ~[Geyser.jar:?]
	... 24 more

**Server Version**
1.16

**Geyser Version**
1.0-SNAPSHOT

**Minecraft: Bedrock Edition Version**
v1.16.0 

**Additional Context**
My guess is that it can't load in new stuff for nether update. If there are fixes please comment below

**Comment by RednedEpic** [comment]
Please download a jar from here: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/feature%252F1.16/. You're using a jar from the master branch.
