### ISSUE TITLE
PS4 Bedrock Game Crash Isssue

### ISSUE THREAD

**Issue by Callum-Bell** [GeyserMC/Geyser#851]
**Describe the bug**
Connecting to Java 1.16.1 from Bedrock PS4. Game will crash on PS4. The bug will occur within 30 seconds of connecting.

**To Reproduce**
1.) Running Geyser and Floodgate on Spigot (Spigot build of Geyser being used, also happened with bukkit)
2.) Connect from PS4 using MineProxyDroid.

**Expected behavior**
I expected to connect to the server which it does, then it crashes the game on the console.

**Server Version**
This server is running CraftBukkit version git-Spigot-ad703da-e2403a3 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build #50 for 1.16 Branch | Floodgate is being used

**Minecraft: Bedrock Edition Version**

1.16.0
[latest.log](https://github.com/GeyserMC/Geyser/files/4846648/latest.log)

Edit: Fixing application name / Correct Log.

**Comment by rtm516** [comment]
Correct log, from discord: [latest.log](https://github.com/GeyserMC/Geyser/files/4846653/latest.17.log)
Error:
```
[11:51:51] [Thread-35/WARN]: [Geyser-Spigot] Could not translate packet ServerPlayBuiltinSoundPacket
java.lang.IllegalArgumentException: No enum constant com.nukkitx.protocol.bedrock.data.LevelEventType.SOUND_ITEMFRAME_ADD_ITEM
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_241]
	at com.nukkitx.protocol.bedrock.data.LevelEventType.valueOf(LevelEventType.java:3) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:57) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:399) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-Spigot.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[11:51:51] [Thread-35/WARN]: java.lang.IllegalArgumentException: No enum constant com.nukkitx.protocol.bedrock.data.LevelEventType.SOUND_ITEMFRAME_ADD_ITEM
[11:51:51] [Thread-35/WARN]: 	at java.lang.Enum.valueOf(Unknown Source)
[11:51:51] [Thread-35/WARN]: 	at com.nukkitx.protocol.bedrock.data.LevelEventType.valueOf(LevelEventType.java:3)
[11:51:51] [Thread-35/WARN]: 	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:57)
[11:51:51] [Thread-35/WARN]: 	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40)
[11:51:51] [Thread-35/WARN]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
[11:51:51] [Thread-35/WARN]: 	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:399)
[11:51:51] [Thread-35/WARN]: 	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[11:51:51] [Thread-35/WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[11:51:51] [Thread-35/WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[11:51:51] [Thread-35/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by ultramoo** [comment]
What is MineDroidProxy ? Have you tried with phantom? I can connect with PS4 without any crashes.
 https://github.com/jhead/phantom

**Comment by Callum-Bell** [comment]
MineProxyDroid sorry. , https://play.google.com/store/apps/details?id=com.luzenna.mineproxydroid&hl=en_GB

My friend is on PS4 with no PC. We use to use PocketMine but doesn't work in 1.16 and they removed the /transferserver command so it's useless.

**Comment by Heath123** [comment]
Have you tried Phantom at all?

**Comment by Callum-Bell** [comment]
> Have you tried Phantom at all?

Hi, My friend is on PS4 without a PC. Not possible.

**Comment by Heath123** [comment]
Yes, I didn't read that, sorry.

**Comment by DoctorMacc** [comment]
When was the last time MineProxyDroid was updated?

**Comment by rtm516** [comment]
If you're referring to [this](https://play.google.com/store/apps/details?id=com.luzenna.mineproxydroid), I think it's updated.

**Comment by Callum-Bell** [comment]
It is that, do you's happen to know other software that allow this on Android?

**Comment by Heath123** [comment]
> It is that, do you's happen to know other software that allow this on Android?

You could try getting Phantom on an app called Termux

**Comment by rtm516** [comment]
> It is that, do you's happen to know other software that allow this on Android?

Im working on something currently todo that Ill update here when I have a working test build :)

**Comment by ultramoo** [comment]
So I used the app you have:  Minecraft LAN Proxy - Servers on PS4/Xbox (mineproxydroid) on my Samsung Galaxy s20
Tested with exact same setup: Running Geyser-Spigot Plugin (Build #70)  + Floodgate Plugin on Paper Spigot 1.16.1 (Build 37)

I didn't see any problems, was able to connect with my PS4. Tested for 5 mins without a glitch. For confirmation I shutdown the mineproxydroid app during play and immediately Miencraft on PS4 disconnected. (meaning the app is working as intended)

Is your issue intermittent? How often does it happen? 

If you would like to test on my test server and confirm its not a configuration with your Geyser build:
IP: 118.127.60.135
Port: 25888
(Server location: Australia)

**Comment by Callum-Bell** [comment]
Managed to get him connected now without bluescreening on PS4, Just errors now.

>[17:55:06] [Thread-18/WARN]: [Geyser-Spigot] Could not translate packet ServerPlayBuiltinSoundPacket
java.lang.IllegalArgumentException: No enum constant com.nukkitx.protocol.bedrock.data.LevelEventType.SOUND_ITEMFRAME_ADD_ITEM
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_251]
	at com.nukkitx.protocol.bedrock.data.LevelEventType.valueOf(LevelEventType.java:3) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:57) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:399) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-Spigot.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[17:55:06] [Thread-18/WARN]: java.lang.IllegalArgumentException: No enum constant com.nukkitx.protocol.bedrock.data.LevelEventType.SOUND_ITEMFRAME_ADD_ITEM
[17:55:06] [Thread-18/WARN]: 	at java.lang.Enum.valueOf(Unknown Source)
[17:55:06] [Thread-18/WARN]: 	at com.nukkitx.protocol.bedrock.data.LevelEventType.valueOf(LevelEventType.java:3)
[17:55:06] [Thread-18/WARN]: 	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:57)
[17:55:06] [Thread-18/WARN]: 	at org.geysermc.connector.network.translators.java.world.JavaPlayBuiltinSoundTranslator.translate(JavaPlayBuiltinSoundTranslator.java:40)
[17:55:06] [Thread-18/WARN]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
[17:55:06] [Thread-18/WARN]: 	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:399)
[17:55:06] [Thread-18/WARN]: 	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[17:55:06] [Thread-18/WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[17:55:06] [Thread-18/WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[17:55:06] [Thread-18/WARN]: 	at java.lang.Thread.run(Unknown Source)


 

> [18:01:47] [Thread-25/WARN]: [Geyser-Spigot] Could not translate packet ServerPlayEffectPacket java.lang.IllegalArgumentException: No enum constant com.nukkitx.protocol.bedrock.data.LevelEventType.BONEMEAL
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_251]
	at com.nukkitx.protocol.bedrock.data.LevelEventType.valueOf(LevelEventType.java:3) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayEffectTranslator.translate(JavaPlayEffectTranslator.java:62) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.java.world.JavaPlayEffectTranslator.translate(JavaPlayEffectTranslator.java:49) ~[Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93) [Geyser-Spigot.jar:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:399) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Spigot.jar:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-Spigot.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[18:01:47] [Thread-25/WARN]: java.lang.IllegalArgumentException: No enum constant com.nukkitx.protocol.bedrock.data.LevelEventType.BONEMEAL
[18:01:47] [Thread-25/WARN]: 	at java.lang.Enum.valueOf(Unknown Source)
[18:01:47] [Thread-25/WARN]: 	at com.nukkitx.protocol.bedrock.data.LevelEventType.valueOf(LevelEventType.java:3)
[18:01:47] [Thread-25/WARN]: 	at org.geysermc.connector.network.translators.java.world.JavaPlayEffectTranslator.translate(JavaPlayEffectTranslator.java:62)
[18:01:47] [Thread-25/WARN]: 	at org.geysermc.connector.network.translators.java.world.JavaPlayEffectTranslator.translate(JavaPlayEffectTranslator.java:49)
[18:01:47] [Thread-25/WARN]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:93)
[18:01:47] [Thread-25/WARN]: 	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:399)
[18:01:47] [Thread-25/WARN]: 	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[18:01:47] [Thread-25/WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[18:01:47] [Thread-25/WARN]: 	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[18:01:47] [Thread-25/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by DoctorMacc** [comment]
That is a different error and this can be closed.
