### ISSUE TITLE
Can't connect to server 1.16 from Minecraft Windows 10

### ISSUE THREAD

**Issue by DjArt** [GeyserMC/Geyser#864]
**Describe the bug**
```
[18:47:21 ERROR]: [com.nukkitx.network.raknet.RakNetServer] An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:83) ~[?:?]
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:19) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:271) ~[?:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[?:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
        at org.geysermc.platform.bukkit.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.util.zip.DataFormatException: No zlib header
        at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:32) ~[?:?]
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:64) ~[?:?]
        ... 24 more
```
**To Reproduce**
Connect from Minecraft Windows 10 1.16. Connecting don't happen.

**Expected behavior**
All must work fine.

**Server Version**
Paper 1.16.1 #24

**Geyser Version**
Geyser: #247, Floodgate: #24

**Comment by RednedEpic** [comment]
Please download a jar from here: https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/feature%252F1.16/. You're trying to use a build from the master branch.

**Comment by DjArt** [comment]
Oh, thanks!
