### ISSUE TITLE
[1.16.1]can't join

### ISSUE THREAD

**Issue by MAX-XiaoKui** [GeyserMC/Geyser#910]
**Describe the bug**

I can ping my server but I can't join it, and there is error in the console
**Screenshots / Videos**

![Screenshot_2020-07-07-12-00-00-37_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/53287753/86706779-d5c7ad00-c049-11ea-9202-3a73146612d5.jpg)
![Screenshot_2020-07-07-11-59-46-32_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/53287753/86706799-dc562480-c049-11ea-9978-bc60aa69f1e8.jpg)

**Server Version**
Waterfall build 360
fabric server 1.16.1

**Geyser Version**
Geyser-bungeecord build 249

**Minecraft: Bedrock Edition Version**
Minecraft 1.16.1.02 on Android

**Console**
[11:42:32 INFO] [Geyser-BungeeCord]: /117.88.*.*:21053 tried to connect!
[11:42:34 INFO] [Geyser-BungeeCord]: Bedrock user with ip: /117.88.*.* has disconnected for reason CLOSED_BY_REMOTE_PEER
[11:42:37 INFO] [Geyser-BungeeCord]: /117.88.170.105:21053 tried to connect!
[11:42:37 ERROR] [com.nukkitx.network.raknet.RakNetServer]: An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:83) ~[?:?]
at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:19) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:271) ~[?:?]
at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[?:?]
at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[?:?]
at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[?:?]
at org.geysermc.platform.bungeecord.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.util.zip.DataFormatException: No zlib header
at com.nukkitx.protocol.util.Zlib.inflate(Zlib.java:32) ~[?:?]
at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:64) ~[?:?]
... 24 more

**Comment by RednedEpic** [comment]
Current master build does not support 1.16. Please download one from the 1.16 feature branch on Jenkins for the time being.
