### ISSUE TITLE
Error putting unamed MineTinker tool into anvil

### ISSUE THREAD

**Issue by ishland** [GeyserMC/Geyser#935]
**Describe the bug**
Geyser keeps complaining about empty names when putting a unamed MineTinker tool into an anvil. Named tools aren't affected. 

**To Reproduce**
1. Get a new MineTinker tool.
2. Put it into anvil.
3. See error

**Expected behavior**
No error should be seen. 

**Screenshots / Videos**
Nope

**Server Version**
`This server is running Paper version git-Paper-86 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)`

**Geyser Version**
This server is running Geyser version 1.0.0 (git-master-3e0cb28) (Java: 1.16.1, Bedrock: 1.16.0)
I am running Geyser-Spigot. 

**Minecraft: Bedrock Edition Version**
`v1.6.1`

**Additional Context**
Error message:
```
[22:04:56 WARN]: [Geyser-Spigot] Could not translate packet ServerSetSlotPacket
java.lang.NullPointerException: null
        at org.geysermc.connector.network.translators.inventory.AnvilInventoryTranslator.updateSlot(AnvilInventoryTranslator.java:140) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:59) ~[?:?]
        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:38) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407) ~[?:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[22:04:56 WARN]: java.lang.NullPointerException
[22:04:56 WARN]:        at org.geysermc.connector.network.translators.inventory.AnvilInventoryTranslator.updateSlot(AnvilInventoryTranslator.java:140)
[22:04:56 WARN]:        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:59)
[22:04:56 WARN]:        at org.geysermc.connector.network.translators.java.window.JavaSetSlotTranslator.translate(JavaSetSlotTranslator.java:38)
[22:04:56 WARN]:        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[22:04:56 WARN]:        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407)
[22:04:56 WARN]:        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[22:04:56 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[22:04:56 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[22:04:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

And also the tool name is completely empty

**Comment by rtm516** [comment]
Can you please test https://github.com/GeyserMC/Geyser/pull/936 for me? If you're not sure how to download it join our [discord](https://discord.geysermc.org) and run `!tag prdownload`

**Comment by ishland** [comment]
China blocked discord so I built it myself. It no longer output errors.
