### ISSUE TITLE
[1.16.1]Unable to join the server.

### ISSUE THREAD

**Issue by W-Kazdel** [GeyserMC/Geyser#943]
**Describe the bug**

Unable to join the server.
**To Reproduce**

**Expected behavior**

**Screenshots / Videos**

**Server Version**

1.16.1 BC
**Geyser Version**

#264
**Minecraft: Bedrock Edition Version**

1.16.1
**Additional Context**

[22:33:59 ERROR] An exception occurred in RakNet
java.lang.AssertionError: Expected AES to be available
        at com.nukkitx.natives.aes.JavaAes.<init>(JavaAes.java:26) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.enableEncryption(BedrockSession.java:200) ~[Geyser.jar:?]
        at org.geysermc.connector.utils.LoginEncryptionUtils.startEncryptionHandshake(LoginEncryptionUtils.java:148) ~[Geyser.jar:?]
        at org.geysermc.connector.utils.LoginEncryptionUtils.encryptConnectionWithCert(LoginEncryptionUtils.java:133) ~[Geyser.jar:?]
        at org.geysermc.connector.utils.LoginEncryptionUtils.encryptPlayerConnection(LoginEncryptionUtils.java:99) ~[Geyser.jar:?]
        at org.geysermc.connector.network.UpstreamPacketHandler.handle(UpstreamPacketHandler.java:59) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:21) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278) ~[Geyser.jar:?]
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279) ~[Geyser.jar:?]
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288) ~[Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [Geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [Geyser.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [Geyser.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [Geyser.jar:?]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [Geyser.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [Geyser.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [Geyser.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [Geyser.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by rtm516** [comment]
Please update Java, this is caused by a really old Java 8 version https://adoptopenjdk.net/
