### ISSUE TITLE
Hitting a bedrock player can cause their client to crash

### ISSUE THREAD

**Issue by ryanbester** [GeyserMC/Geyser#948]
**Describe the bug**

On a survival server where PvP is enabled, hitting a Bedrock player from a Java client can sometimes cause the client of the Bedrock player to crash. The player would still appear to be in the game (in tab list and available in commands) but trying to teleport the player would result in a JSON exception in the BungeeCord log, and the teleport will fail.

When the Bedrock player reloads their client, they will be disconnected from the server, until they manually log back into the server.

**To Reproduce**

1. Join PvP enabled survival server on a Java and Bedrock account.
2. Hit the Bedrock player from the Java account. It’s better to do this with your fist as it doesn’t cause as much damage.
3. The Bedrock client will sometimes crash after hitting the player several times.

**Expected behavior**

Repeatedly hitting the player should kill them and allow them to respawn or return to the title screen without crashing their client.

**Screenshots / Videos**

**Server Version**

Java (Paper): 1.16.1 (git-paper-12)
BungeeCord (with Geyser and Floodgate as plugins): 1.16.1

**Geyser Version**

Geyser version 1.0.0 (git-master-e7657c7) (Java: 1.16.1, Bedrock: 1.16.0)

**Minecraft: Bedrock Edition Version**

1.16.0

**Additional Context**

**Comment by DoctorMacc** [comment]
Any plugins?

**Comment by ryanbester** [comment]
I’ve got Essentials, WorldEdit, and WorldGuard. Sorry, I should’ve mentioned that in the issue description.

**Comment by DoctorMacc** [comment]
Thanks for the report - in the meantime, if you have a moment please see if you can replicate the issue in vanilla. That would be valuable information.

**Comment by ryanbester** [comment]
I’ll be able to try it tomorrow, and I’ll report back the exact error message too.

**Comment by DoctorMacc** [comment]
Lovely, thank you.

**Comment by ryanbester** [comment]
I tried recreating the issue on a vanilla server with BungeeCord, and a Spigot server with and without BungeeCord, but the issue did not occur. I then used the same plugins I use on the server where the issue exists on this test server and the issue still did not occur.

I then tested it back on my main server, the player’s client crashed but no error was logged to the console (BungeeCord nor Spigot) other than a timed out error.

The only thing I didn’t test was what the bedrock client was connected with; it could just be a WiFi connectivity issue, since after reporting this I noticed that this could happen at any time.

**Comment by RednedEpic** [comment]
> The player would still appear to be in the game (in tab list and available in commands) but trying to teleport the player would result in a JSON exception in the BungeeCord log, and the teleport will fail.

Can you please provide this error?

**Comment by ryanbester** [comment]
I wasn't getting the JSON exception again for some reason, but I got a ClassCastException for the player metadata packet.
```
[22:10:51] [Thread-71/WARN] [Geyser-BungeeCord]: Could not translate packet ServerEntityMetadataPacket
java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float
	at org.geysermc.connector.entity.PlayerEntity.updateBedrockMetadata(PlayerEntity.java:257) ~[?:?]
	at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:48) ~[?:?]
	at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:36) ~[?:?]
	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407) ~[?:?]
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[22:10:51] [Thread-71/ERROR]: java.lang.ClassCastException: java.lang.Byte cannot be cast to java.lang.Float
[22:10:51] [Thread-71/ERROR]: 	at org.geysermc.connector.entity.PlayerEntity.updateBedrockMetadata(PlayerEntity.java:257)
[22:10:51] [Thread-71/ERROR]: 	at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:48)
[22:10:51] [Thread-71/ERROR]: 	at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:36)
[22:10:51] [Thread-71/ERROR]: 	at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[22:10:51] [Thread-71/ERROR]: 	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407)
[22:10:51] [Thread-71/ERROR]: 	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[22:10:51] [Thread-71/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[22:10:51] [Thread-71/ERROR]: 	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[22:10:51] [Thread-71/ERROR]: 	at java.lang.Thread.run(Thread.java:748)
```
The player disconnects after that with a TIMED_OUT status.

**Comment by DoctorMacc** [comment]
Can you provide a dump from `/geyser dump`?

**Comment by ryanbester** [comment]
[https://dump.geysermc.org/cQNgG56O87DDoq6rLBIIVnrxaJTLMHNE](Dump).

I updated Geyser last night, now it's running Geyser version 1.0.0 (git-master-5b1116b) (Java: 1.16.1, Bedrock: 1.16.0).

**Comment by DoctorMacc** [comment]
Does this issue still occur?

**Comment by RednedEpic** [comment]
Closing as we've seen no future reports of this. The stacktrace provided is no longer valid due to the code changes we done, and it seems probable that whatever may have been causing this crash (if it be related to that stacktrace) has since been resolved.
