### ISSUE TITLE
There is an error when trying to open a submenu in the GUI DynamicShop plugin. The menu is closed.

### ISSUE THREAD

**Issue by valenvaio** [GeyserMC/Geyser#964]
There is an error when trying to open a submenu in the GUI DynamicShop plugin. The menu is closed.

git.branch=master
git.build.host=nukkitx.com
git.build.number=272
git.build.time=2020-07-15T00\:58\:41+0200

[00:00:36 WARN]: Error dispatching event ChatEvent(super=TargetedEvent(sender=⏏ValenVaio, receiver=net.md_5.bungee.ServerConnection@278e58d4), cancelled=false, message=/shop Ore) to listener com.jakub.premium.listener.ChatListener@6e00837f
java.lang.NullPointerException: null
        at com.jakub.premium.listener.ChatListener.onChat(ChatListener.java:29) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:150) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:76) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.16-R0.3-SNAPSHOT:9eb5b42:364]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

**Comment by rtm516** [comment]
1. Please follow the issue template next time
2. That error is not caused by Geyser
