### ISSUE TITLE
Translatable Chat Component doesn't work properly in titles and above mob name tags

### ISSUE THREAD

**Issue by LOOHP** [GeyserMC/Geyser#971]
**Describe the bug**

Chat Components with Translatable Components does not work properly. For titles, subtitles and actionbar, whenever they are shown, for example, with this command: `/title @a actionbar {"translate":"item.minecraft.diamond_sword"}` This error would be shown
```
[12:20:54 WARN]: [Geyser-Spigot] Could not translate packet ServerTitlePacket
java.lang.ClassCastException: com.github.steveice10.mc.protocol.data.message.TranslationMessage cannot be cast to com.github.steveice10.mc.protocol.data.message.TextMessage
        at org.geysermc.connector.utils.MessageUtils.getBedrockMessage(MessageUtils.java:236) ~[?:?]
        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:59) ~[?:?]
        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:36) ~[?:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) ~[?:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407) ~[?:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) ~[?:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[12:20:54 WARN]: java.lang.ClassCastException: com.github.steveice10.mc.protocol.data.message.TranslationMessage cannot be cast to com.github.steveice10.mc.protocol.data.message.TextMessage
[12:20:54 WARN]:        at org.geysermc.connector.utils.MessageUtils.getBedrockMessage(MessageUtils.java:236)
[12:20:54 WARN]:        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:59)
[12:20:54 WARN]:        at org.geysermc.connector.network.translators.java.JavaTitleTranslator.translate(JavaTitleTranslator.java:36)
[12:20:54 WARN]:        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[12:20:54 WARN]:        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407)
[12:20:54 WARN]:        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[12:20:54 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[12:20:54 WARN]:        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[12:20:54 WARN]:        at java.lang.Thread.run(Unknown Source)
```

***

As for above head mob names, the translatable part would just disappear, so a mob with the name `item.minecraft.diamond_sword : hello` would become ` : hello` instead of `Diamond Sword : hello`

**To Reproduce**

Title Problem:
1. Login on bedrock
2. Run `/title @a actionbar {"translate":"item.minecraft.diamond_sword"}`
3. Take a look at the screen as well as the console

Nametag Problem:
1. Login on bedrock
2. Have a mobs' EntityMetaDataPacket customname field use a translatable component (I used my own plugin [HoloMobHealth](https://www.spigotmc.org/resources/holomobhealth-display-mob-health-above-head-client-side-display-only-no-messing-up-mob-names.75975/))
3. Look at the nametag of the mob

**Expected behavior**
Translatable Chat to be shown correctly, like how Geyser already does pretty well for normal chat messages.

**Server Version**
Paper version git-Paper-98 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

**Geyser Version**
Build 272

**Minecraft: Bedrock Edition Version**
v1.16.0

**Comment by DoctorMacc** [comment]
Has the second problem been fixed? Working on fixing the first problem now.

**Comment by DoctorMacc** [comment]
Nevermind.
