### ISSUE TITLE
Error when translating ServerEntityMetadataPacket including AbstractHorseEntity

### ISSUE THREAD

**Issue by Alvinn8** [GeyserMC/Geyser#99]
**Describe the bug**
Whenever I am connecting to the java server from bedrock, this error occasionally appears in the console. I got this error 26 times during the ~40 minutes the server was running. Feel free to change the title of this issue of you have a better fitting title.

**To Reproduce**
I'm not 100% sure what is causing this error. But looking at the stack trace, it seams like it's a problem with horses.

**Expected behavior**
No error appears

**Server version**
Paper/PaperMC/PaperSpigot 1.14.4
/version output: "This server is running CraftBukkit version git-Spigot-56f8471-ccd47a5 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)"

**Geyser version**
1.0-SNAPSHOT
I downloaded the jar on 1 december 2019 at 11:43 (CET). So I think that means I have Jenkins #137

**Bedrock version**
1.13.3

**Error**
```Could not translate packet ServerEntityMetadataPacket
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
	at org.geysermc.connector.entity.living.AbstractHorseEntity.updateBedrockMetadata(AbstractHorseEntity.java:43)
	at org.geysermc.connector.entity.living.ChestedHorseEntity.updateBedrockMetadata(ChestedHorseEntity.java:45)
	at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:46)
	at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:34)
	at org.geysermc.connector.network.translators.Registry.translate(Registry.java:54)
	at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:207)
	at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
	at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
	at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RednedEpic** [comment]
This error appears to happen when a donkey or mule is loaded in. Thanks for reporting it!

**Comment by EOT3000** [comment]
@RednedEpic 
`metadata.put(EntityData.VARIANT, (int) entityMetadata.getValue());` the int cast is redundant. And it causes this isuue

**Comment by EOT3000** [comment]
I can fix + push if you'd like
