### ISSUE TITLE
is this a bug?

### ISSUE THREAD

**Issue by brokiem** [GeyserMC/Geyser#999]
[03:12:03] [Thread-23/WARN]: [Geyser-Spigot] Could not translate packet ServerEntityMetadataPacket
java.lang.NullPointerException: null
        at org.geysermc.connector.entity.living.animal.StriderEntity.updateBedrockMetadata(StriderEntity.java:81) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.entity.Entity.updateBedrockMetadata(Entity.java:370) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.entity.LivingEntity.updateBedrockMetadata(LivingEntity.java:77) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.entity.living.InsentientEntity.updateBedrockMetadata(InsentientEntity.java:49) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.entity.living.AgeableEntity.updateBedrockMetadata(AgeableEntity.java:52) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.entity.living.animal.StriderEntity.updateBedrockMetadata(StriderEntity.java:56) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:48) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:36) ~[Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94) [Geyser-Spigot.jar:?]
        at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149) [Geyser-Spigot.jar:?]
        at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324) [Geyser-Spigot.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[03:12:03] [Thread-23/WARN]: java.lang.NullPointerException
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.entity.living.animal.StriderEntity.updateBedrockMetadata(StriderEntity.java:81)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.entity.Entity.updateBedrockMetadata(Entity.java:370)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.entity.LivingEntity.updateBedrockMetadata(LivingEntity.java:77)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.entity.living.InsentientEntity.updateBedrockMetadata(InsentientEntity.java:49)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.entity.living.AgeableEntity.updateBedrockMetadata(AgeableEntity.java:52)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.entity.living.animal.StriderEntity.updateBedrockMetadata(StriderEntity.java:56)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:48)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.network.translators.java.entity.JavaEntityMetadataTranslator.translate(JavaEntityMetadataTranslator.java:36)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.network.translators.PacketTranslatorRegistry.translate(PacketTranslatorRegistry.java:94)
[03:12:03] [Thread-23/WARN]:    at org.geysermc.connector.network.session.GeyserSession$1.packetReceived(GeyserSession.java:407)
[03:12:03] [Thread-23/WARN]:    at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[03:12:03] [Thread-23/WARN]:    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:149)
[03:12:03] [Thread-23/WARN]:    at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:324)
[03:12:03] [Thread-23/WARN]:    at java.base/java.lang.Thread.run(Thread.java:834)
[03:12:06] [Thread-41/INFO]: [Geyser-Spigot] Spawned player at 5.5 20 -2.5

MC 1.16.1
OS: Ubuntu

**Comment by SinonGame** [comment]
Please follow the issue formate!
and yes, this is a problem

**Comment by rtm516** [comment]
Please fill in the template as @SinonGame mentioned, and this might fix the issue with the very limited information we have https://github.com/GeyserMC/Geyser/pull/1001
